부산대 BE_박수빈 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #100
Opened 2024-07-16 05:33 UTC by kuma4188

고민했던 부분
#addProduct / EditProduct

처음에 카테고리변수를 string으로 해서 입력받으려고 했습니다.
하지만 상품수정, 추가시에 카테고리 지정을 해야하는데
이용자가 기존의 카테고리외의 카테고리를 입력하거나 ,
오타를 입력할 경우 예외 처리를 해야할것 같아서 번호로 만들었습니다.
따라서 입력받는 폼은 다중선택 박스를 선택해서 
이용자에게는 카테고리를 한글로 보여주고 , 내부에서는 value를 카테고리 번호로 설정
해서 서버로 넘겨주는 방식을 선택했습니다.

2024-07-16 14:09 UTC, yoo-jaein requested changes
step1 고생하셨습니다!
리뷰 코멘트 확인 부탁드려요~

2024-07-16 14:09 UTC, deactivated-user commented on src/main/java/gift/dto/CategoryDTO.java
> +
메서드 순서는 일반적으로 getter - setter 로 둡니다!
예: getId, getName, getColor, ... setId, setName, setColor

2024-07-16 14:09 UTC, deactivated-user commented on src/main/java/gift/dto/CategoryDTO.java
> +
그리고 DTO는 보일러플레이트 코드가 많은데 record로 선언하는 것도 괜찮겠네요

2024-07-16 14:09 UTC, deactivated-user commented on src/main/java/gift/dto/ProductDTO.java
> +    public int getCategory() {return category;}
기존 코드 포맷을 지켜주세요!

2024-07-16 14:09 UTC, deactivated-user commented on src/main/java/gift/service/ProductServiceImpl.java
>      private ProductDTO convertToDTO(Product product) {
ProductDTO <-> product 와 같은 매핑 코드는 DTO에 넣거나 별도 매퍼 클래스에 넣는 것이 더 괜찮을 것 같습니다.

2024-07-16 14:09 UTC, deactivated-user commented on src/main/java/gift/service/CategoryServiceImpl.java
> +    private List<CategoryDTO> categories = Arrays.asList(
카테고리 데이터를 애플리케이션 코드에서 관리하는 것 보다 미리 데이터베이스에 세팅해놓는 것이 좋을 것 같습니다.

2024-07-16 14:09 UTC, yoo-jaein commented on README.md
> +해서 서버로 넘겨주는 방식을 선택했씁니다.
적절히 구현하셨습니다! 👍
일반적으로 웹 페이지에서는 카테고리 이름을 사용자에게 보여주고, 사용자가 선택한 카테고리의 id 값을 서버에게 전달하도록 구현합니다.

2024-07-17 05:26 UTC, kuma4188 commented
수정사항
1. id가 1부터 자동생성중인것을 발견 , DB에서 id값을 넣어주고 있었기 떄문에 , DB에서 받는걸로 수정
2. DTO getter , setter 순으로 재 배열
3. convertDTO를 DTO로 이동
4. serviceImpl에 있던 카테고리DB를 DatasourseLoader로 이동

2024-07-17 12:19 UTC, yoo-jaein approved these changes
step1 머지하겠습니다! :)
테스트 코드쪽 확인 부탁드려요

2024-07-17 12:19 UTC, yoo-jaein commented on src/test/java/gift/test/ProductRepositoryTest.java
> +        Product product = new Product(1234L,"Test Product", 1000, "test.jpg" , 1;
끝에 ) 가 빠졌습니다!

2024-07-17 12:19 UTC, merged