경북대 BE_이도훈 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #104
Opened 2024-07-16 05:59 UTC by 2iedo

### 요구사항 관련 궁금한 점

- 기능 요구사항의 GET /api/categories HTTP/1.1 가 정확히 무엇을 요구하는지 잘 모르겠습니다. 해당 request만 보았을 때에는 카테고리 데이터베이스에 있는 카테고리 목록이라 생각되어 카테고리 데이터베이스에 있는 데이터를 response로 보내고, 해당 category 데이터베이스에는 Long id(primary key), String name, String color, String imageUrl, String description 의 요소로 테이블을 만들었습니다. 그런데 밑의 힌트에는 category 데이터베이스에는 Long id(primary key), String name만 있습니다. 그러면 response를 Long id, String name만 나타나게 하기위해 데이터베이스를 수정하거나(1), 특정 제품의 카테고리를 포함하여 출력하는 것(2)이 됩니다.
- (1)인 경우 힌트가 늦게 추가되어서 일단 요구사항의 response에 맞추어서 데이터베이스를 구현하였습니다. 혹시 힌트를 바탕으로 구현해야할 경우 남겨주시면 수정하도록 하겠습니다.
- (2)인 경우는 request에 특정 제품의 id라던가 이름이 포함되어야할 것 같은데, 따로 명시된 것이 없어서 해당 request에는 카테고리 목록만 응답하도록 하고, product(Rest)Controllerd에서 카테고리의 이름을 포함하여 응답하도록 수정했습니다. 이것 또한 피드백 남겨주시면 빠르게 수정하겠습니다.

2024-07-16 15:55 UTC, khj68 commented
도훈님 고생 많으셨습니다!

GET /api/categories 의 경우 DB에 저장된 카테고리 목록을 조회하는 API입니다.
따라서 상품 (product)와는 관계가 없습니다.
카테고리의 id와 name (카테고리명)을 리스트로 내려주면 되겠습니다.

이를 위해서 DB를 수정하는 방법도 있지만,
이미 CategoryDTO를 만들어두셨습니다.

dto에서 반환하고자 하는 컬럼을 제한함으로써 손쉽게 요구사항을 충족할 수 있습니다.

2024-07-16 15:59 UTC, khj68 requested changes
도훈님 고생 많으셨습니다 :)

2024-07-16 15:59 UTC, khj68 commented on src/main/java/gift/Model/DTO/CategoryDTO.java
> +public record CategoryDTO(Long id, String name, String color, String imageUrl, String description) {
이 부분에서 db의 모든 컬럼을 내려주는 것이 아니라 요구사항에 적힌 컬럼만 선택하여 내려줄 수 있습니다.

2024-07-16 15:59 UTC, khj68 commented on src/main/java/gift/Model/Entity/ProductEntity.java
> +        private CategoryEntity category;
상품과 카테고리가 oneToOne인 것은 이상합니다.
카테고리 하나에 여러 상품이 올 수 있습니다.
Product 입장에서는 ManyToOne이 되어야 합니다.

도메인적으로 좀 더 생각해보면 이해가 쉬우실 겁니다.
가전이라는 카테고리 하나가 있고, 그 카테고리 안에 티비, 청소기, 냉장고 등 다양한 상품이 들어오게 되기 때문입니다.

2024-07-16 15:59 UTC, khj68 commented on src/test/java/gift/CategoryEntityRepositoryTest.java
> +        String expectedDescription = "test4";
테스트이더라도 어느정도 필드와 연관성 있는 값을 설정해주는 것을 추천드립니다.
testName, testColor, testUrl 등이 되겠습니다.

2024-07-16 15:59 UTC, khj68 commented on src/test/java/gift/WishEntityRepositoryTest.java
>          MemberEntity member = new MemberEntity("a","b", Role.CONSUMER);
테스트이더라도 어느정도 유추 가능한 이름을 넣어두어야 추후 유지보수가 편리합니다.

2024-07-17 05:05 UTC, 2iedo commented on src/main/java/gift/Model/DTO/CategoryDTO.java
> +public record CategoryDTO(Long id, String name, String color, String imageUrl, String description) {
수정 완료했습니다!

2024-07-17 05:07 UTC, 2iedo commented on src/main/java/gift/Model/Entity/ProductEntity.java
> +        private CategoryEntity category;
제품 하나당 카테고리 하나가 추가된다고 생각해서 oneToOne을 했었는데, 생각해보니 카테고리 하나를 여러 제품이 가질 수 있는 것 같습니다. 제가 잘못 생각했네요ㅠㅠ
수정 완료했습니다!

2024-07-17 05:16 UTC, 2iedo commented on src/test/java/gift/CategoryEntityRepositoryTest.java
> +        String expectedDescription = "test4";
수정 완료했습니다!

2024-07-17 05:16 UTC, 2iedo commented on src/test/java/gift/WishEntityRepositoryTest.java
>          MemberEntity member = new MemberEntity("a","b", Role.CONSUMER);
수정 완료했습니다!

2024-07-17 16:05 UTC, khj68 commented on src/main/java/gift/Model/DTO/CategoryDTO.java
> +public record CategoryDTO(Long id, String name, String color, String imageUrl, String description) {
말씀하신대로 힌트가 정답은 아니니 요구사항을 최우선으로 보아주시면 되겠습니다!
고생하셨습니다 :)

2024-07-17 16:05 UTC, khj68 approved these changes
반영 확인했습니다.
고생하셨습니다 :)

2024-07-17 16:06 UTC, merged

2024-07-17 16:27 UTC, 2iedo commented on src/main/java/gift/Model/DTO/CategoryDTO.java
> +public record CategoryDTO(Long id, String name, String color, String imageUrl, String description) {
감사합니다!