경북대 BE_도기헌 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #106
Opened 2024-07-16 06:34 UTC by Dockerel

안녕하세요! 이번 4주차 1단계 과제는 상품의 카테고리 추가하기였습니다. 상품당 하나의 카테고리만을 가지고 두번째 카테고리는 고려하지 않는다는 조건으로 보아 category - product 간에 OneToMany 관계를 매핑해야 하는 것으로 보여 해당 방식으로 구현하였습니다. 이때 상품이 무조건 카테고리를 가져야 한다는 조건이 존재하였습니다. 그래서 다음과 같은 방식으로 구현해보았습니다.

**1.** 상품에 매핑되어 있는 카테고리가 삭제되는 경우
&rarr; 해당 카테고리를 가지는 상품들에게 DefaultCategory를 부여한 후 카테고리 삭제

위 방식을 사용하면 상품에 카테고리가 null이 아님을 보장가능합니다. 하지만 위 방법을 사용함으로써 만약 상품의 카테고리가 변경될 시 카테고리 또한 처리해주어야 했습니다 그래서 만약

**2.** 상품의 카테고리가 변하는 경우
&rarr; 해당 카테고리에 매핑되어 있는 상품 리스트에서 해당 상품 삭제

위와 같은 방식으로 구현하였으니 해당 부분에 대해 집중적으로 봐주시면 감사하겠습니다! 😊

## 1단계 질문
**1.** 해당 카테고리 객체에 저장되어 있는 상품 리스트에서 해당 상품을 삭제할 때 아래와 같은 방식으로 삭제하였습니다.
```java
public void removeProduct(Product product) {
        products.remove(product);
    }
```
다행히 정상적으로 작동은 하지만 해당 방식이 효율적인지는 잘 모르겠습니다. 혹시 더 나은 구현 방식이나 처리 방식이 존재할까요??

**2. ** 이번 월요일 실시간 강의 시간 때 mockito 테스트 방식에 대해 배웠습니다. 이번 과제에서 사용해보는걸 추천한다고 말씀하셨습니다. 그래서 categoryService에서 사용해보려 하였으나 실질적으로 사용하기 개인적으로 애매한 느낌이 들어 결국 사용하지 못하였습니다. mockito가 가짜 객체를 만들어 스프링 컨텍스트를 만드는 SpringBootTest보다 빠른 속도로 단위 테스트를 하기 좋다는 것 까지는 이해를 하였습니다. 또한 mock 객체를 만들어 정해진 결과를 만들어 놓고 테스트를 진행한다는 것까지도 이해를 하였습니다. 하지만 정해진 결과만 내놓는 것이면 해당 테스트를 사용할 이유가 있는건지 잘 모르겠습니다. 제가 만든 service 클래스에서만 사용하기가 애매하여 그런 느낌이 드는 것인지 궁금합니다. mockito를 사용하여 테스팅 하기좋은 예시가 있을까요?

감사합니다!

2024-07-16 16:15 UTC, gongdongho12 requested changes
매번 리뷰마다 저도 마음의 준비를 하고 들어오게 되네요 😎 
4주차 1단계 작업하시느라 고생 많으셨습니다

### 질의응답

> 1. 해당 카테고리 객체에 저장되어 있는 상품 리스트에서 해당 상품을 삭제할 때 아래와 같은 방식으로 삭제하였습니다.
```kotlin
public void removeProduct(Product product) {
        products.remove(product);
    }
```

실제 연관관계로 매핑해두고 삭제를 매핑에서 지우면 commit이 일어날 때까지 실 데이터 반영이 되지 않아서 걱정하는 걸까요?
만약 제가 저런 구조형태를 유지해서 삭제작업을 만들어야 한다면 entity 그대로가 아닌 id를 파라미터로 받아서 removeIf로 아이디만 지워서 사용할 것 같은데 이 부분이 궁금하셨을까요?
대답이 되었을지는 모르겠지만 어떤 부분이 효율적이지 않은지 작성해주시면 좋을 것 같습니다

> **2. ** 이번 월요일 실시간 강의 시간 때 mockito 테스트 방식에 대해 설명해주셨고 이번 과제에서 사용해보는걸 추천한다고 말씀하셨습니다. 그래서 categoryService에서 사용해보려 하였으나 실질적으로 사용하기 개인적으로 애매한 느낌이 들어 결국 사용하지 못하였습니다. 스프링 컨텍스트를 만드는 SpringBootTest보다 mockito가 가짜 객체를 만들어 빠른 속도로 단위 테스트를 하기 좋다는 것 까지는 이해를 하였습니다. 또한 mock 객체를 만들어 정해진 결과를 만들어 놓고 테스트를 진행한다는 것까지도 이해를 하였습니다. 하지만 정해진 결과만 내놓는 것이면 해당 테스트를 사용할 이유가 있는건지 잘 모르겠습니다. 제가 만든 service 클래스에서만 사용하기가 애매하여 그런 느낌이 드는 것인지 궁금합니다. 혹시 mockito를 사용하여 테스팅 하기 좋은 예시가 있을까요?

Mocking을 각각의 레포지토리에 구현하고, A사용자의 데이터를 입력했을 때 나오는 실제 DB의 값들을 미리 정의해둔 다음
실제 서비스에서 그 모킹된 레포지토리에 연결되서 비지니스 로직(로그인 토큰 발급 등)이 일어나게 되면 미리 모킹된 데이터를 바탕으로 DB없이 서비스단의 비지니스 로직을 동작시켜 테스트 할 수 있게 됩니다

현재 말씀주신 고민의 경우에는 아직 조회나 Validation 정도의 기능 밖에 없는 서비스를 이렇게 테스트하는게 의미가 있을까 하는 느낌이셨을 거에요 (사실 구현도 JPA나 DB 연결에 더 고생을 했으니까요)

하지만 데이터로 금액 계산이나 할인 등 중요한 로직들이 서비스 레벨에 포함되고, 상품 금액 10000, 쿠폰 1000, 신규 사용자 대상으로만 첫구매 프로모션 50% 적용 등이 서비스 단에 존재한다면, DB 조회에 대한 부분보다 실제 금액에 대한 연산 결과가 더 중요하게 작용할 수 있겠죠?

2024-07-16 16:15 UTC, gongdongho12 commented on src/main/java/gift/service/CategoryService.java
> +        }
이렇게 되면 실제 카카오톡 쇼핑하기에서 그 많은 상품의 카테고리를 업데이트 하게 되는데요
모든 상품에 대한 업데이트라 부하가 많이 심해지지 않을까요?

### 정답은 아니지만 기헌님 코드를 보고 드는 생각
만약 프로젝트 레벨이라면 위에 카테고리가 없으면 exception 나는 것 대신, defaultCategoryId로 조회시에 대체하는 방식으로 가는 것은 어떨까요?

2024-07-16 16:15 UTC, gongdongho12 commented on src/main/java/gift/controller/rest/WishlistController.java
> +    }
API 처리인데 일반적으로 웹에서 사용하는 데이터 규격인 json으로 주지 않고 단순 body string으로 주신 이유가 있을까요?

2024-07-16 16:15 UTC, gongdongho12 commented on src/main/java/gift/entity/Category.java
> +    }
commit 순서가 가장 마지막이라 큰 차이는 아니겠지만,
카테고리 지정한 상품을 상품 목록에 추가의 순서가 일반적이지 않을까요?

2024-07-16 16:15 UTC, gongdongho12 commented on src/main/java/gift/service/CategoryService.java
> +        category.setDescription(categoryDTO.getDescription());
이런 경우에 category에 DTO를 파라미터로 하는 메서드에서 저 동작들을 같이 처리해주면 어떨까요?

2024-07-16 16:15 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +                .orElseThrow(() -> new ResourceNotFoundException("Category not found with id: " + id));
이 로직 같은 경우에는 실제로 카테고리 서비스 같은 부분에서 진행되고
프러덕트 서비스에서 카테고리 서비스의 getCategory 조회하는 메서드로 공통화하는 방향이 좋지 않을까요?

스프링은 일반적으로 빈 객체를 주입해서 사용하는 DI 패턴을 이용하는데요
빈의 주입이 1:1이 아니라면 순환참조가 발생할 수 있어요

> as-is: 카테고리 서비스 - 카테고리 레포지토리 / 프러덕트 서비스 - 카테고리 레포지토리 형태
> to-be: 카테고리 서비스 - 카테고리 레포지토리 / 프러덕트 서비스 - 프러덕트 레포지토리

이렇게 간 이후 프러덕트 서비스에서의 카테고리 대응은 카테고리 서비스를 불러서 사용하는게 일반적이지 않을까요?

2024-07-16 16:15 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        product.setCategory(category);
이부분도 product 객체에 update 메서드로 캡슐화 하면 깔끔해지죠?

2024-07-16 16:15 UTC, gongdongho12 commented on src/main/resources/sql/schema.sql
> +VALUES ('DefaultCategory', '#FFFFFF', '', '');
이렇게 에러가 발생했을 때 대응될 수 있는 임시 데이터 정의해두는 부분은 좋은 설계라구 생각해요 💯

2024-07-16 16:15 UTC, gongdongho12 commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +            products.add(new ProductDTO("name" + Integer.toString(i), i, "imageUrl" + Integer.toString(i), 1L));
fixture의 역할을 분리하신 부분 너무 좋네요👍🏼
시간나실 때 test fixture를 분리하는 방안에 대해 한번 찾아보시면 좋을 것 같아요

2024-07-16 16:15 UTC, gongdongho12 commented on src/test/java/gift/util/ProductNameValidatorTest.java
> +        ProductDTO product = new ProductDTO(wrongName, 123, "www.test.com", 1L);
테스트가 대부분 같은 값인데요, 실제 상품은 여러 다른 상품이 들어올 수 있어서 실제 상황 그대로를 적용할 수는 없지만, 데이터셋을 다채롭게 해보는 것도 좋은 방향일 것 같아요

그래도 케이스는 잘 구성해주셨습니다 👍🏼

2024-07-16 16:15 UTC, gongdongho12 commented on src/test/java/gift/service/ProductServiceTest.java
> +        em.clear();
영속성 처리도 세세하게 👍🏼

2024-07-17 05:35 UTC, Dockerel commented on src/main/java/gift/service/CategoryService.java
> +        }
없는 카테고리 id로 조회 시 defaultCategory를 리턴하는 방식이 정말 좋은 것 같습니다! 

그리고 해당 방식이면 엔티티간에 연관관계를 딱히 사용할 필요가 없을 것 같아 삭제하고 그냥 product에서 categoryid 필드만 관리하도록 해보았습니다!

2024-07-17 05:39 UTC, Dockerel commented on src/main/java/gift/controller/rest/WishlistController.java
> +    }
post, delete mapping시 보통 post되어 만들어진 결과를 json으로 리턴하는 것이 일반적이지만 해당 post는 위시리스트에 상품을 추가하는 기능이라 추가된 한 상품만 리턴하기도 이상하고 그렇다고 지금 위시리스트에 담겨있는 모든 상품을 리턴해주기도 이상하여 String 형태로 리턴으로 처리했던 것 같습니다.

일단은 
```java
Map<String, String> response = new HashMap<>();
response.put("message", "Product added to wishlist");
return ResponseEntity.status(HttpStatus.OK).body(response);
```
위와 같은 방식으로 그나마 json 형태로 결과값을 message 필드에 넣어 반환하게 바꾸어 보았는데 혹시 위에서 말했던 대로 리턴해야 할까요?

2024-07-17 05:39 UTC, Dockerel commented on src/main/java/gift/entity/Category.java
> +    }
아하! 그런 것 같습니다. 이번에는 연관관계를 삭제해버려서 바꾸지 못하였지만 다음에 연관관계 지정시 주의해서 지정해보겠습니다!

2024-07-17 05:40 UTC, Dockerel commented on src/main/java/gift/service/CategoryService.java
> +        category.setDescription(categoryDTO.getDescription());
넵넵! Category 엔티티에 DTO를 받아와 설정하는 메서드를 추가해보았습니다~!

2024-07-17 05:48 UTC, Dockerel commented on src/main/java/gift/service/ProductService.java
> +                .orElseThrow(() -> new ResourceNotFoundException("Category not found with id: " + id));
일단 ProductService에서 CategoryService를 주입받아 처리하는 방식으로 바꾸긴 했습니다! 그런데 이해가 잘 가지않는 부분이 있습니다. 스프링 빈의 순환 참조에 대해 말씀하셨는데

프러덕트 서비스 - 카테고리 레포지토리

와 같은 경우는 순환참조가 발생하지 않고 오히려

프러덕트 서비스 - 카테고리 서비스

이렇게 참조하는 경우가 오히려 프러덕트 서비스 - 카테고리 서비스간에 순환참조가 발생할 수도 있지 않나요? 서비스 간에는 참조할 수도 있지만 어차피 레포지토리 클래스들은 어떠한 참조도 하고있지 않은 상태라 오히려 일반적으로 레포지토리를 참조해오는 경우가 더 안전하지 않나요? 만들어진 프로젝트마다 다를수도 있을까요?

그와 별개로 멘토님이 위에서 제안해주신 defaultCategory 리턴 방식으로 개선하며 존재하지 않는 categoryid로 조회 시 deafultCategory를 리턴해주는 부분을 service에서 처리하였기 때문에 service를 불러서 사용하는 것이 더 나을 것 같아 해당 방식으로 리펙터링 해보았습니다!

2024-07-17 05:49 UTC, Dockerel commented on src/main/java/gift/service/ProductService.java
> +        product.setCategory(category);
네넵! 해당 방식도 처리해놓았습니다!

2024-07-17 05:49 UTC, Dockerel commented on src/main/resources/sql/schema.sql
> +VALUES ('DefaultCategory', '#FFFFFF', '', '');
감사합니다😊

2024-07-17 05:50 UTC, Dockerel commented on src/test/java/gift/repository/ProductRepositoryTest.java
> +            products.add(new ProductDTO("name" + Integer.toString(i), i, "imageUrl" + Integer.toString(i), 1L));
아하 넵! 한번 알아보고 다음 과제에 적용해보겠습니다~!

2024-07-17 05:52 UTC, Dockerel commented on src/test/java/gift/util/ProductNameValidatorTest.java
> +        ProductDTO product = new ProductDTO(wrongName, 123, "www.test.com", 1L);
아하 넵! 다음부터는 더 다양하게 테스트셋을 구성해보겠습니다!

2024-07-17 05:52 UTC, Dockerel commented on src/test/java/gift/service/ProductServiceTest.java
> +        em.clear();
👍👍

2024-07-17 12:35 UTC, gongdongho12 commented on src/main/java/gift/controller/rest/WishlistController.java
> +    }
서비스 관점에서 개발할 떄 규격이 다양화 되어있으면 별도로 세팅을 해줘야 하니까요
API를 단순 문자열도 사용하고, JSON을 사용하면 불편하니 컨벤션으로 통일해주면 어떤가 하는 의견이었습니다
말씀주신대로 message로 표현하면 json 타입으로 받아서 편리하겠죠?

2024-07-17 12:47 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +                .orElseThrow(() -> new ResourceNotFoundException("Category not found with id: " + id));
순환참조라는 명칭으로 잘못 사용했네요 🤣
관리포인트를 1:1로 구성해서 기능을 적용할 때 레이어를 침범하는 현상을 방지하는 용도 정도로 생각해주시면 좋을 것 같습니다

2024-07-17 12:47 UTC, gongdongho12 approved these changes
고생하셨습니다

2024-07-17 12:48 UTC, merged