경북대 BE_배규민 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #108
Opened 2024-07-16 07:09 UTC by GyuminBae

* 4주차 1단계 과제입니다!
* 상품 추가 시 카테고리 존재 여부를 체크하고 있으면 기존 카테고리 사용, 없으면 새로 생성하는 식으로 만들었습니다!

2024-07-16 14:50 UTC, lsm7179 requested changes
규민님 과제 잘 진행해주셨습니다.
몇가지 피드백드렸는데 확인해보시고 반영해보세요.
화이팅입니다.🔥

2024-07-16 14:50 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/ProductCategoryEntity.java
> +    private Long id;
요구사항이 생길수록 계속해서 엔티티 클래스에 반복되는 id
baseEntity를 도출해보세요.
https://devfunny.tistory.com/684

2024-07-16 14:50 UTC, lsm7179 commented on src/main/java/gift/product/restapi/ProductCategoryController.java
> +    }
nit: 지난주에 사용했던 paging 처리도 하면 좋을거 같습니다.😁

2024-07-16 14:50 UTC, lsm7179 commented on src/main/java/gift/product/restapi/dto/response/ProductResponse.java
> +                product.category().name()
우리의 코드가 디미터의 법칙을 준수할수있도록 수정해보세요.
다른곳도 같이 확인해주세요~
https://mangkyu.tistory.com/147

2024-07-16 14:50 UTC, lsm7179 commented on src/main/java/gift/product/service/ProductServiceImpl.java
> +    @Transactional
👍

2024-07-16 14:50 UTC, lsm7179 commented on src/test/java/gift/product/ProductRepositoryTests.java
>      public void saveProduct() {
`@DisplayName` 어노테이션을 이용하면 어떤 검증을 하는지 다른 개발자에게 잘 알려줄수있습니다.

2024-07-16 14:50 UTC, lsm7179 commented on src/main/java/gift/core/domain/product/Product.java
>                  price != null ? price : this.price(),
price는 0보다 작아도 등록되어도 될까요?

2024-07-16 14:50 UTC, lsm7179 commented on src/test/java/gift/wishes/WishRepositoryTests.java
> +        ProductEntity product = new ProductEntity("test", 100, "test", category);
각 테스트 코드에서 반복되어지네요.
`@BeforeEach` 를 사용해보세요.

2024-07-16 14:50 UTC, lsm7179 commented on src/test/java/gift/wishes/WishesServiceTests.java
> +        );
각 테스트 코드에서 반복되어지네요.
@BeforeEach 를 사용해보세요.
또는 필드로 빼서 작성할수도있습니다. TestFixture 개념을 한번 도입해보세요.

2024-07-16 18:33 UTC, GyuminBae commented on src/main/java/gift/product/restapi/ProductCategoryController.java
> +    }
반영했습니다!

2024-07-16 18:33 UTC, GyuminBae commented on src/main/java/gift/core/domain/product/Product.java
>                  price != null ? price : this.price(),
컨트롤러단 유효성 검사에서 막도록 수정했습니다!

2024-07-16 18:44 UTC, GyuminBae commented on src/test/java/gift/product/ProductRepositoryTests.java
>      public void saveProduct() {
반영했습니다!

2024-07-16 18:45 UTC, GyuminBae commented on src/test/java/gift/wishes/WishRepositoryTests.java
> +        ProductEntity product = new ProductEntity("test", 100, "test", category);
반영했습니다!

2024-07-16 18:47 UTC, GyuminBae commented on src/test/java/gift/wishes/WishesServiceTests.java
> +        );
반영했습니다!

2024-07-16 18:59 UTC, GyuminBae commented on src/main/java/gift/product/infrastructure/persistence/ProductCategoryEntity.java
> +    private Long id;
반영했습니다!

2024-07-17 13:18 UTC, lsm7179 commented on src/main/java/gift/core/BaseEntity.java
> +    private Long id;
👍

2024-07-17 13:22 UTC, lsm7179 commented on src/main/java/gift/core/domain/product/Product.java
>                  price != null ? price : this.price(),
유효성검사에서 막는것과 도메인 비즈니스 로직에서 처리하는건 다릅니다.
상품을 서비스나 repo계층에서도 사용하기 때문에 상품쪽에 코드를 작성하는것이 좋을거 같습니다.

2024-07-17 13:23 UTC, lsm7179 approved these changes
규민님 1단계 잘 정리해주신거 같아요.
머지하겠습니다.

2024-07-17 13:23 UTC, merged

2024-07-17 13:24 UTC, lsm7179 commented on src/main/java/gift/product/restapi/dto/response/ProductResponse.java
> +                product.category().name()
이부분은 다음단계에서 꼭 수정해주세요.