전남대 BE_박준형 4주차 과제(step1)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #113
Opened 2024-07-16 09:34 UTC by cliant

이번 주 클론코딩 강의를 듣고 한 번에는 어렵더라도 주차별 과제를 진행하며 조금씩 테스트 코드를 추가해보고자 하고있습니다!

### 코드를 작성하며 어려웠던 점

-  아직 해결하지 못한 문제이긴 한데.. 프로덕트가 추가된 후 다시 api/products로 리다이렉트 되어 돌아오면 추가된 상품이 admin_page에 표시되지 않는 현상이 나타납니다. 동작 쿼리 로그를 통해 저장과 조회가 일어나고 있음은 확인했습니다. 다만 이게 왜 페이지에 나타나지 않는지 이유를 찾기 어려워 이에 대해 제가 실수한 부분이 있는지 질문드리고 싶습니다!

### 코드 리뷰시 중점적으로 봐주셨으면 하는 부분

- 1,2,3주차 리뷰를 돌아보면 리뷰어님이 수정하지 않아도 될 부분이라도 왜 이렇게 코딩을 했냐는 질문이 저에겐 다시 생각해볼 기회를 주어 큰 도움이 됐던거 같습니다. 최대한 근거를 가지고 코딩을 하려하지만 무심코 예제코드를 따라서 ,혹은 기존 코드처럼, 이런 식으로 코딩을 하는 경우들이 있기 때문에 이런 부분들이 보인다면 짚어주셨으면 합니다.

2024-07-17 13:11 UTC, jjongwa requested changes
1단계 진행하느라 수고 많으셨어요!

에러가 발생하는 원인은 CategoryService의 getCategories()인 것 같네요!
해당 부분을 중점적으로 흐름을 다시 한 번 점검해 보시길 바랍니다!

2024-07-17 13:11 UTC, jjongwa commented on src/main/java/gift/controller/CategoryController.java
> +    private CategoryService categoryService;
초기 생성 시에 할당되고 변경될 일이 없는 필드에는 final을 붙여주는게 좋습니다!

`private final CategoryService categoryService;`

final 키워드가 무엇이고 어떤 효과를 가지는지 알아볼까요?

2024-07-17 13:11 UTC, jjongwa commented on src/main/java/gift/controller/CategoryController.java
> +    }
Product와 Wish에서는 따로 response 객체를 만들어 이를 반환했는데, 여기선 그러지 않은 이유가 있을까요~?

2024-07-17 13:11 UTC, jjongwa commented on src/main/java/gift/controller/CategoryController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
보통 새로운 데이터가 생성되었음을 응답하는 Statatus는 201 Created를 사용합니다!

200번대에서 500번대의 HttpStatus 중 자주 쓰이는 것들에 대해 정리해 보면 좋을 것 같네요!

2024-07-17 13:11 UTC, jjongwa commented on src/main/java/gift/dto/ProductDto.java
>      }
카테고리를 받아 product를 만드는 작업을 productDto가 맡는게 약간 어색하게 느껴지네요..!
dto의 목적은 무엇이고, 어떤 역할만을 담당해야 할까요?

2024-07-17 13:11 UTC, jjongwa commented on src/main/java/gift/entity/Category.java
> +@Table(name = "category")
해당 줄을 제거했을 때, db에서 카테고리 테이블의 이름은 어떻게 생성될까요?

2024-07-17 13:11 UTC, jjongwa commented on src/main/java/gift/entity/Category.java
> +    private List<Product> products;
category와 product를 양방향 관계로 설정한 이유는 무엇인가요?

FetchType과 orphanRemoval에는 각각 어떤 설정들이 존재하나요?

2024-07-17 13:11 UTC, jjongwa commented on src/main/java/gift/entity/Product.java
>      }
마찬가지로 dto를 만드는 로직을 꼭 엔티티가 가져야 할 필요가 있을까요?

그냥 dto의 생성자를 통해 만들어 내는 것과 어떤 차이가 있을까요?

2024-07-17 13:11 UTC, jjongwa commented on src/main/java/gift/service/CategoryService.java
> +        }
현재 해당 로직은 product를 조회할 때마다 함께 호출되는데, 이 때문에 에러가 발생하고 있어요!

<img width="428" alt="image" src="https://github.com/user-attachments/assets/c11c61fb-81af-418d-a64e-b0aff837c78d">

이러한 로직이면 새로운 상품을 추가할 때마다 test와 test2라는 카테고리를 다시 save하게 되고, test와 test2라는 이름의 카테고리는 이미 존재하기 때문에 유니크 조건에 걸려 에러가 발생하게 됩니다!

test와 test2 같은 기본 세팅된 카테고리를 넣어주려면 어떤 방법이 있을까요?

2024-07-17 13:11 UTC, jjongwa commented on src/main/java/gift/service/CategoryService.java
> +        }
자바17부턴 그냥 .toList(); 로 해도 됩니다~!
```
return categories.stream()
                .map(CategoryDto::fromEntity)
                .toList();
```

2024-07-18 06:08 UTC, cliant commented on src/main/java/gift/controller/CategoryController.java
> +    private CategoryService categoryService;
final에 대해서는 변수를 상수로 만들어준다! 정도로 알고 정확한 쓰임새에 대해서는 인지하지 못하고 있었습니다. spring에서의 final사용에 대해 공부하며, final 키워드를 추가해줌으로써 컨트롤러에서 서비스의 기능을 사용하는 동안 서비스의 기능은 변화하지 않는다는 의미를 암시하며 코드가 복잡해지고 기능이 많아질 수록 꼭 필요한 요소임을 알게되었습니다.

2024-07-18 06:09 UTC, cliant commented on src/main/java/gift/controller/CategoryController.java
> +    }
현재 요구사항에서는 List<CategoryDto>만 반환해주어도 괜찮을 것 같다는 생각이 들어 이렇게 하였습니다. 다만 나중에 코드 유지보수를 위해 Response객체를 추가하였습니다!

2024-07-18 06:10 UTC, cliant commented on src/main/java/gift/controller/CategoryController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
넵! 반영하였습니다. 추가적으로 CRUD 작업이 완료 되었을 때 자주 쓰이는 것들에 대해서도 학습해봤습니다.

2024-07-18 06:13 UTC, cliant commented on src/main/java/gift/dto/ProductDto.java
>      }
DTO는 말 그대로 데이터 이동에만 사용되어야 되는데 코드를 작성하다보니 편의상 toEntity를 Dto에 만들어 사용했던 것 같습니다. 이를 Service에서 하게끔 코드를 변경하였습니다. 추가적으로 DTO에서 fromEntity라는 메서드를 사용중인데 이 또한 Service에서 실행하게끔 하여 DTO에는 멤버 필드, getter, setter만 두는게 나을지 궁금합니다!

2024-07-18 06:18 UTC, cliant commented on src/main/java/gift/entity/Category.java
> +@Table(name = "category")
클래스명을 테이블 이름으로 하여 생성됩니다. 다만 대소문자를 구분하는 Spring Boot의 DB Physical Naming Strategy때문에 category라는 이름 그대로 테이블을 생성하게 됩니다.

2024-07-18 06:23 UTC, cliant commented on src/main/java/gift/entity/Category.java
> +    private List<Product> products;
1. 양방향 관계로 설정한 이유는 양방향 참조가 가능해야된다고 생각했기 때문입니다. 단적으로 제가 경험한 선물하기에서는 상품에서 카테고리를 볼 수 있고, 카테고리를 이용한 상품조회도 가능했기 때문입니다.

2. FetchType는 지연로딩에 관한 옵션이며 두가지 전략이 존재한다고 공부하였습니다. EAGER 옵션은 연관 엔티티를 다 불러오지만 LAZY 필요할 때만 불러옵니다. 엔티티 모두에서 LAZY옵션을 사용해서 불필요한 데이터베이스 조회를 줄여야겠다 생각했습니다.

3. orphanRemove은 말그대로 고아 제거 옵션이며, Category1 을 참조하던 Product1 가 있다고 가정하면 Category1이 사라졌을 때 참조할 객체를 잃은 Product1도 함께 사라지는 옵션입니다. true와 false가 존재하며 true는 위와 같이 작동하고, false는 PK값이 NULL로 변경됩니다.

2024-07-18 06:26 UTC, cliant commented on src/main/java/gift/service/CategoryService.java
> +        }
//TEST 부분을 생성자로 이동하여 실행하였습니다. 이렇게 된다면 아까 final키워드를 붙여줬으므로 CategoryService가 한 번만 초기화될 때 이 test1, test2도 한 번만 저장될 것이라 생각했습니다.

2024-07-18 06:26 UTC, cliant commented on src/main/java/gift/service/CategoryService.java
> +        }
넵! 반영하였습니다.

2024-07-18 06:27 UTC, cliant commented on src/main/java/gift/entity/Product.java
>      }
사실 별 차이를 느끼지 못하였습니다. 그래서 toDto메서드를 삭제하고 그 자리에 DTO객체를 생성하여 리턴하도록 변경하였습니다.

2024-07-18 12:25 UTC, jjongwa commented on src/main/java/gift/dto/ProductDto.java
>      }
초기 할당된 값의 변경을 막기 위해 getter만 두는 걸 지향하긴 합니다.! (데이터의 계층간 전달만을 위한 객체인데 생성되고 중간에 내부 값이 바뀐다는게 의도에 맞지 않을 수 있기 떄문에)
하지만 필드가 많은 경우에는 setter도 열어두기도 해요!

2024-07-18 12:30 UTC, jjongwa commented on src/main/java/gift/entity/Category.java
> +    private List<Product> products;
그럼 현재 설정에서 상품이 삭제되면 어떤 변화가 있을까요?

그리고 만약 카테고리라는 개념이 서비스가 운영되며 손쉽게 추가/변경/삭제가 된다면 각각의 상품들은 어떻게 처리해 줄 수 있을까요?

정답은 없지만 이러한 고민들을 하다 보면 연관관계를 걸어야 할지, 건다면 단방향으로 걸지 양방향으로 걸지에 대해 기준이 세워지겠네요,!

2024-07-18 12:33 UTC, jjongwa commented on src/main/java/gift/entity/Product.java
>      }
만약 어떤 SuperDto라는 클래스가 존재하고, 해당 dto를 만드는 메서드인 toDto()가 Product, WishList, Category, Member 등에 각각 따로 존재한다고 가정해 볼까요?

이러한 상황에서 만약 SuperDto 라는 클래스를 삭제해야 한다면 어떻게 될까요? 변경이 일어나는 파일의 범위는 어디까지일까요?

2024-07-18 12:35 UTC, jjongwa commented on src/main/java/gift/service/CategoryService.java
> +        }
이러한 방법도 현재 규모에서는 충분한 처리이긴 하지만, 이렇게 기본으로 세팅되는 데이터들은 sql파일을 통해 정의해 주는게 좋습니다~!

2024-07-18 12:35 UTC, jjongwa approved these changes
리뷰 반영 확인했습니다! 이번 스텝은 머지할께요, step2로 가시죠~! 🚗 🚗

2024-07-18 12:36 UTC, merged

2024-07-18 13:30 UTC, cliant commented on src/main/java/gift/entity/Category.java
> +    private List<Product> products;
선물하기 기능을 생각해봤을 때 기준으로 생각해봤습니다.
- 카테고리 추가 : 자유

- 카테고리 변경 :  기존의 참조하고 있던 상품들의 카테고리를 NULL or 참조하고 있던 상품들의 카테고리를 임의의 카테고리(기타)로 변경 or 기존의 참조하고 있던 상품들의 카테고리를 변경되는 카테고리로 변경 3가지 방법 중 2,3번이 합리적인 것 같습니다.

- 카테고리 삭제 : 여기서는 기존의 참조하고 있던 상품들의 카테고리를 NULL or 참조하고 있던 상품들의 카테고리를 임의의 카테고리(기타)로 변경 or 참조하고 있던 상품들도 삭제 3가지 방법 중 2번째 방법이 젤 합리적이라 생각합니다.

2024-07-18 14:06 UTC, cliant commented on src/main/java/gift/entity/Product.java
>      }
모든 entity가 superDto를 사용하게 된다면 controller부터 entity까지 거의 전범위의 파일을 수정해야될 것 같습니다.