충남대 BE_정현서 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #116
Opened 2024-07-16 09:53 UTC by hynseoj

안녕하세요 멘토님.
1단계 과제 제출합니다.

카테고리는 클라이언트가 생성, 수정, 삭제할 수 없고 또 카테고리 하나만 조회 요청하는 경우는 없다고 생각해 전체 조회 기능만 구현했습니다.

그리고 카테고리를 상품 도메인에 넣어보았는데... 적절한지 잘 모르겠습니다.
카테고리는 "상품 카테고리"로 상품 도메인에서만 쓰인다고 생각되어 저렇게 해봤는데 수정이 필요하다고 생각하시는지 궁금합니다.

감사합니다~!

2024-07-16 10:35 UTC, ksy90101 requested changes
1단계 고생 많으셨습니다~
간단한 피드백을 남겼으니 확인해주시면 감사하겠습니다!
궁금한게 있다면 언제든 DM주세요!

2024-07-16 10:35 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Category.java
> +    private String color;
color라는 것이 "##6c95d1"이렇게 들어올거 같은데
color code를 정규표현식으로 validate를 해보면 어떨가 생각이 드네요!

참고링크 :https://stackoverflow.com/questions/1636350/how-to-identify-a-given-string-is-hex-color-format

2024-07-16 10:35 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Category.java
> +    }
기본생성자를 jpa를 만들면 무조건 생성해야 하긴 하지만, protected로 해서 좀더 접근제어를 좁혀봐도 좋을거 같습니다.

2024-07-16 10:35 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Category.java
> +    private String imageUrl;
여기서도 url에 대한 validate를 해보면 어떨가 생각이 듭니다!

2024-07-16 10:35 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Category.java
> +    private String description;
카테고리의 설명이 얼마나 길수 있을까요?
과연 지금 255자로 충분할까요?

한번 Lob를 알아보시고 사용해야할지 고민해보면 어떨까요?

2024-07-16 10:35 UTC, ksy90101 commented on src/main/java/gift/domain/product/repository/ProductJpaRepository.java
> +    @Query("select distinct p from Product p join fetch p.category")
distinct를 넣은 이유가 잇나요?

2024-07-16 10:35 UTC, ksy90101 commented on src/test/java/gift/domain/product/service/CategoryServiceTest.java
> +}
readById
이 메서드 테스트도 넣어두면 좋지 않을까요?

2024-07-16 10:35 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/CategoryRestController.java
> +    public ResponseEntity<List<Category>> readAll() {
DTO를 쓰지 않은 이유가 있나요?

참고링크 : https://hstory0208.tistory.com/entry/SpirngJPA-Dto%EC%99%80-Entity%EB%A5%BC-%EB%B6%84%EB%A6%AC%ED%95%B4%EC%84%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

https://kgvovc.tistory.com/64

2024-07-16 10:38 UTC, hynseoj commented on src/main/java/gift/domain/product/entity/Category.java
> +    private String color;
맞습니다! 생각은 했었는데 코드 작성 중에 잊어버렸습니다.. 적용하겠습니다!

2024-07-16 10:38 UTC, hynseoj commented on src/main/java/gift/domain/product/entity/Category.java
> +    }
넵!!

2024-07-16 10:38 UTC, hynseoj commented on src/main/java/gift/domain/product/entity/Category.java
> +    private String imageUrl;
아하! 네 수정하겠습니다!

2024-07-16 10:40 UTC, hynseoj commented on src/main/java/gift/domain/product/entity/Category.java
> +    private String description;
충분하지 않을 것 같습니다. 찾아보고 수정해보겠습니다~!

2024-07-16 10:53 UTC, hynseoj commented on src/main/java/gift/domain/product/repository/ProductJpaRepository.java
> +    @Query("select distinct p from Product p join fetch p.category")
N+1 문제에 대해 알아보던 중에 다대일(N:1) 연관 관계를 가지고 있는 경우 "1" 쪽의 객체가 N만큼 생성되는 문제를 distinct로 해결한다고 해서 충분히 이해하지 못하고 일단.. 작성했었는데,
주신 코멘트 보고 다시 생각해보니 지금 product 쪽은 "N" 쪽 엔티티라 distinct가 필요 없을 것 같습니다! 제거하도록 하겠습니다.

지난 주에 작성했던 UserJpaRepository와 WishlistJpaRepository의 distinct도 필요 없어 보여 함께 제거하겠습니다.
혹시 필요한데 제가 잘못 생각한 것이라면 정정 부탁드립니다..!

2024-07-16 10:55 UTC, hynseoj commented on src/test/java/gift/domain/product/service/CategoryServiceTest.java
> +}
빠트렸네요.. 수정하겠습니다!

2024-07-16 10:59 UTC, hynseoj commented on src/main/java/gift/domain/product/controller/CategoryRestController.java
> +    public ResponseEntity<List<Category>> readAll() {
없습니다. 1주차에 반환에는 DTO를 적용하지 않고 진행했는데 같은 코드에서 이어서 진행해오면서 다른 도메인의 Controller에도 아직 DTO를 적용하지 못해 Category도 일단 DTO를 사용하지 않았습니다.
수정하면서 이김에 다른 도메인까지 함께 적용하겠습니다!

2024-07-16 12:30 UTC, hynseoj commented on src/main/java/gift/domain/product/entity/Category.java
> +    private String description;
멘토님! 덕분에 Lob라는 걸 처음 알게 돼서 찾아보고 어노테이션으로 간단하게 적용도 한 번 해보았습니다.

그런데 고민해보니 상품 설명 같은 경우라면 255자로 부족할 것 같지만,
카테고리의 경우는 무엇을 포함하는지 간단한 설명만으로 충분할 것 같아 255자면 괜찮을 것 같다고 생각됩니다.

사실 예시에 description 필드가 있어서 포함했는데 '카테고리에 설명이 필요한가?' 하는 생각이 더 큽니다.
아주 간단한 설명 정도를 포함한다고 가정하고 구현하겠습니다!

2024-07-17 02:52 UTC, hynseoj commented
> 카테고리를 상품 도메인에 넣어보았는데... 적절한지 잘 모르겠습니다.
> 카테고리는 "상품 카테고리"로 상품 도메인에서만 쓰인다고 생각되어 저렇게 해봤는데 수정이 필요하다고 생각하시는지 궁금합니다.

추가적으로 지금 Wishlist를 요청할 때 `@LoginUser User user` 로 어노테이션을 통해 엔티티를 바로 받아오고 있는데 이 부분도 UserDto로 바꾸는 편이 좋을까요?
검증은 어차피 어노테이션으로 이루어지기도 하고, Dto를 사용하면 Service 계층에서 엔티티로 변환하는 코드가 추가되어 그냥 엔티티를 바로 사용해도 될 것 같다는 생각이 들어서 멘토님 의견이 궁금합니다!

2024-07-17 13:07 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Category.java
> +    private String description;
네네 가장 요구사항에서 잘 아는건 현서님이라고 생각합니다.
해당 키워드와 비교해봤으면 좋을거 같아서 제안드린거였습니다~
string인 경우 길이 제한이 항상 있기 때문에 놓치기 쉽거든요!

2024-07-18 02:46 UTC, ksy90101 commented
> 추가적으로 지금 Wishlist를 요청할 때 @LoginUser User user 로 어노테이션을 통해 엔티티를 바로 받아오고 있는데 이 부분도 UserDto로 바꾸는 편이 좋을까요?
검증은 어차피 어노테이션으로 이루어지기도 하고, Dto를 사용하면 Service 계층에서 엔티티로 변환하는 코드가 추가되어 그냥 엔티티를 바로 사용해도 될 것 같다는 생각이 들어서 멘토님 의견이 궁금합니다!

저는 엔티티로 처리하는 편입니다.
굳이 쿼리를 하나 더 늘릴 필요는 없어서요~

굿굿입니다.

2024-07-18 02:46 UTC, ksy90101 approved these changes
꼼꼼한 테스트 코드 굿입니다 👍 
고생하셨어요~ 다음단계에서 뵐게요!

2024-07-18 02:46 UTC, merged