경북대 BE_심규민 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #117
Opened 2024-07-16 10:27 UTC by sim-mer

### 궁금한 점
- 이번 step에서 mock을 이용한 단위테스트를 처음 작성하면서 Mock Repository에서 엔티티를 반환해야할 경우가 있었습니다. 보통 ID필드는 DB에서 자동으로 관리하므로 setter나 생성자를 통해 지정하지 않기에 리플렉션을 이용해 id필드를 설정하였습니다. 이렇게 리플렉션을 테스트코드에서 사용하는게 옳은 방식인지, 아니면 테스트를 위해 setter같은 메서드를 작성하는게 좋은 방법인지, 혹은 다른 방법이 있는지 궁금합니다!

2024-07-17 15:00 UTC, leaf-upper requested changes
1단게 고생많으셨습니다~
몇가지 코멘트와 질문에 대해서 답변드렸는데 확인해주시고 반영해주시면
어프로브 드리겠습니다
고생하셨습니다~ 👍

2024-07-17 15:00 UTC, leaf-upper commented on src/main/java/gift/global/exception/DBException.java
> +public class DBException extends RuntimeException {
이제부터는 조금더 발생할 수 있는 예외가 많아질것 같아요~
본인만의 추상 Exception Class를 선언하고 해당 클래스에서 ErrorCode와 details를 관리해보는것은 어떨까요?
네이밍은 ApplicationException, CustomException 등등 편하신 네이밍으로 진행해주시면 좋을것 같습니다.

2024-07-17 15:00 UTC, leaf-upper commented on src/main/java/gift/global/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(DBException.class)
ErrorResponseDto는 GlobalExceptionHandler 코드안에 포함시켜주시거나, 별도 파일로 빼주시면 좋을것 같아요. 탑레벨 클래스는 하나만 선언해서 사용하면 좋을것 같습니다.

2024-07-17 15:00 UTC, leaf-upper commented on src/main/java/gift/product/business/dto/CategoryDto.java
> +    public static List<CategoryDto> of(List<Category> categories) {
N:N 매핑을 만들어주신김에 1:1 매핑도 정적팩터리메서드로 생성해주시면 좋을것 같아요~

2024-07-17 15:00 UTC, leaf-upper commented on src/main/java/gift/product/business/service/CategoryService.java
> +    public Long updateCategory(Long id, CategoryRegisterDto categoryRegisterDto) {
업데이트에서는 등록Dto를 재활용하기보다는 UpdateDto를 별도로 선언해서 사용해보는것은 어떨까요? id값도 UpdateDto안에 포함시킬수있고, 업데이트할 수 있는 부분과 업데이트 할 수 없는 부분을 좀더 명시적으로 알 수 있을것 같아요

2024-07-17 15:00 UTC, leaf-upper commented on src/main/java/gift/product/persistence/repository/CategoryJpaRepository.java
> +public interface CategoryJpaRepository extends JpaRepository<Category, Long> {
CategoryRepository,
CategoryJpaRepository,
CategoryRepositoryImpl
이런 3단 구조로 사용하시는 이유가 있을까요?

2024-07-17 15:00 UTC, leaf-upper commented on src/main/java/gift/product/persistence/entity/Product.java
> +    public void setCategory(Category category) {
set도 좋지만 set은 자바에서 조금 관습적으로 사용하는 부분이 있어서
명시적으로 updateCategory라고 명명 해주시면 좋을것 같아요.

2024-07-17 15:00 UTC, leaf-upper commented on src/main/java/gift/product/persistence/entity/Category.java
> +    public Category() {
Jpa는 객체 생성후 리플렉션으로 값들을 세팅해주는데요, Category에 대한 파라미터 없는 생성자는, 최대한 외부에서 접근이 불가능하도록 protected로 사용해주시면 좋을것 같아요.

2024-07-17 15:00 UTC, leaf-upper commented on src/main/java/gift/product/persistence/entity/Category.java
> +    public Category() {
다른 도메인 엔티티도 같이 반영해주시면 좋을것 같아요~

2024-07-17 15:00 UTC, leaf-upper commented on src/main/java/gift/product/presentation/restcontroller/CategoryController.java
> +public class CategoryController {
해당 API는 인증을 타지 않아도 될까요?

2024-07-17 15:00 UTC, leaf-upper commented on src/test/java/gift/category/CategoryServiceTest.java
> +        category = new Category("name");
이번 step에서 mock을 이용한 단위테스트를 처음 작성하면서 Mock Repository에서 엔티티를 반환해야할 경우가 있었습니다. 보통 ID필드는 DB에서 자동으로 관리하므로 setter나 생성자를 통해 지정하지 않기에 리플렉션을 이용해 id필드를 설정하였습니다. 이렇게 리플렉션을 테스트코드에서 사용하는게 옳은 방식인지, 아니면 테스트를 위해 setter같은 메서드를 작성하는게 좋은 방법인지, 혹은 다른 방법이 있는지 궁금합니다!

이 질문에 대한 답변은 여기서 드릴게요~
리플렉션으로 이렇게 ID를 주입해주셔도 동작은 하겠지만 저는 이런 방식은 추천드리지 않아요. mockito를 사용하셨으니 Category또한 Mock 객체로 만들어서 사용하실 수 있을것 같습니다.
Mockito.doReturn()
Mockito.when() 참고해주시면 좋을것 같습니다

2024-07-18 00:13 UTC, sim-mer commented on src/main/java/gift/global/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(DBException.class)
넵 반영했습니다!

2024-07-18 00:13 UTC, sim-mer commented on src/main/java/gift/product/business/dto/CategoryDto.java
> +    public static List<CategoryDto> of(List<Category> categories) {
넵 추가했습니다!

2024-07-18 00:14 UTC, sim-mer commented on src/main/java/gift/product/persistence/entity/Product.java
> +    public void setCategory(Category category) {
변경했습니다!

2024-07-18 00:14 UTC, sim-mer commented on src/main/java/gift/product/persistence/entity/Category.java
> +    public Category() {
전부 반영했습니다!

2024-07-18 00:14 UTC, sim-mer commented on src/test/java/gift/category/CategoryServiceTest.java
> +        category = new Category("name");
변경했습니다!

2024-07-18 00:23 UTC, sim-mer commented on src/main/java/gift/product/presentation/restcontroller/CategoryController.java
> +public class CategoryController {
개인적인 생각으로는 단순히 Member에 대한 인증/인가를 수행하는 것이 아니라 Member별 권한을 부여하고 Category를 관리할 수 있는 권한이 있는 Member만 API에 접근하도록 해야할 것 같습니다!
그리고 만약 단순히 DB의 Member테이블에 권한이나 역할을 컬럼으로 저장한다면 매 인증과정 마다 항상 DB 커넥션이 일어날 것 같아 적절치 않아 보여 실제 실무에서는 어떻게 사용자들의 ROLE과 권한을 관리하는지 궁금합니다.

2024-07-18 01:13 UTC, sim-mer commented on src/main/java/gift/global/exception/DBException.java
> +public class DBException extends RuntimeException {
넵 그렇게 변경했습니다!

2024-07-18 01:34 UTC, sim-mer commented on src/main/java/gift/product/persistence/repository/CategoryJpaRepository.java
> +public interface CategoryJpaRepository extends JpaRepository<Category, Long> {
기본적으로는 service의 JpaRepository에 대한 의존성을 추상화해 결합도를 낮추기 위해서 인터페이스를 사용해 추상화하였습니다.
만약 Service에서 JPA에 강결합하게 된다면 DBMS의 변경이나 인프라의 변화가 있을때 비즈니스 코드에 영향이 가겠지만 추상화한다면 인프라 계층의 코드의 변경만 일어납니다. 또한 같은 맥락으로 인프라의 변화가 있을 때 Repository에 mock을 주입하여 사용하고 있었다면 테스트 코드의 변화도 없습니다.
이외에도 예외처리와 같은 동작들을 구현체에 정의하여 서비스 코드가 간결해지는 부가적인 장점도 있기에 이런 식으로 사용하고 있습니다.
- 이렇게 생각을 정리하다보니 Repository 인터페이스는 Persistence 계층이 아니라 Business 계층에 더 가까워 보이긴 합니다.

2024-07-18 02:58 UTC, sim-mer commented on src/main/java/gift/product/business/service/CategoryService.java
> +    public Long updateCategory(Long id, CategoryRegisterDto categoryRegisterDto) {
추가했습니다!

2024-07-18 13:23 UTC, leaf-upper approved these changes
넵 1단계 고생많으셨습니다
코멘트 코멘트 드린부분들 다 수정해주셔서 어프로브드릴게요 
고생하셨습니다! 👍

2024-07-18 13:23 UTC, merged