전남대 BE_김수랑 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #119
Opened 2024-07-16 11:05 UTC by rdme0

안녕하세요! 1단계 과제를 구현하게 되어 PR 올립니다

1. 엔티티 : 상품 -> 카테고리 단방향 관계로 구현하였습니다.
2. 상품 DTO : 상품 요청 DTO와 상품 응답 DTO로 분리하였습니다.
   - 이유 : 상품을 추가 할 때는 카테고리 이름만 필요하고, 상품을 조회할 때는 카테고리의 모든 정보가 필요함
3. 상품 CRUD에 관한 기능의 테스트 코드 추가하였습니다.
   - 각 계층별로 테스트 코드를 구현하였고, 그 계층과 맞닿아 있는 계층은 Mocking 하였습니다.
4. 서버를 Run 하는 순간에 "기타" 라는 카테고리를 DB에 넣도록 구현하였습니다.

2024-07-18 16:43 UTC, Hongdonggeon requested changes
안녕하세요 수랑님~
1단계는 비교적 간단해서 코멘트를 크게 남길게 없네요!
코멘트 확인해주시고! 
서비스, 컨트롤러 레이어에 테스트 코드가 category쪽만 작성되어 있는데, 다른 클래스들도 테스트 코드 작성해주시면 좋을 것 같아요~

2024-07-18 16:43 UTC, Hongdonggeon commented on src/main/java/gift/controller/CategoryController.java
> +    @Autowired
생성자 주입인데 `@Autowired`를 사용할 필요가 없을 것 같아요

2024-07-18 16:43 UTC, Hongdonggeon commented on src/main/java/gift/entity/Product.java
> +    @JoinColumn(name = "Category_id", nullable = false)
category 테이블에는 Category_id라는 필드가 존재하지 않는 것 같아요

2024-07-18 16:43 UTC, Hongdonggeon commented on src/main/java/gift/util/validator/databaseValidator/CategoryDatabaseValidator.java
> +public class CategoryDatabaseValidator {
이 validator 클래스를 따로 설계한 이유가 궁금해요 
ProductService에서 존재한 카테고리인지 검증해도 되지 않나요?

2024-07-19 07:51 UTC, rdme0 commented on src/main/java/gift/util/validator/databaseValidator/CategoryDatabaseValidator.java
> +public class CategoryDatabaseValidator {
productService 코드의 길이를 최대한 줄이려고 그랬던 것 같습니다.
지금 보니, orElseThrow 하나만 하면 되니까 굳이 따로 분리할 필요가 없는 것 같아서 리팩터링 하였습니다!

2024-07-19 08:24 UTC, rdme0 commented
피드백 반영 하였습니다!

2024-07-21 04:26 UTC, Hongdonggeon approved these changes
안녕하세요 수랑님
리뷰 반영하신거 잘 확인했습니다! 
1단계 머지할게요!

2024-07-21 04:26 UTC, merged