경북대 BE_안재민 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #123
Opened 2024-07-16 12:04 UTC by dkswoals

늘 고생 많으십니다 멘토님😊
4주차 1단계 구현 후 리뷰 요청 드립니다! 
## 중점적으로 리뷰받고 싶은 부분
- 예외를 보다 구별되고 처리하기 쉽게하기 위해 커스텀 예외를 만들어 사용하다 보니 꽤 많아졌는데 제가 적절하게 사용하고 있는지 궁금합니다.
- 전반적인 엔티티 매핑 구조가 적절한지 궁금합니다!

2024-07-17 15:13 UTC, leaf-upper requested changes
안녕하세요 재민님~
1단계 고생 많으셨습니다 매핑관계는 잘해주신것 같아요~
그 외로 몇가지 코멘트 드렸는데 확인해주시면 감사하겠습니다 👍

2024-07-17 15:13 UTC, leaf-upper commented on src/main/java/gift/controller/AuthController.java
> +            throw new CustomArgumentNotValidException(null, result, ErrorCode.BAD_REQUEST);
매번 생성자에서 null을 넣기보다는 생성자를 한개 더 선언해서 사용해주시면 좋을것 같아요.

2024-07-17 15:13 UTC, leaf-upper commented on src/main/java/gift/controller/AuthController.java
> +            throw new CustomArgumentNotValidException(null, result, ErrorCode.BAD_REQUEST);
CustomException 패키지 소문자로 수정 부탁드립니다!

2024-07-17 15:13 UTC, leaf-upper commented on src/main/java/gift/controller/CategoryController.java
> +        if (categoryService.isDuplicateName(categoryForm.getName())) {
👍 👍 Service에서는 신뢰하고 name값을 사용할수있겠네요

2024-07-17 15:13 UTC, leaf-upper commented on src/main/java/gift/exception/CustomException/CategoryNotFoundException.java
> +public class CategoryNotFoundException extends CustomException {
NotFoundException 같은 경우에는 한개로 통일해도 괜찮을것 같아요

2024-07-17 15:13 UTC, leaf-upper commented on src/main/java/gift/model/categories/Category.java
> +    public Category() {
외부에서 해당 엔티티를 생성할 수 없도록, 생성자에 대한 접근제어자는 protected로 해주시면 좋을것 같아요~

2024-07-17 15:13 UTC, leaf-upper commented on src/main/java/gift/model/categories/Category.java
> +    private String name;
NotNull 애너테이션도 붙여두면 좋을것 같아요

2024-07-17 15:13 UTC, leaf-upper commented on src/main/java/gift/model/item/Item.java
>      public Item() {
이부분도 접근제어자 체크 한번 부탁드릴게요!

2024-07-17 15:13 UTC, leaf-upper commented on src/main/java/gift/model/item/Item.java
> +    private final List<WishItem> wishes = new ArrayList<>();
final 접근제어자를 붙이신 이유가 있을까요?

2024-07-17 15:13 UTC, leaf-upper commented on src/main/java/gift/model/user/User.java
> +@BatchSize(size = 100)
BatchSize는 클래스보다는 대상 컬럼에 붙여주시면 더 명확할것 같아요

2024-07-18 00:28 UTC, dkswoals commented on src/main/java/gift/controller/AuthController.java
> +            throw new CustomArgumentNotValidException(null, result, ErrorCode.BAD_REQUEST);
헐 그런 간단한 방법이 있었네요,, 바로 반영하였습니다!

2024-07-18 00:28 UTC, dkswoals commented on src/main/java/gift/exception/CustomException/CategoryNotFoundException.java
> +public class CategoryNotFoundException extends CustomException {
반영하였습니다!!

2024-07-18 00:28 UTC, dkswoals commented on src/main/java/gift/model/categories/Category.java
> +    public Category() {
반영하였습니다!

2024-07-18 00:39 UTC, dkswoals commented on src/main/java/gift/model/categories/Category.java
> +    private String name;
반영하였습니다!

2024-07-18 00:50 UTC, dkswoals commented on src/main/java/gift/model/item/Item.java
> +    private final List<WishItem> wishes = new ArrayList<>();
별 생각 없이 기본적으로 초기화가 됬으니까 final로 선언해도 되지 않을까 하였는데
프록시 객체 생성을 위해 원본 엔티티를 상속받을때 문제가 생기는군요,,
제거하였습니다!

2024-07-18 00:50 UTC, dkswoals commented on src/main/java/gift/model/user/User.java
> +@BatchSize(size = 100)
반영하였습니다!

2024-07-18 00:51 UTC, dkswoals commented
피드백 반영 후 리뷰 요청 드립니다!

2024-07-18 13:24 UTC, leaf-upper approved these changes
👍 1단계 고생많으셨습니다.
대부분 코멘트를 잘 반영해주셔서 바로 어프로브드릴게요
👍 👍

2024-07-18 13:24 UTC, merged