충남대 BE_이은경 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #130
Opened 2024-07-16 13:25 UTC by pkyung

## 과제 진행 사항
### 상품 카테고리
- [x] 카테고리 도메인 설계
- [x] 상품과 관계 설정
- [x] 카테고리 ru 구현
- [x] 화면 반영 - 상품과 함께 추가

## 구현에 대한 부가 설명
카테고리는 상품 생성 이전에 데이터베이스에 미리 들어가 있지 않으면 오히려 이상한 프로그램이라는 생각이 들어서 카테고리는 이미 db에 입력되었다고 생각하고 상품과 카테고리 구현을 진행했습니다.

2024-07-17 00:37 UTC, ksy90101 requested changes
간단한 피드백 남겼습니다~
확인 부탁드려요!
고생많으셨습니다!
질문이 있다면 언제든 DM주세요!

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/controller/CategoryController.java
> +@RequestMapping("/api")
여기에 categories를 같이 적으면 좋지않을까요?

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/controller/CategoryController.java
> +        List<Category> categoryList = categoryService.findAllCategories();
콜렉션인 경우 변수명에 콜렉션을 쓰기보딘 복수형으로 적는게 더 명확할수 있습니다.



참고: https://devlog.jsyoo5b.net/ko/posts/clean-code/ch02/

> 예를 들어 accountList는 해당 변수가 진짜 List 형식이 아니라면 사용하지 말고, 차라리 accountGroup, bunchOfAccounts, 혹은 그냥 accounts로 표현하는 것이 더 낫다고 한다.

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/controller/CategoryController.java
> +    public ResponseEntity updateCategory(CategoryRequest request) {
컨트롤러를 보면 카테고리라는걸 이해할수 있으니. Update만 적어도 되지않을까요?

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/controller/CategoryController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
201 created는 기본적으로 의미가 리소스가 생성될때를 의미합니다.
따라서 update는 생성되었다는 의미는 아니기 때문에 

200이나 지금처럼 내려줄 body가 없다면 204 no_content를 쓰는 편입니다.

참고링크 : https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/controller/CategoryController.java
> +    public ResponseEntity updateCategory(CategoryRequest request) {
따로 body가 없기 때문에 Void로 제네릭의 타입을 지정하면 더 의미전달이 잘 될거 같아요~

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/dto/CategoryRequest.java
> +        String imageUrl,
여기도 color코드와 url validate를 하면 좋을거 같습니다.

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/dto/ProductRequest.java
> +                             String imageUrl,
여기도 url validate가 필요해보입니다.

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/dto/ProductRequest.java
>                               int price,
boxed Type이 아닌경우 "int"에서 null이 들어올수 있을까요?

참고링크: https://unit-15.tistory.com/172

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/dto/ProductResponse.java
> +        String categoryName,
지금도 괜찮지만, 대부분 계층형으로 두기도 합니다.

{
   id:
....
  category: {
     id:
     name: 
  }
}

이렇게 하면 훨씬 모델을 이해하는게 쉽거든요~

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/exception/NotFoundExceptionHandler.java
> +public class NotFoundExceptionHandler {
점점 NotFound가 많아지는거 같아요.
이런경우 NotFoundException을 만들어서 공통으로 처리하기도 합니다.

모델이 만들어질때마다 Exception을 만들면 힘드니깐요.

cf) MemberNotFoundException은 다른 로직이기 떄문에 공통으로 하기 어려울거 같아요 ㅎㅎ 이 부분은 뺴고 ㅎㅎ

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/model/Category.java
> +    private String name;
요구사항에서 name은 유니크한값으로 봤는데.. ㅎㅎ 유니크 인덱스 처리가 안되어있네요!?

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/model/Category.java
> +    private String imageUrl;
이번엔 한번 모델에도 validate를 고려해보죠.
엔티티, 모델에도 validate가 필요합니다.

한번 validate를 해보시길 바랍니다.

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/model/Category.java
> +    private String description;
description이 255자로 충분할까요?

"@Lob"을 적용할 필요는 없을까요?

2024-07-17 00:37 UTC, ksy90101 commented on src/main/java/gift/service/CategoryService.java
> +        Optional<Category> category = categoryRepository.findById(request.id());
여기서 orElesThrow로 추출해서 처리하면 더 편하지 않을까요?

2024-07-17 04:55 UTC, pkyung commented on src/main/java/gift/controller/CategoryController.java
> +@RequestMapping("/api")
네 수정하겠습니다.

2024-07-17 05:17 UTC, pkyung commented on src/main/java/gift/controller/CategoryController.java
> +        List<Category> categoryList = categoryService.findAllCategories();
참고하고 수정하겠습니다!

2024-07-17 05:46 UTC, pkyung commented on src/main/java/gift/controller/CategoryController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
update 할 때의 상태 반환을 어떻게 할 지에 대해 잘 몰랐는데 감사합니다. 수정하겠습니다.

2024-07-17 05:47 UTC, pkyung commented on src/main/java/gift/dto/CategoryRequest.java
> +        String imageUrl,
정규식을 통해 검증을 진행해보았습니다.

2024-07-17 05:48 UTC, pkyung commented on src/main/java/gift/dto/ProductRequest.java
>                               int price,
수정했습니다.

2024-07-17 05:51 UTC, pkyung commented on src/main/java/gift/dto/ProductResponse.java
> +        String categoryName,
계층형으로 수정하겠습니다!

2024-07-17 05:55 UTC, pkyung commented on src/main/java/gift/model/Category.java
> +    private String name;
요구사항에 힌트가 추가되어 확인하지 못했습니다.  추가해서 수정하겠습니다!

2024-07-17 06:14 UTC, pkyung commented on src/main/java/gift/service/CategoryService.java
> +        Optional<Category> category = categoryRepository.findById(request.id());
수정하겠습니다!

2024-07-17 06:29 UTC, pkyung commented on src/main/java/gift/model/Category.java
> +    private String imageUrl;
고려해서 수정해보겠습니다.

2024-07-17 06:36 UTC, pkyung commented on src/main/java/gift/model/Category.java
> +    private String description;
적용해야할 것 같습니다. 추가하겠습니다!

2024-07-17 06:38 UTC, pkyung commented on src/main/java/gift/exception/NotFoundExceptionHandler.java
> +public class NotFoundExceptionHandler {
이전의 피드백을 보고 Exception Handler를 한 곳으로 모은 것인데 notfound과 같은 Exception을 공통으로 처리하라는 말씀이었군요,,, 혹시 그러면 Handler 또한 다시 분리해야할까요?

2024-07-17 06:56 UTC, pkyung commented on src/main/java/gift/exception/NotFoundExceptionHandler.java
> +public class NotFoundExceptionHandler {
exception을 하나로 모은 다음 global handler를 두는 게 나을까요?

2024-07-18 02:47 UTC, ksy90101 commented on src/main/java/gift/exception/NotFoundExceptionHandler.java
> +public class NotFoundExceptionHandler {
분리에 대해서는 정답이 존재하지 않습니다.

저같은 경우엔 공통인 경우엔 GlobalHendler에 넣고, 각 컨트롤러에서 각각의 예외 핸들러가 필요하면 그때가서 예외에 대한 컨트롤러를 넣는 편입니다.

2024-07-18 02:54 UTC, ksy90101 approved these changes
고생하셨어요!
Optional의 메서드 체이닝에 대해서 좀더 찾아보시면 좋을거 같습니다.
2단계에서 뵐게요~

2024-07-18 02:54 UTC, ksy90101 commented on src/main/java/gift/service/ProductService.java
> +            throw new NotFoundException("해당 카테고리가 존재하지 않습니다.");
Optional을 쓰는곳을 모두 orElseThrow 형식으로 변경하면 어떠까요?

2024-07-18 02:54 UTC, merged