강원대 BE_안승환 4주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #133
Opened 2024-07-16 13:42 UTC by Awhn

Category 엔티티와 그에 수반하는 리포지터리, 서비스, 컨트롤러를 작성하였습니다.
Product에서 Category ID를 외래키로 포함하도록 변경하였습니다. 그에 따라 관리자 페이지도 수정하였습니다.
엔티티 클래스에 대한 테스트 코드를 수정하고, Category 클래스에 대한 테스트 코드를 추가하였습니다.

작성을 하며 궁금했던 부분은 Product에 필드 하나만 추가하면 되는 간단한 부분이라 생각했는데, 생각보다 수정할 부분이 많았던 점이었습니다. 현업에서도 이러한 필드 변경이나 추가가 흔히 발생하는 일일까요? 만약 그렇다면 이를 좀 더 쉽게 작성하는 방법이나 설계가 있을까요?

2024-07-17 00:55 UTC, jaymarystella requested changes
안녕하세요 승환님
1단계 코멘트 남겼습니다. 확인주시고 반영부탁드려요

2024-07-17 00:55 UTC, jaymarystella commented on src/main/java/gift/controller/AdminController.java
>  @RequestMapping("/admin/products")
각 메서드들 path에 있는 edit이라는 단어는 지워주세요

2024-07-17 00:55 UTC, jaymarystella commented on src/main/java/gift/entity/Category.java
> +    private String imgUrl;
이름축약은 지양해주세요

2024-07-17 00:55 UTC, jaymarystella commented on src/main/java/gift/entity/Category.java
> +    @GeneratedValue
전략은 명시를 해주시는게 좋습니다

2024-07-17 00:55 UTC, jaymarystella commented on src/main/java/gift/entity/Product.java
> +    private Category category;
서비스를 운영하고있는 도중에 카테고리추가 요구사항이 추가됐다면 어떻게 진행하면 좋을지 생각정도만 해보셔요

2024-07-17 00:55 UTC, jaymarystella commented on src/main/java/gift/service/CategoryService.java
> +        }
어떤 예외가 발생할 수 있는지와, runtime으로 던져버리면 추적이 용이할지 고민해보셔요

2024-07-17 00:55 UTC, jaymarystella commented on src/main/java/gift/repository/CategoryRepository.java
> +    Category save(Category category);
명시를 해야되는 부분과 아닌부분은 어떤것들이 있을까요

2024-07-17 00:55 UTC, jaymarystella commented on src/main/java/gift/service/CategoryService.java
> +            throw new NoSuchElementException("Can't find category with id " + id);
예외catch가 아닌 optional처리로 개선해보면 어떨까요? 다른 메서드들도 예외처리를 개선해보아요

2024-07-17 00:55 UTC, jaymarystella commented on src/main/java/gift/controller/CategoryController.java
> +public class CategoryController {
> 상품에는 항상 하나의 카테고리가 있어야 한다.
> 상품 카테고리는 수정할 수 있다.
> 관리자 화면에서 상품을 추가할 때 카테고리를 지정할 수 있다.

요구사항이 위와같은데 상품카테고리를 수정하는부분이 없는것같아요. 확인부탁드립니다.

2024-07-17 00:55 UTC, jaymarystella commented on src/main/java/gift/controller/CategoryController.java
> +public class CategoryController {
핵심 클래스 상품,카테고리 에 대한 단위테스트도 확인해주세요

2024-07-17 00:55 UTC, jaymarystella commented on src/main/java/gift/controller/CategoryController.java
> +public class CategoryController {
> 작성을 하며 궁금했던 부분은 Product에 필드 하나만 추가하면 되는 간단한 부분이라 생각했는데, 생각보다 수정할 부분이 많았던 점이었습니다. 현업에서도 이러한 필드 변경이나 추가가 흔히 발생하는 일일까요? 만약 그렇다면 이를 좀 더 쉽게 작성하는 방법이나 설계가 있을까요?

넵 흔히 발생합니다. 쉽게작성하는법이라기보다 서비스운영중에 영향을 받지 않게끔 하는 방향으로 고민해야합니다. 질문이 좀 광범위한데 특정 케이스를 말씀주시면 좀 더 답변드릴 수 있을거같습니다.

2024-07-17 10:50 UTC, Awhn commented on src/main/java/gift/controller/AdminController.java
>  @RequestMapping("/admin/products")
넵! 생각해보니 불필요한 부분이었던 거 같습니다.

2024-07-17 10:51 UTC, Awhn commented on src/main/java/gift/entity/Category.java
> +    private String imgUrl;
넵! 축약하다 보니 오타도 생겼네요 :( 다른 부분도 수정하였습니다.

2024-07-17 10:56 UTC, Awhn commented on src/main/java/gift/entity/Product.java
> +    private Category category;
기존의 데이터베이스에 존재하는 값에는 카테고리가 없을테니, nullable 제약 조건을 단순히 적용하면 문제가 발생할 수 있을 거 같습니다.

2024-07-17 10:59 UTC, Awhn commented on src/main/java/gift/service/CategoryService.java
> +        }
Argument가 없으므로 사용자의 입력에 의해서(클라이언트 오류)는 예외가 발생하지 않을 거 같은데, 내부 처리에서 문제가 발생할 수 있을 거 같습니다. DB와 연결이 끊어졌다던지, 다른 요구를 처리하던 중 테이블에 예외가 발생하는 등의 문제가 있을 거 같습니다.
해당 경우를 나누어서 처리해보았습니다.

2024-07-17 11:23 UTC, Awhn commented on src/main/java/gift/entity/Category.java
> +    @GeneratedValue
미처 생각치 못했는데, 전략이 생략된 경우 Auto로 상황에 따라 다르게 나타날 수 있으며 UUID Generator로 값이 생성된다는 것을 알게 되었습니다. [참고](https://www.baeldung.com/hibernate-identifiers)

2024-07-17 11:25 UTC, Awhn commented on src/main/java/gift/repository/CategoryRepository.java
> +    Category save(Category category);
findAll과 같은 경우에는 상속 받은 인터페이스에 동일한 메서드가 있으므로 명시하지 않아도 될 거 같습니다. ...ById 메서드와 같은 경우에는 입력 받는 인자를 int로 명시하기 위해서 필요한 거 같습니다.

2024-07-17 11:30 UTC, Awhn commented on src/main/java/gift/service/CategoryService.java
> +            throw new NoSuchElementException("Can't find category with id " + id);
optional처리가 무엇인지 잘 몰랐는데, try catch보다 직관적으로 값이 없는 경우를 처리할 수 있는 거 같아 수정하였습니다.

2024-07-17 11:37 UTC, Awhn commented on src/main/java/gift/controller/CategoryController.java
> +public class CategoryController {
상품 카테고리에 대해서 Put 매핑을 통한 수정은 작성하였는데, Patch를 통한 수정도 추가하였습니다.

2024-07-17 12:02 UTC, Awhn commented on src/main/java/gift/controller/CategoryController.java
> +public class CategoryController {
테스트에 추가적인 케이스를 추가하였습니다.

2024-07-17 12:07 UTC, Awhn commented on src/main/java/gift/controller/CategoryController.java
> +public class CategoryController {
> 만약 그렇다면 이를 좀 더 쉽게 작성하는 방법이나 설계가 있을까요?

작성을 하면서 Entity, DTO, Repository, Service, Controller 클래스 전체에서 수정이 필요하였어서, 해당 과정을 자동화하거나 필요한 부분만 수정할 수 있도록 하는 방법이 궁금했습니다. 이전에 강의에서 언급하셨던 Lombok이 도움을 줄 수 있을까요?

2024-07-19 15:52 UTC, jaymarystella commented on src/main/java/gift/repository/CategoryRepository.java
> +    Category save(Category category);
저 save도 꼭 적어주어야할까요?

2024-07-19 15:53 UTC, jaymarystella commented on src/main/java/gift/controller/CategoryController.java
> +public class CategoryController {
강의에서 언급한부분은 잘모르겠으나, 필드추가에 대한 요구사항이나 정책변경은 롬복과는 관련이 없습니다.

2024-07-19 15:54 UTC, jaymarystella approved these changes
안녕하세요 리뷰 반영하느라 고생많으셨습니다.
다음단계에서 뵐게요.

2024-07-19 15:54 UTC, merged