경북대 BE_석혜원 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #134
Opened 2024-07-16 13:57 UTC by hyeywon

2024-07-17 03:15 UTC, lsm7179 commented
도메인에 단위테스트 코드를 만들어보세요.
예를 들어 상품 수정시 잘 수정되었는지 update 메소드에 대한 검증이 필요해보여요.
https://mangkyu.tistory.com/144

2024-07-17 03:15 UTC, lsm7179 requested changes
혜원님 과제 수고하셨습니다.
몇가지 피드백 드렸으니 수정 후 다시 리뷰요청해주세요~

2024-07-17 03:15 UTC, lsm7179 commented on src/main/java/gift/api/category/Category.java
> +    private Long id;
요구사항이 생길수록 계속해서 엔티티 클래스에 반복되는 id
baseEntity를 도출해보세요.
https://devfunny.tistory.com/684

2024-07-17 03:15 UTC, lsm7179 commented on src/main/java/gift/api/category/CategoryController.java
> +    }
nit: 지난주차에 했던 page를 도입해보는건 어떨까요?

2024-07-17 03:15 UTC, lsm7179 commented on src/main/java/gift/api/product/ProductRequest.java
> +    private Long categoryId;
`@NotNull` 만으로 괜찮을까요? 
`@NotBlank`, `@NotEmpty` 어노테이션들 한번 같이 확인해보세요~

2024-07-17 03:15 UTC, lsm7179 commented on src/main/java/gift/api/product/ProductService.java
> +                                .orElseThrow(() -> new NoSuchEntityException("category"));
커스텀 예외로 잘 처리해주셨네요.😁

2024-07-17 03:15 UTC, lsm7179 commented on src/main/java/gift/ui/admin/AdminController.java
> +            .orElseThrow(() -> new NoSuchEntityException("category"));
update의 내용과 반복되어지네요. private 메소드를 이용해서 반복을 줄여보세요.

2024-07-17 03:15 UTC, lsm7179 commented on src/main/java/gift/ui/admin/AdminController.java
> +    private final CategoryRepository categoryRepository;
Service계층을 사용해볼까요?

2024-07-17 16:07 UTC, hyeywon commented on src/main/java/gift/api/product/ProductRequest.java
> +    private Long categoryId;
해당 속성에 `@NotEmpty`, `@NotBlank`로 수정하니 에러가 발생하여, `@NotNull`과 `@Positive`로 함께 검증하도록 수정하였습니다!

2024-07-17 16:08 UTC, hyeywon commented on src/main/java/gift/api/product/ProductRequest.java
> +    private Long categoryId;
다른 도메인에 대해서도 수정하면서, dto와 관련해 궁금한 것이 생겼습니다!

`Wish`의 경우를 예로 들면, 추가 요청 시 product id와 quantity가 필요한데,

1. 이를 포함한 `WishRequest` dto를 product id만 필요한 삭제 요청에도 함께 사용하는 것이 적절한지,
2. 그렇다고 별도의 클래스를 만드는 것은 적절한지 궁금합니다.
3. 만약 `WishRequest`를 같이 사용한다면, quantity 필드에 대한 유효성 검증도 함께 해야 하는지 궁금합니다.

2024-07-18 03:12 UTC, lsm7179 commented on src/main/java/gift/api/category/Category.java
> +    private Long id;
이부분은 수정되지 않은거 같아요~
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/134/files/97dd046022d0b771ff8f37de30d2d58e47ce75de#r1680345407

2024-07-18 03:15 UTC, lsm7179 commented on src/main/java/gift/api/product/ProductRequest.java
> +    private Long categoryId;
실무에서 요구사항이 점점 상세해지고 복잡해진다면 규모에 따라서 나눠야된다고 생각합니다.
예를 들어 `WishAddRequest ` `WishDeleteRequest ` 가 될수있겠네요.
3. request를 같이 사용하지 않는 편이 적절할거같습니다.

2024-07-18 03:19 UTC, lsm7179 approved these changes
혜원님 과제 수고하셨습니다.
다음단계도 화이팅입니다.

2024-07-18 03:19 UTC, lsm7179 commented on src/main/java/gift/api/category/Category.java
> +public class Category extends BaseEntity {
👍

2024-07-18 03:19 UTC, lsm7179 commented on src/main/java/gift/api/product/ProductRequest.java
> +    private Long categoryId;
👍

2024-07-18 03:19 UTC, merged