충남대 BE_김민지 4주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #135
Opened 2024-07-16 13:59 UTC by alsswl

1단계 구현 완료하였습니다!

1. menu 수정 메서드를 필드별(카테고리 수정하는 메서드, 이름 수정하는 메서드)로 구현해야할지 아니면 지금처럼 통으로 구현해도 괜찮은지 궁금합니다.

2. 지금 MemberController과 CategoryController을 보면 처음부터 MenuRequest로 받는 MenuController과 달리 필드값으로 각각 받고, RequestDto로 이를 변환해서 Service단에 넘기는데 이러한 방식이 괜찮은지 궁금합니다!

2024-07-17 09:16 UTC, Hyeon9mak requested changes
안녕하세요 민지님~ 1단계 잘 진행해주셨어요~
코드 퀄리티가 갑자기 상승되었네요?!

> menu 수정 메서드를 필드별(카테고리 수정하는 메서드, 이름 수정하는 메서드)로 구현해야할지 아니면 지금처럼 통으로 구현해도 괜찮은지 궁금합니다.

요구사항에 따라 다릅니다 😄 
한꺼번에 수정하는 것이 주요하다면 통으로, 각각 나누어 수정하는 경우가 잦다면 나누어 구현해주는게 좋겠네요~

> MemberController과 CategoryController을 보면 처음부터 MenuRequest로 받는 MenuController과 달리 필드값으로 각각 받고, RequestDto로 이를 변환해서 Service단에 넘기는데 이러한 방식이 괜찮은지 궁금합니다!

요건 반대로 질문드리고 싶은데요, 필드값을 각각 받도록 한 이유가 있을까요?
관련하여 코멘트를 남겨두었어요!

그 외에도 몇 가지 코멘트 남겼으니 확인해주세요~

2024-07-17 09:16 UTC, Hyeon9mak commented on src/main/java/gift/controller/CategoryController.java
> +
오호, rest api 에 대한 prefix 가 변경되었군요~ 👍

2024-07-17 09:16 UTC, Hyeon9mak commented on src/main/java/gift/controller/CategoryController.java
> +    }
reqeust param 이나 path variable 을 이용하는 것과,
request body 를 이용하는 것에는 어떤 차이가 있을까요?

2024-07-17 09:16 UTC, Hyeon9mak commented on src/main/java/gift/domain/Category.java
> +    private List<Menu> menus;
만약 카테고리가 사라지면 메뉴들은 어떻게 되나요?
이에 대한 표현을 cascade 옵션을 통해 나타내주어도 좋겠네요~

2024-07-17 09:16 UTC, Hyeon9mak commented on src/main/java/gift/domain/Menu.java
> +
category 의 어떤 컬럼을 통해 관계가 지정되는지도 표현해주는 건 어떨까요?

2024-07-17 09:16 UTC, Hyeon9mak commented on src/main/java/gift/domain/Menu.java
>      }
요구사항에는 카테고리 1개가 무조건 지정되어야했던 것 같은데요? 🤔

2024-07-17 18:17 UTC, alsswl commented on src/main/java/gift/controller/CategoryController.java
> +    }
알아본 결과 form태그로 데이터를 받을 때에는 RequestParam을 쓰고, JSON으로 받을 때에는 RequestBody를 쓴다고 합니다!
RequestParam을 쓰면 각 변수별로 데이터를 저장하는 것이 가능하지만, RequestBody를 쓰면 이것이 불가능하다고 합니다.
제 코드 상에서는 DTO통째로 받는 것이 더 깔끔할 것 같아서 RequestBody를 사용하는 것으로 바꾸겠습니다!

2024-07-18 06:20 UTC, alsswl commented on src/main/java/gift/controller/CategoryController.java
> +    }
wishlistController에서 menuId와 jwt토큰을 받아서 이와 연관된 객체를 찾아 wishListRequest를 만들어서 service단에 보내는데, 제 생각에는 RequestBody보다 RequestParam이 더 효율적일 것 같아서 그렇게 구현했는데 이에 대해 어떻게 생각하시는지 궁금합니다.

2024-07-18 07:46 UTC, alsswl commented on src/main/java/gift/domain/Category.java
> +    private List<Menu> menus;
우선 cascade.Type.ALL을 통해 카테고리 삭제 시 메뉴도 삭제되게 하였습니다. 하지만 여기에서 이러한 방식은 위험할 수 있다고 생각했습니다. 이를 위해서 삭제 대신 카테고리가 지워진 메뉴들의 카테고리에 기본값을 추가하고 싶습니다.
알아본 바로는 엔티티핸들러를 통해서 구현할 수 있을 것 같긴 한데, 또 관련한 사례는 찾지 못해서 혹시 이 방법으로 제가 원하는 방식으로 구현할 수 있는 건지 아니면 다른 더 좋은 방법이 있는지 궁금합니다.

2024-07-18 14:37 UTC, Hyeon9mak approved these changes
안녕하세요 민지님~ 1단계 피드백 잘 반영해주셨어요.
몇 가지 코멘트 남겼으니 다음 단계 진행에 참고해주세요~

2024-07-18 14:37 UTC, Hyeon9mak commented on src/main/java/gift/controller/WishListController.java
>      }
> RequestParam이 더 효율적일 것 같아서 그렇게 구현했는데 이에 대해 어떻게 생각하시는지 궁금합니다.

정확히 어떤 부분이 효율적인지 설명이 생략되어서 잘 모르겠네요. 🙄 
인가가 필요한 요청이 전달되었을 때 토큰은 서버에서 다시 발급 후 사용하는 것이 아니라
사용자가 요청 헤더에 함께 담아 전달하는 형태가 되어야 해요.
그림으로 표현하자면 아래와 같은 형태겠네요.

<img width="1386" alt="image" src="https://github.com/user-attachments/assets/4314c791-86d4-4753-abe1-7cd5b215dbb2">

2024-07-18 14:37 UTC, Hyeon9mak commented on src/main/java/gift/domain/Category.java
> +    public Category(Long id, String name, LinkedList<Menu> menus) {
ALL 말고 다른 옵션들은 어떤 기능을 가지는지, 다음 PR 요청에 각각 설명해주실 수 있나요? 😉

2024-07-18 14:37 UTC, Hyeon9mak commented on src/main/java/gift/domain/Category.java
> +    public Category(Long id, String name, LinkedList<Menu> menus) {
> 하지만 여기에서 이러한 방식은 위험할 수 있다고 생각했습니다. 이를 위해서 삭제 대신 카테고리가 지워진 메뉴들의 카테고리에 기본값을 추가하고 싶습니다.

가장 쉬운 방법은 Cascade 옵션에 의존하지 않고, Category 를 삭제하는 로직이 담긴 service 계층에서 
해당 category 를 사용하는 모든 product 를 불러오고, 일일히 변경해주는 것이겠네요 😉

2024-07-18 14:37 UTC, Hyeon9mak commented on src/main/java/gift/domain/MenuRequest.java
카테고리는 별도의 request dto 가 필요하지 않을까요? 🤔

2024-07-18 14:38 UTC, merged

2024-07-19 15:49 UTC, alsswl commented on src/main/java/gift/controller/WishListController.java
>      }
dto 필드들 중에 빈 곳들이 생겨 비효율적이라고 생각했습니다! 그런데 오늘 팀원들과 스크럼 한 결과 그냥 dto를 쓰는 것이 훨씬 깔끔할 것이라는 생각이 들어서 다시 이 부분은 수정하겠습니다!

2024-07-19 16:05 UTC, alsswl commented on src/main/java/gift/domain/MenuRequest.java
아 메뉴 dto로 받을 때에도 RequestDto를 사용해야 하는군요! 근데 혹시 새로운 카테고리를 만드는 요청을 받는 dto와 위와 같이 카테고리가 이미 존재하는 상태에서 메뉴 객체 속의 필드로 받을 때 사용하는 dto를 구별해야 할 필요가 있을까요?

2024-07-19 16:13 UTC, alsswl commented on src/main/java/gift/domain/Category.java
> +    public Category(Long id, String name, LinkedList<Menu> menus) {
persist : 연관된 엔티티도 영속상태로 만든다.
remove : 연관된 엔티티도 함께 삭제한다.
detach : 연관된 엔티티도 함께 준영속상태로 만든다.
merge : 연관된 엔티티도 새로운 영속상태로 만든다
refresh : 데이터베이스로부터 데이터를 다시 읽어 들이는 refresh 동작을 연관된 엔티티로 전파한다.