강원대 BE_김병수 4주차(step1)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #139
Opened 2024-07-16 14:27 UTC by GamJaDo

# [전PR](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/431) 에서 리뷰 해주신 내용을 반영하였습니다.
---
## 멘토님 리뷰
```jsonc
페이징으로 조회하는데 all이라는 단어는 맞지않아보입니다.
```
## 답변
- 말씀해주신 대로 all이라는 단어를 메서드에서 삭제하였습니다.
---
## 멘토님 리뷰
```jsonc
스타일가이드 피드백을 계속드리는데 기본적으로 IDE포맷팅 한번씩 해주시는것을 추천드립니다.
```
## 답변
```java
private void validateBindingResult(BindingResult bindingResult) {
		if(bindingResult.hasErrors()) {
```
style가이드에서는 텝(tab) 한번에 4depth가 되어야 하는데 코드를 리뷰 하실 때 그 2배로 떨어져있어서 말씀해준신것 같습니다.
![dhodlfjfRkdygmdma](https://github.com/user-attachments/assets/ada4373e-f85e-49f5-8e6a-b7b0507d9832)
혹시나 해서 코드를 확인해본 결과 코드창에서는 제대로 4depth로 적혀있는데 왜 이런 현상이 발생하는지 모르겠습니다...
---
## 멘토님 리뷰
```jsonc
찾아서 적기 어려웠다는게 무슨말씀이실까요?
테스트를 작성하는데 테스트데이터를 세팅하는게 어려웠다라는 의미일까요?
추후에 반복되는 작업이 생긴다면 공통메서드로 추출하시면 될것같습니다.
```
## 답변
- 솔직히 말해서 카테캠을 하기 전에는 테스트라는 것을 하지 않았습니다... 정확히 말하면 junit을 쓰지 않고, 브라우저나 postman과 같은 것으로 수동으로 일일이 했었습니다.
하지만 과제를 해나가면서 테스트 코드를 작성하고 테스트를 사용해 보니 예전에 일일이 하던 것 보다 빠르고, 원할 때 테스트 내용을 바꾸거나 여러 테스트를 한 번에 할 수 있어서 훨씬 수월했습니다.
하지만 여태 테스트 코드를 작성하지 않다가 테스트 코드를 작성하려다 보니 어떻게 해야 할지 잘 몰라서 여러 곳에서 테스트를 어떻게 하는지 찾아보는 시간이 오래 걸리고 힘들었다는 것을 [전PR](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/431)의 어려웠던 점에서 그렇게 적었던것 같습니다.
---

2024-07-17 01:17 UTC, jaymarystella commented
포맷팅은 tab뿐만아니라 if문이나 for문 사이의 스페이스에도 해당합니다. IDE에 포맷팅기능을 활용해주시고 스타일가이드는 여러번이야기했던거같은데 학습플랫폼내 문서에 있으니 참고부탁드립니다.

2024-07-17 01:24 UTC, jaymarystella requested changes
안녕하세요 병수님.
1단계 고생많으셨고 몇가지 코멘트 남겼는데 확인부탁드립니다.

2024-07-17 01:24 UTC, jaymarystella commented on src/main/java/gift/controller/AdminController.java
> +    private CategoryService categoryService;
필드주입말고 다른 방법들도 찾아보시면 좋을거같아요.

2024-07-17 01:24 UTC, jaymarystella commented on src/main/java/gift/controller/AuthController.java
> +        return ResponseEntity.ok("User registered successfully.");
이런메세지는 굳이 담지 않아도 됩니다. 어차피 상태코드에서 의미가 드러나니까요

2024-07-17 01:24 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
>  public class ProductController {
상품을 추가할때 Product Entity로 받지말고 다른 클래스를 활용하시는걸 추천드립니다.

2024-07-17 01:24 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
>  public class ProductController {
카테고리를 수정할 수 있는 요구사항이 있는데요, 상품의 전체정보가 아닌 카테고리만을 업데이트하는 api를 만들어보면어떨까요?

2024-07-17 01:26 UTC, jaymarystella commented
> 솔직히 말해서 카테캠을 하기 전에는 테스트라는 것을 하지 않았습니다... 정확히 말하면 Junit을 쓰지 않고, 브라우저나 postman과 같은 것으로 수동으로 일일이 했었습니다.
> 하지만 과제를 해나가면서 테스트 코드를 작성하고 테스트를 사용해 보니 예전에 일일이 하던 것 보다 빠르고, 원할 때 테스트 내용을 바꾸거나 여러 테스트를 한 번에 할 수 있어서 훨씬 수월했습니다.

안했다고 당연히 잘못된게 아닙니다. 지금부터 잘 작성해보시면되죠~ 강사님께서도 잘 알려주시겠지만 과제내의 핵심클래스들에 대한 단위테스트도 함께 봐주세요

2024-07-18 09:08 UTC, GamJaDo commented on src/main/java/gift/controller/AdminController.java
> +    private CategoryService categoryService;
생성자 주입으로 변경하였습니다.

2024-07-18 09:09 UTC, GamJaDo commented on src/main/java/gift/controller/AuthController.java
> +        return ResponseEntity.ok("User registered successfully.");
불필요한 메시지를 삭제하였으며 모든 상태코드 반환을 형식에 맞게 수정하였습니다.

2024-07-18 09:10 UTC, GamJaDo commented on src/main/java/gift/controller/ProductController.java
>  public class ProductController {
상품을 추가할 때 entity 대신에 dto를 통해 상품을 추가하도록 수정하였으며
상품 정보 수정 시 카테고리만 따로 수정할 수 있는 api도 만들어 봤습니다.

2024-07-19 00:48 UTC, jaymarystella approved these changes
안녕하세요 코멘트 남겨드린부분확인주시고 다음단계진행해주시면 될것같습니다.

2024-07-19 00:48 UTC, jaymarystella commented on src/main/java/gift/dto/ProductRequest.java
> +	private String categoryName;
카테고리이름이 같으면 어떻게 될까요?

2024-07-19 00:48 UTC, merged