경북대 BE_김영인 4주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #140
Opened 2024-07-16 14:51 UTC by Youngini

category를 새로 만들면서 고민한 것이 몇 가지 있습니다.

1. 일단 DDL을 봤을 떄, Category의 name이 unique여야 했는데, enum을 사용하면 지정된 값만 사용할 수 있기 때문에 unique처럼 사용할 수 있어서 그렇게 구현했는데 괜찮을까요?

2. product가 하나의 category가 아닌 여러 category에 속할 수 있다고 생각을 하는데, List로 category 여러개를 저장하는 것이 좋을까요?

3. 어떤 한 entity가 다른 entity를 fk로 가진다면 둘 다의 entity에 표시하는게 좋다고 알고있는데, 만약 다른 A라는 엔티티에서 B라는 엔티티의 값을 가져올 일은 없고 B에서는 A의 값을 가져올 일이 있다면 B에만 fk 표시를 해도 되는 걸까요?

2024-07-16 15:23 UTC, Youngini commented
생각해보니, enum을 사용하면 관리자가 새로운 카테고리를 추가할 때, 어려움이 있을 것 같습니다. 카테고리명은 string에 unique 설정을 하는 쪽으로 바꾸는 것이 더 좋을지도 모르겠다는 생각을 했습니다!

2024-07-17 13:38 UTC, gongdongho12 requested changes
1단계 작업하느라 고생 많으셨습니다 😄 
리뷰 남긴 부분 한번 확인 부탁드려요

> 1. 일단 DDL을 봤을 떄, Category의 name이 unique여야 했는데, enum을 사용하면 지정된 값만 사용할 수 있기 때문에 unique처럼 사용할 수 있어서 그렇게 구현했는데 괜찮을까요?

추가 커멘트에서 문자열로 정해주신 것 같습니다 ㅎ

> 2. product가 하나의 category가 아닌 여러 category에 속할 수 있다고 생각을 하는데, List로 category 여러개를 저장하는 것이 좋을까요?

우선 이 부분 고민하기 전에 카테고리 Depth를 둘 것 같아요.
사실 이런 부분은 별도로 생각하기 보다는 실제 쇼핑몰의 카테고리 구분을 한번 참고해보시면 좋을 것 같습니다 (네이버 쇼핑 등)

> 3. 어떤 한 entity가 다른 entity를 fk로 가진다면 둘 다의 entity에 표시하는게 좋다고 알고있는데, 만약 다른 A라는 엔티티에서 B라는 엔티티의 값을 가져올 일은 없고 B에서는 A의 값을 가져올 일이 있다면 B에만 fk 표시를 해도 되는 걸까요?

fk를 꼭 두곳을 참조하게 하지 않아도 되죠, 결국 값을 가져오기만 하면 되는데 양쪽에 fk를 두면 접근포인트가 많아지게 되기만 하고 기능이 늘어나는게 아니여서요

-> 둘다 가져올 일이 있더라도 한쪽에만 FK를 둬도 접근할 수 있지 않나요?

2024-07-17 13:38 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +        Product product = productService.createProduct(productDto, categoryType);
CreateProductDto에 카테고리가 포함되지 못할 이유가 있을까요?
어짜피 Entity엔 이미 join으로 포함이 결정되어 있으니까요!

2024-07-17 13:38 UTC, gongdongho12 commented on src/main/java/gift/domain/CategoryType.java
> +}
이부분은 별도로 제외되는 걸까요?

2024-07-17 13:38 UTC, gongdongho12 commented on src/main/java/gift/dto/CreateProductDto.java
> +        return new Product(name, price, imageUrl, category);
통합되면 별도 파라미터로 관리되지 않아도 되겠죠?

2024-07-17 13:38 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        this.categoryRepository = categoryRepository;
프러덕트 서비스에서 카테고리 레포지토리는
관리포인트가, 카테고리 서비스, 프러덕트 서비스 두가지로 늘어날 것 같은데요

카테고리 서비스만 참조해서 카테고리 동작은 서비스를 통해서 주는게 맞지 않을까요?

2024-07-17 13:38 UTC, gongdongho12 commented on src/main/java/gift/config/JwtConfig.java
> +    public String generateToken(String email) {
넵 이 방식이 Component 개념이랑 가장 일치하는 방식입니다 👍🏼

2024-07-18 05:50 UTC, Youngini commented
> 1단계 작업하느라 고생 많으셨습니다 😄 리뷰 남긴 부분 한번 확인 부탁드려요
> 
> > 1. 일단 DDL을 봤을 떄, Category의 name이 unique여야 했는데, enum을 사용하면 지정된 값만 사용할 수 있기 때문에 unique처럼 사용할 수 있어서 그렇게 구현했는데 괜찮을까요?
> 
> 추가 커멘트에서 문자열로 정해주신 것 같습니다 ㅎ
> 
> > 2. product가 하나의 category가 아닌 여러 category에 속할 수 있다고 생각을 하는데, List로 category 여러개를 저장하는 것이 좋을까요?
> 
> 우선 이 부분 고민하기 전에 카테고리 Depth를 둘 것 같아요. 사실 이런 부분은 별도로 생각하기 보다는 실제 쇼핑몰의 카테고리 구분을 한번 참고해보시면 좋을 것 같습니다 (네이버 쇼핑 등)
> 
> > 3. 어떤 한 entity가 다른 entity를 fk로 가진다면 둘 다의 entity에 표시하는게 좋다고 알고있는데, 만약 다른 A라는 엔티티에서 B라는 엔티티의 값을 가져올 일은 없고 B에서는 A의 값을 가져올 일이 있다면 B에만 fk 표시를 해도 되는 걸까요?
> 
> fk를 꼭 두곳을 참조하게 하지 않아도 되죠, 결국 값을 가져오기만 하면 되는데 양쪽에 fk를 두면 접근포인트가 많아지게 되기만 하고 기능이 늘어나는게 아니여서요
> 
> -> 둘다 가져올 일이 있더라도 한쪽에만 FK를 둬도 접근할 수 있지 않나요?

2024-07-18 05:52 UTC, Youngini commented on src/main/java/gift/domain/CategoryType.java
> +}
넵 해당 내용 삭제했습니다!

2024-07-18 05:53 UTC, Youngini commented on src/main/java/gift/controller/ProductController.java
> +        Product product = productService.createProduct(productDto, categoryType);
Category에도 Product의 fk를 두면서 만약 카테고리가 없다면 product가 category name과 함께 생성된다고 잘못생각해서 저렇게 구현한 것이라 수정해서 코드 작성했습니다!

2024-07-18 05:53 UTC, Youngini commented on src/main/java/gift/service/ProductService.java
> +        this.categoryRepository = categoryRepository;
넵 확인해보니 사용하지 않는 코드라 삭제하였습니다

2024-07-18 05:57 UTC, Youngini commented
현재 2단계 진행중입니다! 1단계가 merge되면 해당 코드로 고민한 2단계 코드 작성하도록 하겠습니다.

그리고 말씀해주신대로 네이버 쇼핑을 참고해보니 대분류>중분류>소분류 같은 식으로 카테고리를 분류하는 것을 확인했습니다.

그래서 멘토님 말씀대로 depth에 대해 고민해보고 3단계가 끝난 후 코드를 리팩토링 해보려 합니다!

바쁘신 와중에 항상 감사합니다!

그리

2024-07-18 10:31 UTC, gongdongho12 approved these changes
고생하셨습니다

2024-07-18 10:32 UTC, merged