강원대 BE_김송목 4주차 과제 (Step 1)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #147
Opened 2024-07-16 15:43 UTC by kimsongmok

Category를 구현해보았습니다!

과제 진행중 궁금한점

1. 카테고리를 관리자 페이지에서 수정할 수 있다그랬는데 저는 Postman으로 POST요청으로 생성, 수정, GET요청으로 조회 했습니다.
이게 맞을까요?

2. 기본생성자를 생성안하고 할 수가 없었습니다. 기본 생성자를 다시 넣고 코드를 짤 수 밖에 없었습니다. 계속 오류가 났습니다. 왜그럴까요??

리뷰 잘 부탁드립니다 멘토님!

2024-07-17 01:27 UTC, jaymarystella commented
송목님 브랜치 PR하는 방법제가 여러번 말씀드렸는데 이해안되면 안된다고 질문계속 주셔도 좋으니 말씀해주세요

2024-07-17 01:35 UTC, jaymarystella requested changes
안녕하세요
1단계 리뷰남겼는데 확인주시고 브랜치도 확인주시면 감사하겠습니다.

2024-07-17 01:35 UTC, jaymarystella commented on src/main/java/gift/controller/CategoryController.java
> +    Category savedCategory = categoryService.saveCategory(category);
entity로 컨버팅하고 나서 다시 꺼낸뒤에 서비스에 넘기는것보다 saveCategory메서드에서 진행해주시는게 좋을거같아요.

2024-07-17 01:35 UTC, jaymarystella commented on src/main/java/gift/model/Category.java
> +  private String description;
column애노테이션도 사용해보시는건 어떨까요

2024-07-17 01:35 UTC, jaymarystella commented on src/main/java/gift/service/CategoryService.java
> +    category.setDescription(categoryDto.getDescription());
setter를 사용하지 않고 구현해보면 어떨까요

2024-07-17 01:35 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +  public ResponseEntity<ProductDto> createProduct(@Valid @RequestBody ProductDto productDto) {
상품생성시 카테고리를 추가해야하고 카테고리 수정관련 요구사항도있으니 요구사항 다시 살펴주시면 감사하겠습니다.

2024-07-17 15:40 UTC, kimsongmok commented
일단 전부 다시 바꿔봤습니다.

2024-07-18 13:29 UTC, jaymarystella approved these changes
1단계는 여기서 머지하겠습니다. 다음단계 구현부탁드려요

2024-07-18 13:29 UTC, jaymarystella commented on src/main/java/gift/service/CategoryService.java
> +}
적절히 개행도 있으면 좋겠네요..!

2024-07-18 13:29 UTC, merged