강원대 BE_오승규 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #152
Opened 2024-07-16 16:55 UTC by 5win

안녕하세요 제이님 step1 PR 드립니다!

3주차 과제에서 주신 피드백도 반영하였고,
카테고리 CRUD 기능과 상품 추가, 수정 시에 카테고리를 지정하도록 변경하였습니다.

질문이나 피드백 반영한 부분은 코드에 코멘트 남기겠습니다!
이번 주도 잘 부탁드립니다 :)

2024-07-16 16:59 UTC, 5win commented on src/main/java/gift/controller/CategoryViewController.java
> +            PageNumberListGenerator.generatePageNumberList(categories));
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/437#discussion_r1677846010
페이지네이션 부분에서 최대한 로직은 컨트롤러에 두지 않고 서비스에 두라고 하셨던 피드백을 반영하였는데
여러 컨트롤러에서 공통으로 사용되는 기능인 것 같아 서비스에 두지 않고 따로 utils 패키지에 두고 재사용하도록 구성해봤습니다.

2024-07-16 17:05 UTC, 5win commented on src/main/java/gift/controller/CategoryViewController.java
> +    @GetMapping("/addForm")
URI 작명에 대해 피드백이 있으실 것 같아 미리 코멘트 남깁니다.
카테고리 수정 페이지는 특정 카테고리에 대한 정보를 함께 받도록 했기 때문에 `GET /api/categories/{id}` 로 하였습니다.

카테고리 추가 페이지에서는 카테고리 목록을 반환하는 부분이 `GET /api/categories`를 사용했기 때문에 사용할 수 없었고, 이것 하나만을 위해서 `/api/categories/category` 처럼 늘려서 사용하기엔 굳이 필요하지 않다고 생각해서 add Form을 가져온다는 뜻으로 `GET /api/categories/addForm` 을 사용했습니다.

혹시 더 괜찮은 방법이 있다면 피드백 주시면 반영하겠습니다!

2024-07-16 17:06 UTC, 5win commented on src/main/java/gift/controller/MemberViewController.java
> +        model.addAttribute("pageNumbers", PageNumberListGenerator.generatePageNumberList(wishlist));
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/437#discussion_r1677846010
페이지네이션 부분에서 최대한 로직은 컨트롤러에 두지 않고 서비스에 두라고 하셨던 피드백을 반영하였는데
여러 컨트롤러에서 공통으로 사용되는 기능인 것 같아 서비스에 두지 않고 따로 utils 패키지에 두고 재사용하도록 구성해봤습니다.

2024-07-16 17:13 UTC, 5win commented on src/main/java/gift/dto/ProductDto.java
> +    private String categoryName;
상품과 카테고리의 연관관계에서 상품이 카테고리의 id를 외래키로 갖도록 구성했습니다.
따라서, 상품 추가 시에 카테고리를 지정하면 카테고리 id를 보내야 했기에 처음에는 ProductDto에서 categoryId 만을 가지도록 했었습니다.

그러나 상품 목록이나 위시리스트 목록에도 각 상품의 카테고리를 보여주도록 하기 위해선 카테고리 이름을 함께 응답해야했습니다.
즉, 요청과 응답에서 필요한 정보가 달랐기에 ProductRequest, ProductResponse 두개로 나눌까 했었는데 변수 하나밖에 차이가 나지 않아서 그냥 ProductDto에서 categoryId, categoryName 둘 다 가지도록 했습니다.

2024-07-16 17:18 UTC, 5win commented on src/main/java/gift/entity/Member.java
> +    public void addWishlist(Wishlist wishlist) {
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/437#discussion_r1677848950
피드백 반영해서 member에서 wishlist를 추가하도록 변경하였습니다.

"도메인에 유효성 검사 책임까지 넘긴다" 는 부분은 잘 이해가 되지 않는데,
혹시 이렇게 null 검사를 뜻하시는 걸까요? 아니면 해당 멤버가 존재하는지 확인하는 findByEmail 과 같은 로직을 넘기는 것을 뜻하는 걸까요?

2024-07-16 17:20 UTC, 5win commented on src/main/java/gift/service/CategoryService.java
> +    private Category checkCategoryExistsById(Long id) {
엔티티 존재 여부, 중복 여부를 확인하는 중복되는 로직들을 따로 메서드로 만들어서 사용해보았습니다.

2024-07-16 17:21 UTC, 5win commented on src/main/java/gift/service/MemberService.java
> +            .map(wishlist -> new ProductDto(wishlist.getProduct()));
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/437#discussion_r1677847637
피드백 반영해서 변수명를 명시적으로 바꿨습니다.

2024-07-16 17:34 UTC, 5win commented on src/main/java/gift/service/MemberService.java
> +        product.addWishlist(wishlist);
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-jpa/pull/437#discussion_r1677849424

> +상품이 위시리스트쪽을 참조할 일이 있나요?

양방향 매핑을 이야기하시는 것이라면,
당장 필요해서 양방향 매핑을 사용한 것은 아니지만, 추후에 필요하게 될 경우과 학습 차원에서 양방향으로 매핑해보았습니다.

저렇게 member, product에 add를 하는 이유를 이야기하시는 것이라면,
연관관계의 주인이라고 칭하는 부분이 wishlist이긴한데 그래도 결국 양방향 매핑이라는 관계가 객체에도 적용되어야한다는 생각에 양쪽 모두 객체를 넣어주도록 했었습니다.

그런데 어차피 wishlist만 저장해도 테이블에는 반영되고, 당장 member, product 객체를 통해 wishlist에 접근하는 로직이 없기 때문에 불필요하다고 생각합니다.
`ProductService`의 `addProduct()`에서도 wishlist 객체에 product를 저장하는 로직이 불필요하고 복잡성을 높인다고 생각해서, 연관관계의 주인인 product에만 반영하도록 구현했습니다.

물론 상황에 따라 다르겠지만 이렇게 연관관계의 주인에만 반영하도록 하는 것이 좋을까요?

2024-07-16 17:43 UTC, 5win commented on src/test/java/gift/controller/CategoryControllerTest.java
> +class CategoryControllerTest {
저번 수업에서 Mockito를 사용하여 특정 메서드의 반환값을 명시해주는 방법으로 테스트하는 것을 배웠습니다.

findById()와 같은 메서드의 반환값을 정해주므로써 실제 DB 접근 없이 테스트가 가능한 것 같더라구요.
DAO 테스트단에서는 사용하지  않을 것 같고, 이렇게 컨트롤러에서는 서비스 메서드의 반환값을 정해주므로써 요청과 응답을 테스트하는 식으로 테스트할 수 있을 것 같습니다.

보통 이렇게 Mockito를 사용하여 하위 레이어 메서드의 반환값을 지정해주는 방법은 각각의 레이어를 따로 따로 테스트하는 단위 테스트?에 사용되는 것일까요?

제가 지금 구현한 테스트는 요청에서부터 DB까지 모두 동작하는 E2E 테스트라고 생각이 됩니다.

2024-07-17 01:43 UTC, jaymarystella commented on src/main/java/gift/controller/CategoryController.java
> +     */
이런 주석들은 지워주셔도 될거같습니다 :)

2024-07-17 01:43 UTC, jaymarystella commented on src/main/java/gift/dto/ProductDto.java
> +    private Long categoryId;
👍🏼

> 관리자 화면에서 상품을 추가할 때 카테고리를 지정할 수 있다.

라는 요구사항인데 지정해야한다가 아니라 할 수 있다면 없어도 되는 걸까요. 이건 저도 잘 모르겟네요. 어쨌든 카테고리 지정이 필수인건 전혀 어색하지 않아서 괜찮은것같습니다.

2024-07-17 01:43 UTC, jaymarystella commented on src/main/java/gift/dto/ProductDto.java
> +    private String categoryName;
정말 좋은 고민입니다. 실제로도 많이 하는고민입니다.

이게 상품만을(카테고리없이) 관리하는 api가 있거나 해당 기능들이 쓰인다면 dto를 나눠보시는것도좋습니다. 불필요한 정보를 나눠서 보낼필요는 없으니까요. 일단은 판단은 잘해주신거같아요.

2024-07-17 01:43 UTC, jaymarystella commented on src/main/java/gift/dto/CategoryDto.java
> +    private String name;
이 필드외에 다른 필드의 제약사항은 필요없을까요?
요구사항에 없더라도 스스로 정의해보시는것도 좋습니다.

2024-07-17 01:43 UTC, jaymarystella commented on src/main/java/gift/controller/CategoryViewController.java
> +    @GetMapping("/addForm")
음 view그려주는거니 괜찮은것같습니다.

2024-07-17 01:45 UTC, jaymarystella commented on src/main/java/gift/entity/Member.java
> +    public void addWishlist(Wishlist wishlist) {
단순히 서비스레이어에서 각 도메인들이 필요한 정보들을 꺼내서 다루기보다 핵심로직은 도메인이 가지도록하는게 좋다는 차원에서 남겼구요, wishlist가 해당 member가 가질 수 있는것인지에 대한 검사가 필요하다면 넣는것 등이 해당될 수 있습니다. 지금은 없을수는 있어도 도메인간의 연관관계를 가질때 필요한 내용이라고 봐주시면 될 것 같습니다.

2024-07-17 01:46 UTC, jaymarystella commented on src/main/java/gift/service/MemberService.java
> +        product.addWishlist(wishlist);
잘 생각해주셨네요 👍🏼 
필요하다면 당연히 구현해야겠지만 일단은 최대한 단방향으로 유지하는게 보기가 더 편하더라고요.

2024-07-17 01:49 UTC, jaymarystella commented on src/test/java/gift/controller/CategoryControllerTest.java
> +class CategoryControllerTest {
넵 말씀주신대로 mock을 사용하면 완전한 통합테스트는 아닙니다. 지금 이 클래스는 통합테스트로써 구현을 해주신거같네요.

2024-07-17 01:53 UTC, jaymarystella requested changes
안녕하세요 승규님
과제 잘 진행해주셨네요.
몇가지 코멘트 남겼는데 확인해주시고 의견 편하게 남겨주세요

2024-07-17 01:53 UTC, jaymarystella commented on src/main/java/gift/service/CategoryService.java
> +    private Category checkCategoryExistsById(Long id) {
check~~ 면 boolean을 리턴할거같아요. 메서드 이름을 바꿔보면 어떨까요?

2024-07-17 01:53 UTC, jaymarystella commented on src/main/java/gift/service/ProductService.java
>      public void editProduct(ProductDto product) {
상품 카테고리만 수정하는 api를 만들어보면 어떨까요?

2024-07-17 01:53 UTC, jaymarystella commented on src/main/java/gift/entity/Member.java
> +import gift.constants.ErrorMessage;
핵심 클래스들에 대한 단위테스트를 만들어보면 어떨까요?

2024-07-17 01:54 UTC, jaymarystella commented on src/main/java/gift/dto/ProductDto.java
> +    private Long categoryId;
추가로 서비스 운영을 하고있는 상황에서 카테고리추가 요구사항이 왔다면 어떻게 사용자들에게 영향이 가지않게 추가할 수 있을지도 고민만해보시면 좋을거같아요.

2024-07-17 01:54 UTC, jaymarystella commented
질문주신부분들은 코멘트 위에 남겨뒀는데 해결안된부분들은 다시 언급주시거나 dm주세요~

2024-07-17 11:35 UTC, 5win commented on src/main/java/gift/dto/ProductDto.java
> +    private String categoryName;
> 정말 좋은 고민입니다. 실제로도 많이 하는고민입니다.
> 
> 이게 상품만을(카테고리없이) 관리하는 api가 있거나 해당 기능들이 쓰인다면 dto를 나눠보시는것도좋습니다. 불필요한 정보를 나눠서 보낼필요는 없으니까요. 일단은 판단은 잘해주신거같아요.

넵 의견 감사합니다!
현재 요구사항으로는 상품은 반드시 카테고리를 가져야하기 때문에 따로 상품만을 관리하는 API는 필요하지 않을 것 같네요 :)
추후에 이런 상황을 만나게 되면 DTO를 나누는 방향을 고려해보도록 하겠습니다!

2024-07-17 11:51 UTC, 5win commented on src/main/java/gift/entity/Member.java
> +    public void addWishlist(Wishlist wishlist) {
> 단순히 서비스레이어에서 각 도메인들이 필요한 정보들을 꺼내서 다루기보다 핵심로직은 도메인이 가지도록하는게 좋다는 차원에서 남겼구요, wishlist가 해당 member가 가질 수 있는것인지에 대한 검사가 필요하다면 넣는것 등이 해당될 수 있습니다. 지금은 없을수는 있어도 도메인간의 연관관계를 가질때 필요한 내용이라고 봐주시면 될 것 같습니다.

말씀 감사합니다!
사실 그렇게 와닿지는 않는 것 같긴 한데,  아직 제가하는 과제가 그렇게 복잡한 로직을 가진 것이 아니라 필요성을 느끼지 못해서 그런 것이 아닐까 싶습니다.
DTO도 처음에는 왜 필요한지 몰랐지만 기능을 추가하다보니 필요성을 느끼게 되면서 왜 사용하는지 이해가 되었던 기억이 있네요.

아마 "엔티티와 직접적인 로직에 대한 처리는 엔티티에 맡기는 것이 좋다" 라고 이해가 되는데, 그렇다고 DB와 관계를 가져야하는 로직을 넘길 것 같진 않다고 생각합니다.
예를들어 Member 엔티티에 wishlistCount라는 변수를 추가한다면, 위시리스트가 꽉차있는 회원이 위시리스트 추가를 할 때 엔티티에게 회원의 위시리스트가 꽉차있는지 묻는 로직 같은 경우에 엔티티에 위임할 수 있을 것 같다는 생각이 드는데 어느정도 비슷하게 이해한걸까요?

2024-07-17 11:53 UTC, 5win commented on src/main/java/gift/controller/CategoryController.java
> +     */
> 이런 주석들은 지워주셔도 될거같습니다 :)

넵 반영하였습니다. 너무 뻔한 로직과 리턴값을 가진 메서드들의 주석은 제거했습니다.
주석들 때문에 약간 복잡해보인다는 느낌을 받았는데 지우고나니 더 보기 좋은 것 같기도 합니다.

그리고 주석이 없는 대신 메서드 명을 좀더 잘 지어야겠다는 느낌을 좀 받았습니다

2024-07-17 11:55 UTC, 5win commented on src/main/java/gift/dto/ProductDto.java
> +    private Long categoryId;
> 라는 요구사항인데 지정해야한다가 아니라 할 수 있다면 없어도 되는 걸까요. 이건 저도 잘 모르겟네요. 어쨌든 카테고리 지정이 필수인건 전혀 어색하지 않아서 괜찮은것같습니다.

제가 조금 애매하게 적어놓았네요. 요구사항에는 반드시 지정해야한다고 나와있어서 이렇게 유지하겠습니다!

2024-07-17 12:08 UTC, 5win commented on src/main/java/gift/dto/ProductDto.java
> +    private Long categoryId;
> 추가로 서비스 운영을 하고있는 상황에서 카테고리추가 요구사항이 왔다면 어떻게 사용자들에게 영향이 가지않게 추가할 수 있을지도 고민만해보시면 좋을거같아요.

고민해볼 부분 주셔서 감사합니다 :)

이미 운영 중인 상태에서 지금과 같이 카테고리 기능을 추가하려면 제 생각에는 좀 추가적인 프로세스가 필요하지 않을까 생각됩니다.
카테고리 엔티티를 만들고 상품과 연관관계를 맺는 것 까지는 현재 서비스에 영향이 가지 않을 것 같긴 합니다.
대신 이제 카테고리 선택을 필수(Not Null)로 하는 경우에는 추가된 제약조건에 의해 기존 상품 데이터에 영향이 있을 것으로 생각됩니다.

방법으로는 2가지 정도 있다고 생각이 됩니다.
1. 카테고리 지정을 필수(Not Null)로 하되, 기존 상품들은 모두 "카테고리 지정 안됨"과 같은 임시 카테고리로 일괄 처리합니다. 그 후 상품 관리자들에게 카테고리를 지정하도록 안내를 하면 될 것 같습니다.
2. 카테고리 지정을 선택으로 (Null 허용) 으로 하여 기존 상품 데이터들이 제약조건을 위반하지 않도록 유지합니다. 그리고 마찬가지로 상품 관리자들에게 카테고리를 지정하도록 안내를 합니다. 대신 새 상품들의 경우엔 카테고리를 지정하도록 강제해야하므로 front단이나 컨트롤러 단에서 검증하도록 할 수 있을 것 같습니다. 그 후 모든 기존 상품들의 카테고리 지정이 완료되면 Not Null로 바꾸면 될 것 같습니다.

2024-07-17 12:11 UTC, 5win commented on src/main/java/gift/dto/CategoryDto.java
> +    private String name;
> 이 필드외에 다른 필드의 제약사항은 필요없을까요? 요구사항에 없더라도 스스로 정의해보시는것도 좋습니다.

넵 반영하여 필요하다 생각되는 필드와 Member에 대해서도 검증 로직을 추가해봤습니다.

그리고 물론 아직 서비스 레이어에서의 입력값 검증을 하진 않았지만,
DTO가 없는 경우엔 컨트롤러단의 검증 로직과 엔티티의 검증, 제약조건, 매핑조건들이 섞여 가독성이 떨어지는 것을 느껴서 Member도 MemberDto를 만들어 로직을 좀 분산시켜보았습니다.

2024-07-17 12:13 UTC, 5win commented on src/main/java/gift/service/CategoryService.java
> +    private Category checkCategoryExistsById(Long id) {
> check~~ 면 boolean을 리턴할거같아요. 메서드 이름을 바꿔보면 어떨까요?

생각해보지 못한 부분인데 그럴 수 있을 거 같네요 👍 

해당 클래스의 두 메서드를 각각 `findCategoryByIdOrElseThrow()`, `assertCategoryNotDuplicate()`로 바꿔보았습니다.

2024-07-17 12:16 UTC, 5win commented on src/main/java/gift/service/ProductService.java
>      public void editProduct(ProductDto product) {
> 상품 카테고리만 수정하는 api를 만들어보면 어떨까요?

현재는 상품 정보 수정시에 함께 수정하거나 부분 수정을 하도록 되어있습니다.
상품 카테고리만을 수정하는 경우는 굳이 필요하다고 생각하지 않아서 구현하진 않았는데 어떤 경우에 필요할까요??

2024-07-17 12:18 UTC, 5win commented on src/main/java/gift/entity/Member.java
> +import gift.constants.ErrorMessage;
> 핵심 클래스들에 대한 단위테스트를 만들어보면 어떨까요?

엔티티 클래스에 대한 단위 테스트를 말씀하시는 것으로 이해됩니다!
음..엔티티의 생성, DTO에서 엔티티로 변환, updateProduct(), addWishlist() 와 부분들에 대한 검증을 말씀하시는 걸까요?

2024-07-17 15:05 UTC, jaymarystella commented on src/main/java/gift/entity/Member.java
> +    public void addWishlist(Wishlist wishlist) {
넵 맞습니다. 서비스레이어에서 작성한 로직을 보고 로직의 분기흐름이라든지 트랜잭션 관리라든지 이외의 비지니스로직들이 보이면 항상 책임소재를 고민해보시면 어디에 넣으면 좋겠다의 기준이 생기실거에요

(첨언하면 사실 지금은 데이터베이스와 1:1매핑이되는 클래스를 엔티티로 만들어서 사용하고 로직도 가지고있게 되는데 나쁜구조는 아니지만, 개인적인 경험으로 도메인로직을 조금 더 풍부하게 가져가야하는 프로젝트에서는 엔티티는 별도로두고 도메인클래스까지 분리해서 사용한 적이 있었습니다.)

2024-07-17 15:08 UTC, jaymarystella commented on src/main/java/gift/controller/CategoryController.java
> +     */
첨언하면 주석은 꼭 필요하다고생각합니다.
개인적으로.. 주석에 설명이 필요없게 메서드명을 잘짓자 뭐 이런얘기는 크게 공감하진 않구요,

주석에는 코드설명이 아닌 왜이렇게 짤수밖에 없었는지에 대한 정보가 담겨야합니다. 그당시 컨텍스트를 아는사람만이 알수있는 정보들을 담아야합니다. 그래야 후세의 사람들이 코드를 유지보수하기가 수월합니다. 순수한 이론, 이상보다는 현실적이고 퍼포먼스가 날 수 있는 방향을 고민하시길바랍니다.

2024-07-17 15:25 UTC, jaymarystella commented on src/main/java/gift/dto/ProductDto.java
> +    private Long categoryId;
많은 고민해주셨네요 👍🏼
정책적인 부분은 정하기나름이라 말씀주신 방향대로 하는것도 무방할것같습니다.
신규로 추가되는 컬럼이기때문에 테이블에 넣어주는 작업을 먼저하되 작업이 완료될때까지는 사용자가 해당 컬럼을 바라보지 못하도록 처리를 해줘야할거구요, 컬럼추가와 마이그레이션작업도 리소스사용량을 보고 적절한 시점과 시간을 가지고 진행해야될것입니다.
또한 현재 운영중인 테이블을 건드리는 작업은, 특히 수천만에서 억단위의 row를 가진 테이블이라면 (지금기준으로는 관계형데이터베이스) 단순히 업데이트를하게되면 문제가 발생할 수 있습니다. 어떤 벤더사를 쓰느냐에 따라 다를순있겠지만 업데이트하려는 대상 이상으로 레코드가 잠겨버리는경우도 있을수있습니다.

2024-07-17 15:26 UTC, jaymarystella commented on src/main/java/gift/service/ProductService.java
>      public void editProduct(ProductDto product) {
상품의 카테고리를 단순히 변경하려고하는데 상품의 부가정보까지 보낼필요는 없을거라 필요할것도 같은데요, 이 부분은 선택적으로 구현하셔도될거같네요. api하나로 퉁칠순있겠지만 분리해보는것도 효율적인 방법으로 보여서요.

2024-07-17 15:26 UTC, jaymarystella commented on src/main/java/gift/entity/Member.java
> +import gift.constants.ErrorMessage;
넵 addWishList나 updateProduct는 핵심적인 로직으로 보입니다.

2024-07-17 15:27 UTC, jaymarystella approved these changes
안녕하세요 승규님~
과제 열심히 해주셨네요. 멋집니다.
질문주신부분은 코멘트 남겨두었는데 부족한 부분있으면 다시 말씀주시길바랍니다.
다음 단계에서 뵐게요.

2024-07-17 15:28 UTC, merged

2024-07-19 08:51 UTC, 5win commented on src/main/java/gift/controller/CategoryController.java
> +     */
> 첨언하면 주석은 꼭 필요하다고생각합니다. 개인적으로.. 주석에 설명이 필요없게 메서드명을 잘짓자 뭐 이런얘기는 크게 공감하진 않구요,
> 
> 주석에는 코드설명이 아닌 왜이렇게 짤수밖에 없었는지에 대한 정보가 담겨야합니다. 다시말해 그당시 컨텍스트를 아는사람만이 알수있는 정보들을 담아야합니다. 그래야 후세의 사람들이 코드를 유지보수하기가 수월합니다. 순수한 이론, 이상보다는 현실적이고 퍼포먼스가 날 수 있는 방향을 고민하시길바랍니다.

그 당시의 컨텍스르라는 말이 좋은 것 같습니다 👍 
단지 어떤 일을 하는 메서드인지 적는 것보다 "why"에 좀더 초점을 둔 주석이 좋은 주석일 수 있겠네요!

2024-07-19 08:55 UTC, 5win commented on src/main/java/gift/dto/ProductDto.java
> +    private Long categoryId;
단순히 테스트용 DB와 달리 많은 데이터를 가진 운영 DB는 확실히 고려해야할 사항이 많은 것 같네요..
좋은 말씀 감사합니다!