충남대 BE_이택 4주차 과제 step1
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #159
Opened 2024-07-16 21:26 UTC by LeeTaek2T

**궁금한점**
1. 연관관계 매핑을 할 때 id만 FK로 두어 매핑을 하는지 궁금합니다. (id+name을 FK로 두는 경우는 없는지 궁금합니다.)

2. 저는 product에 카테고리 내용이 모두 들어가게 했습니다. 그런데 이렇게 되는 경우 product에 불필요한 내용이 들어가는건 아닌지 궁금합니다. 데이터베이스에서는 product테이블에 category의 PK가 FK로 되어있어, JOIN을 통해 category의 내용을 모두 갖고올 수 있는데 제가 짠 코드는 product에 Category자체가 들어가 있습니다. 데이터베이스와 달리 이렇게 product안에 category클래스를 갖고 있는게 맞는건지, 아니면 product에서 category의 PK만 FK로 갖게하고 나중에 category내용이 필요할 떄 따로 service처리를 해줘야하는지 잘 모르겠습니다.

3. Product와 Wishlist연관관계 매핑에서 cacade=CascadeType.ALL을 사용할 경우, postman에서는 잘 돌아가는데 Test에서는 돌아가지가 않습니다. 구글링을 해보아도 명확한 답을 찾을 수가 없어 질문드립니다.

2024-07-17 13:06 UTC, ksy90101 requested changes
0단계 커밋 머지 이후 다시 요청주세요.
diff가 너무 많아서 확인하기가 어렵습니다 ㅠㅠ

2024-07-18 13:38 UTC, ksy90101 requested changes
고생많으셨어요~
간단한 피드백을 남겼으니 한번 확인해주세요!

2024-07-18 13:38 UTC, ksy90101 commented on src/main/java/gift/Controller/CategoryAdminController.java
> +    @RequestParam String imageUrl, @RequestParam String description){
POST에서 requestParam으로 데이터를 받는게 맞을까요?

참고링크: https://cl8d.tistory.com/63

2024-07-18 13:38 UTC, ksy90101 commented on src/main/java/gift/Controller/CategoryController.java
> +public class CategoryController {
(질문)

기획적으로 Category를 admin이 아닌 다른곳에서도 생성이 가능한가요?

여기도 생성과 업데이트, 삭제가 존재하는 이유가 궁금합니다.

2024-07-18 13:38 UTC, ksy90101 commented on src/main/java/gift/DTO/Category.java
> +  private String description;
일반 string에서는 255자까지만 사용가능한데, 혹시 description이 255자까지 입력되어도 될까요?

이런경우 @Lob이라는 어노테이션이 있는데요 한번 확인해보시면 어떨까 생각이 듭니다~

2024-07-18 13:38 UTC, ksy90101 commented on src/main/java/gift/DTO/Category.java
> +  private String color;
1. color는 코드가 정해져 있을텐데, 글자수 제한이 필요없을까요?
2. 이제부터 한번 모델(엔티티)에도 validate를 신경써보면 어떨까요?

2024-07-18 13:38 UTC, ksy90101 commented on src/main/java/gift/DTO/Category.java
> +  private String imageUrl;
2. 이제부터 한번 모델(엔티티)에도 validate를 신경써보면 어떨까요?

2024-07-18 13:38 UTC, ksy90101 commented on src/main/java/gift/DTO/CategoryDto.java
> +public class CategoryDto {
혹시 DTO에 setter를 유지하시는 이유가 있나요?

2024-07-18 13:38 UTC, ksy90101 commented on src/main/java/gift/DTO/Category.java
> +  public Category() {
JPA를 사용하면 기본적으로 기본생성자가 필요하지만, Protect로 접근제어자를 최소한 해보면 어떨까요?

2024-07-18 13:38 UTC, ksy90101 commented on src/main/java/gift/DTO/ProductDto.java
> +    this.categoryDto=categoryDto;
```suggestion
    this.categoryDto = categoryDto;
```
이런부분을 신경쓰시면 좋을거 같아요.

그러나 신경쓰기 어려우니.

https://dev-jhl.tistory.com/entry/IntelliJ-IDEA-%EC%A0%80%EC%9E%A5-%EC%8B%9C-%EC%95%A1%EC%85%98-Actions-on-Save-%EA%B8%B0%EB%8A%A5-%EC%B6%94%EA%B0%80

위의 링크를 참고하여 save action 기능을 쓰시면 좋을거 같네요~

2024-07-18 13:38 UTC, ksy90101 commented on src/main/java/gift/Service/CategoryService.java
> +    List<CategoryDto> categoryDtos = categories.stream().map(ConverterToDto::convertToCategoryDto)
```suggestion
    List<CategoryDto> categoryDtos = categories.stream()
    .map(ConverterToDto::convertToCategoryDto)
   .toList()
```
이런식으로 개행을 한줄의 점 하나씩으로 해서 하면 더 가독성이 높아집니다~

2024-07-18 13:38 UTC, ksy90101 commented on src/test/java/gift/Controller/ProductControllerTest.java
> +  private CategoryController categoryController;
CategoryController는 따로 만드셨는데 테스트코드는 ProductController에 넣으신 이유가 있나요?

2024-07-18 15:20 UTC, LeeTaek2T commented on src/main/java/gift/Controller/CategoryController.java
> +public class CategoryController {
1. Cateogory를 admin이 아닌 다른 곳에서도 생성 가능합니다.
2. 생성과 업데이트, 삭제가 존재하는 이유는 관리자가 필요한 Category를 생성, 업데이트, 삭제를 시켜 Product가 Category에 들어갈 수 있게 하기 위함입니다.


위처럼 질문해주신 의도가 궁금합니다!

제가 질문을 이해한 바로는 admin(관리자)이 아닌 다른 곳(클라이언트)도 Category를 생성할 수 있는지로 이해를 했습니다.
현재 저는 관리자와 클라이언트를 나눠 개발하지 않아 "admin"과 "다른 곳"에서도 생성이 가능합니다.
(Product 생성, 업데이트, 삭제도 Category와 똑같이 관리자와 클라이언트를 나누지 않았습니다.)

멘토님은 Cateogory생성을 admin과 client를 나눠(사용자에게 권한을 주어) Category를 생성하는 것이 좋다고 생각하여 위와 같은 질문을 주신 것일까요?

2024-07-18 16:10 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Category.java
> +  private String description;
>일반 string에서는 255자까지만 사용가능한데, 혹시 description이 255자까지 입력되어도 될까요?

이 부분은 생각 못했습니다. 알려주셔서 감사합니다!

2024-07-18 16:12 UTC, LeeTaek2T commented on src/main/java/gift/DTO/CategoryDto.java
> +public class CategoryDto {
다 지웠던 걸로 기억했는데 이 부분은 맨 처음에 만들어두고 잊었던 것 같습니다..ㅠㅠ

2024-07-18 16:18 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Category.java
> +  private String color;
1. 코드가 최소 글자가 어떻게 되고 최대 글자가 어떻게 되는지 확인한 다음에 제한하겠습니다!
2. DTO에서 validate를 모두 거쳐 entity에 저장이 되는데 entity에도 validate를 적용하면 똑같은 validate를 두 번 적용한다는 생각이 듭니다.  혹시 entity에도 validate를 적용하면 어떤 점이 좋나요?

2024-07-18 16:19 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Category.java
> +  private String imageUrl;
이 부분도 위의 답변과 똑같은 생각이 듭니다.

2024-07-18 19:56 UTC, LeeTaek2T commented on src/main/java/gift/Controller/CategoryAdminController.java
> +    @RequestParam String imageUrl, @RequestParam String description){
맨 처음에는 해당 부분을 @modelAttribute를 이용하여 바인딩 후 Product를 추가했습니다.
그런데 modelAttribute를 이용하려면 setter가 필요했고, RequestParam을 이용했습니다.

멘토님이 보내주신 링크를 보고 RequestParam을 이용하는건 좋지 않다라는 생각이 들어,
RequestBody로 받아야겠다는 생각을 하였습니다.
이후, ajax를 이용하여 json으로 값을 받아왔습니다.

2024-07-18 20:35 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Category.java
> +  public Category() {
Protect로 접근제어자를 최소화 하는게 좋은 것 같습니다!

2024-07-18 20:35 UTC, LeeTaek2T commented on src/main/java/gift/DTO/ProductDto.java
> +    this.categoryDto=categoryDto;
알려주셔서 감사합니다!

2024-07-18 20:38 UTC, LeeTaek2T commented on src/main/java/gift/Service/CategoryService.java
> +    List<CategoryDto> categoryDtos = categories.stream().map(ConverterToDto::convertToCategoryDto)
오..감사합니다! 앞으로 해당사항 반영하며 코드를 구현하겠습니다

2024-07-18 21:19 UTC, LeeTaek2T commented on src/test/java/gift/Controller/ProductControllerTest.java
> +  private CategoryController categoryController;
해당 부분은 ProductController Test를 할 때 의존성 떄문에 필요하여 넣었습니다.
CategoryController Test도 따로 만들었습니다!

2024-07-19 07:37 UTC, ksy90101 approved these changes
고생많으셨습니다~
2단계에서 뵐게요!
언제든 질문이 있다면 DM주세요!

2024-07-19 07:37 UTC, merged