충남대 BE 박상우 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #164
Opened 2024-07-17 04:23 UTC by pswaao88

충돌 확인을 위해 미리 생성했습니다.

2024-07-17 09:24 UTC, Hyeon9mak requested changes
안녕하세요 상우님~ 1단계 잘 진행해주셨어요.

요구사항에서 에 카테고리 등록이 가능해야했던 것 같아요.
관련 로직이 누락된 것 같네요..!
주어진 요구사항을 달성하는 것은 그 무엇보다 중요합니다.
요구사항을 꼼꼼히 확인하는 습관을 다시 한번 점검하는 것도 좋겠네요!

> Lazy 와 Eager에 대해서 이해가 되도록 공부를 진행하여 이 코드들를 왜 썼는지에 대해서 알게될거같습니다.

다음 리뷰 요청 전 학습하신 내용을 PR 코멘트로 남겨주세요~!

그 외 간단한 코멘트 몇 가지 남겼으니 확인해주세요~

2024-07-17 09:24 UTC, Hyeon9mak commented on src/main/java/gift/Controller/CategoryController.java
> +    public CategoryController(CategoryService categoryService){
`@RestController` 의 의미를 알게 되었으므로 `@Controller` 대신 적용해줄 수 있겠네요!

2024-07-17 09:24 UTC, Hyeon9mak commented on src/main/java/gift/Controller/ProductController.java
>          productService.addProduct(product);
🤔 코드를 제출하기 전에 한번 더 확인하는 습관을 기르면 좋겠어요. 관련 코멘트를 자주 남기는 것 같아요.

2024-07-17 09:24 UTC, Hyeon9mak commented on src/main/java/gift/Model/Product.java
> +    private Category category;
ManyToOne 방향에서 CascadeType.REMOVE 를 사용할 경우
Many 가 지워질 때와 One 이 지워질 때 각각 어떤 결과가 발생할까요?

2024-07-17 09:24 UTC, Hyeon9mak commented on src/main/java/gift/Model/Wishlist.java
> +    @ManyToOne(fetch = FetchType.EAGERgit , cascade = CascadeType.REMOVE)
👀

2024-07-17 09:38 UTC, pswaao88 commented on src/main/java/gift/Controller/ProductController.java
>          productService.addProduct(product);
계속 step0 merge전에 step1을 진행하려고 하면서 데이터가 날라가지 않도록 하기 위해 다른 저장소에 파일 저장하다가 브랜치 변경시에 파일이 사라지고 복구하면서 미처 확인을 못해 계속 남는 것 같습니다! 한번 더 확인을 하도록 하겠습니다!

2024-07-17 09:39 UTC, pswaao88 commented on src/main/java/gift/Model/Wishlist.java
> +    @ManyToOne(fetch = FetchType.EAGERgit , cascade = CascadeType.REMOVE)
git을 바로쓰면서 잘못 쓰여진거 같습니다 지우겠습니다!

2024-07-17 09:58 UTC, pswaao88 commented on src/main/java/gift/Controller/CategoryController.java
> +    public CategoryController(CategoryService categoryService){
기존 Controller들은 html파일과 연결을 하기 위해서 @Controller를 사용했는데 Category같은 경우 Category DTO를 생성해서 값을 넘겨줄 수 있도록 하겠습니다!

2024-07-17 12:18 UTC, pswaao88 commented on src/main/java/gift/Model/Product.java
> +    private Category category;
우선 공부를 통해 알게된 것은 CascadeType.REMOVE를 쓰게되면 CascadeType.REMOVE이 선언된 부모 엔티티가 삭제가 되면 그 부모 엔티티의 자식 엔티티가 삭제가 됨을 알게 됐습니다.

ManyToOne관계에서
Many가 지워지는 경우는 Many쪽에 연관된 One엔티티 1개 만 삭제가 됩니다.
One 지워지는 경우 One 쪽에 연관된 모든 Many엔티티가 삭제가 됩니다.
라고 이해를 했습니다.  제가 이해한 내용이 맞을까요?

2024-07-18 12:59 UTC, pswaao88 commented on src/main/java/gift/Controller/CategoryController.java
> +    public CategoryController(CategoryService categoryService){
아직 jpa에 대한 이해도가 높지않아서 질문 드립니다!
category의 경우 product에 쓰여지지 않으면 그냥 delete가 가능하지만 쓰여지는 경우에는 wishlist에서 했던 것 처럼 category와 product의 연결을 끊기 위해 null로 바꿔준 다음에 진행 해야 삭제를 할 수 있는게 맞을까요?

2024-07-18 14:07 UTC, Hyeon9mak approved these changes
안녕하세요 상우님 피드백 잘 반영해주셨어요!
질문 주신 내용에 대해서도 답변 남겨드렸으니 확인해주세요 😄 👍

2024-07-18 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Controller/CategoryController.java
> +        return ResponseEntity.ok().body(deleteCategory);
Post, Put, Delete 가 각각 "추가한다", "변경한다", "제거한다" 의 의미를 가지므로
`add`, `update`, `delete` 를 url 에서 생략해볼 수도 있겠어요 👍

2024-07-18 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Model/Product.java
> +    private Category category;
현재 작성된 구조는 그러한 형상을 띄겠네요~ 그렇다면 ManyToOne 에서는 REMOVE 대신 다른 걸 이용해주는게 더 좋겠죠? 😉

2024-07-18 14:07 UTC, Hyeon9mak commented on src/main/java/gift/Model/Product.java
> +    private Category category;
> category의 경우 product에 쓰여지지 않으면 그냥 delete가 가능하지만 쓰여지는 경우에는 wishlist에서 했던 것 처럼 category와 product의 연결을 끊기 위해 null로 바꿔준 다음에 진행 해야 삭제를 할 수 있는게 맞을까요?

category 가 product 에 대한 의존 (category 테이블에 product_id 컬럼이 있음)이 있다면 제거가 가능할테고,
product 가 category 를 의존하고 있다면 곧바로 제거가 어렵겠죠.
그런데 대부분 many 쪽이 one 을 의존하는 형상을 가집니다.
즉, product 가 category 를 의존하고 있을거에요.

그렇다면 category 를 지우기 위해서는 product 들에서 category 를 모두 제거하거나,
product 를 다른 category 로 이동, 이관시켜준 후 제거를 시도하는게 좋겠네요~

2024-07-18 14:07 UTC, merged