경북대 BE_박준석_4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #179
Opened 2024-07-17 09:58 UTC by Lucerna00

상품 카테고리 관련 로직을 추가하였고, 관리자 페이지에서 카테고리를 고를 수 있도록 수정하였습니다.
그리고 말씀하신 @AssertTrue도 사용해 보았습니다.

Q. product DTO는 category ID를 다루기 때문에 toEntity에선 서비스에서 찾은 category를 넘겨주었습니다.
앞으로도 연관 관계가 되어 있는 DTO의 toEntity는 이런 식으로 하면 될까요?
```
public Product toEntity(Category category) {
    return new Product(name, price, imageUrl, category);
}
```

2024-07-17 13:01 UTC, gongdongho12 requested changes
리뷰 많이 하지도 않았던 것 같은데 벌써 4주차네요

이번주차도 고생 많으셨습니다!

2024-07-17 13:01 UTC, gongdongho12 commented on src/main/java/gift/dto/CategoryDTO.java
> +    }
이런 로직을 이 프로젝트의 컨벤션으로 가져가면 이렇게 사용해도 되는거라서
준석님께서 더 좋은방향이 있거나 하면 바꿔서 컨벤션으로 적용하시면 됩니다

다만 기존에 사용하던 패턴인 느낌인데 어디는 이렇게 쓰고 어디는 다르게 쓰는 중구난방만 아니면 좋을 것 같아요
그리고 만약 회사에서 프로젝트를 진행한다면 그 팀의 컨벤션에 녹아들어가야곘죠?

2024-07-17 13:01 UTC, gongdongho12 commented on src/main/java/gift/dto/MemberPasswordDTO.java
> +    }
이런 기능을 위해 `@NewPasswordsMatch`를 만들면 사실 동작은 equals하나인데 어노테이션과 로직처리 각각 파일로 만들어주는 기능이니까요

2024-07-17 13:01 UTC, gongdongho12 commented on src/test/java/gift/service/CategoryServiceTest.java
> +        category = new Category(1L, "test", "#FFFFFF", "testImageUrl", "test");
이렇게 만들어서 자주 사용하는 테스팅 객체는 testFixture 관리 방법에 대해 찾아보시구 적용해봐도 좋을 것 같습니다

2024-07-17 13:01 UTC, gongdongho12 commented on src/test/java/gift/service/CategoryServiceTest.java
> +    void deleteProduct() {
DisplayName으로 깔끔하게 테스트 결과 보고 빠르게 파악할 수 있게 되서 좋네요 👍🏼

2024-07-17 13:01 UTC, gongdongho12 commented on src/test/java/gift/service/ProductServiceTest.java
> +        given(productRepository.save(any(Product.class))).willReturn(updatedProduct);
mockking 적용 👍🏼

2024-07-17 13:01 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        Product product = new Product(id, productDTO.name(), productDTO.price(), productDTO.imageUrl(), category);
프러덕트 서비스인데 카테고리 레포지토리를 조회하는 상황이면
카테고리 관리포인트가 2개로 늘어나는 상황이 아닐까요?

예를 들어 위와 같은 로직에서 categoryService에 getCategoryById 같은 메서드를 사용하면 로직의 중복 예외 처리 없이 위 로직이 간소화 되겠죠?

2024-07-17 13:01 UTC, gongdongho12 commented on src/main/java/gift/controller/CategoryController.java
> +    }
카테고리 갯수는 페이징 처리가 없어도 괜찮을까요?

2024-07-17 14:35 UTC, Lucerna00 commented on src/main/java/gift/dto/CategoryDTO.java
> +    }
개인 취향이나 환경에 맞추어 사용하는군요!
중구난방 안되게 주의하겠습니다
답변 감사합니다~

2024-07-17 14:36 UTC, Lucerna00 commented on src/main/java/gift/dto/MemberPasswordDTO.java
> +    }
두 필드 값을 비교하며 검증하기 위해 방법을 찾다가 커스텀 어노테이션이 보여 적용했었는데,
`@AssertTrue` 이 방법이 확실히 간편하네요!

2024-07-17 14:36 UTC, Lucerna00 commented on src/test/java/gift/service/CategoryServiceTest.java
> +        category = new Category(1L, "test", "#FFFFFF", "testImageUrl", "test");
Test Fixture를 관리하는 방법에는 크게

- `@beforeAll` / `@beforeEach`
- private 메서드
- 별도의 클래스

가 있던데 이것도 개인 취향이나 컨벤션에 맞추면 되나요?

2024-07-17 14:36 UTC, Lucerna00 commented on src/main/java/gift/service/ProductService.java
> +        Product product = new Product(id, productDTO.name(), productDTO.price(), productDTO.imageUrl(), category);
해당 코드를 작성할 때 서비스를 주입할지, 레퍼지토리를 주입할지 많이 고민했습니다
서비스로 바꾸어 보니 Product 서비스가 Product 데이터에만 집중하는 듯한 느낌이 드네요

다만 WishedProduct 서비스에선
productRepository를 productService로 바꾸게 될 시
productService 리턴값이 DTO라서 다시 Product 엔티티와 Category 엔티티를 생성해야 한다는 단점이 있습니다.
여기선 trade-off라고 생각하고 그대로 두는 것이 나을까요?
```
public WishedProductDTO addWishedProduct(MemberDTO memberDTO, WishedProductDTO wishedProductDTO) {
    Product product = productRepository.findById(wishedProductDTO.productId()).orElseThrow(NoSuchProductException::new);
    WishedProduct wishedProduct = new WishedProduct(memberDTO.toEntity(), product, wishedProductDTO.amount());
    return wishedProductRepository.save(wishedProduct).toDTO();
}
```

2024-07-17 14:36 UTC, Lucerna00 commented on src/main/java/gift/controller/CategoryController.java
> +    }
상품을 추가하거나 수정할 시 카테고리를 셀렉트 박스에서 선택할 수 있도록 하였고,
카테고리 개수도 많지 않을 거 같아서 페이징 처리를 하지 않았습니다

2024-07-18 10:32 UTC, gongdongho12 commented on src/test/java/gift/service/CategoryServiceTest.java
> +        category = new Category(1L, "test", "#FFFFFF", "testImageUrl", "test");
넵넵 코드가 많아지면 분리해서 정리하는게 좋으니까요!

2024-07-18 10:34 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        Product product = new Product(id, productDTO.name(), productDTO.price(), productDTO.imageUrl(), category);
영속성 객체를 쓰는 경우라면 엔티티를 리턴하는 메서드를 서비스에 생성하라고 했을 것 같은데요
위 내용은 꼭 영속성 객체가 아니라도 적용가능한 부분이라 저렇게 사용되어도 무방할 것 같습니다

2024-07-18 16:10 UTC, Lucerna00 commented on src/test/java/gift/service/CategoryServiceTest.java
> +        category = new Category(1L, "test", "#FFFFFF", "testImageUrl", "test");
여러 테스트에서 공동으로 사용되는 엔티티가 많다 보니 별도의 fixture 클래스를 만들어 사용하였습니다

2024-07-18 16:30 UTC, Lucerna00 commented on src/main/java/gift/service/ProductService.java
> +        Product product = new Product(id, productDTO.name(), productDTO.price(), productDTO.imageUrl(), category);
계층 간의 데이터 전달은 DTO로 하려다 보니 서비스 반환 값을 다 DTO로 하였네요😓
그리고 아래 문장이 잘 이해되지 않는데 혹시 추가 설명해 주실 수 있을까요??

> 위 내용은 꼭 영속성 객체가 아니라도 적용가능한 부분이라 저렇게 사용되어도 무방할 것 같습니다

2024-07-19 14:49 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        Product product = new Product(id, productDTO.name(), productDTO.price(), productDTO.imageUrl(), category);
영속성 객체는 DAO객제중에 DB 커넥션이 물려있는 친구들을 의미합니다
DAO로 전달이 필요한 상황이 있을 수 있어요 (연관관계 데이터 조회 등)

그래서 서비스라고 항상 DTO로 변환해서 준다기 보다 필요할 땐 DAO로 줄 수 있다 정도로 생각하시구 넘어가시면 될 것 같아요!

2024-07-19 14:49 UTC, merged