부산대 BE_박정우 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #185
Opened 2024-07-17 11:18 UTC by doubleclip118

2024-07-17 14:36 UTC, yoo-jaein requested changes
step2 고생하셨습니다!
리뷰 코멘트 확인 부탁드려요

2024-07-17 14:36 UTC, deactivated-user commented on src/main/java/gift/controller/OptionController.java
> +@RequestMapping("api/products/option")
~/options 로 복수형이 되는 것이 더 적합한 것 같습니다!

2024-07-17 14:36 UTC, deactivated-user commented on src/main/java/gift/controller/OptionController.java
> +        Long deletId = optionService.deleteOption(id);
변수 이름에 오타가 있습니다

2024-07-17 14:36 UTC, deactivated-user commented on src/main/java/gift/controller/dto/OptionRequest.java
> +    @NotEmpty(message = "Product Quantity can not be empty")
```
- 옵션 이름은 공백을 포함하여 최대 50자까지 입력할 수 있다.
- 특수 문자
    - 가능: ( ), [ ], +, -, &, /, _
    - 그 외 특수 문자 사용 불가
- 옵션 수량은 최소 1개 이상 1억 개 미만이다.
```
요구사항을 추가해주세요!

2024-07-17 14:36 UTC, deactivated-user commented on src/main/java/gift/repository/OptionRepository.java
> +    Optional<Option> findByName(String name);
지금 사용하는 곳이 없네요!

2024-07-17 14:36 UTC, deactivated-user commented on src/main/java/gift/service/OptionService.java
> +    OptionRepository optionRepository;
private final로 선언해주세요!

2024-07-17 14:36 UTC, deactivated-user commented on src/main/java/gift/controller/dto/OptionRequest.java
> +    private int quantity;
```@Range``` 를 서서 숫자 범위에 대한 검증을 추가할 수 있습니다.

2024-07-17 14:36 UTC, deactivated-user commented on src/main/java/gift/service/OptionService.java
> +    public OptionResponse addOption(OptionRequest optionRequest) {
옵션 이름에 대한 중복 검사 로직을 별도의 메서드로 분리하면 가독성이 향상될 것 같습니다!

2024-07-17 14:36 UTC, deactivated-user commented on src/main/java/gift/domain/Option.java
> +public class Option {
Option 클래스에 기본 생성자가 없습니다. JPA 엔티티는 기본 생성자가 필요하므로 추가하는 것이 좋습니다!

2024-07-17 14:36 UTC, yoo-jaein commented on src/main/java/gift/controller/dto/ProductRequest.java
> +    @NotEmpty(message = "Product must have at least one option")
옵션 validation에 대한 요구사항을 반영해주세요!

2024-07-17 14:36 UTC, yoo-jaein commented on src/main/java/gift/service/GiftService.java
>          productById.setName(productRequest.getName());
현재 코드는 Product 객체의 내부 상태를 직접 변경하고 있습니다. (setName, setPrice 등) 
이는 객체의 캡슐화를 위반합니다.
Product 클래스 내에 update 메서드를 만들어 한 번에 상태를 변경하도록 수정해볼까요?

2024-07-17 14:36 UTC, yoo-jaein commented on src/main/java/gift/service/GiftService.java
> +        if (options.stream().map(ProductOptionRequest::getName).distinct().count() < options.size()){
Set을 사용하면 중복 체크가 더 간결해질 것 같습니다.

2024-07-17 14:36 UTC, yoo-jaein commented on src/main/java/gift/controller/WishController.java
>  public class WishController {
/wishes로 바꾸는 것이 어떨까요? API 엔드포인트를 복수형으로 두는 것이 일반적인 restful API 설계 방법입니다.

추가로 아래 API에서 POST, DELETE 에 이미 add, remove라는 의미가 담겨있어 ```@PostMapping```, ```@DeleteMapping```으로 두는 것이 적합할 것 같습니다.

2024-07-17 14:36 UTC, yoo-jaein commented on src/main/java/gift/controller/OptionController.java
> +}
관리자 페이지와 사용자 페이지(실서비스)의 요구사항과 역할이 다르기 때문에..
관리자 페이지에서 쓰는 API와 사용자 페이지에서 쓰는 API가 분리되면 좋겠습니다.
섞여있는 경우 다른 개발자(서버, 클라 모두)가 해당 API의 역할을 이해하기 어렵습니다.

2024-07-17 17:20 UTC, doubleclip118 commented on src/main/java/gift/controller/OptionController.java
> +}
그럼 giftcontroller를 customgiftcontroller와 admincontroller 같은 형식으로 바꾸면 될까요??

2024-07-17 18:35 UTC, yoo-jaein commented on src/main/java/gift/controller/OptionController.java
> +}
넵 GiftController, AdminGiftController 등 이름은 적절히 정하시면 될 것 같습니다!

2024-07-18 09:58 UTC, yoo-jaein approved these changes
리뷰 반영된 것 확인했습니다.

API를 분리했더니 애플리케이션 구조가 더 잘 이해되네요! 앞으로 과제 중에 여유가 되신다면 프로젝트의 가독성, 유지보수성을 위해 틈틈히 리팩토링해보시는 것을 추천드립니다.

step2 머지하겠습니다! :)

2024-07-18 09:58 UTC, yoo-jaein commented on src/main/java/gift/service/OptionService.java
> +            () -> new OptionNotFoundException("Option Not Found")
지금 코드도 충분히 좋지만, 엔티티별로 XXXNotFoundException을 만들면 엔티티를 하나 추가할 때마다 예외를 추가해줘야 하는 부담이 있겠네요.
NotFoundException을 사용하되 에러 메시지에 객체 타입을 담아주는 방법을 사용해볼 수도 있을 것 같습니다!

2024-07-18 09:58 UTC, merged