부산대 BE_박혜연 4주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #189
Opened 2024-07-17 13:20 UTC by hyyyh0x

저번에 test코드에서도 @Autowired 대신 생성자 주입 방식을 사용하는 것을 추천하셨는데, 막상 쓰려고 보니 잘 안되더라고요. Repository Test들에서 잘 안됐습니다. 어떤 방식으로 하면 RepositoryTest에도 생성자 주입 방식으로 쓸 수 있을까요?

2024-07-17 14:12 UTC, hyyyh0x commented
양방향 관계에서 부모와 자식 간 데이터 일관성과 무결성을 유지하기 위해서 update쪽에 코드를 작성하였는데,계속 DB에 있는 값이 삭제 되었습니다. 그래서 지금은 주석 처리 해뒀는데 없어도 되는지, 아니면 수정할 수 있는지 궁금합니다!

2024-07-17 18:31 UTC, yoo-jaein requested changes
step1 고생하셨습니다!
리뷰 코멘트 확인 부탁드립니다

2024-07-17 18:31 UTC, deactivated-user commented on src/test/java/gift/repository/WishListRepositoryTest.java
> +
```@DataJpaTest```는 JPA 컴포넌트를 테스트하는 목적으로 만들어졌습니다. 

전체 애플리케이션 컨텍스트를 로드하지 않고 JPA 관련 설정들(repository, datasource, jpa 설정 등..)만 로드하기 때문에 일부 동작하지 않는 부분이 있습니다.
그 중 생성자 주입을 자동으로 처리해주지 않아서, 테스트 클래스 생성자에 ```@Autowired```를 붙이거나 필드 주입을 하는 방법 등을 사용해야 합니다.

```java
@DataJpaTest
public class ProductRepositoryTest {
    private final ProductRepository productRepository;
    private final CategoryRepository categoryRepository;

    @Autowired // 이 부분을 추가
    ProductRepositoryTest(ProductRepository productRepository, CategoryRepository categoryRepository) {
        this.productRepository = productRepository;
        this.categoryRepository = categoryRepository;
    }
    ...
}```

2024-07-17 18:31 UTC, deactivated-user commented on src/main/java/gift/product/ProductApiController.java
>      public ResponseEntity<String> addProduct(@Valid @RequestBody ProductDTO productDTO,
String을 반환하는 것보단 추가된 상품에 대한 정보를 반환하는 것이 클라이언트 측 사용성이 더 좋을 것 같습니다!

2024-07-17 18:31 UTC, deactivated-user commented on src/main/java/gift/product/ProductService.java
> +            productRepository.findByName(productDTO.getName()).getId())) {
이렇게 최적화할 수 있을 것 같아요
```java
    if (productRepository.existsByNameAndIdNot(productDTO.getName(), productDTO.getId())) {
        throw new IllegalArgumentException("존재하는 이름입니다.");
    }
```

2024-07-17 18:31 UTC, deactivated-user commented on src/main/java/gift/product/ProductService.java
> +    }
컨트롤러와 서비스 코드를 전체적으로 한 번 정리하면 좋을 것 같습니다.
1. restful api와 웹페이지용 api 관점에서
현재 XXXApiContoller, XXXController로 어느정도 잘 분리되어 있는 것 같습니다.

2. 관리자 기능을 위한 api와 실서비스 기능을 위한 api 관점에서
관리자 페이지와 사용자 페이지(실서비스)의 요구사항과 역할이 다르기 때문에..
관리자 페이지에서 쓰는 API와 사용자 페이지에서 쓰는 API가 분리되면 좋겠습니다.
섞여있는 경우 다른 개발자(서버, 클라 모두)가 해당 API의 역할을 이해하기 어렵습니다.

2024-07-17 18:31 UTC, deactivated-user commented on src/test/java/gift/repository/CategoryRepositoryTest.java
> +        assertThat(actual.getDescription()).isEqualTo("money");
복합 assertion을 사용하면 여러 필드를 한번에 검증할 수 있습니다.
```java
assertThat(actual)
    .extracting(Category::getName, Category::getColor, Category::getImageUrl, Category::getDescription)
    .containsExactly("상품권", "#ff11ff", "image.jpg", "money");
```

2024-07-17 18:31 UTC, deactivated-user commented on src/test/java/gift/repository/CategoryRepositoryTest.java
> +        //Then
테스트의 예상 결과를 변수로 선언하는 것을 추천합니다!
```java
Category expected = new Category("상품권", "#ff11ff", "image.jpg", "money");

assertThat(actual.get().getName()).isEqualTo(expected.getName());
```

2024-07-17 18:31 UTC, deactivated-user commented on src/main/java/gift/product/ProductService.java
> +    public List<String> getAllCategory() {
메서드 이름은 getAllCategory 인데 실제로는 카테고리의 이름을 반환하고 있네요!

2024-07-17 18:31 UTC, deactivated-user commented on src/main/java/gift/product/ProductService.java
> +        return productRepository.findAll().stream()
productRepository.findAll()을 쓰고 있네요. 
제품의 개수가 적다면 문제가 되지 않겠지만, 서비스가 성장하면서 제품 수가 많아질 경우 성능 문제가 발생할 수 있습니다.

쿼리 최적화를 해볼까요?
현재 카테고리 이름만 반환하고 있기 때문에 '제품이 있는 카테고리의 이름만 가져오는 쿼리' 를 작성해보시면 될 것 같아요.
```java
@Query("SELECT DISTINCT ...... ")
List<String> findDistinctCategoryNamesWithProducts();
```

2024-07-17 18:31 UTC, deactivated-user commented on src/main/java/gift/product/ProductService.java
> +    public Product toProduct(ProductDTO productDTO) throws NotFoundException {
이 메서드는 DTO를 엔티티로 변환하는 역할을 가지고 있습니다.
일반적으로 이런 매핑 로직은 별도의 매퍼 클래스나 DTO 클래스 내부에 들고있습니다.

그리고 매핑 과정에서 categoryService를 의존하고 있어 다소 복잡해 보이네요..
getCategoryById를 해당 메서드 바깥에서 수행하고 카테고리를 이 메서드에 전달하는 방식으로 수정하면 코드가 깔끔할 것 같습니다.

2024-07-17 18:31 UTC, deactivated-user commented on src/main/java/gift/category/CategoryService.java
> +        if (existsByName(categoryDTO.getName())
여기도 쿼리 최적화를 하면 좋겠어요.

2024-07-18 03:14 UTC, hyyyh0x commented
`Category oldCategory = product.getCategory();

        if (!oldCategory.equals(newCategory)) {
            oldCategory.removeProducts(product);
            newCategory.addProducts(product);
        }`
이 부분을 productService의 update에 넣으면 저장되었던 부분을 수정할 때, 저장된 값이 DB에서 사라집니다! 예를 들어 id=1인 값을 저장하고 id=1을 수정하면 id=1이 DB에서 삭제됩니다. 과제는 수정하고 있으며 일단은 위 코드를 삭제하고 작성하도록 하겠습니다.

2024-07-18 05:33 UTC, hyyyh0x commented
멘토님 피드백 반영 완료했습니다.

> 관리자 기능을 위한 api와 실서비스 기능을 위한 api 관점에서
> 관리자 페이지와 사용자 페이지(실서비스)의 요구사항과 역할이 다르기 때문에..
> 관리자 페이지에서 쓰는 API와 사용자 페이지에서 쓰는 API가 분리되면 좋겠습니다.
> 섞여있는 경우 다른 개발자(서버, 클라 모두)가 해당 API의 역할을 이해하기 어렵습니다.

이 부분을 잘 모르겠어서 일단은 users, administrator로 다른 패키지에 구분해뒀는데, 다른 것을 의도하고 말씀 하신 것이라면 알려주세요!

2024-07-19 04:54 UTC, yoo-jaein commented
네 제가 의도한 것은 패키지 분리 / 클래스 분리가 맞습니다!

그리고 toProduct의 파라미터를 조금 수정해보면 categoryService 의존도를 없앨 수 있을 것 같아요.
```java
    public Product toProduct(ProductDTO productDTO, category Category) { ... }
```

2024-07-19 05:09 UTC, yoo-jaein approved these changes
수정할 부분이 많았을 것 같은데 고생하셨어요
step1 머지하겠습니다!

질문주신 부분은 제품을 이전 카테고리에서 제거하고 새로운 카테고리에 넣는 과정에서 cascade와 orphanRemoval 옵션이 적용된 것으로 보여요.
원하는 대로 동작하지 않는 경우 해당 옵션들을 제거하거나, 양방향 대신 단방향 관계로 바꿔보는 등 수정이 필요할 것 같습니다.

2024-07-19 05:10 UTC, merged