경북대 BE_정성훈 4주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #193
Opened 2024-07-17 15:02 UTC by zzoe2346

2024-07-21 16:10 UTC, sang5c requested changes
리뷰가 많이 늦었네요 고생하셨습니다 👍  

요구사항은 모두 만족했으나, 꼭 고민해보고 지나가야하는 부분들이 있어 request change를 드려요.   
리뷰 확인해보시고, 이해가 안가는 부분이 있다면 DM이나 댓글로 남겨주세요!

추가로 다음 내용도 같이 확인해주세요.

- Entity가 DTO를 의존하는 것이 맞는지 다시 고려해주세요!
- getter가 무분별하게 사용되고 있습니다. 의식적으로 연습하는게 어렵다면 getter를 만들지 말고 코드를 작성하기 시작해보면 어떨까요?
- 강의 자료에 나온 E2E 테스트를 먼저 작성해보고, 현재 entity 패키지 내에 위치한 코드들에 대한 테스트를 작성한 다음 다른 테스트들을 작성해주세요.
- 놓친 리뷰가 있는데, CategoryService.getAllCategoryResponses() 메서드 코드 컨벤션이 다른 코드와 다르네요.

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/entity/Option.java
> +    @ManyToOne(fetch = FetchType.LAZY)
`@JoinColumn`을 생략 가능합니다만, 여기서 외래키를 갖고 있음을 확실히 표현해주기 위해 적어주는 편입니다.  
프로젝트나 팀원들의 의견 차이에 따라 생략 하기도, 하지 않기도 하니 있으니 참고해주세요 :)

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +        productRepository.flush();
repository.flush()는 어떤 이유로 호출하고 있나요?

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +        optionService.checkDuplicateOptionName(product.getOptions(), optionRequest.name());
product.getOptions()를 호출하여 값을 꺼낸 다음, 밖에서 값에 대해 검증하는 작업을 하고 있는데 getter 사용 대신 객체가 책임을 수행해보면 어떨까요?

2024-07-21 16:10 UTC, sang5c commented on src/test/java/gift/concurrency/OptionQuantityTest.java
> +public class OptionQuantityTest {
👍  
CountDownLatch에 대해서도 알아보고 적용해보면 좋을 것 같아요.

2024-07-21 16:10 UTC, sang5c commented on src/test/java/gift/concurrency/OptionQuantityTest.java
> +    OptionService optionService;
의도한게 아니라면 접근제어자를 생략하지 말아주세요~

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +    public List<String> getOptionNames(Long productId) {
사용되지 않고 있네요

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +    public List<String> updateOptionNames(Long productId, Long optionId, String changedName) {
사용되지 않고 있네요

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +    public List<Option> convertToOptions(List<OptionRequest> options) {
이 메서드는 여기서 가지는게 맞는지 고민이 좀 필요하겠네요!

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +                .map(optionRequest -> new Option(optionRequest.name(), optionRequest.quantity()))
OptionRequest를 Option으로 바꿔주고 있는데 바로 이어지는 convertToOption()을 사용하지 않는 이유가 있을까요?

2024-07-21 16:10 UTC, sang5c commented on src/test/java/gift/concurrency/OptionQuantityTest.java
> +@SpringBootTest
여기서는 SpringBootTest를 사용했는데 Service와 Controller 테스트에서는 Mock 테스트를 수행했습니다. 어떤 차이가 있나요?

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +        targetOption.subtract(subtractQuantity);
다른 개발자가 56번과 같은 검증 과정을 누락하고 subtract를 호출하면 어떻게 될까요?  
해당 코드는 subtract 코드가 수행될 때 반드시 사전에 수행되어야 하는데 subtract가 해당 로직을 직접 수행하는 방식은 어떨까요?  
https://www.baeldung.com/java-anemic-vs-rich-domain-objects

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +        if (targetOption.getQuantity() < subtractQuantity) {
getter를 쓰고 있네요!  
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +            if (option.getId().equals(targetOptionId)) {
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +                .anyMatch(option -> option.getName().equals(newOptionName));
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-21 16:10 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +        Option option = optionService.convertToOption(optionRequest);
Option이 product를 갖고있는데, option.setProduct(...)를 해주지 않아도 될까요?  
https://skatpdnjs.tistory.com/49

2024-07-22 02:00 UTC, zzoe2346 commented on src/main/java/gift/entity/Option.java
> +    @ManyToOne(fetch = FetchType.LAZY)
네 외래키 표시를 해주는게 좀 더 친절한? 코드가 되는것 같습니다. 적어주도록하겠습니다!

2024-07-22 02:06 UTC, zzoe2346 commented on src/main/java/gift/service/ProductService.java
> +    public List<String> getOptionNames(Long productId) {
수정하겠습니다

2024-07-22 02:06 UTC, zzoe2346 commented on src/main/java/gift/service/ProductService.java
> +    public List<String> updateOptionNames(Long productId, Long optionId, String changedName) {
수정해보겠습니다! 감사합니다.

2024-07-22 03:02 UTC, zzoe2346 commented on src/main/java/gift/service/ProductService.java
> +        productRepository.flush();
이유: 해당 메서드가 새로 생성된 옵션 id를 반환하도록 설계하였는데 productRepository.flush();로 강제 커밋을 하지 않느면 null값이 옵션 id로 반환되어 저렇게 만들었었습니다.

해결: -----------ing

2024-07-22 03:21 UTC, zzoe2346 commented on src/main/java/gift/service/ProductService.java
> +        optionService.checkDuplicateOptionName(product.getOptions(), optionRequest.name());
넵 말씀대로 개선해보았습니다. Entity 와 DTO의 차이를 정확히 몰랐었는데 이번 기회로 좀더 객체 지향에대한 이해가 높아진거 같습니다. 감사합니다.

2024-07-22 03:22 UTC, zzoe2346 commented on src/test/java/gift/concurrency/OptionQuantityTest.java
> +public class OptionQuantityTest {
넵 감사합니다. 적용 시도 해보겠습니다.

2024-07-22 03:23 UTC, zzoe2346 commented on src/test/java/gift/concurrency/OptionQuantityTest.java
> +    OptionService optionService;
넵. 신경써보려하는데 왜이렇게 눈에 안띄는지 모르겠습니다 ㅜ. 개선하겠습니다.

2024-07-22 04:10 UTC, zzoe2346 commented on src/main/java/gift/service/OptionService.java
> +    public List<Option> convertToOptions(List<OptionRequest> options) {
다른 서비스 코드랑 통일을 시켜보았습니다. 굳이 메서드화 하지않고 그대로 코드를 사용해도 괜찮은거 같습니다.

2024-07-22 04:24 UTC, zzoe2346 commented on src/main/java/gift/service/OptionService.java
> +                .map(optionRequest -> new Option(optionRequest.name(), optionRequest.quantity()))
뭔가 착각이 있었던 코드들 같습니다. 주말동안 동시성에대해 테스트해본다고 신경을 써서 다른 코드의 퀄리트는 크게 신경 못쓴것같습니다. 다음 리뷰에서는 꼼꼼히 코드 검사 해보겠습니다!

2024-07-22 04:31 UTC, zzoe2346 commented on src/main/java/gift/service/OptionService.java
> +        targetOption.subtract(subtractQuantity);
아 제가 엔티티와 DTO에대한 차이에대해 무지했던거 같습니다. 좋은 자료 감사합니다!

2024-07-22 04:31 UTC, zzoe2346 commented on src/main/java/gift/service/OptionService.java
> +        if (targetOption.getQuantity() < subtractQuantity) {
넵 수정하겠습니다.

2024-07-22 04:32 UTC, zzoe2346 commented on src/main/java/gift/service/OptionService.java
> +            if (option.getId().equals(targetOptionId)) {
수정 하겠습니다

2024-07-22 04:32 UTC, zzoe2346 commented on src/main/java/gift/service/OptionService.java
> +                .anyMatch(option -> option.getName().equals(newOptionName));
네 고치겠습니다

2024-07-22 04:34 UTC, zzoe2346 commented on src/main/java/gift/service/ProductService.java
> +        Option option = optionService.convertToOption(optionRequest);
set 하도록 수정하였습니다.

2024-07-22 05:50 UTC, zzoe2346 commented on src/main/java/gift/service/ProductService.java
> +        Option option = optionService.convertToOption(optionRequest);
set해줘야합니다! 수정하겠습니ㅏㄷ.

2024-07-22 06:21 UTC, zzoe2346 commented on src/test/java/gift/concurrency/OptionQuantityTest.java
> +@SpringBootTest
Mockito와 DataJpaTest 조합등으로 빈을 최소로 해보고 싶었는데 계속 실패하는 바람에 SpringBootTest를 사용하였습니다. 멘토님 리뷰 후에 또 다시 시도를 해보았지만 어떻게하는줄 모르겠어서 SpringBootTest를 유지하는 중입니다. 

이 동시성 테스트는 서비스와 레포지토리의 조합이 필요해서 한 계층만 테스트 하는 Mock과는 다른 조건을 사용해보았습니다.

2024-07-22 06:37 UTC, zzoe2346 commented
DTO와 Entity를 제대로 몰랐었던것 같습니다. 멘토님 덕분에 그걸 알게되어 고쳐보았습니다.

 테스트의 e2e 패키지에 테스트를 해보았습니다. 저번 리뷰요청때 이상한 패키지명을 했어서 혹시 못보신건가 하여 말씀드려봅니다.

2024-07-22 16:25 UTC, sang5c approved these changes
머지합니다~!  
5주차 시작 전에 리뷰 마지막으로 점검해주세요 :)

2024-07-22 16:25 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +        Option savedOption = optionService.saveOption(product, optionRequest);
변경 감지의 핵심은 트랜잭션입니다. 기존에 사용하던 방식에서 트랜잭션을 추가하면 flush를 하지 않아도 됩니다.

2024-07-22 16:25 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +        productRepository.flush();
변경 감지를 활용하기 위해선 트랜잭션을 설정해줘야 합니다. 현재 `@Transactional` annotation은 어떤 기준으로 메서드별로 다르게 달려있나요?

2024-07-22 16:25 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +        product.addOption(savedOption);
> 이 리뷰를 적용하기 위해선 optionService.saveOption()이 동일 트랜잭션 내에서 수행되어야 합니다.

addOption 내부에서 checkDuplicateOptionName을 수행하면 필수로 수행해야 하는 validation 누락을 막을 수 있습니다.

2024-07-22 16:25 UTC, sang5c commented on src/test/java/gift/concurrency/OptionQuantityTest.java
> +@SpringBootTest
`@SpringBootTest`를 사용하지 말아야 한다는 리뷰가 아닙니다.  

슬랙에서 이야기 했던 부분을 점검하기 위함입니다.
- 내가 하고자 하는 테스트가 무엇인지
- 그 테스트를 통해 무엇을 얻고자 하는지
- 실제로 달성이 되는지

차이를 알고 있는지, 어떤 이유로 mock test를 수행하고있는지 다시 돌아보시면 좋겠네요.  
mock test는 어떤 이점이 있나요? 꼭 해야하나요?  
mock test가 통합 테스트보다 낫나요?

2024-07-22 16:25 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +                .anyMatch(option -> option.getName().equals(newOptionName));
반영되지 않았네요~

2024-07-22 16:25 UTC, sang5c commented on src/main/java/gift/entity/Product.java
> +    public List<Option> getOptions() {
생성자처럼 연관관계 편의 메서드를 작성해볼 수 있을 것 같아요.

2024-07-22 16:25 UTC, merged

2024-07-22 16:41 UTC, zzoe2346 commented on src/main/java/gift/service/OptionService.java
> +                .anyMatch(option -> option.getName().equals(newOptionName));
아! 다시 수정해보겠습니다

2024-07-22 17:15 UTC, zzoe2346 commented on src/main/java/gift/service/ProductService.java
> +        product.addOption(savedOption);
아 그런방법이! 적용해보겠습니다

2024-07-23 02:50 UTC, zzoe2346 commented on src/main/java/gift/service/ProductService.java
> +        Option savedOption = optionService.saveOption(product, optionRequest);
넵 멘토님. 트랜잭션 자세히 공부해보겠습니다!

2024-07-23 02:54 UTC, zzoe2346 commented on src/main/java/gift/entity/Product.java
> +    public List<Option> getOptions() {
적용하여 보겠습니다

2024-07-23 03:02 UTC, zzoe2346 commented on src/main/java/gift/service/ProductService.java
> +        productRepository.flush();
이 커밋당시의 코드에서 

`return new AddedOptionIdResponse(option.getId());` 을 리턴하였는데 `@Transactional`을 사용하여도 option.getId()에서 null이 반환 되었었습니다. 알아보니 아직 엔티티 매니저에 새로 만든 option이 등록이 안되어 변경감지가 안되어서 그랬던것 같습니다. 현재 `@Transactional`이 메서드의 원자성을 보장한다는것 정도의 지식만 있는데 이번주에 더 공부해 보겠습니다. 

감사합니다!

2024-07-23 03:09 UTC, zzoe2346 commented on src/test/java/gift/concurrency/OptionQuantityTest.java
> +@SpringBootTest
넵 멘토님. 슬랙에 올려주신 자료도 꼼꼼히 다시 봐보고 테스트에 관해 돌아보고 생각해보겠습니다!

2024-07-23 03:20 UTC, zzoe2346 commented on src/main/java/gift/service/ProductService.java
> +        Option savedOption = optionService.saveOption(product, optionRequest);
아! 멘토님 제가 마지막에 `return new AddedOptionIdResponse(savedOption.getId());` 에서 `savedOption.getId()`를 하고자하는데 메서드가 마칠때 커밋이 되어서 반환 시점에서는 아직 option의 ID가 null값이였습니다. 

옵션을 상품에 추가 요청시, 반환을 새로 생성된 옵션의 ID로 하기를 원하여 먼저 옵션을 save하는 로직으로 변경해보았습니다.