전남대 BE_김보민_4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #195
Opened 2024-07-17 15:20 UTC by KBM05haruin30

# 1단계
### 코드 작성하면서 어려웠던 점
Category를 삭제할 때 해당 카테고리를 가지고 있는 상품이 위시 리스트에 들어가 있는 경우 에러가 발생했습니다. 고민하다가 나온 방법은 위시 리스트부터 지우기 였습니다. 위시 리스트에서 상품 삭제 -> 상품 목록에서 삭제 -> 카테고리 삭제 순으로 실행하게 만들었습니다.
html에서 카테고리를 드롭아웃 형태로 나타내고 싶어 팀원의 도움을 받았습니다.

### 중점적으로 봐주셨으면 하는 점
테스트 코드 잘 작성했는지 봐주셨으면 합니다.
Product와 Category 간의 연관 매핑이 잘 되었는지 봐주셨으면 합니다. 3주차 과제처럼 카테고리가 존재하기 위해서는 Product가 존재할 필요는 없지만 Product가 존재하기 위해서는 카테고리가 존재해야 한다고 생각하고 코드를 작성했습니다.

### 궁금한 점
schema.sql에서 category 테이블이 product보다 밑에 있었더니 에러가 발생했었습니다. 여기에 작성된 테이블은 순서대로 만들어지는지 궁금합니다.
Wishlist에서는 Product, Member에 대한 검증, Product에서는 Category에 대한 검증을 작성하지 않았었습니다. 제 생각에는 Product, Member, Category는 각자 따로 검증 메서드가 있어서 할 필요가 없다 생각하는데 작성할 필요가 있는지 궁금합니다

2024-07-17 16:26 UTC, KBM05haruin30 commented
멘토님, 과제 관련은 아니지만 깃 관련으로 궁금한 점이 있습니다. 제가 step1을 작성한 후에 pr을 만들고 그 이후에 멘토님께서 step0를 머지해주셨는데, 그럼 충돌이 발생했다고 하여 파일을 수정하라고 뜹니다. 이 때 충돌이 난 파일들을 제가 작성한 코드로 덮어쓰면 'merge'로 초록색 버튼이 떠 이걸 눌러주었습니다. 이렇게 해도 상관이 없는 건지 아니면 step1 브랜치를 지우고 
[https://github.com/next-step/nextstep-docs/blob/master/codereview/review-step3.md](url) 을 따라 step1 브랜치를 다시 작성해주어야 하는지 궁금합니다.

2024-07-18 05:21 UTC, KBM05haruin30 commented
git rebase를 통해 step0에 대한 커밋을 지울 수 있다는 것을 찾았습니다! 또 인텔리제이에서 손 쉽게 rebase가 가능하다는 것을 찾았습니다.

2024-07-18 05:55 UTC, KBM05haruin30 commented
rebase를 통해 step1 브랜치에서 step0 커밋을 지웠습니다. 하지만 pr에서는 step0에 대한 커밋이 남아있습니다. pr을 남기기 전에 커밋을 지워야 안보이는 건지 아니면 제가 지웠다고 생각했지만 안지워진건지 궁금합니다..

2024-07-20 06:29 UTC, Hongdonggeon requested changes
안녕하세요 보민님
미션 구현하느라 수고많으셨습니다!
전체적으로 확인해보니, api를 restful하게 설계하는걸 학습해보면 좋을 것 같아요
또한 테스트코드가 현재 repository 레벨만 작성되어 있는 것 같은데, service와 controller 까지 모두 테스트 코드 작성해줘야 할 것 같아요!
수고하셨습니다

2024-07-20 06:29 UTC, Hongdonggeon commented on src/main/java/gift/controller/CategoryController.java
> +    public String listCategories(Model model) {
list라는 표현보다는 get이나 find와 같은 표현이 좋을 것 같아요

2024-07-20 06:29 UTC, Hongdonggeon commented on src/main/java/gift/service/CategoryService.java
> +                wishlistRepository.deleteByProduct(product);
for문안에 delete 쿼리보다 deleteAll 같은 메서드를 이용하는게 좋을 것 같아요

2024-07-20 06:29 UTC, Hongdonggeon commented on src/main/java/gift/service/CategoryService.java
> +        categoryRepository.save(toEntity(categoryDTO, id));
업데이트 로직이라고 하기에 새로운 엔티티를 만들어서 저장하네요? 기존 엔티티가 변경되는게 맞나요?

2024-07-20 06:29 UTC, Hongdonggeon commented on src/main/java/gift/model/Category.java
> +        if (name.trim().isEmpty()) {
위 조건과 합쳐도 될 것 같아요

2024-07-20 06:29 UTC, Hongdonggeon commented on src/main/java/gift/controller/CategoryController.java
> +    @DeleteMapping("/delete/{id}")
api path에 delete라는 표현이 필요 없을 것 같아요
http method만으로도 충분해요

2024-07-20 06:29 UTC, Hongdonggeon commented on src/main/java/gift/controller/CategoryController.java
> +    @PutMapping("/edit/{id}")
edit라는 표현이 path 에서 제외되도 될 것 같아요

2024-07-20 06:29 UTC, Hongdonggeon commented on src/main/java/gift/controller/CategoryController.java
> +    @PostMapping("/add")
rest api에 대해서 공부해보면 좋을 것 같아요
동사 (행위)를 api path에서 제외시키는게 좋습니다

2024-07-20 08:29 UTC, KBM05haruin30 commented on src/main/java/gift/model/Category.java
> +        if (name.trim().isEmpty()) {
넵 알겠습니다! Category뿐만 아니라 Member, Product도 null과 trim().isEmpty() 조건은 합치도록 하겠습니다.

2024-07-20 08:34 UTC, KBM05haruin30 commented on src/main/java/gift/controller/CategoryController.java
> +    public String listCategories(Model model) {
넵 알겠습니다! AdminController를 보면서 만들다 보니 CategoryController도 list라고 작성했었습니다. 확실히 list라는 표현보다는 get이 의미가 더 잘 전달되는 것 같습니다. CategoryController와 AdminController에서 이름을 수정하도록 하겠습니다!

2024-07-20 08:48 UTC, KBM05haruin30 commented on src/main/java/gift/service/CategoryService.java
> +                wishlistRepository.deleteByProduct(product);
넵 알겠습니다. 관련해서 검색하니 In절을 통해 리스트 안에 있는 값을 지울 수 있는 것 같습니다! 그래서 deleteByProductIn 메서드를 wishlistRepository에 새로 만들었습니다.

2024-07-20 08:58 UTC, KBM05haruin30 commented on src/main/java/gift/service/CategoryService.java
> +        categoryRepository.save(toEntity(categoryDTO, id));
최대한 setter를 사용하지 않으려고 하다 보니 새로운 엔티티를 만들어서 저장하게 했었습니다. 업데이트 로직에서 기존 엔티티가 변경되는 것이 맞으므로 setter를 사용해서 수정하도록 하겠습니다!

2024-07-20 13:45 UTC, KBM05haruin30 commented
### 테스트 코드 작성
Service 계층 테스트 코드 작성을 했습니다. 강의 때 알려준 mock을 사용하고 싶었지만 아직 잘 모르겠어서 공부를 한 후 mock을 사용해서 테스트 코드를 수정하려고 합니다. 추가로 Controlleer 계층도 mock을 사용해야 할 것 같아 아직 작성하지는 않았습니다. 

### rest api에 대한 공부
RESTful API 디자인 가이드 중 URI에 HTTP Method가 들어가면 안되고 행위에 대한 동사 표현이 들어가면 안된다고 나와 있습니다. 전에 찾아 보았을 때 이런 부분은 찾아 보지 못했던 것 같습니다. 그리고 자원에 대한 행위는 HTTP Method로 표현하고 path에 적었던 내용을 빼면 더 RESTful 하게 설계 가능하다는 것을 배웠습니다!

2024-07-21 04:38 UTC, Hongdonggeon commented on src/main/java/gift/service/CategoryService.java
> +        categoryRepository.save(toEntity(categoryDTO, id));
setter를 만들지 않고 엔티티에 필드를 변경해주는 update 메서드를 만드는게 좋다고 생각해요
setter는 지양하는게 좋습니다!

2024-07-21 04:39 UTC, Hongdonggeon approved these changes
안녕하세요 보민님
미션 구현하느라 수고 많으셨습니다!
setter 생성한거에 대해서 코멘트 드렸어요
이 부분만 추가 수정하면 될 것 같아요
1단계 머지할게요!

2024-07-21 04:39 UTC, merged

2024-07-21 04:42 UTC, KBM05haruin30 commented on src/main/java/gift/service/CategoryService.java
> +        categoryRepository.save(toEntity(categoryDTO, id));
넵 알겠습니다!