경북대 BE_이도훈_4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #197
Opened 2024-07-17 17:06 UTC by 2iedo

2단계 과제 제출합니다!

2024-07-19 14:36 UTC, khj68 requested changes
도훈님 고생하셨습니다 :)
피드백 확인 부탁드립니다!

2024-07-19 14:36 UTC, khj68 commented on src/main/java/gift/Service/OptionService.java
> +        }
이전 핸들러 메소드명처럼 OptionDuplicatedException 을 명시하는게 좋지 않을까요?
option 관련해서도 여러 상황에 대한 에러가 나올 수 있어서,
에러 클래스에도 유즈케이스를 명시해주는 것이 좋을 것 같다는 의견 드립니다.
OptionException을 공통적으로 사용하시려는 것일까요?

2024-07-19 14:36 UTC, khj68 commented on src/main/java/gift/Service/OptionService.java
> +        }
비슷하게 같은 exception이 아니라 존재하지 않는 것에 대한 것임을 명시해주는 게 좋아보여요 :)

2024-07-19 14:36 UTC, khj68 commented on src/main/java/gift/Service/OptionService.java
> +        }
위와 같은 의견입니다 :)

2024-07-19 14:36 UTC, khj68 commented on src/main/java/gift/Service/ProductService.java
>              throw new AuthorizedException();
이런 조건문은 엔티티 내의 메소드로 변경하면 좀 더 도메인 지향적으로 코드를 작성하실 수 있습니다 :)

2024-07-19 14:36 UTC, khj68 commented on src/main/java/gift/Service/WishService.java
> +        }
repository에서 하나씩 조회하게 되면 쿼리의 횟수가 많아집니다.
이런 경우에는 list로 한번의 쿼리로 추출해오는 것을 추천드립니다 :)

2024-07-20 05:31 UTC, 2iedo commented on src/main/java/gift/Service/WishService.java
> +        }
productRepository로 한 번 더 찾는 대신 wishEntities에서 바로 getProduct() 메소드로 가져오게 수정했습니다!

2024-07-20 05:42 UTC, 2iedo commented on src/main/java/gift/Service/OptionService.java
> +        }
수정 완료했습니다!

2024-07-20 05:44 UTC, 2iedo commented on src/main/java/gift/Service/OptionService.java
> +        }
OptionDuplicatedException(409), OptionNotFoundException(404) 두 개의 예외 처리로 수정했습니다!

2024-07-20 05:44 UTC, 2iedo commented on src/main/java/gift/Service/OptionService.java
> +        }
IllegalArgumentException으로 변경했습니다!

2024-07-20 05:56 UTC, 2iedo commented on src/main/java/gift/Service/ProductService.java
>              throw new AuthorizedException();
수정 완료했습니다!

2024-07-20 13:45 UTC, khj68 approved these changes
피드백 반영 확인하였습니다.
도훈님 고생 많으셨습니다 :)

2024-07-20 13:45 UTC, merged