경북대 BE_배규민 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #210
Opened 2024-07-18 05:57 UTC by GyuminBae

* 4주차 2단계 과제입니다!

2024-07-18 13:35 UTC, lsm7179 commented
> * 4주차 2단계 과제입니다!
> * product와 option 간 연관관계 매핑에 대해서 고민을 해보게 되었습니다.
>   option이 N:1 관계로 product 와 매핑될 수는 있지만,  option을 통해  product를 참조하는 일이 없고,
>   product를 참조할 때 그와 관련된 모든 option을 한꺼번에 불러올 일이 잘 없을 것 같아서
>   느슨하게 연결하는게 더 효율적이라고 생각하여 묶지 않았습니다!

좋은 고민을 하셨네요!
ORM를 쓰면서 연관관계 매핑에 대해 고려하는건 개발자의 숙명인거 같아요.
나름 합리적인 기준으로 맵핑을 고려해주셨군요.👍

2024-07-18 13:56 UTC, lsm7179 reviewed
규민님 과제 수고하셨습니다.
appove 하기 살짝 아쉬워서 request changes 보냅니다.
간단한 내용이니 반영하고 다시 리뷰요청해주세요.

2024-07-18 13:56 UTC, lsm7179 commented on src/main/java/gift/core/domain/product/ProductCategory.java
> +    }
정적 팩토리 메서드👍

2024-07-18 13:56 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/entity/ProductOptionEntity.java
> +    }
정적 팩토리 메소드는 생성자 밑에 두는게 어떤가요?

2024-07-18 13:56 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/entity/ProductOptionEntity.java
> +    }
protect생성자를 사용해보는건 어떤가요?
다른 엔티티클래스도 마찬가지 입니다.
객체지향적인 코드의 핵심은 사용하는 곳에서 무분별한 사용을 막는 것입니다.

2024-07-18 13:56 UTC, lsm7179 commented on src/main/java/gift/product/service/ProductOptionServiceImpl.java
> +public class ProductOptionServiceImpl implements ProductOptionService {
cud에 `@Transactional`을 붙여주세요.

2024-07-18 13:56 UTC, lsm7179 commented on src/main/java/gift/product/service/ProductOptionServiceImpl.java
> +    }
생성 전에 검증로직이 많이 있네요. test코드를 작성해보세요😁

2024-07-18 13:59 UTC, lsm7179 requested changes
규민님 과제 수고하셨습니다.👍
appove 하고 넘어가기 살짝 아쉬워서 간단한 피드백 남겼습니다.
간단한 내용이니 반영하고 다시 리뷰요청해주세요.🤗

2024-07-18 14:01 UTC, BGMSound commented on src/main/java/gift/product/service/ProductOptionServiceImpl.java
> +public class ProductOptionServiceImpl implements ProductOptionService {
반영했습니다!

2024-07-18 14:01 UTC, BGMSound commented on src/main/java/gift/product/infrastructure/persistence/entity/ProductOptionEntity.java
> +    }
반영했습니다!

2024-07-18 14:30 UTC, BGMSound commented on src/main/java/gift/product/service/ProductOptionServiceImpl.java
> +    }
조건에 대한 테스트케이스 모두 반영했습니다!

2024-07-18 14:32 UTC, BGMSound commented on src/main/java/gift/product/infrastructure/persistence/entity/ProductOptionEntity.java
> +    }
반영했습니다! 팩토리 메서드를 통해 도메인 객체를 통해서만 생성할 수 있도록 변경했습니다

2024-07-18 14:38 UTC, BGMSound commented on src/main/java/gift/product/infrastructure/persistence/entity/ProductOptionEntity.java
> +    }
궁금했던 점이 제가 코틀린을 최근에 많이 다뤄보고 있는데 코틀린같은 경우는 자바의 static과 유사한
companion object 코드를 일반적으로 맨 아래 위치하다보니 다음과 같이 클래스 레이아웃을 구성했던 것 같습니다..!
자바에서는 일반적으로 생성자 밑에 정적 팩터리 메서드를 위치시키는 편인지 궁금합니다!

2024-07-19 08:24 UTC, lsm7179 commented on src/main/java/gift/product/infrastructure/persistence/entity/ProductOptionEntity.java
> +    }
잘못말씀드렸네요. 
java라이브러리를 참고해서 보면 좋은데요. 관례상 정적 팩토리 메소드를 생성자보다 위에 두고 있습니다.
https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/java/time/LocalDate.java

2024-07-19 08:33 UTC, lsm7179 commented on src/test/java/gift/product/ProductOptionRepositoryTests.java
> +public class ProductOptionRepositoryTests {
이건 service 테스트인거같네요.
클래스명수정이 필요해보여요~

2024-07-19 08:35 UTC, lsm7179 approved these changes
규민님 과제 수고하셨습니다.👍
머지하겠습니다.
다음 단계도 화이팅입니다.

2024-07-19 08:35 UTC, merged