경북대 BE_김민주 4주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #212
Opened 2024-07-18 06:23 UTC by minju26

**1단계 - 상품 카테고리** 과제 제출합니다.

이전 코드 리팩토링까지 반영해서 pr 하려고 했으나, 시간이 생각보다 오래 걸려서 일단 과제 수행 내용만 담았습니다!

2024-07-18 14:34 UTC, gongdongho12 requested changes
민주님 안녕하세요
4주차 1단계 작성하시느라 고생 많으셨습니다

이전 코멘트에 남겨드린 내용이 전부 누락되어있는 상황인데요 🤔 

시간에 쫒겨서 진행하기 보다는 한번 정리하는 시간을 가지고 PR 올려주시는게 좋을 것 같습니다
코멘트 확인해서 적용 부탁드려요!

2024-07-18 14:34 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +            productToUpdate.setCategory(category);
업데이트 하고싶은 대상만 업데이트 하는데, 이런 구조면 항상 기존 초기값을 가지고 있을 거자나요
request의 값이랑 현재 객체랑 값이 같으면 set을 안해줘도 되지 않을까요? null 이 아닐때만 체크할게 아니라요

2024-07-18 14:34 UTC, gongdongho12 commented on README.md
> +  - 관리자 화면에서 상품을 추가할 때 카테고리를 지정할 수 있다.
카테고리를 추가하고 수정할 수 있는 기능은 빠진 것 같아요!

2024-07-18 14:34 UTC, gongdongho12 commented on src/main/java/gift/controller/WishListController.java
addWishProduct나 deleteWishProduct 메서드의 결과는 API형태인데 문자열로 전달하면 어떤곳은 json 어떤곳은 string 형식인데 컨벤션을 위해 통일해주는게 좋지 않을까요?

2024-07-18 14:34 UTC, gongdongho12 commented on src/main/java/gift/controller/WishListController.java
> +        Page<WishProductResponse> wishes = wishListService.getWishList(member.getId(), page);
이전에도 말씀드렸던 부분인데 SpringBoot에서 제공하는 PageRequest를 활용해서 단순 페이지 번호가 아니라 갯수나 소팅 등을 조절가능하게 하는게 좋지 않을까요?

2024-07-19 03:48 UTC, minju26 commented on src/main/java/gift/service/ProductService.java
> +            productToUpdate.setCategory(category);
항상 기존 초기 값이 들어 있는데
변경 하고자 하는 값만 내용이 들어있고 다른 필드는 null일거라고 생각해서 구현해버렸네요 🥲
id가 같다면 save 했을 때 변경된 정보만 update 된다는 것을 이용해서 수정해보았습니다!

2024-07-19 03:50 UTC, minju26 commented on README.md
> +  - 관리자 화면에서 상품을 추가할 때 카테고리를 지정할 수 있다.
전체 카테고리 조회만 별도의 `CategoryController`에 api가 있고,
카테고리도 상품 정보의 일부라고 생각해서, 추가와 수정은 상품추가와 상품수정에 포함되어 있습니다!

2024-07-19 03:53 UTC, minju26 commented on src/main/java/gift/controller/WishListController.java
안그래도 response 구조를 통일하고 싶었습니다!
그런데, response에 다른 데이터 없이 메세지만 전달하는 경우에도 dto(`MessageResponse` 같은..)를 따로 만들어서 전달하는게 좋을까요?

2024-07-19 03:54 UTC, minju26 commented on src/main/java/gift/controller/WishListController.java
> +        Page<WishProductResponse> wishes = wishListService.getWishList(member.getId(), page);
넵! 전에 언급해주신 내용과 글을 보고 Pageable 적용해보았습니다! 훨씬 컨트롤도 쉽고 깔끔해진 것 같습니다

2024-07-19 16:39 UTC, gongdongho12 commented on src/main/java/gift/controller/WishListController.java
MessageResponse 를 최소 2곳 이상 쓰게 되는건데 만들어도 괜찮을 것 같아요!
만약 한곳이나 임시로 쓰는 경우엔 Map<String, String> 또한 jackson 시리얼라이저가 json으로 잘 변환해주니 이부분도 참고해주시면 좋을 것 같아요

2024-07-19 16:40 UTC, gongdongho12 approved these changes
1단계 작업하시느라 고생많으셨습니다 💯

2024-07-19 16:40 UTC, merged