경북대 BE_우현서 4주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #214
Opened 2024-07-18 06:45 UTC by wndlthsk

1단계 제출합니다!

2024-07-18 13:38 UTC, leaf-upper requested changes
안녕하세요 현서님 1단계 고생많으셨습니다~!
요구사항 기능구현은 너무나 잘해주신것 같아요~
다만 아직 자바 컨벤션이 약간 아쉬운것 같아서 관련해서 코멘트를 드렸습니다.
수정해주시면 바로 어프로브 드릴게요~
고생하셨습니다 👍

2024-07-18 13:38 UTC, leaf-upper commented on src/main/java/gift/config/WebConfig.java
> +            .excludePathPatterns("/login", "/register","/admin/products", "/admin/products/**", "/members", "/members/*", "/api/**");
여기 코멘트는 아니지만 WebConfig에 있는 멤버변수들도 final 키워드를 붙일수있을것 같아요

2024-07-18 13:38 UTC, leaf-upper commented on src/main/java/gift/config/WebConfig.java
> +            .excludePathPatterns("/login", "/register","/admin/products", "/admin/products/**", "/members", "/members/*", "/api/**");
/api 패스로는 인증이 필요없을까요?

2024-07-18 13:38 UTC, leaf-upper commented on src/main/java/gift/controller/CategoryController.java
> +    public ResponseEntity<List<CategoryDto>> getAllCategories(){
요구사항에는 카테고리를 상품에 설정할수만있고, 카테고리 자체를 추가하거나 수정하거나 삭제하는 요구사항은 없지만 
개발해주셔도 좋을것 같아요. 현재는 데이터베이스에 직접 데이터를 넣어야겠네요.

2024-07-18 13:38 UTC, leaf-upper commented on src/main/java/gift/domain/Category.java
> +    public Category() {
요건 접근제어자를 좀더 제한적으로 둘수있을것 같아요! protected로 변경해주시면 좋을것 같습니다.

2024-07-18 13:38 UTC, leaf-upper commented on src/main/java/gift/domain/Product.java
> +    public void setCategory(Category category) {
카테고리를 변경하는 기능이겠죠? set은 자바에서 관례적으로 쓰일때가 있어서 좀더 명시적으로 updateCategory 같은 네이밍은 어떠실까요?

2024-07-18 13:38 UTC, leaf-upper commented on src/main/java/gift/dto/CategoryDto.java
> +    public CategoryDto() {
이 생성자는 꼭 필요할까요?

2024-07-18 13:38 UTC, leaf-upper commented on src/main/java/gift/dto/CategoryDto.java
> +public class CategoryDto {
이런건 record로도 사용해볼수있을것 같아요. 이건 취향이라서 편한방식으로 부탁드립니다.!

2024-07-18 13:38 UTC, leaf-upper commented on src/main/java/gift/dto/CategoryDto.java
> +public class CategoryDto {
필드들에 전부 final 붙일 수 있을까요?

2024-07-18 13:38 UTC, leaf-upper commented on src/main/java/gift/dto/ProductRegisterRequestDto.java
> +        this.categoryName = categoryName;
카테고리 이름으로 기능을 작성하는게 아닌, ID를 기반으로 기능을 작성해주시면 좋을것 같아요.
ID를 기반으로 카테고리 조회 -> 카테고리 이름 확인 하는식으로 가면 어떨까요?

2024-07-18 13:38 UTC, leaf-upper commented on src/main/java/gift/service/CategoryService.java
> +    private CategoryDto convertToDto(Category category) {
이 로직은 CategoryDto 내부로 이동해볼수 있을것 같아요.

2024-07-18 13:38 UTC, leaf-upper commented on src/main/resources/schema.sql
> -                         name VARCHAR(15) NOT NULL,
이 스키마 파일은 삭제하신 이유가 있을까요?

2024-07-19 02:42 UTC, wndlthsk commented on src/main/java/gift/config/WebConfig.java
> +            .excludePathPatterns("/login", "/register","/admin/products", "/admin/products/**", "/members", "/members/*", "/api/**");
현재는 /api 패스 아래에 categories만 있어서 jwtInterceptor가 적용되지 않아도 된다고 생각하였습니다.!

2024-07-19 02:45 UTC, wndlthsk commented on src/main/java/gift/dto/CategoryDto.java
> +public class CategoryDto {
final 추가하였는데 카테고리 추가, 수정하면서 다시 지웠습니다.!

2024-07-19 02:47 UTC, wndlthsk commented on src/main/java/gift/dto/ProductRegisterRequestDto.java
> +        this.categoryName = categoryName;
말씀 주신 대로 수정하려고 하였는데, 사용자에게 카테고리 이름을 선택 받고 선택한 이름을 보여주는 거라 수정하기가 까다로웠습니다. name도 유니크한데 name으로 입력받고 카테고리 조회하는 것에 문제가 있을까요?

2024-07-19 02:51 UTC, wndlthsk commented on src/main/resources/schema.sql
> -                         name VARCHAR(15) NOT NULL,
jpa가 자동으로 생성하는 것으로 충분하다고 생각하였습니다! 또 필드 값이 추가되면 따로 확인을 했었는데, jpa로만 생성되게 하면 그러지 않아도 될 것 같아 삭제하였습니다. 
질문 주신 이유가 스키마 파일이 있는 게 더 나아서 이실까요? 그렇다면 이유도 궁금합니다!

2024-07-19 08:56 UTC, wndlthsk commented
### 과제 제출을 위해 아래에 step2도 추가하였습니다!

2024-07-19 14:54 UTC, leaf-upper commented on src/main/java/gift/dto/ProductRegisterRequestDto.java
> +        this.categoryName = categoryName;
명확하게 설명드리기가 쉽지 않지만 최대한 노력해볼게요~

1. name은 유니크하지만 name을 기반으로 데이터를 조회했을때 같은 데이터베이스 레코드가 나올것을 보장할 수 있을까요?
예시 케이스를 하나 들자면.

1. 카테고리 생성(name=교환권, id=1)
2. 상품 매핑(categoryId=1)
3. 교환권 카테고리 제거
4. 교환권 카테고리 재생성(categoryId=2, name=교환권)

같은 교환권이라는 이름을 가졌지만, category에 대한 레코드는 서로 달라질수있어요.
다만, 외래키 제약조건이 걸려있다면 위 같은 상황이 발생하지 않을수도있어요.
하지만 외래키 제약조건은 데이터베이스 성능에 영향을 미쳐서 최대한 사용을 지양하는 편이기도해요.

2. ID는 데이터를 유일하게 식별하는 단위이고, 특별한 경우가 아닌이상 name이 유니크하더라도 기본적으로 ID를 이용해서 데이터를 식별하고 관련 코드를 작성해주셨으면 해요. 이건 일종의 컨벤션처럼 생각해주셔도 될것 같습니다.

현재는 name으로 입력받고 카테고리를 name기반으로 조회하는것에 대해서 큰 문제는 없기때문에 일단 해당 이슈는 넘어가겠습니다.
고생많으셨어요:) 👍👍

2024-07-19 14:57 UTC, leaf-upper commented on src/main/resources/schema.sql
> -                         name VARCHAR(15) NOT NULL,
JPA는 분명히 좋은 기술이지만, JPA가 자동으로 생성해주는 DDL은 테스트 목적을 제외하고는 생각보다 그렇게 많이 사용되지는 않아요. 이 부분은 명확하게 DDL을 관리해주셨으면 하고, 더 도움이 되실것 같기도하네요

2024-07-19 15:01 UTC, leaf-upper requested changes
안녕하세요 현서님~ 1, 2단계 고생많으셨습니다 👍 
몇가지 코멘트를 드렸는데 확인 부탁드려요~

2024-07-19 15:01 UTC, leaf-upper commented on src/main/java/gift/domain/Product.java
> +    private List<Option> options = new ArrayList<>();
Product와 Option은 생명주기가 같으니,
CascadeType과 orpanRemoval등의 옵션을 한번 공부해보시고 사용해보는건 어떨까요?

2024-07-19 15:01 UTC, leaf-upper commented on src/main/java/gift/domain/Product.java
> +    public Product() {
엔티티에 대한 기본 생성자는 외부에서 생성이 불가능하도록 작성해주시면 좋을것 같아요

2024-07-19 15:01 UTC, leaf-upper commented on src/main/java/gift/domain/Product.java
> +    private List<Option> options = new ArrayList<>();
1:N 관계는 LAZY하게 데이터를 조회할때 성능에 이슈가 있을수 있어요~
`@BatchSize` , Fetch Join등을 알아보시면 좋을것 같아요.

2024-07-19 15:01 UTC, leaf-upper commented on src/main/java/gift/service/OptionService.java
> +public class OptionService {
위에서 말씀드린것처럼 Product와 Option은 생명주기가 같아요~
모든 엔티티에 대해서 Service와 Repository를 작성해야하는건 아닐것 같아요!
옵션에 관련된 비즈니스 로직은 ProductService로 이관해서 작성해보는건 어떨까요?

2024-07-19 15:01 UTC, leaf-upper commented on src/main/java/gift/repository/OptionRepository.java
> +public interface OptionRepository extends JpaRepository<Option, Long> {
OptionRepository가 없어도 엔티티의 매핑관계를 잘정의한다면, ProductRepository를 통해서 Option에 대한 비즈니스 로직 작성이 가능할것 같아요~

2024-07-20 12:57 UTC, wndlthsk commented on src/main/java/gift/dto/ProductRegisterRequestDto.java
> +        this.categoryName = categoryName;
추가 설명 감사합니다! 이해하였습니다.
step3까지 완료한 후 한번 더 고민해보고 수정해보겠습니다!

2024-07-21 07:08 UTC, leaf-upper approved these changes
👍 2단계까지 고생많으셨습니다 현서님
리팩토링요청드렸는데 코드를 잘 반영해주신것 같네요~
고생하셨습니다 👍 👍

2024-07-21 07:08 UTC, leaf-upper commented on src/main/java/gift/service/ProductService.java
> +        Product product = productRepository.findById(productId)
관련 로직들은 전부 Product내로 이동시킬수 있지 않을까요?

2024-07-21 07:09 UTC, merged