전남대_BE 박진화 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #219
Opened 2024-07-18 08:19 UTC by Jinhwa-Park

1. 반영사항들 전부 반영했습니다. (만약 빠진 게 있다면 알려주세요!)
2. Category 관련 사항 구현했습니다.
3. PR 전에 merge conflict 해결했습니다.

2024-07-19 18:52 UTC, pkeugine requested changes
안녕하세요 진화님,
미션 진행하시느라 고생하고 계십니다.
짧은 시간동안 정말 많은 걸 학습하시고, 실력 또한 늘어가는게 느껴져요.
그런데 해당 PR 안에서 해결하고 넘어가면 좋을 것 같은 부분들이 있어서
일단 request changes 보냅니다. 코멘트 한 번 확인해주세요.
파이팅입니다!

2024-07-19 18:52 UTC, pkeugine commented on src/main/java/gift/service/CategoryService.java
> +    }
Optional 상태로 controller 까지 보내주지 않고 service 에서 예외를 처리해보면 어떨까요?

2024-07-19 18:52 UTC, pkeugine commented on src/main/java/gift/service/CategoryService.java
> +        Category category = categoryRepository.findById(id).orElseThrow(() -> new RuntimeException("Category not found"));
여기서 `RuntimeException` 을 던지면 `GlobalExceptionHandler` 의 어떤 메서드가 실행될까요?

2024-07-19 18:52 UTC, pkeugine commented on src/main/java/gift/service/ProductService.java
> +    public Optional<Category> getCategoryById(Long id) {return categoryRepository.findById(id);}
category 도 product 관련 클래스가 다루네요!
이 서비스를 사용할 때, 여기서 말하는 id 가 product 의 id 인지, 아니면 category 의 id 인지 헷갈릴 것 같아요. 🤔

2024-07-19 18:52 UTC, pkeugine commented on src/main/java/gift/util/JwtUtil.java
> +    // Extract getEmailFromRequest logic as JwtUtil to reduce redundancy
흠 수상한 주석이네요.
어쩌다 이런 주석을 작성하셨을까요?

2024-07-19 18:52 UTC, pkeugine commented on src/main/resources/static/css/style.css
> ->>>>>>> upstream/jinhwa-park
git conflict 가 잘 해결되지 않았습니다!

2024-07-19 18:52 UTC, pkeugine commented on src/test/oldTestCodes/MemberControllerTest.java
> +//@WebMvcTest(MemberController.class)
테스트를 일단 제외하고 개발을 하시겠다는 말이 기억나는데,
그래도 pr 이라는 하나의 결과물에는 그런 행위가 없으면 좋겠어요.

2024-07-20 04:03 UTC, Jinhwa-Park commented on src/main/java/gift/service/CategoryService.java
> +    }
왜 그러면 안되는 건지 궁금해서 좀 찾아봤습니다!
컨트롤러는 HTTP 요청을 처리하고, 서비스 계층과의 인터페이스 역할을 담당하는데, Optional을 직접 사용하면 컨트롤러에 비즈니스 로직이 포함될 수 있어서 서비스 계층에서 Optional을 처리하고 컨트롤러는 명확하게 결과나 처리된 예외만 받아서 작동하게 하는 것이 좋다는 내용을 읽게 됐습니다.!

따라서 Optional을 컨트롤러까지 보내지 않는 것을 추천해주신 이유가 컨트롤러와 서비스 레이어의 책임 분리를 위해서라고 이해했는데 이런 사유로 추천해주신 사항이 맞나요?

2024-07-20 04:07 UTC, Jinhwa-Park commented on src/main/java/gift/service/CategoryService.java
> +        Category category = categoryRepository.findById(id).orElseThrow(() -> new RuntimeException("Category not found"));
`RuntimeException`을 던지면 `handleException`이 실행되겠네요. `findById`에서 id를 못찾은 경우에 실행되라고  `handleEntityNotFoundException`을 만든건데 작동되지 않을 것 같습니다. `RuntimeException`이 아니라 `EntityNotFoundExecption`으로 변경하는 게 좋을 것 같네요! 감사합니다!

2024-07-20 04:08 UTC, Jinhwa-Park commented on src/main/java/gift/service/ProductService.java
> +    public Optional<Category> getCategoryById(Long id) {return categoryRepository.findById(id);}
`categoryId`나 `productId `같이 좀 더 명확하게 변경하는 작업을 거쳐야 할 것 같네요!

2024-07-20 04:11 UTC, Jinhwa-Park commented on src/main/java/gift/util/JwtUtil.java
> +    // Extract getEmailFromRequest logic as JwtUtil to reduce redundancy
원래 이전 코드에서는 여러 클래스에서 같은 getEmailFromRequest 로직을 쓰고 있었어서 JwtUtil에 이식하는 과정에서 작성한 주석입니다. 영어로 작성되어있어서 요상하다고 생각하실 수도 있을 것 같은데 해당 주석은 제가 단 게 맞습니다! 타이핑하는 과정에서 주석을 한국어로 달고 다시 코드를 영어로 치는 과정을 여러번 반복하는걸 좀 싫어하는 편이라서 에러 메시지 같은 부분도 전부 영어로 다는 편이기 때문에 주석도 영어로 적었습니다!

2024-07-20 04:13 UTC, Jinhwa-Park commented on src/main/resources/static/css/style.css
> ->>>>>>> upstream/jinhwa-park
충돌 표시를 지우는 과정을 한 번 거치고 나서 kakao-tech-campus-2nd-step2::jinhwa-park에서 pull 이후 다시 merge하고 그 안에서 conflict를 해결하는 과정을 다시 했었는데 merge 이후 conflict를 해결하고 나서 체크하는 과정을 넣지 않아서 생긴 문제인 것 같습니다. 시정하겠습니다.

2024-07-20 04:15 UTC, Jinhwa-Park commented on src/test/oldTestCodes/MemberControllerTest.java
> +//@WebMvcTest(MemberController.class)
PR에는 테스트 코드까지 전부 넣은 결과물을 담는 것이 훨씬 좋다!라는 의미로 이해했는데 맞는지 다시 여쭙고 싶습니다!
개발 중에는 일단 테스트 코드를 차치하고 적더라도 PR을 보내기 전에는 테스트코드를 작성해서 테스트를 하고 난 뒤에 보내는 걸 추천합니다. -> 이게 맞는지 궁금합니다.

2024-07-20 12:26 UTC, Jinhwa-Park commented on src/test/oldTestCodes/MemberControllerTest.java
> +//@WebMvcTest(MemberController.class)
혹시 괜찮다면 step2까지 수정 완료하고 나서 테스트 코드를 새로이 작성해도 괜찮을까요?

2024-07-21 12:45 UTC, pkeugine commented on src/main/java/gift/service/CategoryService.java
> +    }
잘 알아봐주셨네요. 맞습니다.
그리고 예외가 발생했을 때의 처리는 GlobalExceptionHandler 가 처리할 수 있도록 둘 수 있구요.
꼭 '그러면 안돼' 느낌은 아니지만, 이왕이면 분리하는게 관리하기 편하죠!

2024-07-21 12:46 UTC, pkeugine commented on src/main/java/gift/service/CategoryService.java
> +        Category category = categoryRepository.findById(id).orElseThrow(() -> new RuntimeException("Category not found"));
`handleException` 이 예외 메시지를 응답에 담는 것도 다시 한 번 고민해보시면 좋을 것 같아요!

2024-07-21 12:46 UTC, pkeugine commented on src/main/java/gift/util/JwtUtil.java
> +    // Extract getEmailFromRequest logic as JwtUtil to reduce redundancy
네 그럴 수 있다고 생각합니다.
그런데 GlobalExceptionHandler 의 경우엔 주석이 또 한글로 적혀있더라구요.

그리고 주석은 제가 매번 지워보자고 코멘트를 남기는 편입니다.

2024-07-21 12:49 UTC, pkeugine commented on src/test/oldTestCodes/MemberControllerTest.java
> +//@WebMvcTest(MemberController.class)
PR 이 빌드가 안된다거나, 테스트가 통과되지 않으면 문제가 되겠지만,
그에 대한 해결책으로 테스트를 주석처리하는 것 역시 그리 좋지 않은 해결책입니다.
불이 나서 집 안의 경고음이 울리는데, 그에 대한 해결책으로 불을 끄지 경고음이 울리는 장치를 꺼버리진 않으니까요.

네 그렇게 하죠.

2024-07-21 13:07 UTC, Jinhwa-Park commented on src/main/java/gift/service/CategoryService.java
> +        Category category = categoryRepository.findById(id).orElseThrow(() -> new RuntimeException("Category not found"));
handleException이 예외 메시지를 응답에 담는 것을 고려해보라는 제안은 보안과 관련되었기 때문인가요?

2024-07-21 13:09 UTC, Jinhwa-Park commented on src/main/java/gift/util/JwtUtil.java
> +    // Extract getEmailFromRequest logic as JwtUtil to reduce redundancy
다른 요구사항들을 처리하고 피드백 사항들을 처리하느라 주석을 지우는 것을 잊는 것은 반성해야될 것 같습니다..! 이번 2단계 리뷰 코멘트 반영한 것을 다시 push할 때 주석을 모두 지워서 보내는 것으로 시정하겠습니다!

2024-07-21 13:09 UTC, Jinhwa-Park commented on src/test/oldTestCodes/MemberControllerTest.java
> +//@WebMvcTest(MemberController.class)
넵!

2024-07-21 17:17 UTC, Jinhwa-Park commented
코드 수정했습니다. 2단계도 대대적으로 뜯어고쳤는데 확인하시면 리뷰 부탁드립니다.

2024-07-22 13:57 UTC, pkeugine commented on src/main/java/gift/service/CategoryService.java
> +        Category category = categoryRepository.findById(id).orElseThrow(() -> new RuntimeException("Category not found"));
네 맞습니다!

2024-07-22 13:58 UTC, pkeugine approved these changes
고생하셨습니다 진화님,
해당 단계는 이제 머지하도록 하겠습니다.

2024-07-22 13:58 UTC, merged