충남대 BE_박서현 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #225
Opened 2024-07-18 10:18 UTC by sseooh

2024-07-18 12:52 UTC, jjongwa requested changes
현재 존재하는 테스트를 모두 돌리면 MemberRepositoryTest가 실패하고 있어요!
남긴 리뷰에 대한 답 & 해당 부분 수정되면 2단계도 바로 머지하겠습니다!

<img width="488" alt="image" src="https://github.com/user-attachments/assets/d33609c6-f1a9-4abc-8fbf-ecde0a19aa31">

2024-07-18 12:52 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +@Table(name = "options", uniqueConstraints = {
`options` 👍 👍

2024-07-18 12:52 UTC, jjongwa commented on src/main/java/gift/domain/Product.java
> +
option과 Product간 양방향 관계를 선택한 이유는 무엇인가요?

cascade와 orphanRemoval 설정을 각각 ALL과 true로 한 이유도 궁금합니다~!

2024-07-18 12:52 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +    private Integer quantity;
전체적으로 이러한 Unique, Min, Max 제약 조건들에 대해 

requestDto / domain / db scheme 
이 중 domain에 제약조건을 거는 이유가 무엇인지,
각각 부분에 걸었을 때의 장단점은 무엇인지 정리해 볼까요?

2024-07-18 12:52 UTC, jjongwa commented on src/main/java/gift/domain/Product.java
>  public class Product {
상품에는 하나 이상의 옵션이 있어야 하는데, 이는 어떻게 제약조건을 부여해줄 수 있을까요?

2024-07-18 12:52 UTC, jjongwa commented on src/main/java/gift/service/ProductService.java
> +        }
이름에 대한 unique 제약 조건은 이미 Option에 존재하는 상황인데, 여기서는 해당 기능을 활용하지 못하고 값을 가져와서 이름을 비교하고 있네요!

이러한 부분은 어떻게 개선할 수 있을까요? 아니면 어떻게 할 수 없는 부분일까요?

2024-07-19 08:21 UTC, sseooh commented on src/main/java/gift/domain/Product.java
> +
Product에서 Option을 조회하고, Option에서 Product를 조회해야 하는 경우가 있는 것 같아 양방향으로 설정했습니다!

cascade와 orphanRemoval 설정을 각각 ALL과 true로 한 이유는 Product의 변경이 Option에도 영향을 줄 수 있기 때문입니다..! 특히 product가 삭제되는 경우에는 option도 남아있을 이유가 없기 때문에 저렇게 설정했습니다

2024-07-19 08:41 UTC, sseooh commented on src/main/java/gift/domain/Option.java
> +    private Integer quantity;
domain에 제약조건을 거는 이유는 데이터 무결성을 보장하고 관리를 쉽게 하기 위해서 입니다.
데이터베이스와의 상호작용 전에 먼저 제약 조건을 검증하는 것이 가능하기 때문에 데이터의 무결성을 보장할 수 있습니다!

RequestDto에 제약조건을 거는 경우에는 입력받은 데이터를 빠르게 검증할 수 있다는 장점이 있지만, domain과 중복된 제약 조건으로 인해 코드가 중복될 수 있다는 단점이 있습니다. DB schema에 거는 경우에는 모든 레이어에서 일관된 데이터가 저장됨을 보장할 수 있지만, 데이터베이스 오류가 발생하기 전까지는 입력이 잘못 들어온 것을 알지 못할 수도 있습니다!

2024-07-19 14:11 UTC, sseooh commented on src/main/java/gift/service/ProductService.java
> +        }
코드 수정했습니다..!

2024-07-19 14:22 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +    private Integer quantity;
💯 
정말 엄격한 조건이라면 db와 도메인 모두에 걸 수도 있습니다~! 꼭 한 가지만을 선택해야 하는 건 아니에요!

2024-07-19 14:23 UTC, jjongwa approved these changes
👍 👍 
3단계로 가시죠~!

2024-07-19 14:23 UTC, merged