충남대 BE_이은경 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #247
Opened 2024-07-18 14:28 UTC by pkyung

## 과제 진행 사항
### 상품 옵션
- [x] 옵션 도메인 설계
- [x] 옵션 dto validation 설정
- [x] 상품과 옵션 설정
- [x] 옵션 cr 구현
- [x] 옵션 이름 중복 확인 메서드 생성 (도메인 계층에 생성)

2024-07-19 07:35 UTC, ksy90101 requested changes
깔끔하게 잘 구현해주셨네요 👍 
고생많으셨습니다!
간단한 피드백을 남겼으니 확인해주세요~
질문이 있다면 언제든 DM주세요!

2024-07-19 07:35 UTC, ksy90101 commented on src/main/java/gift/dto/OptionRequest.java
> +        @Max(99999999)
max는 지정 안해도 괜찮을거 같기도 해요~
굳이 정해지지 않았다면요!

2024-07-19 07:35 UTC, ksy90101 commented on src/main/java/gift/model/Product.java
> +            if (option.getName().equals(optionName)) {
해당 코드를 option 메서드로 구현해서 처리하면 어떨까요?

2024-07-19 07:35 UTC, ksy90101 commented on src/main/java/gift/model/Product.java
> +        for (Option option : options) {
stream을 사용해볼수도 있을거 같은데 한번 해보시면 어떨까요?

2024-07-19 07:35 UTC, ksy90101 commented on src/main/java/gift/service/OptionService.java
> +            throw new AlreadyExistsException("해당 상품에 등록된 옵션과 동일한 이름이 존재합니다.");
👍

2024-07-19 07:35 UTC, ksy90101 commented on src/main/java/gift/service/OptionService.java
> +        option.setProduct(product);
생성자에서 처리해볼수도 있을거 같아요?

2024-07-19 07:35 UTC, ksy90101 commented on src/test/java/gift/JpaOptionTest.java
> +public class JpaOptionTest {
JPA 테스트는 이제 잘 되는거 같아요~
한번 이번엔 Service Test도 추가해보면 어떨까여?

2024-07-19 07:36 UTC, pkyung commented on src/main/java/gift/dto/OptionRequest.java
> +        @Max(99999999)
요구사항에 1억개 미만이라는 요구사항이 있어서 넣었습니다!

2024-07-19 08:01 UTC, pkyung commented on src/main/java/gift/model/Product.java
> +            if (option.getName().equals(optionName)) {
네 optoin으로 수정하겠습니다. product에서 한 이유는 option이 아직 생성되기 이전이었기 때문이었는데 option의  생성자를 통해 product를 정의하면 option에서 메서드로 구현할 수 있을 것 같습니다.

2024-07-19 08:01 UTC, pkyung commented on src/main/java/gift/model/Product.java
> +        for (Option option : options) {
네 stream을 통해 처리해보겠습니다.

2024-07-19 08:05 UTC, pkyung commented on src/test/java/gift/JpaOptionTest.java
> +public class JpaOptionTest {
네 추가해보겠습니다.

2024-07-19 10:23 UTC, pkyung commented on src/main/java/gift/model/Product.java
> +            if (option.getName().equals(optionName)) {
생성자에서 처리하니 option 객체 생성 시에 이미 product의 options에 option이 들어가서 동일한 이름으로 체킹 되어서 product에서 해야할 것 같습니다.

2024-07-20 03:29 UTC, ksy90101 commented on src/main/java/gift/model/Product.java
> +            if (option.getName().equals(optionName)) {
차라리 지금 보니 SQL 쿼리로 처리해도 무관할거 같기도 하네요.

2024-07-20 03:31 UTC, ksy90101 approved these changes
2단계도 고생많으셨어요~
간단한 피드백을 남겼으니 확인해주세요!
추가적으로 궁금한게 있다면 DM주세요!

2024-07-20 03:31 UTC, ksy90101 commented on src/test/java/gift/OptionServiceTest.java
> +package gift;
테스트 파일도 실제 프로덕션의 패키지 구조와 동일하게 가져갑니다.
지금 service가 service폴더 내에 있으니 테스트도 동일하게 패키지 구조를 가져가면 좋겠습니다.

2024-07-20 03:31 UTC, ksy90101 commented on src/test/java/gift/OptionServiceTest.java
> +public class OptionServiceTest {
👍

2024-07-20 03:32 UTC, ksy90101 commented on src/main/java/gift/model/Product.java
> +            if (option.getName().equals(optionName)) {
혹은 product 도메인 로직으로 있는게 어울릴거 같아요,.
product의 options의 validate 느낌이죠.

2024-07-20 03:32 UTC, merged

2024-07-20 12:29 UTC, pkyung commented on src/test/java/gift/OptionServiceTest.java
> +package gift;
네 수정하겠습니다!