경북대 BE_김영인 4주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #250
Opened 2024-07-18 14:37 UTC by Youngini

과제를 하면서 느낀점은 여전히 FK 설정에 관해서 헷갈려한다는 것 입니다!

일단 Product와 Option이 1대다 관계로, 외래키는 다 쪽인 Option에 있도록 했습니다.

그러니까 Option이 연관관계의 주인이 된다는 것까지 생각을 했는데

그 뒤에 product가 생성될 때 option도 함께 생성되고 Product가 수정될 때 Option도 함께 수정되야하는 곳에서 갑자기 헷갈리기 시작했습니다.

그래서 일단 CreateProductDto에 Option List를 넣어서 Product에 들어가도록 했는데, 이러면 Option이 생성되서 저장되기 전인데 입력받은 Option만으로 Product에 저장하는 것이 맞는가에 대한 생각이 들었습니다.

아직까지 개념이 많이 헷갈리고있는 것같아서 자바 ORM 표준 JPA 책을 읽어야하나 하는 생각이 들었습니다!

지금처럼 구현하는 것이 맞을까요?

Product를 수정할 때, Option을 수정하는 api를 호출하고, Product를 수정하는 api를 호출하는 식인지

Product를 수정하면서 연결된 Option도 같이 수정되는 것이 맞는지가 고민이 됩니다.

2024-07-19 16:26 UTC, gongdongho12 requested changes
확실히 연관관계 작업은 현직자도 바로 설명하기는 어려운 그런 것 같아요!
다만 직접 쿼리를 보면서 수정하다 보니 처음부터 바로 설명은 어려워도 가장 합리적인 방향으로 적용할 수 있던 것 같습니다

> 일단 Product와 Option이 1대다 관계로, 외래키는 다 쪽인 Option에 있도록 했습니다.

말씀주신대로 FK는 N개인 대상에서 1개인 대상을 나타낼 수 있게 하는 부분을 잘 적용주셨습니다

> Product를 수정할 때, Option을 수정하는 api를 호출하고, Product를 수정하는 api를 호출하는 식인지 / Product를 수정하면서 연결된 Option도 같이 수정되는 것이 맞는지가 고민이 됩니다.

정확히는 DB는 커밋 방식이라, 연관관계에 새로 추가할 대상이 아직 추가 전이라도
product에 아직 추가 안된 옵션이 들어가도 정확히 들어가게 됩니다!
이부분은 바로 적응하기는 어렵고 커밋 전, 커밋 후 개념을 익히고 가시면 좋을 것 같습니다

이번 단계도 고생하셨습니다 💯

2024-07-19 16:26 UTC, gongdongho12 commented on src/main/java/gift/domain/Product.java
> +    }
엔티티의 업데이트는 DTO로 전달받는게 좋지 않을까요?

2024-07-19 16:26 UTC, gongdongho12 commented on src/main/java/gift/dto/CreateProductDto.java
> +        return product;
넵 맞습니다 잘 적용해 주셨어요 👍🏼

2024-07-19 16:26 UTC, gongdongho12 commented on src/main/java/gift/dto/UpdateProductDto.java
> +
DTO인데 jakarta validator가 정상 동작 할까요?
```java
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
```

2024-07-19 16:26 UTC, gongdongho12 commented on src/main/java/gift/dto/UpdateProductDto.java
> +        product.update(product);
이건 DTO인데 DAO의 역할을 침범해서 적용하는거 아닐까요?
DTO는 말 그대로 데이터의 전달인데, 데이터의 업데이트까지 진행하는 모습이에요

2024-07-19 16:26 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +        this.optionService = optionService;
서비스 레이어 잘 구분해서 적용되었네요!
프러덕트 서비스 - 프러덕트 레포지토리 형식으로요 💯

2024-07-19 16:26 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +    }
옵션 서비스에 이미 정의된걸 프러덕트 서비스에 추가로 가져오지 않아도 되지 않을까요?
이미 있는 기능을 프러덕트 서비스에 라우팅만 하는 용도로 보여서요

2024-07-20 17:47 UTC, Youngini commented on src/main/java/gift/dto/UpdateProductDto.java
> +        product.update(product);
안그래도 이 부분이 걱정이 되었습니다.
그런데 위에서도 말했듯이 아직 FK관련 내용이 헷갈리다보니 service쪽에서 어떻게 처리를해야할지 모르겠어서 한번에 진행을 해버렸는데 분리해서 다시 도전해 보겠습니다!

2024-07-20 17:53 UTC, Youngini commented on src/main/java/gift/domain/Product.java
> +    }
createProductDto의 toProduct에서 한 것처럼 수정해보도록 하겠습니다!

2024-07-20 18:04 UTC, Youngini commented on src/main/java/gift/dto/UpdateProductDto.java
> +        product.update(product);
관련 내용들을 모두 ProductService 코드 내로 이동시켰습니다!

여기서 궁금증이 드는 것은, Product를 업데이트하는 method내에 option을 Update하는 method도 호출해서 사용했는데 이 내용은 역시 OptionService에서 진행하는 것이 맞는것이겠죠?

updateProductOptions코드에서 Product product를 method 인자로 받은 이유가 product.setOptions(optionList)를 위해서 였는데 생각해 보면, fk로 연결되어있기 때문에 option값이 바뀌면 알아서 option과 연관이 된 product의 option도 알아서 수정이 되는 것 이라고 생각이 듭니다.

후자로 이해한 내용이 혹시 맞을까요?

2024-07-20 18:24 UTC, Youngini commented on src/main/java/gift/service/ProductService.java
> +    }
말씀하신 내용이 맞는 것 같습니다! productService에 호출하는게 아니라 controller에서 바로 호출하도록 수정하겠습니다!

2024-07-20 18:36 UTC, Youngini commented on src/main/java/gift/dto/UpdateProductDto.java
> +
@Valid 어노테이션을 Controller에서 사용하면 DTO에서도 사용이 가능할거라 생각하고 작성한 것인데 관련 내용은 테스트를 통해서 다시 확인해보도록 하겠습니다!

2024-07-20 19:01 UTC, Youngini commented
3단계 과제는 상품 판매가 일어날 때, 남은 재고들을 처리하기 위한 code로 생각하고 작성하였습니다.

위에서 제가 Product의 Update를 DTO에서 진행해버린 것과 같은 일을 다시 안저지르기 위해서 일단 3단계 과제도 모든 일을 Service에서만 일어나도록 먼저 코드를 작성하였습니다.

그런데 과제에 보면 "서비스 클래스 또는 엔티티 클래스에서 기능을 구현"하고 라는 말이 있었는데, 수량을 빼거나 하는 그런 간단한 코드는 Entity나 Dto 에서 일어나도 괜찮은 걸까요?

기준이 업데이트와 삭제인것인지가 궁금했습니다!

그래서 일단 모든 동작이 Service에서 일어나도록 작성한 다음, subtract 자체를 Entity로 빼서도 작성을 해봤는데, 오류를 저렇게 Entity에서 동작하도록 하는 것이 아닌것 같은데 저렇게 해도 되는 것인지 여쭤보고 싶었습니다!

황금 주말에도 피드백 해주셔서 정말 감사합니다!

항상 멘토님이 주신 피드백들을 다시 생각하면서 코드를 작성하면서 점점 나아지고 있다는 생각이 듭니다! 다시한번 감사합니다 😊😊

2024-07-21 08:43 UTC, gongdongho12 commented
@Youngini 3단계 PR 구분 없이 그대로 병합하신 사유가 궁금합니다 ㅠ

2024-07-21 08:44 UTC, gongdongho12 commented on src/main/java/gift/dto/UpdateProductDto.java
> +        product.update(product);
넵 후자가 맞습니다
다만 실제 쿼리 나가는 시점은 눈으로 직접 확인해보시는 쪽이 이해가 빠를 수 있어요

2024-07-21 08:52 UTC, gongdongho12 requested changes
우선 3단계 리뷰라고 생각하고 리뷰 드리겠습니다

> 그런데 과제에 보면 "서비스 클래스 또는 엔티티 클래스에서 기능을 구현"하고 라는 말이 있었는데, 수량을 빼거나 하는 그런 간단한 코드는 Entity나 Dto 에서 일어나도 괜찮은 걸까요?

간단한 코드는 Entity에서 일어나는 부분은 이미 과제에 나온 부분인데요
DTO에서 일어나도 되냐는 질문이라하면, DTO에서 DB에 대한 동작이 일어나면 안됩니다!

> DTO에서 동작해서는 안되는 기능이 업데이트와 삭제인것인지가 궁금했습니다!

DTO의 역할은 Data Transfer 데이터 상하차 용도라고 생각해주시면 될거에요, 조회, 생성, 수정, 삭제 전부 일어나면 안되는 객체입니다

> 그래서 일단 모든 동작이 Service에서 일어나도록 작성한 다음, subtract 자체를 Entity로 빼서도 작성을 해봤는데, 오류를 저렇게 Entity에서 동작하도록 하는 것이 아닌것 같은데 저렇게 해도 되는 것인지 여쭤보고 싶었습니다!

엔티티에서 할 수 있는건 수정이나 연관관계 추가, 삭제등이 있는데요
오류는 발생한 지점이 있으면 catch가 있을떄까지는 호출부까지 올라오기 떄문에 서비스에서 에러로 감지될 수 있는 부분이라면 크게 걱정하지 않으셔도 됩니다

### 그리고 3단계는 기존에 작성된 전체 로직에 대한 테스트가 필요합니다
지금 작성된 코드들에 테스트들 작성해서 재 요청 부탁드립니다

2024-07-21 08:52 UTC, gongdongho12 commented on src/main/java/gift/dto/UpdateProductDto.java
> +
jakarta validator는 정상 동작이 맞네요
넵넵 이부분 테스트 추가되면 좋을 것 같습니다

2024-07-21 08:52 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +                    }
업데이트 방식이 N X N 호출인데 이부분 개선되면 좋을 지점 같아요!
상품마다 옵션은 여러번 있을 수 있는 다량의 데이터인데 이런 구조로 수정되면 안되지 않을까요?

2024-07-23 15:55 UTC, gongdongho12 approved these changes
4주차 처리하는 작업인데 벌써 화요일이네요 ㅠㅠ
이번 과제에 학습할 내용이 많았는데두 잘 마무리해주셔서 다행입니다!

이번주차두 리뷰드렸던 내용들 상기해서 좋은 코드 작성해봐요
고생하셨습니다 🥇

2024-07-23 15:55 UTC, gongdongho12 commented on src/test/java/gift/service/OptionServiceTest.java
> +    }
각 예외에 대해 구체적으로 EntityNotFoundException 정의해주셔서 이해하기 용이하네요 👍🏼

2024-07-23 15:55 UTC, gongdongho12 commented on src/test/java/gift/service/OptionServiceTest.java
> +        assertThrows(IllegalArgumentException.class, () -> optionService.decreaseQuantity(1L, -5));
이런 케이스를 별도로 분리하기 보다는 appendQuantity 라는 메서드 하나로 양수 음수로 구분지어보면 어떨까요?

2024-07-23 15:55 UTC, gongdongho12 commented on src/test/java/gift/service/ProductServiceTest.java
> +    }
셋업 로직이 많은 편이긴 하네요 ㅎㅎ
각 로직에서 공통되는 부분만 셋업에 넣고, 사용부에 맞게 테스트를 채워나가는게 흐름을 이해하는데 도움이 될 것 같습니다!

2024-07-23 15:55 UTC, merged