충남대 BE_이동현 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #254
Opened 2024-07-18 16:29 UTC by Thornappl2

- 과제를 구현하던 중, CategoryDTO 구성에 대한 고민을 많이 했습니다. Product와의 관계를 설정함에 있어서
  CategoryID를 사용해서 해야 할 지, 혹은 CategoryName을 사용해야 할지, 둘 다 할지에 대해 고민을 진행하였는데, 
  구글링을 통해 관련 자료를 찾아보던 중 DTO 내부에 DTO를 넣는 방식을 발견하였습니다. 하지만 ProductDTO 내부에 CategoryDTO를 필드로 넣어 사용하면 좋은 결과가 있지 않을 듯 하여 최대한 분리하는 방식으로 진행해보았습니다. 이에 대해 옳게 진행한 것인지 궁금합니다.

2024-07-19 07:49 UTC, ksy90101 requested changes

2024-07-19 07:49 UTC, ksy90101 commented on src/main/java/gift/controller/CategoryPageController.java
> +    }
이건 save라는 단어를 쓸 필요는 없어보이니다!

2024-07-19 07:49 UTC, ksy90101 commented on src/main/java/gift/controller/CategoryPageController.java
> +    @PostMapping("/update/{id}")
update를 할떄 POST를 쓸까요?
PUT 이라는 메서드를 찾아보면 어떨까요?

2024-07-19 07:49 UTC, ksy90101 commented on src/main/java/gift/controller/CategoryPageController.java
> +    public String updateCategoryForm(@PathVariable long id, Model model) {
Long vs long의 차이가 무엇일까요?

2024-07-19 07:49 UTC, ksy90101 commented on src/main/java/gift/controller/CategoryPageController.java
> +    @GetMapping("/delete/{id}")
삭제도 DELETE 메서드를 찾아보면 어떨까요?

2024-07-19 07:49 UTC, ksy90101 commented on src/main/java/gift/dto/CategoryDTO.java
> +    private String color;
colorsms color 코드인데 이것도 Validate가 필요하지 않을까요?

2024-07-19 07:49 UTC, ksy90101 commented on src/main/java/gift/dto/CategoryDTO.java
> +public class CategoryDTO {
DTO에는 setter를 쓰지 않으셔도 됩니다!

2024-07-19 07:49 UTC, ksy90101 commented on src/main/java/gift/model/Category.java
> +    private String name;
이름이 중복되어도 되나요!?

2024-07-19 07:49 UTC, ksy90101 commented on src/main/java/gift/service/CategoryService.java
> +    public CategoryDTO createCategory(CategoryDTO categoryDTO) {
이미 서비스에서 카테고리 서비스라고 되어 있으니

메서드명을 create로 적어도 괜찮을수도 있어요~

(이건 정답이 존재하진 않지만 그런 식으로 하긴 합니다!)

2024-07-19 16:02 UTC, Thornappl2 commented on src/main/java/gift/controller/CategoryPageController.java
> +    }
위의 createCategoryForm과 같이 new로 수정하였습니다.

2024-07-19 16:23 UTC, Thornappl2 commented on src/main/java/gift/controller/CategoryPageController.java
> +    public String updateCategoryForm(@PathVariable long id, Model model) {
데이터베이스에서 조회한 값이 null일 수 있는 경우 Long을 사용하는 것이 적합하다 하여 수정하였습니다.

2024-07-19 16:23 UTC, Thornappl2 commented on src/main/java/gift/controller/CategoryPageController.java
> +    @PostMapping("/update/{id}")
수정하였습니다.

2024-07-19 16:23 UTC, Thornappl2 commented on src/main/java/gift/controller/CategoryPageController.java
> +    @GetMapping("/delete/{id}")
수정하였습니다.

2024-07-19 16:27 UTC, Thornappl2 commented on src/main/java/gift/dto/CategoryDTO.java
> +    private String color;
적용하였습니다.

2024-07-19 16:30 UTC, Thornappl2 commented on src/main/java/gift/model/Category.java
> +    private String name;
unique 를 사용하여 적용하였습니다.

2024-07-19 16:39 UTC, Thornappl2 commented on src/main/java/gift/service/CategoryService.java
> +    public CategoryDTO createCategory(CategoryDTO categoryDTO) {
넵 create를 비롯하여 update, deleteById, getById와 같은 형태로 다른 메서드들도 간소화하였습니다.

2024-07-19 16:43 UTC, Thornappl2 commented on src/main/java/gift/dto/CategoryDTO.java
> +public class CategoryDTO {
제가 검색하며 공부한 것에 의하면, 엔티티에서는 setter를 최대한 지양하고 DTO에서는 자유롭게 사용해도 괜찮다고 봐서 DTO에선 getter와 setter를 우선 생성하였었습니다! DTO에서도 setter 대신 생성자를 사용하는 방식 혹은 정적 팩토리 메서드를 사용하는 것이 맞을까요?

2024-07-20 02:54 UTC, ksy90101 commented on src/main/java/gift/dto/CategoryDTO.java
> +public class CategoryDTO {
setter는 데이터를 변경하기가 너무 쉬우니, 생성자를 통해 최대한 막는게 좋을거 같아요.
생성자를 사용할수 있다면 setter를 사용할 이유는 없다고 생각이 들어요.

2024-07-20 03:43 UTC, ksy90101 approved these changes
1단계 고생많으셨어요~
2단계에서 바로 뵐게요!

(주의: 다음부턴 PR은 한개씩만 올려주세요 ㅠㅠ 안그러면 리뷰 요청이 꼬이게 됩니다 ㅠㅠ)

2024-07-20 03:43 UTC, merged

2024-07-20 15:37 UTC, Thornappl2 commented on src/main/java/gift/dto/CategoryDTO.java
> +public class CategoryDTO {
넵 알겠습니다!