경북대 BE_신형진 4주차(2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #257
Opened 2024-07-18 17:13 UTC by hjinshin

## 어려웠던 점
* 테스트 코드 작성이 익숙하지 않아 많은 시간을 소모했던 것 같습니다. 
* JPA에서 OneToMany관계에 있는 엔티티와 Fetch Join하여 조회할 때 Limit 쿼리가 나가지 않는 문제를 해결하지 못했습니다. 일단 Product 페이징을 return할 때는 Option을 반환하지 않도록 구현해놓았습니다.

## 리뷰 받고 싶은 부분
* Product와 Option에 양방향 연관관계를 맺어 Product 모델에서 생성하도록 구현하였습니다. 제가 생각했을 때 로직의 주체가 Product인 것 같아 양방향매핑을 해주었는데 이럴 경우에 매핑해주는게 맞는지 궁금합니다. 만약 두 엔티티가 의존하지 않는게 좋아보인다면 어떤 식으로 구현해야할지 알고싶습니다.

2024-07-19 14:27 UTC, leaf-upper requested changes
형진님 2단계 고생많으셨습니다~ 👍 
코드가 너무 좋아진게 느껴지네요
몇가지 수정해주시면 좋을것 같은 부분은 코멘트 드렸어요~ 
고생하셨습니다!

2024-07-19 14:27 UTC, leaf-upper commented on src/main/java/gift/common/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<ProblemDetail> illegalArgumentException(IllegalArgumentException e) {
메서드 이름은 동사로 시작하는게 좋은것 같아요~
handle~Exception 이런식으로 네이밍해보는건 어떨까요?

2024-07-19 14:27 UTC, leaf-upper commented on src/main/java/gift/controller/dto/request/CategoryRequest.java
> +public class CategoryRequest {
되게 좋은것 같아요~ 👍👍

2024-07-19 14:27 UTC, leaf-upper commented on src/main/java/gift/controller/admin/AdminOptionController.java
> +            @RequestParam("productId") @NotNull @Min(1) Long ProductId) {
요기 카멜케이스 부탁드립니다~!

2024-07-19 14:27 UTC, leaf-upper commented on src/main/java/gift/model/Option.java
> +        @UniqueConstraint(columnNames = {"name", "product_id"})
Option에서 product_id도 유니크 제약조건으로 거는걸까요?

2024-07-19 14:27 UTC, leaf-upper commented on src/main/java/gift/model/Product.java
> +    private List<Option> options = new ArrayList<>();
잘 작성해주셨는데요~ Option은 여러개가 있을수 있으니 N+1 Query를 방지하기 위해 `@BatchSize` 같은 애너테이션만 추가해주시면 좋을것 같아요.
orphanremoval 옵션도 가능하지 않을까 싶습니다. 혹시 모르신다면 한번 공부해주시면 좋을것 같아요

2024-07-19 14:27 UTC, leaf-upper commented on src/main/java/gift/repository/OptionRepository.java
> +    List<Option> findAllByProductIdFetchJoin(Long productId);
OptionRepository가 꼭 필요할까요?
Product와 Option은 생명주기가 같은데요, ProductRepository에서 조회후, 이를 기반으로 Option응답도 가능할것 같아요.
모든 엔티티에 Repository가 필요한건 아닌것 같아요. 한번 고민해보시고 반영 부탁드립니다.

2024-07-19 14:27 UTC, leaf-upper commented on src/main/java/gift/repository/ProductRepository.java
> +    List<Product> findByCategoryId(Long categoryId);
말씀주신거에서 1:N 관계에서 페이징은 Fetch Join이 힘들어요. `@BatchSize`를 통해서 N+1문제를 해결해보는게 좋을것 같아요.

2024-07-19 14:27 UTC, leaf-upper commented on src/main/java/gift/repository/ProductRepository.java
> +    List<Product> findByCategoryId(Long categoryId);
Batch Size는 200개 이하를 권장합니다. 200개 이상일 경우 where in의 성능이 저하될 수 있어요.
(궁금하시다면 mysql eq_range_index_dive_limit 관련 옵션을 참고해보시면 좋을것 같습니다.)

2024-07-19 14:27 UTC, leaf-upper commented on src/main/java/gift/service/OptionService.java
> +    private final OptionRepository optionRepository;
이전에 멘토링을 할때 생명주기가 같은 엔티티에 대해서만 매핑하고, 생명주기가 다른 엔티티는 매핑하지 않았으면 좋겠다 라고 얼핏 말씀드렸던것 같아요~

저는 Member, Product, Wish 이 3개 엔티티는 생명주기가 다르기때문에 오히려 매핑이 불필요한것 같다는 생각이에요. (단 요구사항이 있으니 이 연관관계는 일단 지켜주세요)
Product와 Option은 생명주기가 완전히 동일한 엔티티인데요, 이런경우 연관관계 매핑을 사용해주시면 좋을것 같습니다.

---
그래서 말씀드리고 싶은 부분은 옵션과 관련된 비즈니스 로직은 `ProductService`로 이전해보는건 어떨까요?

매 엔티티마다 Service, Repository를 생성해야하는건 아닙니다.
OptionService, OptionRepository는 ProductService, ProductRepository에서 그 역할을 수행할 수 있을것 같아요.

1. 상품에 대한 옵션 추가
Product에 CASCADETYPE을 ALL로 설정하셨으니, Product가 save될때 Option도 같이 save될수 있어요.
Product 객체의 List에 Option을 엔티티를 추가합니다.

2. 상품에 대한 옵션 제거
Product에서 orphanremoval=true로 주시면 List에서 Option을 제거하고 ProductRepository에 save하면 옵션도 제거됩니다.

3. 상품에 대한 옵션 조회
상품에 대한 옵션 조회는 LAZY로 조회하되, N+1 Query를 방지하기 위해 `@BatchSize`를 사용해보는건 어떨까요

위 3가지 한번 고민해봐주세요~

2024-07-19 15:04 UTC, hjinshin commented on src/main/java/gift/controller/admin/AdminOptionController.java
> +            @RequestParam("productId") @NotNull @Min(1) Long ProductId) {
케밥케이스 말씀하시는거 맞나요?

2024-07-19 15:06 UTC, leaf-upper commented on src/main/java/gift/controller/admin/AdminOptionController.java
> +            @RequestParam("productId") @NotNull @Min(1) Long ProductId) {
오 케밥케이스는 처음들어보네요 ㅋㅋ 이런것도 있군요
케밥케이스를 말씀드린것 아니였고 `ProductId`라서 => `productId`로 변경해주시면 좋을것 같습니다 :)

2024-07-19 15:07 UTC, hjinshin commented on src/main/java/gift/model/Option.java
> +        @UniqueConstraint(columnNames = {"name", "product_id"})
네. 하나의 product내에 동일한 name이 생기지 않도록 제약조건을 설정하였습니다!

2024-07-19 16:39 UTC, hjinshin commented on src/main/java/gift/model/Product.java
> +    private List<Option> options = new ArrayList<>();
@BatchSize 적용하여서 Product 조회할 때 Option도 같이 조회하도록 하였습니다! 
또 orphanremoval 옵션으로 Product의 Option 리스트에서 제거하면 Option 엔티티를 삭제하도록 수정하였습니다.

2024-07-19 16:46 UTC, hjinshin commented on src/main/java/gift/repository/ProductRepository.java
> +    List<Product> findByCategoryId(Long categoryId);
네 BatchSize로 Option까지 반환해 주었습니다!

2024-07-19 17:45 UTC, hjinshin commented on src/main/java/gift/repository/OptionRepository.java
> +    List<Option> findAllByProductIdFetchJoin(Long productId);
OptionService, OptionRepository 전부 Product에 통합하였습니다.

2024-07-19 17:58 UTC, hjinshin commented on src/main/java/gift/service/OptionService.java
> +    private final OptionRepository optionRepository;
3가지 내용 위에서 전부 반영하였습니다!

2024-07-19 20:04 UTC, hjinshin commented
Option의 quantity 필드에 대해서 동시성을 제어하기 위해서 Lock을 사용하려고 합니다. 
이때 Option에만 Lock을 걸기 위해서는 OptionRepository가 필요하지않나요?

2024-07-21 06:53 UTC, leaf-upper commented
@hjinshin 
비관적락을 말씀해주시는거라면, SELECT FOR UPDATE를 말씀하시는걸까요?
OptionRepository를 통해서 락을 Option에 걸수도 있겠지만
락을 거는 방법은 굉장히 다양해서요~ 오히려 SELECT FOR UPDATE는 데이터가 없을경우 락이 걸리지 않을수도 있으며, 
성능이 좋지 못할수도 있어요. 이런 현상을 쓰기스큐라고 합니다.

옵션에 락을걸지 않고, 좀더 큰개념으로 상품에 락을걸수도 있을것 같아요~
혹은 다른 인프라를 통해서(쓰레드의 안정성이 보장되는 인프라. ex. redis)를 통해서 분산락을 잡아주실수도 있어요.
혹은 낙관적 락 방식을 통해 별도 락을 잡지 않고, 트랜잭션이 커밋될때의 Version정보를 가지고도 기능구현이 가능할것 같습니다.

2024-07-21 06:54 UTC, leaf-upper approved these changes
👍 고생하셨습니다~
OptionService와 OptionRepository를 제거하는 리팩토링을 부탁드려는데요~
갑작스런 리팩토링 요청에도 잘 코드를 구현해주신것 같아요.
고생하셨습니다 👍

2024-07-21 06:54 UTC, merged