강원대 BE_김송목 4주차 과제(Step 2)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #261
Opened 2024-07-18 17:55 UTC by kimsongmok

Option 구현해보았고, test코드로 테스트 해봤습니다..! 리뷰 부탁드립니다! 그리고 깃 확인 부탁드립니다!

2024-07-19 15:51 UTC, jaymarystella requested changes
안녕하세요 
브랜치정리가 드디어 잘 된거같네요ㅠ 
코멘트 남긴부분들 확인 해주시고 의견 및 반영 부탁드리겠습니다.

2024-07-19 15:51 UTC, jaymarystella commented on src/main/java/gift/controller/OptionController.java
> +  private OptionService optionService;
다른 주입방식도 있을까요?

2024-07-19 15:51 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
> +    option.setProduct(this);
쓰이는 메서드일까요?

2024-07-19 15:51 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
> +    option.setProduct(this);
모델 패키지 안에 있는 클래스들이 가지고있는 메서드들에 대해서 테스트코드를 작성해보면 어떨까요

2024-07-19 15:51 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
>  public class Product {
>   public void updateFromDto(ProductDto productDto, CategoryRepository categoryRepository) {
>     this.name = productDto.getName();
>     this.imageUrl = productDto.getImageUrl();
>     this.price = productDto.getPrice();
>     this.category = categoryRepository.findById(productDto.getCategoryId())
>             .orElseThrow(() -> new CustomNotFoundException("Category not found"));
>   }

updateFromDto 메서드인자가 어색한것같습니다. repository를 model에 들고와서 평가하기보다는 상위에서 평가한 결과를 내려주는게 낫지 않을까요?

2024-07-19 15:51 UTC, jaymarystella commented on src/main/java/gift/controller/OptionController.java
> +    Option createdOption = optionService.addOptionToProduct(productId, option);
Option에 대한 request 클래스로 엔티티를 사용하고있는데요, 별도의 클래스를 정의해보는건 어떨까요?

2024-07-19 15:51 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +    return optionRepository.save(option);
옵션 엔티티를 조회한 후에 상태만 변경해주면 충분하지 않을까요?

2024-07-19 15:51 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +    return optionRepository.save(option);
트랜잭션설정도 같이 들어가면 어떨까요?

2024-07-19 15:51 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +  public Option addOptionToProduct(Long productId, Option option) {
> 옵션 수량은 최소 1개 이상 1억 개 미만이다.
> 중복된 옵션은 구매 시 고객에게 불편을 줄 수 있다. 동일한 상품 내의 옵션 이름은 중복될 수 없다.

위와같은 요구사항은 반영이 되어있을까요?

2024-07-20 09:59 UTC, kimsongmok commented on src/main/java/gift/service/OptionService.java
> +  public Option addOptionToProduct(Long productId, Option option) {
그 요구사항 부분은 모델 클래스 Option.java 내에 반영이 되어있습니다!!

2024-07-20 17:49 UTC, kimsongmok commented
최대한 리뷰를 반영했고, 멘토님의 의도가 담겼을지는 모르겠습니다..! 테스트 코드로 돌려본 결과는 괜찮았던 것 같습니다.
혹시 부족한 부분 있으면 말씀해주시길 바랍니다!

2024-07-21 06:44 UTC, jaymarystella approved these changes
리뷰 수정하느라 고생많으셨어요.
다음단계 진행해주세요~

2024-07-21 06:44 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
> +    this.category = category;
단순히 업데이트하는것보다 검증을 해주시는것을 추천드립니다. 단순 세터와 다를게 없어서요.

2024-07-21 06:44 UTC, merged

2024-07-21 06:47 UTC, kimsongmok commented on src/main/java/gift/model/Product.java
> +    this.category = category;
네! 다음단계에서 반영하겠습니다!