전남대 BE_박민규 4주차 과제(Step 2)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #262
Opened 2024-07-18 18:23 UTC by ps9319

그냥 다른 것과 같이 그냥 CRUD라서 어렵지 않게 작성했습니다만, 테스트 코드 짜기가 너무 어려워요 엉엉엉.... 단위 테스트도 해보고 싶고, 다 해보고 싶은데 엄두가 안 나서 시도를 못하고 있습니다....강사님께서는 목객체도 만드시고 테스트용 객체도 따로 만들어서 어떻게 저렇게 하시던데.. 테스트 코드 짜는 팁 있을까요..?

2024-07-18 18:29 UTC, ps9319 commented on src/main/java/gift/domain/Option.java
> +    }
```
public void create(final Long productId, final CreateOptionRequest request) {
    var product = productRepository.findById(productId)
        .orElseThrow(() -> new NoSuchElementException("상품이 존재하지 않습니다."));
    var option = new Option(request.getName(), request.getQuantity(), product);
    var options = optionRepository.findAllByProduct(product);
    options.validate(option);
    optionRepository.save(option);
}
```
이 부분 강사님께서 Options 객체를 만들어서 사용한 걸 inner class로 만들어보았는데 inner class를 잘 사용해보질 않아서 이게 잘 한 건지 잘 모르겠어요.. 피드백해주시면 감사하겠습니다!!

2024-07-19 13:52 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +    }
> 저는 따로 inner class로 만들어보았습니다. 그런데 제가 inner class를 잘 사용해보질 않아서 이게 잘 한 건지 잘 모르겠어요.

왜 inner class로 만든건가요? 본인이 선택한 방식에 대한 이유를 알지 못하면 피드백도 드릴수가 없답니다.!

지금 적혀있는 설명과 코드 만으로는 
inner class가 어떤 장점이 있다고 생각해 해당 방식으로 구성해 봤는지 or 강사님은 따로 클래스를 만들어 설명했는데 본인은 inner class로 만들어보게 된 계기 

같은 내용이 없기 때문에 잘 하고 못하고를 따질 수가 없습니다~~

2024-07-19 14:41 UTC, jjongwa reviewed
리뷰알림 채널에 박제하고싶진 않아 여기다 적어요.

> 그냥 다른 것과 같이 그냥 CRUD라서 어렵지 않게 작성했습니다만

여기서부터 잘못된 것 같습니다. 제가 봤을 때 지금 Option 관련 로직을 추가하면서 깊게 생각하고 고민한 흔적이 보이지 않고,
그저 Product, Wish에서 만들어 놓았던 엔티티, Dto, Service를 보고 복붙한 수준이라고 보여져요.

이렇게 학습하면 의미가 없습니다.

전체적으로 사용하지 않는 메서드, 각 단계별 요구사항, 패키지 및 메서드 네이밍 정리 등 기본적인 부분 먼저 쭉 개선해 주세요.

2024-07-19 14:41 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +    Product product;
product와 단방향 관계를 설정 & OnDeleteAction을 추가해 준 이유가 궁금합니다~!

2024-07-19 14:41 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +                throw new IllegalArgumentException("같은 이름의 옵션이 존재합니다.");
여기서 it은 어떤 객체를 지칭하게 되나요?

2024-07-19 14:41 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +        List<Option> optionList;
static class로 선언한 이유는 무엇인가요?

static을 붙이면 어떤 효과가 있나요?

2024-07-19 14:41 UTC, jjongwa commented on src/main/java/gift/dto/requestDTO/OptionNameUpdateRequestDTO.java
> +    }
여기선 toEntity를 사용하지 않는데도 만들어져 있군요!

꼭 dto에서 도메인을 만들어내는 메서드가 있어야할 필요는 없습니다!

개인적으로 지금 dto의 필드가 굳이 많지 않은 상황이어서 저는 toEntity라는 메서드를 하나도 만들지 않을 것 같아요~!

2024-07-19 14:41 UTC, jjongwa commented on src/main/java/gift/dto/requestDTO/OptionCreateRequestDTO.java
패키지는 소문자로 만들어 주세요~!

2024-07-19 14:41 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +        List<Option> optionList;
보통 필드의 네이밍에 자료형을 붙이지 않습니다!

https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/

2024-07-19 14:41 UTC, jjongwa commented on src/main/java/gift/dto/responseDTO/OptionResponseDTO.java
> +    }
위와 같은 형식을 `정적 팩토리 메서드` 패턴이라고 부르는데,

이러한 정팩매는 왜 사용하고 어떨 때 사용할까요?

2024-07-19 14:41 UTC, jjongwa commented on src/main/java/gift/dto/requestDTO/OptionNameUpdateRequestDTO.java
> +    }
그리고 Product와 quntity를 받아 Option을 만들어내는 작업을 dto가 하는 이유가 있을까요?

OptionDto는 이름만 option과 비슷한거지 엄연히 다른 객체입니다!
지난 단계에서의 리뷰와 비슷한 내용이라고 보면 될 것 같아요~!

+이해하기 어렵다면, 해당 메서드를 Option 클래스가 가지고 있는 것과 장단점을 비교해 보는 것부터 시작하면 좋을 것 같네요.!

2024-07-19 14:41 UTC, jjongwa commented on src/test/java/gift/integration/repository/JpaProductRepositoryTest.java
> +            () -> assertThat(productList).hasSize(0)
하나만 있는 상황에서 굳이 assertAll로 감쌀 필요는 없겠네요..!

2024-07-19 14:47 UTC, jjongwa requested changes
현재 요구사항을 만족하지 못한 상황입니다!

<img width="580" alt="image" src="https://github.com/user-attachments/assets/2c2c6c11-a748-4daf-918c-68c36d064408">

해당 요구사항에 따르면, 상품을 등록할 때 기본적으로 하나의 옵션은 준비된 상태여야 하겠네요!
그리고 상품이 하나의 옵션만 가지고 있을 때 옵션 삭제 요청을 보내면 이를 막는 로직이 필요하겠구요.!

2024-07-19 15:30 UTC, ps9319 commented on src/main/java/gift/domain/Option.java
> +    Product product;
1. 일단 처음에 생각했던 건 product에서 option으로 조회할 일이 더 많을 거라고 생각해서, 일대다 단방향을 처음에 생각했습니다. 그런데 일대다 단방향은 insert후 update과정을 한 번 더 거쳐야해서 쓰지 않았습니다. 그래서 양방향을 쓸까 다대일 단방향을 쓸까 고민했는데, 양방향 연관관계를 맺으면 관리를 잘못할 것 같아서, 다대일 단방향 관계를 설정했습니다.
2. OnDeleteAction은 Product가 삭제될 때, 관련 Option들도 삭제되어야 된다고 생각해서 추가해주었습니다.

2024-07-19 15:35 UTC, ps9319 commented on src/main/java/gift/domain/Option.java
> +                throw new IllegalArgumentException("같은 이름의 옵션이 존재합니다.");
Product와 연관된 optionList의 각각의 Option을 지칭합니다. 각각의 Option의 이름과 Option을 생성하려는 요청이 들어올 때의 이름을 비교해서 중복되는 이름이 있는지 확인합니다.

2024-07-19 15:50 UTC, ps9319 commented on src/main/java/gift/domain/Option.java
> +        List<Option> optionList;
inner class를 선언할 때, 내부 클래스가 외부 클래스의 필드를 사용하는 것이 아니라면 static으로 사용해야된다고 알고 있어서 static으로 사용했습니다. 만약 static으로 선언하지 않는다면 자바의 가비지 컬렉션 기능을 이용하지 못하고 메모리 누수가 일어난다고 해서 사용했습니다. 중복된 이름이나 상품 개수를 검증하기 위해서만 만든 객체라서 Option과 비슷하지만 Option에서 Options를 사용할 일은 없다고 생각해서 static으로 선언해보았습니다.

2024-07-19 15:52 UTC, ps9319 commented on src/main/java/gift/dto/requestDTO/OptionNameUpdateRequestDTO.java
> +    }
아하...생각해보니 update 할때는 entity를 수정하기만 해도 돼서 Entity로 만들 필요가 없겠네요. 저는 혹시 몰라서 만들어놨었는데 필요없는 것 같네요 감사합니다!

2024-07-19 15:57 UTC, ps9319 commented on src/main/java/gift/dto/requestDTO/OptionCreateRequestDTO.java
넵 알겠습니다!!

2024-07-19 16:00 UTC, ps9319 commented on src/main/java/gift/domain/Option.java
> +        List<Option> optionList;
아... 저는 오히려 s로 붙은 복수형이 더 헷갈릴 수 있다고 생각했는데 자료형이 바뀔 때 생각을 못했던 것 같습니다. 필드의 네이밍에 자료형 빼겠습니다!

2024-07-19 16:01 UTC, ps9319 commented on src/test/java/gift/integration/repository/JpaProductRepositoryTest.java
> +            () -> assertThat(productList).hasSize(0)
혹시 나중에 테스트가 더 추가될 수 있다고 생각해서 assertAll로 해놨었는데, 하나만 있는 상황에서는 그냥 assertThat으로만 하는게 더 좋을까요??

2024-07-19 16:29 UTC, ps9319 commented on src/main/java/gift/dto/requestDTO/OptionNameUpdateRequestDTO.java
> +    }
저도 여기가 조금 맘에 걸리긴 했는데, Option 클래스에서 변경이 자주 일어날 수 있는 dto 클래스를 의존하는게 좋지 않다고 생각해서 Option에 선언하지 않고, dto 클래스에서 선언했습니다.

2024-07-19 17:25 UTC, ps9319 commented on src/main/java/gift/dto/responseDTO/OptionResponseDTO.java
> +    }
저번 피드백을 받고 정적 팩토리 메서드를 많이 찾아보았습니다.
보통 정적 팩토리 메서드는 
1. 객체를 생성할 때 따로 이름을 지어줄 수 있다.
2. 객체 생성을 캡슐화할 수 있다.
3. 불필요한 객체를 생성하지 않는다.
4. 자주 사용하는 객체는 캐싱할 수 있다.
5. 하위 자료형 객체를 반환할 수 있다.

사실 처음 사용한 이유는 그냥 사람들이 많이 쓰니까 썼습니다... 그런데 직접 써보면서 느낀 장점은 3번에서 불필요한 객체를 생성하지 않아도 되는 것이 정말 좋은 것 같습니다. 
1번과 2번은 인스턴스 메서드로도 충분히 느낄 수 있는 장점이지만, 3번의 장점이 정팩메의 큰 장점으로 와 닿았습니다.

만약 인스턴스 메서드로 선언했다면 아래와 같이 작성했어야되는 코드를
```
Option option = new Option(...);

OptionResponseDTO optionResponseDTO = new OptionResponseDTO();
optionResponseDTO.of(Option);
```
아래와 같이 불필요한 객체를 생성하지 않아도 돼서 편리한 것 같습니다.
```
Option option = new Option(...);

OptionResponseDTO.of(option);
```

2024-07-19 17:35 UTC, ps9319 commented on src/main/java/gift/domain/Option.java
> +    }
중복된 이름이나 상품 개수를 검증할 때 편리할 것 같아서 Options를 만들어보았습니다.
아무래도 inner class로 만들면 Option과 Options를 같이 관리하기 편할 것 같아서 inner class로 만들었습니다.
또 domain 패키지에서는 @Entity가 달린 클래스들만 만들어놓고 싶어서 inner class로 만들게 되었습니다!!

2024-07-19 17:56 UTC, ps9319 commented
따끔한 리뷰와 배려 감사합니다... 

> 그냥 다른 것과 같이 그냥 CRUD라서 어렵지 않게 작성했습니다만

이 부분에서 제가 오해되게 작성한 것 같네요... 항상 고민은 많이 하구 코드를 짜고 있는데 코드에 담기지 못한 것 같아서 아쉬워요 ㅠㅠㅠ

요구사항을 어떻게 반영해야할 지 몰라서 아래와 같이 product에 대한 옵션들을 조회할 때 옵션이 없으면 예외를 터트리게 해놓았습니다.
[edad171](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/262/commits/edad171353e22e298eb7385bc2139349adbd1724)

요구사항을 생각했을 때 Product를 생성할 때 Option도 같이 생성하게 하는 것도 생각해봤는데, Product와 Option이 항상 같이 생겨야하지 않아도 된다고 생각해서, Product의 Option들을 조회할 때 예외가 터지게 해놓았습니다. 또한 상품이 하나의 옵션만 가지고 있을 때 삭제하지 못하게 하는 것도 생각했었는데, 그럼 상품에 옵션이 하나만 있고, 그 옵션이 다른 옵션으로 교체되어야된다면 다른 옵션을 추가하고 삭제해야되는 불편함이 있다고 생각해서 그렇게 하지 않았습니다. 물론 하나만 있는 그 옵션을 수정하면 되겠지만, 그건 "수정"의 역할이 아닌 것 같아서 하나만 있을 때 삭제를 못하게 막아놓지는 않았습니다. 제가 생각했을 때 수정은 옵션의 이름을 잘못 설정했거나 바꾸고 싶을 때 사용하게 하고 싶었습니다.

2024-07-21 06:35 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +    }
>Option과 Options를 같이 관리하기 편할 것 같아서

이런 의도였다면 저도 납득이 갈 것 같습니다!ㅎㅎ 하지만 뭔가 Option이 Options를 가지고 있는 상황이 어색하다고 느낄 수도 있을 것 같아요.!

> 또 domain 패키지에서는 https://github.com/entity가 달린 클래스들만 만들어놓고 싶어서 inner class로 만들게 되었습니다!!

이 부분도 나중에 객체지향에 대한 지식이 조금 늘어나고, 프로젝트가 복잡해지게 되면 entity와 domain을 서로 분리해야 할 필요성을 느끼게 될 거라고 생각합니다.!
domain > entity의 관계라고 보면 될 것 같아요! 그래서 저도 실제 프로젝트 구조를 보면 domain 패키지 하위에 entity 패지지를 만들어 관리하는 경우가 많아요!

2024-07-21 06:37 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +    Product product;
맞아요 양방향 연관관계는 확실히 그에 따른 관리가 필요하고, 로직 상으로도 본인이 예상했던 결과가 나오는지 확인해가면서 작업을 진행해야 한다는 단점이 있습니다.!

1, 2번 모두 잘 생각해서 설정해 주신 것 같네요! 👍

2024-07-21 06:38 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +                throw new IllegalArgumentException("같은 이름의 옵션이 존재합니다.");
👍 
만약 스트림이 더 길고 복잡해지면 그냥 option이라고 명시해 가독성을 높혀주는게 좋을 수도 있어요!

2024-07-21 06:41 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +        List<Option> optionList;
오히려 static을 붙이면 GC가 관리하지 않게 됩니다~!

static으로 선언하면 해당 클래스는 런타임동한 하나의 인스턴스만을 사용하게 강제되면서 오히려 가비지 컬렉터에서 관리하지 않게 됩니다.!

자바의 장점이 가비지 컬렉터를 이용해 오랫동안 사용되지 않는 인스턴스를 알아서 삭제해 주어 메모리의 누수를 방지한다는 점이에요!

2024-07-21 06:43 UTC, jjongwa commented on src/main/java/gift/dto/requestDTO/OptionCreateRequestDTO.java
requestDto -> requestdto
패키지 이름은 모두 소문자로 작성해 주는게 컨벤션입니다!

2024-07-21 06:48 UTC, jjongwa commented on src/main/java/gift/domain/Option.java
> +        List<Option> optionList;
넵넵 나중에 보면 List<Option> 이던 객체를 Set<Option> 으로 바꿔서 사용하기도 하는 등 Collection 프레임워크 내의 자료형은 서로 유연하게 바꿔가며 사용하는 편이 많기 때문에 변수의 이름에 자료형을 넣는게 오히려 독이 될 수도 있어요!

간단히 예를 들어보면, 현재 JpaRepository에서 `List<Option> findAllByProduct(Product product);` 이런 식으로 선언해 놓은 메서드를 `Set<Option> findAllByProduct(Product product);` 이렇게 바꾸기만 해도 JPA에서 중복을 알아서 제거해 Set으로 반환해 주는데요, 

만약 여기서 메서드 이름을 `findOptionListByProduct` 이렇게 지워놨다면 나중에 List를 Set으로 바꿔야할 일이 생길 때 메서드 이름도 List -> Set으로 바꾸고, 해당 메서드를 사용하는 부분 모두 변경의 대상이 됩니다! 
변경 범위의 증가 -> 유지보수성의 증가이므로 이 부분을 생각해보면 오히려 s를 통해 약간의 추상화를 해 놓는게 합리적으로 느껴지게 될 거에요!

2024-07-21 06:52 UTC, jjongwa commented on src/main/java/gift/dto/responseDTO/OptionResponseDTO.java
> +    }
3번의 장점 느낀거 아주 좋네요!
하지만 다시 말하면 현재는 이러한 5개 장점 중 한가지밖에 사용하고 있지 못한다 - 라고도 볼 수 있겠네요! 
그래서 이러한 부분도 생각해 보며 코드를 짜보면 좋을 것 같아요!

+사실 처음에 여기가 눈에 걸린 이유는 보통 정팩메의 파라미터가 1개면 from, 2개 이상이면 of를 쓰는 컨벤션이 있어서긴 합니다.!ㅋㅋ

2024-07-21 06:55 UTC, jjongwa commented on src/test/java/gift/integration/repository/JpaProductRepositoryTest.java
> +            () -> assertThat(productList).hasSize(0)
사실 뭐 이정도는 상관 없긴 합니다! 
중요한건 결국 `혹시 나중에 테스트가 더 추가될 수 있다고 생각해서`와 같이 나중을 위해서 미리 준비해 놓을 때, **해당 코드를 다음에 다시 건드릴 사람이 본인이 아닐 수도 있다**는 거예요! 

그래서 결국 어디까지 미래의 유지보수성을 생각해야 하는가? 를 고민한다면, 이 코드를 나중에 다른 사람이 봐도 나의 의도를 알아차릴 수 있을까? 를 역으로 생각해 보는게 좋아요!
(간단히 말해, 상대방이 이해하지 못했다면 실패다.. 라고도 볼 수 있는거죠..!)

2024-07-21 07:00 UTC, jjongwa approved these changes
💯 💯 💯 
제가 남긴 리뷰에 대한 답변을 보니 민규님이 어디까지 고민해 보았는지 잘 느껴졌습니다.! 👍 
(앞으로도 이렇게.!!)

2단계도 여기서 마무리 하겠습니다! 3단계 요구사항은 많이 없으니 후딱 구현하고 리뷰 주시면 필요한 부분 조금 더 리뷰 남길께요~!

2024-07-21 07:00 UTC, merged

2024-07-21 10:39 UTC, ps9319 commented on src/main/java/gift/dto/responseDTO/OptionResponseDTO.java
> +    }
맞아요...! 저도 공부하면서 알게됐는데 이미 다 of로 네이밍을 해놓은 상태라 일단 of로 해놓고 나중에 from으로 바꾸려고 했습니다.