전남대 BE_나제법 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #263
Opened 2024-07-18 18:47 UTC by nove1080

2024-07-20 06:42 UTC, Hongdonggeon requested changes
안녕하세요 제법님
1단계는 비교적 간단하기도 하고 제법님이 잘해주셔서 크게 코멘트 드릴게 없네요!
테스트 코드도 잘 짜주셨는데, 다른 도메인의 테스트코드도 추가해주면 좋을 것 같아요!
수고하셨습니다~

2024-07-20 06:42 UTC, Hongdonggeon commented on src/main/java/gift/domain/Category.java
> +    public Category update(Category category) {
업데이트 메서드 인자로 category 객체를 전달받는 이유가 뭘까요? 
category 생성자에 따로 검증로직이 있는 것도 아닌 것 같은데요!
필드로 name, description, imageUrl, color를 전달받아도 되지 않을까요?

2024-07-20 06:42 UTC, Hongdonggeon commented on src/main/java/gift/domain/base/BaseEntity.java
> +public abstract class BaseEntity extends BaseTimeEntity {
baseTimeEntity와 baseEntity를 분리해서 상속구조로 가져간 이유가 뭘까요?
한클래스에서 선언하거나 아예 분리하거나 하는 방법도 있었을 것 같은데요!

2024-07-20 08:00 UTC, nove1080 commented on src/main/java/gift/domain/Category.java
> +    public Category update(Category category) {
```java
public Category update(String name, String description, URL imageUrl, Color color)
public Category update(Category category)
```
두 가지 중 고민을 해보았었는데 이후에 업데이트할 필드가 많아지면 메서드 호출부가 지저분해질 것 같아 객체로 전달하도록 하였습니다

2024-07-20 08:41 UTC, nove1080 commented on src/main/java/gift/domain/base/BaseEntity.java
> +public abstract class BaseEntity extends BaseTimeEntity {
### 1. `BaseTimeEntity`와 `BaseEntity`를 한 클래스로 선언하지 않는 이유
***
레코드의 생성 시간과 수정 시간은 모든 테이블에 대해 적용하고 싶었고 
생성자(`@CreateBy`)와 수정자(`@LastModifiedBy`)의 경우에는 굳이 기록할 필요가 없는 데이터에는 적용하고 싶지 않아서 분리하였습니다. (예를 들면 회원 테이블의 경우 본인이 생성하고 수정하는게 굳이 기록할 필요가 있을까? 라고 생각되어 분리하였습니다)

추가로 궁금한 점이 있는데 만약에 회원(Member) 레코드에도 생성자와 수정자를 추가하게 된다면, 회원가입을 통해 발생하게 되는데 생성자와 수정자를 알아낼 수 있는 방법을 모르겠습니다. 현재는 서버로 요청 시, accessToken 값을 가지고 사용자가 누구인지 식별하는데 회원가입의 경우에는 로그인을 하지 않은 사용자가 수행하게 되므로 accessToken을 가지고 있지 않아 생성자와 수정자를 채워줄 수 없을 것 같습니다 ㅜㅜ 제가 생성자와 수정자를 채우는 방법을 잘못 구현한건지 혹시 다른 좋은 방법이 있을까요?

### 2. `BaseTimeEntity`와 `BaseEntity`를 아예 분리하지않고 상속구조로 만든 이유
***
```java
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @CreatedDate
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @CreatedBy
    @Column(nullable = false, updatable = false)
    private Long createdBy;

    @LastModifiedBy
    @Column(nullable = false)
    private Long updatedBy;
}
```
```java
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseTimEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @CreatedDate
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(nullable = false)
    private LocalDateTime updatedAt;

}
```
상속을 하지 않으면 이런식으로 id, createdAt, updatedAt 필드의 중복이 발생하여 코드의 중복을 없애기 위해 사용하였습니다
그리고 개념적으로도 `BaseEntity`는 기존에 id, createdAt, updatedAt 만 존재하는 클래스 에서 생성자와 수정자라는 필드를 추가하여 확장한 클래스라고 생각하여 상속을 통해 관계를 명시하였습니다

2024-07-20 08:42 UTC, nove1080 commented
> 안녕하세요 제법님 1단계는 비교적 간단하기도 하고 제법님이 잘해주셔서 크게 코멘트 드릴게 없네요! 테스트 코드도 잘 짜주셨는데, 다른 도메인의 테스트코드도 추가해주면 좋을 것 같아요! 수고하셨습니다~

피드백은 https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/329 PR에서 반영할 수 있도록 하겠습니다!

2024-07-21 04:34 UTC, Hongdonggeon commented on src/main/java/gift/domain/base/BaseEntity.java
> +public abstract class BaseEntity extends BaseTimeEntity {
생성자와 수정자를 기록하지 않아도 되는 데이터들에 대해서 분리하고 싶었던 거였군요! 의도 잘 알았습니다
제법님 말처럴 회원가입할때는 데이터가 생성되기 전이여서 cratedBy를 기록하지 못하겠네요. 
근데 꼭 생성자, 수정자에 회원만 들어가진 않고 서비스 (실사용 서비스, 어드민 ...) 를 기록하기도 해요 
이 데이터가 어드민으로 변경된건지, 실제 운영하는 서비스에서 회원이 변경된건지 등등의 케이스를 구분하기 위해서요!

2024-07-21 04:35 UTC, Hongdonggeon approved these changes
제법님 안녕하세요!
리뷰 반영하느라 수고 많으셨습니다
1단계는 머지할게요!

2024-07-21 04:35 UTC, merged