경북대 BE_김은선 4주차 과제 (0단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #265
Opened 2024-07-18 23:08 UTC by eunsoni

안녕하세요!

이번주에 자격증 시험이 있었어서 0단계 PR이 많이 늦었습니다 !ㅜ

이번주에는 피드백주신 것들 위주로 업데이트 해보았습니다. 

0단계에서 업데이트한 내용들은 Read.me에 적어놓았습니다.

추가적으로 기존 위시리스트 상품 추가 구현이 부실해서(클라이언트단에서 상품을 담지 못하고 디비에서 담아서 보여주는 방식), 

user용 상품 목록을  추가 구현하였습니다. (기존에는 상품 목록이 하나라서 관리자용 페이지와 함께 사용함)

2024-07-19 16:07 UTC, gongdongho12 requested changes
0단계, 1단계 같이올라와서 구분을 따로 못드렸네요

4주차 시작 화이팅입니다 💪🏼

2024-07-19 16:07 UTC, gongdongho12 commented on src/main/java/gift/controller/AdminController.java
> +        }
이부분 지금은 계정 하나라 큰 문제가 아니겠지만 나중에 ROLE으로 ADMIN 타입 체크하는게 정확한 구분이지 않을까요?

2024-07-19 16:07 UTC, gongdongho12 commented on src/main/java/gift/dto/Role.java
> +    }
중간중간 유효성 검사 👍🏼

2024-07-19 16:07 UTC, gongdongho12 commented on src/main/java/gift/entity/Member.java
> +    private List<Wishlist> wishlists;
DAO에서 join 객체는 LAZY로 필요할떄만 조회해두시는게 좋지 않을까요?

2024-07-19 16:07 UTC, gongdongho12 commented on src/main/java/gift/filter/JwtTokenFilter.java
> +        }
minor) 이런 미사용 부분은 지워주면 좋을 것 같아요!

2024-07-19 16:07 UTC, gongdongho12 commented on src/main/java/gift/repository/WishlistRepository.java
> +    Page<Wishlist> findByMemberEmail(String email, Pageable pageable);
이런 부분은 email이라는 연관객체 보다는 실제 wishlist의 멤버 아이디로 조회해야 더 리소스 절약해서 조회할 수 있지 않을까요?

2024-07-19 16:07 UTC, gongdongho12 commented on src/main/java/gift/repository/WishlistRepository.java
> +    Wishlist findByMemberEmailAndProductId(String email, Long productId);
여기두요!

2024-07-19 16:07 UTC, gongdongho12 commented on src/main/java/gift/repository/WishlistRepository.java
> +    Page<Wishlist> findByMemberEmail(String email, Pageable pageable);
멤버 서비스에서 이메일 -> 아이디 조회 -> 위시리스트 조회 형식으로요!

2024-07-19 16:07 UTC, gongdongho12 commented on src/main/java/gift/service/MemberService.java
> +        Member member = memberRepository.findByEmail(email);
이걸 이 서비스의 getMember 메서드 호출하면 더 정확하게 조회 가능하지 않을까요?

2024-07-19 16:07 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +    private CategoryRepository categoryRepository;
상품 서비스 도메인인데 카테고리 레포지토리까지 있으면 관리하는 도메인이 두개가 되버리는데요

이부분은 카테고리 서비스로 대체해보면 어떨까요?
ex) 아래에 카테고리 가져오는 부분들이 많은데 그런 부분을 서비스 메서드로 통일해 나갈 수 있을 거구요!

2024-07-19 18:18 UTC, eunsoni commented on src/main/java/gift/entity/Member.java
> +    private List<Wishlist> wishlists;
넵 처리해두었습니다!

2024-07-19 18:19 UTC, eunsoni commented on src/main/java/gift/filter/JwtTokenFilter.java
> +        }
넵 !!

2024-07-19 18:21 UTC, eunsoni commented on src/main/java/gift/service/MemberService.java
> +        Member member = memberRepository.findByEmail(email);
오 그렇네요!

2024-07-20 00:24 UTC, eunsoni commented on src/main/java/gift/service/ProductService.java
> +    private CategoryRepository categoryRepository;
서비스들 모두 레포지토리(도메인) 한 개가 되도록 수정해놓았습니다!

2024-07-20 00:45 UTC, eunsoni commented on src/main/java/gift/repository/WishlistRepository.java
> +    Page<Wishlist> findByMemberEmail(String email, Pageable pageable);
서비스, 레퍼지토리 수정했습니다!

2024-07-20 00:57 UTC, eunsoni commented on src/main/java/gift/controller/AdminController.java
> +        }
넵 적용해두었어요!

2024-07-20 11:12 UTC, gongdongho12 approved these changes
작업 고생 많으셨습니다 2단계 작업도 화이팅입니다!

2024-07-20 11:12 UTC, merged