경북대 BE_도기헌 4주차 과제 (2단계, 3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #268
Opened 2024-07-19 03:26 UTC by Dockerel

안녕하세요! 이번 2단계 과제는 상품 정보에 옵션을 추가하는 것이었습니다.

상품과 옵션에 ManyToMany 관계를 적용해보았고, 개인적으로 다음 두 기능을 구현하는데 많은 시간을 들였습니다!

1. 상품에는 항상 하나 이상의 옵션이 있어야 한다.
&rarr; 1단계의 방식과 비슷하게 defaultOption을 생성해놓고 product 생성 시 자동으로 해당 옵션을 포함하게 하였습니다. 그리고 product에서 option 삭제 시 option의 개수가 1개 밑으로 내려가지 않도록 검사해서 구현하였습니다!
2. 중복된 옵션은 구매 시 고객에게 불편을 줄 수 있다. 동일한 상품 내의 옵션 이름은 중복될 수 없다.
&rarr; for문으로 순회하며 비효율적으로 검사해야할지 고민했는데, 결국 stream의 anyMatch로 구현해보았습니다.

그리고 이번에 product - option 관련 서비스단에 위의 중요한 로직들이 포함되어 한번 test에서 MockBean을 사용하여 테스트를 작성해보았는데 그 부분도 한번 봐주시면 좋겠습니다! 

---

안녕하세요~! 2단계와 3단계를 따로 낼까 하다가 3단계에 크게 복잡한 로직이 없어서 같이 제출하게 되었습니다.

이번 3단계 과제는 옵션에 수량(quantity)를 지정된 숫자(amount)만큼 빼는 기능을 구현하였습니다. 기능 요구사항에 해당 기능이 추후 사용될 예정이니 별도의 HTTP API를 만들 필요는 없다고 되어 있어서 간단하게 option entity에서 빼는 기능과 service 클래스에서 빼기가 가능한지(amount<quantity인지 확인) 확인하는 기능만 추가하고 간단하게 테스팅 해보았습니다.

감사합니다~! 😆

2024-07-19 16:53 UTC, gongdongho12 requested changes
와우 2, 3단계 한꺼번에 제출해주셨네요
고생많으셨습니다 💯 

> 상품에는 항상 하나 이상의 옵션이 있어야 한다.
→ 1단계의 방식과 비슷하게 defaultOption을 생성해놓고 product 생성 시 자동으로 해당 옵션을 포함하게 하였습니다. 그리고 product에서 option 삭제 시 option의 개수가 1개 밑으로 내려가지 않도록 검사해서 구현하였습니다!
중복된 옵션은 구매 시 고객에게 불편을 줄 수 있다. 동일한 상품 내의 옵션 이름은 중복될 수 없다.
→ for문으로 순회하며 비효율적으로 검사해야할지 고민했는데, 결국 stream의 anyMatch로 구현해보았습니다.

이부분 옵션의 name과 product_id에 복합 unique 키 적용해보면 어떨까요?
[힌트](https://why-dev.tistory.com/362) 스윽 소매넣기 하구갑니당

2024-07-19 16:53 UTC, gongdongho12 commented on src/main/java/gift/controller/rest/CategoryController.java
> +        return ResponseEntity.ok().body(response);
메시지 출력이 이곳만 사용하면 이렇게 써도 무방한데 N회 반복되면 메시지용 클래스 만들어두면 어떨까요?
이 PR에만 두번이상 보여서요

2024-07-19 16:53 UTC, gongdongho12 commented on src/main/java/gift/entity/OptionDTO.java
> +    private int quantity;
다른 것과 달리 하이버네이트 밸리데이션은 DAO만 동작합니다!
`org.hibernate.validator.constraints.Length;`

2024-07-19 16:53 UTC, gongdongho12 commented on src/main/java/gift/entity/Product.java
> +    private List<ProductOption> productOption = new ArrayList<>();
연관관계에는 그래도 Lazy 걸어서 불필요한 호출을 방지할 수 있게 예방하는 습관을 주시는게 어떨까요?

2024-07-19 16:53 UTC, gongdongho12 commented on src/main/java/gift/exception/advice/UnacceptableAdvice.java
> +}
기존에 사용하던 컨트롤러 어드바이스에 추가하지 않고 분리하신 사유가 있을까요?
결국 에러처리 용도인데 비슷한 도메인 단위로 묶어둔 느낌은 아닌 것 같고 길이가 엄청 길지도 않아서요

2024-07-19 16:53 UTC, gongdongho12 commented on src/main/java/gift/entity/Option.java
> +    private int quantity;
궁금한게 결국 옵션과 상품 옵션은 1:1 관계인데 억지로 두개의 테이블로 분리한 상황 아닐까요?

2024-07-19 16:53 UTC, gongdongho12 commented on src/test/java/gift/service/OptionServiceMockTest.java
> +                .isThrownBy(() -> productService.deleteProductOption(1L, 1L));
이부분 when 주석 놔두고 전부 given에 들어가있네요 ㅎㅎ...

로직 자체는 잘 구성해주셨습니다 👍🏼

2024-07-19 16:53 UTC, gongdongho12 commented on src/test/java/gift/service/OptionServiceTest.java
> +                () -> optionService.subtract(saved.getId(), 100));
이런 Exception은 직접 구성한게 아니다보니 메시지 레벨까지 체크하면 좋지 않을까요?

2024-07-20 02:16 UTC, Dockerel commented on src/main/java/gift/controller/rest/CategoryController.java
> +        return ResponseEntity.ok().body(response);
아하 넵! 지금 보니 해당 로직이 생각보다 많이 반복되었네요 ReponseUtility로 빼서 개선하였습니다!

2024-07-20 02:19 UTC, Dockerel commented on src/main/java/gift/entity/OptionDTO.java
> +    private int quantity;
아하 그렇군요! 그런데 entity 테스트에서 확인했을 때는 하이버네이트 밸리데이션인 Length가 DTO에서 작동하는 것을 확인할 수 있었는데 이건 @SpringBootTest로 스프링 컨테이너를 띄워서 테스트했기 때문일까요?

2024-07-20 02:24 UTC, Dockerel commented on src/main/java/gift/entity/Product.java
> +    private List<ProductOption> productOption = new ArrayList<>();
아하 넵! 그런데 xxxToMany의 경우 defaultFetchType이 Lazy로 되어 있는걸로 아는데 명시적으로 적어놓는게 나을까요??

2024-07-20 02:26 UTC, Dockerel commented on src/main/java/gift/exception/advice/UnacceptableAdvice.java
> +}
결국 에러 처리 용도이긴 한데 구현 당시에 에러의 성격이 다른것 같아 분리하게 되었습니다! 혹시 어드바이스 계열은 보통 분리를 잘 하지 않는 편인가요?

2024-07-20 02:29 UTC, Dockerel commented on src/main/java/gift/entity/Option.java
> +    private int quantity;
옵션과 상품을 말하시는거죠? 제가 생각하기엔 옵션과 상품이 n:m 관계가 될 수 있을 것 같습니다. 한 상품에 여러 옵션이 들어갈 수 있고 한 옵션 또한 여러 상품에 들어갈 수 있기 때문입니다. 예를 들어 상품1, 상품2를 같이 파는 페이지와 상품1만 파는 페이지에 대해 상품1의 옵션 재고 관리가 동시에 들어가야 한다고 생각했기 때문입니다!

2024-07-20 02:38 UTC, Dockerel commented on src/test/java/gift/service/OptionServiceMockTest.java
> +                .isThrownBy(() -> productService.deleteProductOption(1L, 1L));
아하... when() 로직이 when에 들어갔어야 했겠군요 ㅋㅋㅋㅋㅋㅜㅜㅜ
![image](https://github.com/user-attachments/assets/aaf4740b-a006-4050-9efc-bc8b4ded2899)
지난 라이브 강의에서 BDDMockito를 사용하실 때 given()을 //given 에 작성하셔서 비슷하게 해보았는데 그냥 Mockito 테스트 시에는 when을 when에 넣는게 낫겠죠...?

2024-07-20 02:58 UTC, Dockerel commented on src/test/java/gift/service/OptionServiceTest.java
> +                () -> optionService.subtract(saved.getId(), 100));
아하 그러면 훨씬 철저하게 테스팅을 할 수 있겠군요! 각 exception의 메시지까지 체크해놓았습니다. 다만 위에서 소매넣기 해주신 힌트로 구현한 한 상품에 중복 option name 금지 기능은 DataIntegrityViolationException을 반환하고 특별한 message를 반환하지 않아 따로 체크하지 않았습니다~!😆

2024-07-20 03:30 UTC, Dockerel commented on src/main/java/gift/exception/advice/UnacceptableAdvice.java
> +}
아하 지금 보니 막 에러의 성격이 막 다른 것 같지도 않은데 분리를 해놓았군요! 하나로 합쳐두고 여기도 JSON 형태로 리턴하게 리펙터링 해보았습니다~!

2024-07-20 07:18 UTC, gongdongho12 commented on src/main/java/gift/entity/Option.java
> +    private int quantity;
상품에 옵션 여러개는 이미 들어가는데요
말씀주신 내용은 상품 그룹이지 옵션이 여러개 생기는 방식이 아니여서요

쿠팡을 예시로 들면
상품 A - 옵션 1, 2, 3
상품 B - 옵션 4, 5, 6
형식이지
상품 C - 옵션 1, 2, 4
를 쓰지는 않아요

2024-07-20 07:21 UTC, gongdongho12 commented on src/main/java/gift/entity/OptionDTO.java
> +    private int quantity;
그렇다 하더라도 컨벤션 상 이곳만 이렇게 쓰면 나중에 다 똑같은 객체로 인식할 수 있는데
https://stackoverflow.com/questions/68231771/how-can-i-validate-the-string-length-using-java-spring-validation jakarta validation에서 제공하는 기능을 사용하는게 낫지 않을까요?

2024-07-20 10:14 UTC, Dockerel commented on src/main/java/gift/entity/Option.java
> +    private int quantity;
아.....으으음..그러면 상품과 옵션이 OneToMany 관계로 매핑된다는 걸까요...? 사실 저는 아직도 이해가 잘 안됩니다. 
![image](https://github.com/user-attachments/assets/71eaaa76-6b87-4274-9d0c-add8be1b6f68)
과제 링크에서 제시해준 자료에 의하면 상품의 옵션을 조회했을 때 name과 quantity를 포함한 옵션을 **하나 이상** 리턴하는데 이는 상품의 색상 등을 선택할 수 있는 옵션이라 생각하였습니다.

예를 들어 product에는 다음과 같은 내용이 들어있을 것입니다.
```
{
    "id" : 1,
    "name" : "키보드A 색상 2종",
    "price" : 20000,
    "imageurl" : "뭐시기1.com",
    "categoryid" : 1
}
```
그리고 위 상품에 매핑되어 있는 옵션은 다음과 같을 것입니다.
```
[
{
    "id":2,
    "name":"keyboardA-white",
    "quantity":500
},
{
    "id":2,
    "name":"keyboardA-black",
    "quantity":1000
}
]
```
그럼 상품과 옵션에 대해 OneToMany 관계가 성립하고
만약 아래와 같은 product가 따로 있으면
```
{
    "id" : 1,
    "name" : "키보드A 화이트 색상",
    "price" : 20000,
    "imageurl" : "뭐시기2.com",
    "categoryid" : 1
}
```
위 상품에 대한 옵션은 다음과 같을 것입니다.
```
[
{
    "id":2,
    "name":"keyboardA-white",
    "quantity":500
}
]
```
실제로 네이버 쇼핑에서 다음과 같은 상황을 보았고 그런 상황을 고려하여 구현하였습니다. 하지만 멘토님이 말하신대로 제가 앞에서 말한 내용이 상품의 그룹을 말하고 있을 수 있다고도 충분히 생각이 가능할 것 같긴 합니다. 

하지만 말하신대로
```
상품 A - 옵션 1, 2, 3
상품 B - 옵션 4, 5, 6
상품 C - 옵션 1, 2, 4
```
는 불가능할지라도
```
상품 A - 옵션 1, 2, 3
상품 B - 옵션 1
```
형태로 구현이 가능하지 않을까요? 그러면 결론적으로 옵션과 상품간에도 OneToMany 관계가 가능해져 결국 ManyToMany로 가능할 것이라 생각하였습니다.

2024-07-20 10:17 UTC, Dockerel commented on src/main/java/gift/entity/Option.java
> +    private int quantity;
제가 생각한 product 객체 하나는
![image](https://github.com/user-attachments/assets/5d88d5cf-371d-4671-af1c-c75443262678)
위 이미지와 같이 여러 제품을 하나의 name으로 보여주고 옵션으로 그레이, 블랙, 그린 등을 보여주는 형태입니다!

2024-07-20 10:24 UTC, Dockerel commented on src/main/java/gift/entity/OptionDTO.java
> +    private int quantity;
오오오 컨벤션 상으로도 말씀하신 jakarta validation으로 일치시키는 것이 나을 것 같습니다! 해당 기능으로 바꾸겠습니다~!

2024-07-20 11:13 UTC, gongdongho12 commented on src/main/java/gift/entity/Product.java
> +    private List<ProductOption> productOption = new ArrayList<>();
지금 말구 나중에는 혼자 개발하는게 아니니까 중요한 이부분은 저는 명시적으로 표현하는게 좋을 것 같아요 😄

2024-07-20 11:15 UTC, gongdongho12 commented on src/main/java/gift/entity/Option.java
> +    private int quantity;
제가 현재 커머스관련 업무를 진행하지만
상품 A의 옵션명이랑 상품 B의 옵션을 실제로 매칭해서 관리하는 케이스를 못 보기는 했지만
이런 목적으로 나중에 사용한다면 그럴 수는 있긴 하겠네요...

실 서비스를 개발 해 나가는 것 보다는 프로젝트에 하나씩 적용하는 관점이라면 의견대로 잘 구현해주신 것 같습니다

2024-07-20 11:16 UTC, gongdongho12 commented on src/test/java/gift/service/OptionServiceMockTest.java
> +                .isThrownBy(() -> productService.deleteProductOption(1L, 1L));
넵 저는 그렇게 생각했습니다!
when 써놓고 when은 따로 써두는 느낌이라서요

2024-07-20 11:35 UTC, Dockerel commented on src/main/java/gift/entity/Product.java
> +    private List<ProductOption> productOption = new ArrayList<>();
아하 나중에 팀원과도 같이 개발하는 것을 고려해야 하겠군요! 😅

2024-07-20 11:37 UTC, Dockerel commented on src/main/java/gift/entity/Option.java
> +    private int quantity;
아하 현업에서는 이런식으로 관리하지 않는군요..! 다음에 멘토링 할 때 그런 부분에 대해서도 들어보고 싶어요!😊 감사합니다~!

2024-07-20 13:14 UTC, Dockerel commented on src/main/java/gift/entity/Product.java
> +    private List<ProductOption> productOption = new ArrayList<>();
FetchType.LAZY 모두 표현해놓았습니다! 🥹

2024-07-20 14:06 UTC, gongdongho12 approved these changes
PR내용 잘 반영된 것 확인했습니다
4주차 기간동안 고생하셨습니다 💯

2024-07-20 14:06 UTC, merged