경북대 BE_이지호 4주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #277
Opened 2024-07-19 06:14 UTC by GitJIHO

> 3단계 미리 제출합니다!

**코드 작성하면서 어려웠던 점**
---

- 3단계 요구사항이나 구현 자체가 2단계와 유사한 부분이 많아서 3단계 자체는 그렇게 어렵지 않았지만, 2단계에서 update를 구현할 때 멘토님께서 말씀해주신 변경감지를 활용하여 작성해보았습니다. 아직 2단계(https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/198) 에 대한 코멘트를 받지 못하여 혹시 2단계에 제가 수정한 변경감지 관련 코드에 문제가 있다면 3단계의 코드도 동일한 문제가 생길 것 같습니다. 기능은 정상 작동합니다! 2단계 코멘트 기반으로 수정사항 있다면 3단계도 추가로 수정하도록 하겠습니다 😄

**코드 리뷰 시, 멘토님이 중점적으로 리뷰해주셨으면 하는 부분**
---

- dto중 레코드로 선언해준 클래스가 몇개 있는데, 적절히 사용한건지 궁금합니다. 또한 다른 dto나 클래스 중에서도 레코드로 표현하면 좋을만한 것들이 있을까요?

2024-07-21 17:11 UTC, sang5c requested changes
4주차 고생하셨습니다.  
반드시 고민해보고 넘어가야 하는 부분들이 있어 request change를 드려요.  

> setter 사용 구분?  

절대 사용하지 말아야 한다는 의미는 아닙니다.  
현재 하나의 dto를 모든 곳에서 사용하고 있는데 어디서 사용하는지에 따라 DTO를 구분해보면 진짜 필요한 곳에서만 setter가 사용될 수 있을 것 같습니다.

> setSkipOptionCheck

사용하면 안되는 이유에 대해 리뷰 남겼으니 확인해주세요.  
상품 생성시점에 option이 반드시 같이 생성되어야 한다면 request자체에 담겨 오는게 가장 이상적이라고 생각됩니다.  
이부분도 request별로 dto를 분리해보면 어떨까요?  

> rebase...

origin과 upstream을 어떻게 설정하셨는지 모르겠지만, 다음 기준으로 설명드립니다.  
- upstream: kakao-tech-campus-2nd-step2
- origin: GitJIHO
- 3단계가 머지되고 4단계를 수행해야 하는 상태  

3단계 PR 머지가 완료된 후 -> upstream/gitjiho fetch를 수행하고 -> upstream/gitjiho를 대상으로 rebase를 수행해야 합니다.  

> ifPresentOrElse  

ifPresentOrElse 사용이 필수가 아닙니다. 어떤 상황인지 코드 예시랑 어떤 결과를 반환하고자 했는지 남겨주시면 확인해볼게요! 

> 변경감지  

작성하신 코드가 의도한 내용이 맞습니다!  

---

추가로, getter가 무분별하게 사용되고 있습니다. 의식적으로 연습하는게 어렵다면 getter를 만들지 말고 코드를 작성하기 시작해보면 어떨까요?

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/CategoryService.java
>          }
JPA 2단계의 힌트를 보고 데이터 중심의 개발을 하고있는게 아닐지 고민해보세요 :)

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/CategoryService.java
> +        categoryRepository.findById(id).orElseThrow(
find 후 값을 사용하지 않는다면 exists 쿼리로 교체해보면 어떨까요?

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/CategoryService.java
> +        Category category = categoryRepository.findById(id).orElseThrow(
점 앞에서 개행해주면 가독성이 좋아집니다.  
.orElseThrow 앞에서 개행해주세요

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +                (excludeOptionId == null || !option.getId().equals(excludeOptionId)));
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +        product.getOptions().remove(option);
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +        if (product.getOptions().size() <= 1) {
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +        if (!option.getName().equals(request.getName())) {
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +        boolean duplicate = product.getOptions().stream()
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/entity/Option.java
> +    public Option() {
모든 entity의 default 생성자를 protected로 변경해주세요.

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +        checkDuplicateOptionName(product, request.getName(), null);
35번라인을 누락하면 버그가 생길 것 같아요.  
option이 추가되거나 변경될 때마다 반드시 수행되어야 하는 코드인데 객체가 책임을 갖고 수행하도록 바꿔보면 어떨까요?
https://www.baeldung.com/java-anemic-vs-rich-domain-objects

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +    private Boolean skipOptionCheck = false;
스프링 빈으로 등록되고 나면 ProductService에서 setSkipOptionCheck 변수를 공유하기에 어드민에 2명 이상이 접속해서 작업하거나 여러 요청이 동시에 들어오면 치명적인 버그가 발생합니다.  
하나의 스레드에서 해당 옵션을 true로 변경하면 모든 스레드가 validation 체크를 수행할 수 없습니다. (키워드: thread safety)

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +        if (!skipOptionCheck && (product.getOptions() == null || product.getOptions()
`규칙 9: getter/setter/프로퍼티를 쓰지 않는다.`

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/entity/Option.java
> +    Product product;
의도하신게 아니라면 접근제어자를 생략하지 말아주세요!

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +        productRepository.findById(productId)
return 값을 사용하지 않는다면 exists 사용을 고려해주세요.

2024-07-21 17:11 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +        Option option = optionRepository.findById(id)
findByProductId를 사용하지 않고, product를 찾고 option을 다시 찾는 순서로 수행하는 이유가 무엇인가요? 🤔

2024-07-22 05:28 UTC, GitJIHO commented on src/main/java/gift/service/CategoryService.java
>          }
entity에 검증 메서드를 추가해서 수정해봤습니다!

2024-07-22 05:35 UTC, GitJIHO commented on src/main/java/gift/service/CategoryService.java
> +        categoryRepository.findById(id).orElseThrow(
아하 좋은 방법인 것 같습니다. 해당 부분은 검증 데이터 참조를 위해 리턴값을 사용하였고, OptionsService에서 subtractOptionQuantity 메서드중 리턴값을 쓰지 않는 부분을 exists 쿼리로 교체하였습니다.

2024-07-22 05:56 UTC, GitJIHO commented on src/main/java/gift/entity/Option.java
> +    public Option() {
변경하고 기본생성자를 사용하는 product의 경우 factory를 만들어주었는데 맞을까요?

2024-07-22 06:06 UTC, GitJIHO commented on src/main/java/gift/service/OptionService.java
> +        Option option = optionRepository.findById(id)
다른 옵션 조작 경로와 마찬가지로 subtract도 productId와 옵션 id를 PathVariable로 받는 방식을 선택하였습니다.
두개의 인자가 들어오기 때문에 해당 두 인자를 최대한 활용하는것이 좋다 생각하였고, 각각 예외처리도 쉽게 나타낼 수 있기 때문에 해당 방식으로 나태내었습니다.

findByProductId를 사용하면 productId에 해당하는 옵션들이 여러개가 리턴될 것이라 생각해 어차피 여러 옵션중에서 id에 해당하는 옵션을 다시 골라야 하는 과정을 거쳐야 한다고 생각하였습니다.
또한 findByProductIdAndId 등과 같이 두개의 인자를 받아 한번에 정확한 옵션을 리턴하는 메서드도 고려해보았지만, 해당 방식으로는 product가 없는 경우와 option이 없는 경우의 오류를 분리하여 던지기 복잡하다 생각하여 선택하지 않았습니다!

2024-07-22 10:29 UTC, GitJIHO commented on src/main/java/gift/service/OptionService.java
> +        checkDuplicateOptionName(product, request.getName(), null);
DTO와 엔티티로 로직을 내렸습니다!

2024-07-22 17:25 UTC, GitJIHO commented
**수정사항**
---

- 엔티티에 메서드를 추가하여 rich-domain방식으로 진행하였습니다.
- 상품 생성 DTO를 분리하여 상품을 생성시 최소 하나의 옵션을 입력받도록 하였습니다.
- 상품의 옵션 이름 중복 검증을 DTO와 entity단으로 내렸습니다. 리스트로 옵션을 입력받는 ProductCreateRequest에서는 커스텀 어노테이션을 통해 입력 항목에 대한 중복여부를 검증하였고, 다른 일반적인 상황에 대해서는 Option entity에 JPA 관련 어노테이션을 활용한 검증 로직을 넣었습니다.
- entity Getter을 사용한 부분들에 역할에 맞는 메서드를 생성하여 바꿔주었습니다.
- 추가된 entity 메서드들에 대해 entity 테스트코드를 추가하였고, 옵션 관련한 E2E 테스트를 추가하였습니다.
- 어드민페이지의 상품 생성 부분을 분리된 DTO에 맞게 수정해주었습니다.

2024-07-23 13:03 UTC, sang5c commented on src/main/java/gift/service/OptionService.java
> +        product.removeOption(option);
removeOption() 내부에서 67-69 라인을 수행해주면 누락될 염려 없이 비즈니스 요구사항을 만족할 수 있습니다.

2024-07-23 13:03 UTC, sang5c commented on src/main/java/gift/entity/Option.java
> +        boolean duplicate = product.sortAndBringOptions().stream()
sortAndBringOptions()도 결국 getter의 역할을 수행하고 있습니다.  
`product에서 options를 가져와서 순회하며 이름이 같은 것들을 찾는다`  

getter 대신 product가 직접 로직을 수행해보면 어떨까요?

2024-07-23 13:03 UTC, sang5c commented on src/main/java/gift/entity/Option.java
> +    public Option() {
클라이언트와 상호작용하는 부분을 DTO로 변경해보시면 좋겠네요.  
DTO가 무엇인지 다시 한 번 고민해보세요 :)

2024-07-23 13:11 UTC, sang5c approved these changes
마지막 질문은 리뷰로 답변 남겼습니다.  
혹시 리뷰나 피드백이 더 필요하면 DM을 보내시거나 새로 PR을 만드셔도 좋습니다~

2024-07-23 13:11 UTC, sang5c commented on src/main/java/gift/service/ProductService.java
> +        return product;
작성하신 코드 내에서 product가 가진 options에 추가해주는 작업을 해주지 않으셨어요! 그래서 getOptions()를 호출해도 빈 리스트를 반환하는 상태입니다.

2024-07-23 13:11 UTC, merged

2024-07-23 13:39 UTC, GitJIHO commented on src/main/java/gift/entity/Option.java
> +        boolean duplicate = product.sortAndBringOptions().stream()
```
    @PrePersist
    @PreUpdate
    private void checkDuplicateOptionNames() {
        for (Option option : options) {
            boolean duplicate = options.stream()
                .anyMatch(o -> o.sameName(option.getName()) && !o.equals(option));
            if (duplicate) {
                throw new DuplicateOptionNameException("상품에 이미 동일한 옵션 이름이 존재합니다: " + option.getName());
            }
        }
    }
```

이런식으로 넣었는데 작동을 안하네요 ㅠ

2024-07-23 13:50 UTC, GitJIHO commented on src/main/java/gift/service/ProductService.java
> +        return product;
추가를 해주면 중복추가가 될 줄 알았는데 그러지않고 원하는 결과가 잘 나오네요!! 감사합니다