충남대 BE_이택 4주차 과제 step2
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #287
Opened 2024-07-19 06:58 UTC by LeeTaek2T

2024-07-20 03:50 UTC, ksy90101 requested changes
간단한 피드백을 드렸습니다~
수정부탁드려요!
궁금한게 있다면 언제든 DM주세요!

2024-07-20 03:50 UTC, ksy90101 commented on src/main/java/gift/Controller/OptionController.java
> +  @DeleteMapping("products/{id}/options")
이런경우 이 id가 products의 id인지 알기가 어려울거 같아요.
그래서 이런 경우엔 productId라고 명시해두긴 합니다!

2024-07-20 03:50 UTC, ksy90101 commented on src/main/java/gift/Controller/OptionController.java
> +    return ResponseEntity.ok(optionDto);
삭제할땐 reponse를 잘 내려주진 않아요...
그래서 no_content로 하는 편이빈다.
삭제된 id를 내려주는게 의미가 있을지 고민해보시면 좋을거 같습니다.

2024-07-20 03:50 UTC, ksy90101 commented on src/main/java/gift/DTO/Option.java
> +public class Option {
중복된 옵션은 구매 시 고객에게 불편을 줄 수 있다. 동일한 상품 내의 옵션 이름은 중복될 수 없다.


해당 부분 처리가 안되어 있는거 같아요?

2024-07-20 03:50 UTC, ksy90101 commented on src/main/java/gift/DTO/Option.java
> +public class Option {
이제 entity에도 validate를 해보면 어떨까요?

2024-07-20 03:50 UTC, ksy90101 commented on src/main/java/gift/Service/OptionService.java
> +public class OptionService {
한번 이제 서비스 테스트 코드도 작성해보시면 어떨까요?

2024-07-20 03:50 UTC, ksy90101 commented on src/main/java/gift/Repository/OptionRepository.java
> +package gift.Repository;
패키지명을 파스칼 케이스로 적지 않습니다 ㅠㅠ

2024-07-20 07:18 UTC, LeeTaek2T commented on src/main/java/gift/Controller/OptionController.java
> +  @DeleteMapping("products/{id}/options")
네! 알겠습니다

2024-07-20 07:23 UTC, LeeTaek2T commented on src/main/java/gift/Controller/OptionController.java
> +    return ResponseEntity.ok(optionDto);
저렇게 하는 습관을 바꿔보겠습니다...!

2024-07-20 07:42 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Option.java
> +public class Option {
해당 클래스의 name 변수에 unique옵션을 주어 해당 부분을 처리하게 했었습니다.
작동여부를 봤을 때도 중복되는 이름이 들어가지 않았습니다.

2024-07-20 07:49 UTC, LeeTaek2T commented on src/main/java/gift/Repository/OptionRepository.java
> +package gift.Repository;
네! 해당 부분 수정하겠습니다!

2024-07-20 12:57 UTC, LeeTaek2T commented on src/main/java/gift/Service/OptionService.java
> +public class OptionService {
네! 서비스 테스트 코드도 작성해보겠습니다

2024-07-20 12:58 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Option.java
> +public class Option {
알겠습니다!!

2024-07-20 12:58 UTC, LeeTaek2T commented on src/main/java/gift/Repository/OptionRepository.java
> +package gift.Repository;
오류가 났는지 변경이 안되어 구글링 해보고 수정해보겠습니다 ㅠㅠ

2024-07-21 04:38 UTC, ksy90101 approved these changes
꼼꼼한 테스트 코드까지 아주 굿굿입니다 👍 
간단한 피드백을 남겼으니 한번 확인해주세요~
3단계에서 뵐게요!

2024-07-21 04:38 UTC, ksy90101 commented on src/main/java/gift/DTO/Option.java
> +  public Option() {
기본생성자가 필수로 필요하지만, 접근제어자를 protected까지 가능합니다.
접근제어자를 최소한으로 해서 안정적인 코드를 만들어보면 어떨까요?

2024-07-21 04:38 UTC, ksy90101 commented on src/main/java/gift/Service/OptionService.java
> +    List<OptionDto> optionDtos = options.stream().map(ConverterToDto::convertToOptionDto).toList();
한줄의 점 하나씩 작성함으로써 가독성을 지켜보세요!

2024-07-21 04:38 UTC, merged

2024-07-21 07:37 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Option.java
> +  public Option() {
네! 수정하겠습니다!!

2024-07-21 07:42 UTC, LeeTaek2T commented on src/main/java/gift/Service/OptionService.java
> +    List<OptionDto> optionDtos = options.stream().map(ConverterToDto::convertToOptionDto).toList();
네! 반영하겠습니다.