경북대 BE_안재민 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #289
Opened 2024-07-19 07:06 UTC by dkswoals

이번 한 주도 고생 많으셨습니다😊
2단계 요구사항 구현 후 리뷰 요청드립니다!

## 중점적으로 리뷰 받고 싶은 부분
- 전체적인 리뷰 부탁 드립니다!!

2024-07-19 14:35 UTC, leaf-upper requested changes
안녕하세요 재민님 2단계 구현 고생많으셨습니다~
몇가지 매핑관련 코멘트를 드렸는데요~
이부분 반영해주시면 바로 어프로브 드릴게요! 고생하셨습니다 👍

2024-07-19 14:35 UTC, leaf-upper commented on src/main/java/gift/model/item/Item.java
> +    private List<Option> options = new ArrayList<>();
Product와 Option은 완전히 동일한 생명주기를 가지는데요~
CascadeType을 ALL로 주신건 너무 좋은것 같아요
orpanremoval에 대해서도 알아보고 해당 옵션을 줘보는건 어떨까요?

2024-07-19 14:35 UTC, leaf-upper commented on src/main/java/gift/repository/OptionRepository.java
> +public interface OptionRepository extends JpaRepository<Option,Long> {
OptionRepository가 꼭 필요할까요?
ProductRepository를 통해서 Option을 조회해서 충분히 리턴할수있을것 같아요.
모든 엔티티마다 Repository, Service를 만들어서 값을 리턴해야하는건 아니에요

Product와 Option은 생명주기가 같기 때문에 옵션에 대한 값을 리턴할때는 ProductRepository를 통해서 값을 리턴해보시는걸 권장드려요

2024-07-19 14:35 UTC, leaf-upper commented on src/main/java/gift/service/OptionService.java
> +    private OptionRepository optionRepository;
이 부분도 위에서 코멘트 드린 부분과 비슷한데요~ OptionService가 꼭 필요할까요?
ProductService에서 옵션을 추가하는 비즈니스 로직을 작성할 수 있을것 같아요.
옵션과 관련된 로직은 ProductService에서 해보시는걸 권장드립니다

2024-07-19 14:35 UTC, leaf-upper commented on src/main/java/gift/repository/OptionRepository.java
> +public interface OptionRepository extends JpaRepository<Option,Long> {
상품에 대한 옵션 추가
- Product에 CASCADETYPE을 ALL로 설정하셨으니, Product가 save될때 Option도 같이 save될수 있어요.
- Product 객체의 List<Option>에 새로운 Option을 엔티티를 추가합니다 => 이게 옵션 추가 처럼 사용될 수 있어요

상품에 대한 옵션 제거
-Product에서 orphanremoval=true로 주시면 List에서 Option을 제거하고 ProductRepository에 save하면 옵션도 제거됩니다.

상품에 대한 옵션 조회
- 상품에 대한 옵션 조회는 LAZY로 조회하되, N+1 Query를 방지하기 위해 @BatchSize를 사용 (이건 이미 잘해주신것 같아요)

이 3가지를 통해서 OptionRepository OptionService없이 ProductService와 ProductRepository만을 통해서 비즈니스 로직을 작성할 수 있을것 같아요

2024-07-21 05:30 UTC, dkswoals commented on src/main/java/gift/model/item/Item.java
> +    private List<Option> options = new ArrayList<>();
반영하였습니다!

2024-07-21 05:31 UTC, dkswoals commented on src/main/java/gift/repository/OptionRepository.java
> +public interface OptionRepository extends JpaRepository<Option,Long> {
알려주셔서 감사합니다! 바로 반영하였습니다!

2024-07-21 05:33 UTC, dkswoals commented
피드백 반영 후 3단계까지 리뷰 요청 드립니다!!
3단계는 아직 api 구현 요구사항이 없어서 차후에 itemService의 updateOption을 활용할 예정입니다!

2024-07-21 07:13 UTC, leaf-upper approved these changes
👍 
고생하셨습니다 재민님~ 대부분 코드를 잘 작성해주셨는데 
5주차가 진행될때 수정되면 좋겠다 싶은 부분들에 대해서는 코멘트를 드렸습니다~
4주차 고생많으셨습니다~ 👍 👍

2024-07-21 07:13 UTC, leaf-upper commented on src/main/java/gift/service/ItemService.java
> +        throws CustomDuplicateException {
관련 로직들은 전부 Item내로 이동시켜볼수 있을것 같아요~

2024-07-21 07:13 UTC, leaf-upper commented on src/main/java/gift/service/ItemService.java
> +        throws CustomDuplicateException {
BindingResult는 Service Layer에서 사용할 필요가 없을것 같아요~

2024-07-21 07:13 UTC, leaf-upper commented on src/main/java/gift/service/ItemService.java
> +        Item item = findItemById(itemId);
이런 부분도 Product내로 로직을 이동시켜볼수 있을것 같아요~

2024-07-21 07:13 UTC, leaf-upper commented on src/main/java/gift/service/ItemService.java
> +            .map(OptionDTO::getName)
Product내에서 Option이름이 중복되었는지 체크할 수 있을것 같아요

2024-07-21 07:13 UTC, leaf-upper commented on src/main/java/gift/model/option/Option.java
> +    public boolean update(String name, Long quantity) {
update라는 이름보다는 명시적으로 decreaseQuantity등 수량차감이라는 용어로 사용해주시면 좋을것 같아요~

2024-07-21 07:13 UTC, merged