부산대 BE_강수민 4주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #291
Opened 2024-07-19 07:08 UTC by wvssm

아직 step2 코드 리팩토링 중입니다!

2024-07-20 16:56 UTC, jadie0319 commented
안녕하세요 수민님!
4주차 미션 하시느라 고생하셨어요! 이번 4주차 미션에서는 고민해야할 부분도 많아서 더 고생이 많으셨을 것 같아요 ㅠ
그래도 미션을 하시면서 많이 공부하고 생각하시는게 느껴져서 좋네요 :)
질문 드린 것 답변 드릴게요!

- 순환참조문제

고민이 많이 되셨을 만한 문제네요. 전에 카테고리 구현할 때는 ProductService 에서 CategoryRepository 가 아닌 CategoryService 를 의존하게 만드는 정책이 유효했어요. 그런데 옵션은 좀 달라요. 상품을 등록할 때 상품의 옵션도 함께 등록을 해야 하고, 옵션을 생성할 때 상품이 존재하는지 여부를 확인해야 해요. 그리고 API 를 어떻게 설계하느냐에 따라 상품을 등록할때도 옵션이 존재하는지 여부를 확인해야 하는 로직을 만들어야 할수도 있기 때문에 더 강한 결합이 발생할 가능성이 있어요.

이런 강한 결합도 때문에 서로 의존해야 하는 문제가 발생해 순환참조 문제가 발생했습니다. 오히려 이런 상황에서는 서로의 Repository 를 직접 의존하는게 자연스러워요. 또는... TMI 로 부모 엔티티(Product) 의 Repository만 존재하게 하고 자식 엔티티(Option)의 Repository 는 없애는 식으로도 구현할 수 있어요. 이건 미션의 범위를 넘어서는 문제라서 다음에 알아보셔도 될 것 같아요 🙂 이번 미션에서는  ProductService와 OptionService 에서는 ProductRepository, OptionRepository 를 직접 의존하는 식으로 순환참조를 피해 구현해보기로 해요 🙂

사실 상품을 등록할 땐 OptionService 나 OptionRepository 를 의존할 필요가 없어요. Product 와 List<Option > 간에 cascade 를 ALL 로 해놓으셨기 때문이죠. 아래와 같이 코드를 수정해도 save 기능은 동작합니다~ 편하신 방법으로 구현해주세요!

```java
@Transactional
public void save(ProductRequest productRequest){
    Category category = categoryService.findById(productRequest.categoryId()).toEntity();
    Option option = new Option(productRequest.optionName(), productRequest.optionQuantity());
    productRepository.save(productRequest.toEntity(category, option));
}

public Product toEntity(Category category, Option option) {
    return new Product(this.name, this.price, this.imageUrl, category, option);
}

public Product(String name, int price, String imageUrl, Category category, Option option) {
    this.name = name;
    this.price = price;
    this.imageUrl = imageUrl;
    this.category = category;
    if(this.category != null){
        this.category.addProduct(this);
    }
    addOption(option);
}
```

- OptionService 업데이트 쿼리 안날라가는 문제

`@Transactional` 이 없어서 쿼리가 발생 안한것 같아요~ `@Transactional` 붙여서 실행하니 잘 날라갑니다! 👍

2024-07-20 17:29 UTC, jadie0319 requested changes
안녕하세요 수민님! 
4주차 미션하시느라 고생 많으셨습니다!
이번 4주차는 고민되는 부분이 많아서 더 힘드셨을 것 같아요 ㅠ 
질문에 대한 답변 남겨놨으니 확인 부탁드립니다!

2024-07-20 17:29 UTC, jadie0319 commented on src/main/java/gift/domain/Option.java
> +    }
도메인 객체에 잘 구현하셨네요 :)

2024-07-20 17:29 UTC, jadie0319 commented on src/main/java/gift/domain/Product.java
> +    }
상품에는 항상 하나 이상의 옵션이 있어야 한다 요구사항을 지키기 위해 구현한 로직일까요~!? 👍

2024-07-20 17:29 UTC, jadie0319 commented on src/main/java/gift/dto/request/ProductOptionRequest.java
> +public class ProductOptionRequest {
상품 등록시 사용하는 Request 생성 좋습니다! 👍

2024-07-20 17:36 UTC, jadie0319 reviewed
추가피드백

2024-07-20 17:36 UTC, jadie0319 commented on src/main/java/gift/service/OptionService.java
OptionService#deleteById() 피드백
- 아래 로직을 Option 객체에 위치시키는건 어떻게 생각하시나요?
```java
int productOptionCount = foundOption.getProduct().getOptions().size();
if(productOptionCount < 2){
    throw new CannotDeleteLastOptionException(Messages.CANNOT_DELETE_LAST_OPTION);
}
```

2024-07-20 17:36 UTC, jadie0319 commented on src/main/java/gift/service/OptionService.java
>          optionRepository.save(foundOption);
아직 사용되고 있지 않네요 :)

2024-07-20 18:46 UTC, wvssm commented on src/main/java/gift/domain/Product.java
> +    }
넵 하나 이상의 옵션이  있어야 한다는 요구사항을 지키기 위해 추가한 로직입니다!

2024-07-20 18:48 UTC, wvssm commented on src/main/java/gift/service/OptionService.java
>          optionRepository.save(foundOption);
![image](https://github.com/user-attachments/assets/96abf0d3-3b83-4d07-945a-69d847e8d107)
요구사항에 별도의 API를 사용할 필요가 없다고 해서 아직 사용하지는 않았습니당!

2024-07-20 19:03 UTC, wvssm commented on src/main/java/gift/service/OptionService.java
Option 객체에 위치하는 것이 좋다고 생각합니다!
서비스의 delete 로직보다는 option 객체에 포함되는 것이 좀 더 깔끔하다고 생각합니다~

아래와 같이 수정했습니다!
```
public void validateOptionCountBeforeRemove(){
        int productOptionCount = this.product.getOptions().size();
        if(productOptionCount < 2){
            throw new CannotDeleteLastOptionException(Messages.CANNOT_DELETE_LAST_OPTION);
        }
    }

    public void remove() {
        validateOptionCountBeforeRemove();
        if (this.product != null) {
            this.product.removeOption(this);
        }
    }
```

2024-07-20 19:14 UTC, wvssm commented
> 사실 상품을 등록할 땐 OptionService 나 OptionRepository 를 의존할 필요가 없어요. Product 와 List 간에 cascade 를 ALL 로 해놓으셨기 때문이죠. 아래와 같이 코드를 수정해도 save 기능은 동작합니다~ 편하신 방법으로 구현해주세요!

2024-07-21 02:12 UTC, jadie0319 commented on src/main/java/gift/service/OptionService.java
>          optionRepository.save(foundOption);
넵 ㅠ 제가 요구사항을 까먹고 그런 피드백을 달았다가... 피드백 지웠는데 이미 댓글을 다셨군요 ㅠ

2024-07-22 01:02 UTC, jadie0319 approved these changes
안녕하세요 수민님!
피드백 반영 잘 해주셨어요!
4주차 고생 많으셨습니다. 5주차 미선을 위해 머지하겠습니다!
5주차도 화이팅 하세요!

2024-07-22 01:02 UTC, jadie0319 commented on src/main/java/gift/domain/Option.java
> +    }
서비스에 있던 도메인 로직이 도메인 객체로 점점 옮겨지고 있네요 :) 
도메인 객체 테스트에 추가하면 좋겠네요 ㅎ

2024-07-22 01:02 UTC, jadie0319 commented on src/main/java/gift/domain/Option.java
> +    }
유효성 검증 로직, 파라미터명 적절하게 잘 만드셨습니다~

2024-07-22 01:02 UTC, merged