경북대 BE_심규민 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #310
Opened 2024-07-19 08:18 UTC by sim-mer

### 궁금한 점
- 옵션의 이름 중복을 체크하기 위해 비즈니스 레이어에 pojo 클래스를 추가하였는데 이런 로직은 Service 클래스 안에 존재해도 되는지, 혹은 util 클래스를 생성하는지, 아니면 pojo 클래스로 도메인 로직을 처리하는 방법 중 어느 방법이 가장 적절해보이는지 궁금합니다.
- 이렇게 도메인 로직을 구현한 pojo 객체가 비즈니스레이어에 존재하게 된다면 jpa entity는 dto의 역할과 다를게 없어보이는데 어떻게 생각하시는지 궁금합니다!

2024-07-19 14:48 UTC, leaf-upper requested changes
안녕하세요 규민님 2단계 고생 많으셨습니다~
몇가지 코멘트를 드렸는데요~
확인해보시고 반영해봐주시면 좋을것 같아요
고생하셨습니다 👍

2024-07-19 14:48 UTC, leaf-upper commented on src/main/java/gift/product/persistence/entity/Option.java
> +public class Option {
Product와 Option은 생명주기가 같은데요~
Product에 Option을 1:N관계로 매핑해서 사용해보시면 좋을것 같아요

CasCadeType=ALL, orpanRemoval=true를 주시면 OptionService, OptionRepository 없이도 ProductService, ProductRepository에서 관련 비즈니스 로직 수행이 가능할것 같아요

모든 엔티티마다 Service와 Repository를 만드는것도 가능하겠지만 각 엔티티의 생명주기를 잘 파악해서 하나로 합치는것도 좋은것 같아요


- **상품에 대한 옵션 추가**

Product에 CASCADETYPE을 ALL로 설정한다면, Product가 save될때 Option도 같이 save될수 있어요.
Product 객체의 List에 새로운 Option을 엔티티를 추가합니다 => 이게 옵션 추가 처럼 사용될 수 있어요

- **상품에 대한 옵션 제거**
Product에서 orphanremoval=true로 주시면 List에서 Option을 제거하고 ProductRepository에 save하면 옵션도 제거됩니다.

- **상품에 대한 옵션 조회**

상품에 대한 옵션 조회는 1:N LAZY로 조회하되, N+1 Query를 방지하기 위해 `@Batchsize`를 사용 

이 3가지를 통해서 OptionRepository OptionService없이 ProductService와 ProductRepository만을 통해서 비즈니스 로직을 작성할 수 있을것 같아요
한번 반영해봐주시면 좋을것 같아요~

2024-07-19 14:48 UTC, leaf-upper commented on src/main/java/gift/product/persistence/repository/OptionRepositoryImpl.java
> +public class OptionRepositoryImpl implements OptionRepository{
먼저 코멘트 드린 부분처럼 OptionRepository는 없이 비즈니스 로직을 작성해보는건 어떨까요?

2024-07-19 14:48 UTC, leaf-upper commented on src/main/java/gift/product/business/service/OptionService.java
> +public class OptionService {
먼저 코멘트 드린 부분처럼 OptionService도 없이 비즈니스 로직을 작성해볼수 있을것 같아요.

2024-07-19 14:48 UTC, leaf-upper commented on src/main/java/gift/product/business/service/ProductService.java
> +    private final OptionService optionService;
여기서 상품에 대한 옵션추가, 옵션 제거, 옵션 조회를 구현해보는건 어떨까요?
OptionService없이, ProductRepository만을 통해서도 가능할것 같아요.
이 경우 가장 중요한건 매핑관계인데요,
1:N 매핑 및 `@BatchSize`, CasCadeType, orpanRemoval 이 3가지 옵션을 잘 기억하고 사용해주시면 좋을것 같아요.

2024-07-19 14:48 UTC, leaf-upper commented on src/main/java/gift/product/business/service/OptionService.java
> +public class OptionService {
PojoOptions 을 작성해주신 부분도 
ProductService에서는 Product를 조회하고, 1:N관계로 매핑되어있는 Option들에 대한 데이터를 가져와서 이를 이용해 중복체크가 가능할것 같아요.

2024-07-19 14:48 UTC, leaf-upper commented on src/main/java/gift/product/business/dto/OptionRegisterDto.java
> +public record OptionRegisterDto(
Dto는 사실 Request, Response가 늘어날때마다 계속 생겨나는 편인것 같아요.
이런경우 파일들이 굉장히 많이 생기게되고, 응집성이 떨어지는 부분이 있는데요~
제가 리뷰하는 다른 멘티분이 이 문제를 잘 해결해주신것 같아서 
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/257#discussion_r1684420229
이것처럼 한번 리팩토링을 해보면 어떨까 싶어요~
패키지 구조는 지금 현재도 좋고 꼭 정리할필요는 없어보여요~

2024-07-20 11:15 UTC, sim-mer commented on src/main/java/gift/product/persistence/entity/Option.java
> +public class Option {
넵 반영했습니다!

2024-07-20 11:15 UTC, sim-mer commented on src/main/java/gift/product/business/service/OptionService.java
> +public class OptionService {
넵 작성했습니다!

2024-07-20 11:15 UTC, sim-mer commented on src/main/java/gift/product/business/service/ProductService.java
> +    private final OptionService optionService;
넵 사용했습니다!

2024-07-20 11:15 UTC, sim-mer commented on src/main/java/gift/product/business/dto/OptionRegisterDto.java
> +public record OptionRegisterDto(
덕분에 좋은 방식을 배운것 같네요!

2024-07-20 11:17 UTC, sim-mer commented
이번 리팩토링을 진행하면서 의문이 들었던 점입니다!
- Option에 대한 작업을 수행하면서 항상 Product를 가져와야한다면 Option 테이블에 바로 접근할 때보다 쿼리가 한번 더 실행되게 되어 성능이 조금 저하될거같은데 어떻게 생각하시는지 궁금합니다!
- API 테스트 코드를 작성할 때 각 테스트 수행시마다 Option에 대한 값을 rollback 해줘야하는데 productRepository.saveProduct(dummyProduct); 와 같은 방식으로는 되지않아 혹시 다른 방법이 있는지 궁금합니다!

2024-07-20 20:08 UTC, sim-mer commented
시간 관계상 3단계 코드도 작성했습니다!

2024-07-21 07:02 UTC, leaf-upper commented
@sim-mer 

**Option에 대한 작업을 수행하면서 항상 Product를 가져와야한다면 Option 테이블에 바로 접근할 때보다 쿼리가 한번 더 실행되게 되어 성능이 조금 저하될거같은데 어떻게 생각하시는지 궁금합니다!**

사람마다의 생각의 차이가 있을수는 있겠지만, 일단 제 생각은 이렇습니다.
JPA는 다른 프레임워크와 비교해서 좀더 잘 사용하지 않으면 불필요한 쿼리들이 나가는 이슈들이 있어요. ex. (N+1 쿼리), 매핑관계 데이터 패치 
하지만, JPA를 사용했을때의 장점은 쿼리에 의존적인 프로그램 작성방식이 아닌, 도메인 객체 중심으로 애플리케이션 로직을 작성하고 이로인해 유지보수에 장점을 가져갈수 있다는점인것 같습니다.
그래서 JPA를 사용하면 일단 다른 프레임워크에 비해서 쿼리가 좀더 발생할 수 있다보니 성능이 약간 떨어질수도 있을것 같아요.

그렇다면 현재 Option을 가져올때, Product도 조회해야하므로, 성능이 조금 떨어질까? 에 대한 부분은 저는 조금 의구심이 들어요~
위에서 말씀드린것과 다르게 Option은 Product랑 강한연관관계를 가지고 있고, Option을 조회하기 앞서서 항상 Product를 먼저 조회하는 구조가 되지 않을까 싶네요. 
또한 Option만 딱 한개 조회하는것과 Option과 Product를 같이 조회하는것에는 조회 성능의 차이가 있겠지만 이게 성능에 영향을 미칠 정도라면, 그때부터는 MySQL이 아니라 별도 NoSQL을 통해 비정규화된 테이블을 통해 데이터를 가져와야하지않을까 생각이 듭니다. (조회 구조 아키텍처 변경을 고민해볼 필요가 있을것 같아요.)

**API 테스트 코드를 작성할 때 각 테스트 수행시마다 Option에 대한 값을 rollback 해줘야하는데 productRepository.saveProduct(dummyProduct); 와 같은 방식으로는 되지않아 혹시 다른 방법이 있는지 궁금합니다!**

- API 테스트코드를 작성할때 테스트의 마지막에 직접 삭제해줘도 괜찮지 않을까요? 
제가 질문을 잘 이해를 못해서 조금 더 설명해주시면 좋을것 같아요.

2024-07-21 07:06 UTC, leaf-upper approved these changes
👍 3단계까지 진행 고생하셨습니다.
갑작스런 리팩토링 요청에도 잘 코드를 작성해주신것 같네요~
고생하셨습니다 👍 👍

2024-07-21 07:06 UTC, leaf-upper commented on src/main/java/gift/product/business/service/ProductService.java
> +        checkOptionNamesDuplicate(optionInCreates, OptionIn.Create::name);
이름중복체크 같은 부분은 Product 내에서 Option들을 가지고 있으니 Product내에서도 수행할 수 있지 않을까요?

2024-07-21 07:06 UTC, merged

2024-07-22 02:55 UTC, sim-mer commented on src/main/java/gift/product/business/service/ProductService.java
> +        checkOptionNamesDuplicate(optionInCreates, OptionIn.Create::name);
0단계에서 반영하도록 하겠습니다!