충남대 BE_정현서 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #311
Opened 2024-07-19 08:28 UTC by hynseoj

2024-07-20 03:38 UTC, ksy90101 requested changes
고생많으셨습니다~
꼼꼼한 테스트코드로 인해 안정적인 코드가 되가는 중인거 같습니다.
간단한 피드백을 남겼으니 확인해주세요!

2024-07-20 03:38 UTC, ksy90101 commented on src/main/java/gift/domain/product/controller/ProductRestController.java
> +    public ResponseEntity<ProductDetailResponseDto> create(@RequestBody @Valid ProductRequestDto productRequestDto) {
Response라는 단어가 DTO라는 이름을 굳이 붙일 필요가 없을수 있어요.

참고링크 : https://choo.oopy.io/42bb6822-8199-4aef-a010-3e0c81d5bd18

2024-07-20 03:38 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Option.java
> +public class Option {
이번엔 Entity에도 validate를 해볼까요?

여기 내부의 것들에서 validate를 해야하는 경우가 무엇이 있을까요?

2024-07-20 03:38 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Option.java
> +    uniqueConstraints = { @UniqueConstraint(columnNames = { "product_id", "name" }) }
👍

2024-07-20 03:38 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Option.java
> +    }
id setter가 필요한 이유가 무엇인가요?

2024-07-20 03:38 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Product.java
> +    }
이걸 stream으로 한번 써볼까요?

2024-07-20 03:38 UTC, ksy90101 commented on src/main/java/gift/domain/product/entity/Product.java
> +    }
o라는 단어보단 의미잇는 단어를 써주세요.

2024-07-20 03:38 UTC, ksy90101 commented on src/main/java/gift/domain/product/repository/OptionJpaRepository.java
> +    @Query("delete from Option o where o.product.id = :productId")
직접 쿼리를 작성해야 하는 이유가 있나요?

2024-07-20 03:38 UTC, ksy90101 commented on src/main/java/gift/domain/product/service/OptionService.java
> +public class OptionService {
<img width="979" alt="image" src="https://github.com/user-attachments/assets/c8e99252-1d0e-497f-bf2c-4e3f4cd63584">
해당 API는 어디있나요?

2024-07-20 12:20 UTC, hynseoj commented on src/main/java/gift/domain/product/entity/Option.java
> +    }
테스트 코드 때문에 작성했었는데 사용하지 않는 방향으로 수정해보겠습니다!

2024-07-20 12:28 UTC, hynseoj commented on src/main/java/gift/domain/product/entity/Option.java
> +public class Option {
지금 당장 생각나는 경우는
DTO에서 검증한 것과 동일한 요구사항을 한 번 더 검증하거나
이미 저장된 엔티티를 setter를 통해 수정할 때, 그 값에 대해 검증하는 것
정도 인데.. Entity 검증에 대해 좀 더 찾아보고 해보겠습니다~!

2024-07-20 12:32 UTC, hynseoj commented on src/main/java/gift/domain/product/repository/OptionJpaRepository.java
> +    @Query("delete from Option o where o.product.id = :productId")
SimpleJpaRepository의 delete 메서드가 N+1 문제를 발생시킨다고 해서 별도로 쿼리를 작성했습니다.

2024-07-20 12:40 UTC, hynseoj commented on src/main/java/gift/domain/product/service/OptionService.java
> +public class OptionService {
예시는 상품에 해당하는 옵션을 모두 가져오는 API인데
저는 상품을 상세 조회하는 경우 외에 특정 상품에 대한 모든 옵션을 조회해야 하는 경우가 떠오르지 않아서,
그리고 또 상품 상세 조회 시에 항상 모든 옵션 조회를 필요로 할 것 같아서,
상품 상세 조회(readById)의 응답에 모든 옵션을 포함하도록 구현하였습니다.

추후 과제를 진행하면서 별도로 특정 상품에 대한 옵션을 필요로 하는 경우가 생기게 되면 추가로 구현하도록 하겠습니다!

2024-07-21 02:42 UTC, hynseoj commented
안녕하세요 멘토님!
Entity validation에 대해서는 찾아봤는데 다양한 의견이 있어서 어떤 식으로 적용해야할지 판단이 어렵습니다😂
찾아본 내용으로는,

1. 어노테이션 사용 
    -> 다른 계층 검증과 중복되는 부분 多
2. 생성자나 update 메서드에서 사용
    -> 애초에 DB에 들어가 있는 잘못된 값에 대해 find 시 걸러내지 못함

조언 부탁드립니다..

2024-07-21 04:44 UTC, ksy90101 approved these changes
고생 많으셨습니다!
3단계 진행해주세요~
홧팅입니다!

2024-07-21 04:44 UTC, merged