충남대 BE_강지훈 4주차 과제(1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #317
Opened 2024-07-19 08:37 UTC by kangwlgns

### 코드 작성하면서 어려웠던 점
* 리팩토링에 많은 시간을 사용하여 테스트 코드를 작성하지 못했습니다. 주말까지 작성해서 올리겠습니다.
* 규모가 커질 수록 고쳐야 하는 잘못된 부분을 놓치게 되는 것 같습니다.
### 코드 리뷰 시, 멘토님이 중점적으로 리뷰해줬으면 하는 부분
* List<Dto>도 dto로 묶어줘야 하는지 궁금합니다.

감사합니다.

2024-07-19 17:29 UTC, nimunsang requested changes
안녕하세요 지훈님~ 1단계 잘 수행해주셨습니다 😄
몇 가지 코멘트 달았으니, 천천히 확인해보셔도 좋습니다~
(피드백 반영이 힘드시다면, 인지만 하시고 넘어가셔도 괜찮습니다)

* 0단계를 머지하니 1단계 머지 시도 시 충돌이 발생하는데요~ 이 부분만 확인해주세요 ~

2024-07-19 17:29 UTC, nimunsang commented on src/main/java/gift/product/service/ProductService.java
> +        return optionalProduct.get();
요거를 좀 더 쉽게하려면,
```
return productRepository.findById(productId).orElseThrow(() -> new NoSuchElementException("~~"));
``` 
를 활용해보셔도 좋겠네요~

2024-07-19 17:29 UTC, nimunsang commented on src/main/java/gift/wishlist/service/WishListService.java
>              throw new IllegalArgumentException("장바구니에 존재하지 않는 제품입니다.");
아하 Wish를 장바구니라고 생각하신거였군요!! 그래서 Quantity에 대한 정보가 있었네요~
헷갈리실 수 있긴 한데 Wish는 단순히 "좋아요(찜)" 기능입니다 😄 (장바구니는 Cart)
이왕 이렇게 해주셨으니, Cart라고 생각하고 보겠습니다!

2024-07-19 17:29 UTC, nimunsang commented on src/main/java/gift/category/controller/CategoryApiController.java
> +        categoryService.updateCategory(new CategoryIdDto(categoryId), categoryRequestDto);
CategoryIdDto로 한번 더 래핑해주신 이유가 있으실까요!
(제 생각에는 굳이 래핑하지 않아도 될 것 같아요)

2024-07-19 17:29 UTC, nimunsang commented on src/main/java/gift/category/service/CategoryService.java
> +    @Transactional
`readOnly=true` 여도 되겠군요!

2024-07-19 17:29 UTC, nimunsang commented on src/main/java/gift/wishlist/service/WishListService.java
> +    }
꼼꼼한 검증 좋습니다 👍🏻

2024-07-19 17:29 UTC, nimunsang commented on src/main/java/gift/product/controller/ProductApiController.java
> +    @Parameter(name = "category-id", required = true)
Swagger 어노테이션 대신, `@RequestParam` 어노테이션을 사용하는 것은 어떨까요? (`@CategoryInfo` 를 ArgumentResolver에서 받아오는 대신,, 서비스에서 수행하도록)

2024-07-19 17:29 UTC, nimunsang commented on src/main/java/gift/product/service/ProductService.java
>          return products.stream().map(product -> new ProductResponseDto(product.getProductId(),
Mapping하는 행위를 ProductResponseDto에서 수행해도 좋을 것 같아요.
`new ProductResponseDto.from(product)` 
또는,, Mapper를 새로 만들어도 좋구요.
`ProductResponseDto productResponseDto = ProductResponseDtoMapper.map(product)`

한번 고려해보세요! 
또는 지금 이렇게 Dto로 변환하는 작업이 중복되니까, private 메서드로 분리하는 것이 제일 간단할 수도 있겠네요.

2024-07-20 04:43 UTC, kangwlgns commented on src/main/java/gift/category/controller/CategoryApiController.java
> +        categoryService.updateCategory(new CategoryIdDto(categoryId), categoryRequestDto);
dto가 파라미터가 너무 많아지지 않게 분류 별로 묶어 주는 기능인데, 무작정 '파라미터로 넘길 때는 dto로 포장해야 한다.' 라고 생각했었습니다. 지금이라도 다시 생각해보게 되어 다행입니다..😂

2024-07-20 04:46 UTC, kangwlgns commented on src/main/java/gift/product/service/ProductService.java
>          return products.stream().map(product -> new ProductResponseDto(product.getProductId(),
```
같은 도메인 (wishList) 이 아닌 Repository를 가져오는 것은 영역을 넘어서는 것 같아요.

wishListService는 ProductService, PermissionService만을 접근할 수 있도록 리팩토링해보세요!
```
멘토님의 지난 주 피드백이었는데, 이걸 잘못 봐서 '하나의 도메인에서는 같은 도메인에만 접근할 수 있구나' 라고 생각해서 억지로 resolver를 사용하였습니다.. 다시 보니 Repository가 아닌 Service를 쓰도록 고쳐야 하는 것이었군요😭

2024-07-21 14:44 UTC, nimunsang commented
지훈님 정말 고생 많으셨습니다!! 한 주가 벌써 마무리되어 머지하겠습니다 :)

2024-07-21 14:44 UTC, merged