전남대 BE_김수랑 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #321
Opened 2024-07-19 08:40 UTC by rdme0

과제 제출로 인해 일단 PR 올리겠습니다!

2024-07-21 07:49 UTC, Hongdonggeon requested changes
안녕하세요 수랑님
미션 구현하느라 수고 많으셨습니다!
미션 잘해주셨는데, 어플리케이션에서 옵션 정보가 어디쪽에서 노출될까요?
그리고 api 설계할 때, productId나 optionId를 pathVaraible로 받는다면 request body 로 받을 필요도 없을 것 같아요! pathvariable과 requestbody의 값이 동일한지 검증도 제외시킬 수 있을 것 같아요

2024-07-21 07:49 UTC, Hongdonggeon commented on src/main/java/gift/service/OptionRepositoryKeeperService.java
> +public class OptionRepositoryKeeperService {
이 서비스 클래스는 optionService와 분리한 이유가 뭘까요?

2024-07-21 07:49 UTC, Hongdonggeon commented on src/main/java/gift/service/OptionService.java
> +            if(!Objects.equals(productId, optionRequestDTO.productId()))
productId를 pathVaraible로 받는다면 optionRequestDto에서는 productId를 받을 필요가 없어보여요

2024-07-21 07:49 UTC, Hongdonggeon commented on src/main/java/gift/service/OptionService.java
> +            if(!Objects.equals(optionId, optionRequestDTO.optionId()) || !Objects.equals(productId, optionRequestDTO.productId()))
optionId랑 productId를 pathVariable로만 받아도 될 것 같아요

2024-07-21 07:49 UTC, Hongdonggeon commented on src/main/java/gift/dto/OptionRequestDTO.java
> +    public static OptionRequestDTO convertToDTO(Option option){
사용하지 않는 메서드네요

2024-07-21 08:58 UTC, rdme0 commented on src/main/java/gift/service/OptionRepositoryKeeperService.java
> +public class OptionRepositoryKeeperService {
Step2 요구사항 중에
1. 상품에는 항상 하나 이상의 옵션이 있어야 한다
2. 중복된 옵션은 구매 시 고객에게 불편을 줄 수 있다. 동일한 상품 내의 옵션 이름은 중복될 수 없다.

이러한 요구사항이 있었는데
어떻게 구현할지 생각하던 도중 Jpa의 Cascade를 사용하기보단 서비스의 메서드로 구현하는 것을 택하였고, CRUD 자체만을 담은 서비스와, 옵션 DB에 요구사항 1과 2가 잘 반영 되어있는지 검증하는 서비스로 나누고 싶어서 분리하였습니다.
원래 해당 클래스에는 요구사항 1번과 2번을 구현하는 두개의 메서드가 있었지만 현재 보시다시피 현재 해당 클래스에는 요구사항 2번에 대한 메서드만 담고 있습니다.
그 이유로는 OptionService의

``` java
    @Transactional
    public void addOption(Long productId, OptionRequestDTO optionRequestDTO){
        try {
            Product product = productRepository.findById(productId).orElseThrow(
                    () -> new NoSuchProductIdException("해당 상품 Id인 상품을 찾지 못했습니다."));
            optionRepositoryKeeperService.checkUniqueOptionName(product, optionRequestDTO.name());
            optionRepository.save(optionRequestDTO.convertToOption(product));
        } catch (BadRequestException e) {
            throw e;
        } catch (DataIntegrityViolationException e) {
            throw new BadRequestException("해당 상품에 이미 존재하는 옵션 이름 입니다.");
        } catch (Exception e) {
            throw new InvalidIdException(e.getMessage());
        }
    }
```

혹시 OptionService로 통합시키는 것이 나을까요..?

2024-07-21 09:02 UTC, rdme0 commented
피드백 반영하였습니다!

2024-07-22 06:25 UTC, Hongdonggeon commented on src/main/java/gift/service/OptionRepositoryKeeperService.java
> +public class OptionRepositoryKeeperService {
존재하는지 검증해주는 메서드만 클래스를 분리한게 궁금했어요!
혹시 새로운 요구사항들이 추가되어 그런 검증들도 클래스를 분리시킨다면, 클래스가 너무 많아지고 관리하기 힘들어질 수 도 있을 것 같아요
그래서 개인적인 제 생각으로는 OptionService로 통합시켰을 것 같습니다!

2024-07-22 06:26 UTC, Hongdonggeon approved these changes
안녕하세요 수랑님
미션 반영한거 잘 확인했습니다!
그리고 질문 남긴 것에 대해서도 코멘트 남겨놓았어요!
확인 한번 부탁드립니다!

2024-07-22 06:26 UTC, merged