경북대 BE_김민주 4주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #323
Opened 2024-07-19 08:42 UTC by minju26

2024-07-21 12:55 UTC, gongdongho12 requested changes
실제 데이터 적재 테스트도 옵션을 포함해서 JpaTest로 추가해주시면 작업하신 내용에 대한 검증을 더 충실히 할 수 있을 것 같아요

추가적으로 개선될만한 부분들 코멘트 드렸는데 반영 부탁드립니다

2024-07-21 12:55 UTC, gongdongho12 commented on src/test/java/gift/service/ProductServiceTest.java
> +        String successMsg = productService.addProduct(productRequest, optionRequest);
옵션을 프러덕트 안에 넣고 추가하는게 일반적이지 않을까요?

2024-07-21 12:55 UTC, gongdongho12 commented on src/test/java/gift/service/ProductServiceTest.java
> +    }
상품 옵션추가 테스트인데 무슨 상황이라 오류가 발생하는지 테스트명으로 적어두는게 좋을 것 같습니다

2024-07-21 12:55 UTC, gongdongho12 commented on src/test/java/gift/service/ProductServiceTest.java
> +                .isEqualTo(91);
`option의 갯수 - substractRequest의 갯수`를 91 대신에 표현하면 추후 값이 변경되더라도 대응될 수 있지 않을까요?

2024-07-21 12:55 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +    }
화면 그릴 때, 상품 + 옵션목록을 사용하는 경우만 있지
옵션만 따로 조회할 일이 있을까요?

2024-07-21 12:55 UTC, gongdongho12 commented on src/main/java/gift/domain/Option.java
> +    private int quantity;
위에 보면 `jakarta.validation`을 사용하고 있는 것처럼
아래 quantity 옵션도 annotation 방식으로 적용하는게 컨벤션 상 일치하지 않을까요?

2024-07-21 12:55 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +    }
이걸 DB로 체크하게되면 상품에 옵션이 들어날수록 체크할 대상이 많아질 것 같아요!
[힌트](https://why-dev.tistory.com/362) 참고해보시면 어떻게 사용할 수 있지 않을까요?

2024-07-21 12:55 UTC, gongdongho12 commented on src/main/java/gift/util/ProductValidationUtil.java
> +    }
옵션용도 Validator인데 Product안에 포함되고 있네요
Validator 명을 변경하던가 아니면 코드릴 분리하는 편이 좋지 않을까요?

2024-07-22 05:18 UTC, minju26 commented on src/test/java/gift/service/ProductServiceTest.java
> +        String successMsg = productService.addProduct(productRequest, optionRequest);
음 옵션에도 여러 옵션 특성들이 있어서 두 개로 구분해서(기본 `상품 정보`와 `옵션 정보`) 받도록 해보았는데, 그냥 하나로  받는게 더 나을까요..?!

2024-07-22 05:19 UTC, minju26 commented on src/test/java/gift/service/ProductServiceTest.java
> +    }
아하 넵 알겠습니다!

2024-07-22 05:19 UTC, minju26 commented on src/test/java/gift/service/ProductServiceTest.java
> +                .isEqualTo(91);
으음 그렇군요! 반영하도록 하겠습니다!

2024-07-22 05:20 UTC, minju26 commented on src/main/java/gift/controller/ProductController.java
> +    }
음 크게 없을 것 같긴 합니다! 요구사항 문서에 있어서 만들어 두었습니다

2024-07-22 05:20 UTC, minju26 commented on src/main/java/gift/domain/Option.java
> +    private int quantity;
아하 넵 통일하도록 하겠습니다!

2024-07-22 05:23 UTC, minju26 commented on src/main/java/gift/service/ProductService.java
> +    }
unique키와 index에 대한 내용이군요! 참고해서 개선해보도록 하겠습니다!

2024-07-22 05:34 UTC, minju26 commented on src/main/java/gift/util/ProductValidationUtil.java
> +    }
아하 그렇네요! 정리하도록 하겠습니다

2024-07-22 16:05 UTC, minju26 commented on src/main/java/gift/service/ProductService.java
> +    }
알려주신 힌트에는 복합 Column에 대한 유일 제약 조건인데, 현재 name만 제약을 두고 있는 상황이라 `unique=true`를 적용해 보았습니다!

2024-07-22 16:21 UTC, minju26 commented
pr 내용 중 두 번째 질문에 대해 멘토님 의견이 궁금합니다!
> 1, 2단계의 Category, Option 모두 상품의 정보가 되는 특성이라고 생각하여 Category, Option의 추가/수정 등을 ProductService 내에서 처리하게 되었습니다. 그렇다 보니 ProductService가 다소 복잡해 지는 느낌입니다.
CategoryServiec, OptionService 등으로 분리하게 되면 ProductService에서 이들을 참조하게 될 것 같은데 다른 Service를 참조하는 것이 괜찮은지 궁금합니다.

2024-07-22 16:27 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +    }
@minju26 이름에만 제약을 주면, 상품 1에 AAA라는 옵션이 있고 상품 2에 AAA라는 옵션이 있으면 유니크로 잡히지 않을까요?

2024-07-22 16:29 UTC, gongdongho12 commented on src/main/java/gift/service/ProductService.java
> +    }
이런 부분은 사실 직접 테스트 구성하면서 반례를 찾아가는 과정이자나요
테스트 작성해보면 좋지 않을까요?

2024-07-22 16:29 UTC, minju26 commented on src/main/java/gift/service/ProductService.java
> +    }
헉 그러네요..!! 수정하도록 하겠습니다 🥹

2024-07-22 16:33 UTC, gongdongho12 commented
> 1, 2단계의 Category, Option 모두 상품의 정보가 되는 특성이라고 생각하여 Category, Option의 추가/수정 등을 ProductService 내에서 처리하게 되었습니다. 그렇다 보니 ProductService가 다소 복잡해 지는 느낌입니다.
CategoryServiec, OptionService 등으로 분리하게 되면 ProductService에서 이들을 참조하게 될 것 같은데 다른 Service를 참조하는 것이 괜찮은지 궁금합니다.

저는 이 방향을 추천드려요!
그래야 관리포인트를 서비스단에서 정의할 수 있으니까요

간단하게 카테고리 조회를 할 때, nullable이 올 수 있는데 repository에서 nullable로 리턴하되, 서비스단에서 getCategory에 null이 오면 exception을 주거나 정상값을 리턴하는 등으로 묶어서 표현하고, 실제 카테고리를 사용할 productService에서는 카테고리가 정상적으로 들어왔나 체크 할 필요없이 카테고리 서비스에서 리턴한 값을 사용하면 되니까요!

2024-07-23 06:27 UTC, minju26 commented
> 간단하게 카테고리 조회를 할 때, nullable이 올 수 있는데 repository에서 nullable로 리턴하되, 서비스단에서 getCategory에 null이 오면 exception을 주거나 정상값을 리턴하는 등으로 묶어서 표현하고, 실제 카테고리를 사용할 productService에서는 카테고리가 정상적으로 들어왔나 체크 할 필요없이 카테고리 서비스에서 리턴한 값을 사용하면 되니까요!

오호..!!🤩 이해했습니다! 반영해서 수정해보도록 하겠습니다

2024-07-23 15:43 UTC, gongdongho12 commented
@minju26 이번주차 작업을 보면서 반영 안된부분을 바로잡아갈 수 있었던 것 같습니다!
기간도 오래걸린만큼 추후 작성되는 코드에는 리뷰드렸던 포인트를 하나씩 반영해보면 좋을 것 같아요

정말루 고생 많으셨습니다 🥇

2024-07-23 15:43 UTC, gongdongho12 approved these changes
@minju26 이번주차 작업을 보면서 반영 안된부분을 바로잡아갈 수 있었던 것 같습니다!
기간도 오래걸린만큼 추후 작성되는 코드에는 리뷰드렸던 포인트를 하나씩 반영해보면 좋을 것 같아요

정말루 고생 많으셨습니다 🥇

2024-07-23 15:43 UTC, merged