전남대 BE_이장안 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #328
Opened 2024-07-19 08:47 UTC by lja3723

## Change Log

- README.md 업데이트

## TODO

- 기능구현이 아직 이뤄지지 않았습니다 ....
- 추후 기능구현 완료된 뒤 리뷰요청 보내드리겠습니다. 죄송합니다

2024-07-20 13:22 UTC, gunom reviewed
안녕하세요 장안님 4주차 고생하셨습니다! 리뷰 남겼으니 반영해주시면 감사하겠습니다ㅎㅎ
언제든 질문 환영입니다

2024-07-20 13:22 UTC, gunom commented on src/main/java/gift/domain/annotation/RestrictedSpecialChars.java
> +public @interface RestrictedSpecialChars {
커스텀 어노테이션 멋있네요 👍

2024-07-20 13:22 UTC, gunom commented on src/main/java/gift/domain/service/OptionService.java
> +    private void validateOptionIsUniqueInProduct(Product product, String optionName) {
private 메소드가 public 메소드보다 아래에 존재하는게 가독성에 더 좋을 거 같아요~

2024-07-20 13:22 UTC, gunom commented on src/main/java/gift/domain/service/OptionService.java
> +        //OptionRequest 리스트에 이름이 같은 서로 다른 옵션이 있거나 기존 옵션들과 겹치는 경우 이름 중복으로 예외
이 부분도 별도의 private 메소드로 분리하면 좋을 거 같아요!

2024-07-20 13:22 UTC, gunom commented on src/main/java/gift/domain/service/OptionService.java
> +        request.forEach(req -> addOption(product, req));
이렇게 되면 save가 단건으로 여러 번 진행되겠네요? 한번에 넣는 방법은 없을까요? batch insert에 대해 찾아보시고 정말 잘 동작하나 로그를 확인해보시면 좋을 거 같아요! 만약 잘 안되는 거 같다면 바로 리뷰에 질문주세요ㅎㅎ

2024-07-20 13:22 UTC, gunom commented on src/main/java/gift/domain/entity/Option.java
> +    public synchronized void add(Integer quantity) {
서버가 단일 서버롤 이루어져 있다면 JVM에서는 완벽히 동시성을 보장할 수 있겠죠? 하지만 규모가 큰 서비스일 경우, 단일 서버가 아닌 다수의 동일한 서버를 운영하는 경우가 많습니다. JVM에서만 동시성이 보장되면 각 서버에서는 보장되어도 데이터베이스 상에서는 동시성이 보장되지 않겠죠?
A서버와 B서버가 결국 동시성 문제를 일으킬 겁니다. 이 문제는 어떻게 해결할 수 있을지 고민해보시면 좋을 거 같아요!

2024-07-20 13:22 UTC, gunom commented on src/main/java/gift/domain/controller/ProductOptionController.java
> +public class ProductOptionController {
별도의 컨트롤러를 구현하신 의도가 궁금하네요? option이 추가되는 것은 productId와 어떤 옵션들이 추가될 지 만 알면 되므로 다음과 같은 request를 구현하면 optionController에서도 충분히 가능할 거 같은데 별도의 컨트롤러를 구현하신 이유가 있을까요? 이렇게 유사한 컨트롤러가 생길 경우 유지보수 측면에서 불리함이 있을 수 있습니다!
```java
public class OptionAddRequest {

    private Long productId;
    private String optionName;
    private Integer optionQuantity;
}
```

2024-07-20 13:23 UTC, gunom requested changes
실수로 코멘트로 남겼네요! request changes로 다시 남기겠습니다!

2024-07-21 14:38 UTC, lja3723 commented on src/main/java/gift/domain/annotation/RestrictedSpecialChars.java
> +public @interface RestrictedSpecialChars {
감사합니다 :D

2024-07-21 14:39 UTC, lja3723 commented on src/main/java/gift/domain/service/OptionService.java
> +    private void validateOptionIsUniqueInProduct(Product product, String optionName) {
반영하겠습니다!

2024-07-21 15:27 UTC, lja3723 commented on src/main/java/gift/domain/service/OptionService.java
> +        //OptionRequest 리스트에 이름이 같은 서로 다른 옵션이 있거나 기존 옵션들과 겹치는 경우 이름 중복으로 예외
반영하겠습니다!

2024-07-21 15:37 UTC, lja3723 commented on src/main/java/gift/domain/service/OptionService.java
> +        request.forEach(req -> addOption(product, req));
사실 이렇게 작성하게 된 이유는 서비스 메서드를 재활용하자! 라는 취지였는데 성능 관점에서 생각하면 별로 좋지 않은 아이디어였군요... 검색해 보니 application.properties를 좀 만져주고 ID의 GenerationType.IDENTITY를 사용하면 안된다고 해서 생각보다 쉽지 않은 문제인 것 같습니다ㅠㅠ 
GenerationType.IDENTITY를 포기하면 GenerationType.TABLE을 하거나 jdbcTemplate를 써야된다고 보았는데 이부분은 조금 더 공부를 해보겠습니다...
https://do5do.tistory.com/13

2024-07-21 16:45 UTC, lja3723 commented on src/main/java/gift/domain/entity/Option.java
> +    public synchronized void add(Integer quantity) {
synchronized 키워드만 붙이면 될거라고 생각했는데 너무 성급했나보네요... 좀더 생각해보겠습니다ㅠㅠ

2024-07-21 16:57 UTC, lja3723 commented on src/main/java/gift/domain/controller/ProductOptionController.java
> +public class ProductOptionController {
기존 컨트롤러(`ProductController`)는 상품 그 자체에 관심있다면 이번에 추가했던 `ProductOptionController`는 상품 옵션을 위주로 컨트롤하는 기능이어서, 기존 컨트롤러와는 다른 기능이라 판단해 '기능 분리' 목적으로 새로 만들었었습니다.

다시 코드를 살펴보니 정말 기존 컨트롤러와 병합해도 무방할 것 같네요..!! 감사합니다.

2024-07-22 10:49 UTC, gunom commented on src/main/java/gift/domain/service/OptionService.java
> +        request.forEach(req -> addOption(product, req));
맞습니다. JPA에서는 Bulk insert가 잘 동작하지 않을 때가 많아요ㅎㅎ 말씀하신 방법들이 가장 흔하게 bulk insert 문제를 해결하는 방법들 중 하나입니다. 한번 공부해보시면 좋을 거 같아 남겼습니다 :)

2024-07-22 10:49 UTC, gunom approved these changes
4주차도 수고많으셨습니다! 5주차 화이팅입니다~

2024-07-22 10:50 UTC, merged