전남대 BE_나제법 4주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #329
Opened 2024-07-19 08:48 UTC by nove1080

남은 구현을 완료한 후 리뷰 요청을 보내도록 하겠습니다

2024-07-21 08:30 UTC, Hongdonggeon requested changes
안녕하세요 제법님
2단계도 비교적간단하고 구현 잘해주셔서 크게 코멘트 드릴게 없네요
수고하셨어요!

2024-07-21 08:30 UTC, Hongdonggeon commented on src/main/java/gift/domain/Product.java
> +    private List<ProductOption> productOptions;
일대다 연관관계로 매핑한 이유가 뭘까요? (그냥 제법님의 생각이 궁금해서)

2024-07-21 08:30 UTC, Hongdonggeon commented on src/main/java/gift/service/ProductOptionService.java
> +        validateOptionNameExists(productId, optionName);
옵션을 새로 추가할때 무조건 조회 결과값이 안나오는데 굳이 optionId -1로 조회쿼리가 발생하는 것 같아요

2024-07-21 09:44 UTC, nove1080 commented on src/main/java/gift/domain/Product.java
> +    private List<ProductOption> productOptions;
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/329#issue-2418393989

여기에 적어뒀습니다! 그리고 몇가지 궁금한 점도 같이 작성하여 멘토님의 의견이 궁금합니다!

2024-07-21 09:55 UTC, nove1080 commented on src/main/java/gift/service/ProductOptionService.java
> +        validateOptionNameExists(productId, optionName);
현재 createOption 메서드는 

1. 옵션을 새로 추가할 때
2. 기존에 등록된 옵션이 존재하고 추가로 옵션을 저장할 때

위 두 가지 상황에서 사용되고 있는데 옵션을 새로 추가할 때 불필요한 쿼리가 발생하는 문제를 해결하기 위해 따로 메서드로 분리하여야 하나요? 

```java
@Transactional
public CreateProductOptionResponse createOption();
@Transactional
public CreateProductOptionResponse createAdditionalOption();
```

저는 조회쿼리 한 번이 발생하는 것보다 오히려 메서드를 늘려 유지보수 대상이 늘어나는 것을 염려하여 하나로 만들었습니다.
잘못된 판단이었나요?

2024-07-22 05:58 UTC, Hongdonggeon commented
1. product, productOption 연관관계
저도 productOption을 단독으로 사용하는 일도 없을 것 같고, product 사용할 때 option들도 항상 사용될 것 같아서 제법님 동의에 의견합니다 
그런데 productOption데이터가 많아진다면 고려해봐야할 것 같아요. N+1 쿼리가 많이 발생하게 될테니까요.

2. url 경로 pathVariable 
네 좋은 것 같아요, option이라는 자원이 product에 종속된건 맞으니 적절한 path 로 설계한 것 같아요

3. 요구사항 
builder 메서드에도 해주는 것도 좋아보이지만 product 생성자에서 해주는것도 좋을 것 같아요 
근데 현재 객체의 필드로 검증을 해주고 있는 것 같은데, 객체가 생성되기 전에 생성자나 builder 메서드의 파라미터에 대한 값을 검증해야 될 것 같습니다!

2024-07-22 05:59 UTC, Hongdonggeon commented on src/main/java/gift/service/ProductOptionService.java
> +        validateOptionNameExists(productId, optionName);
잘못되었다고 하긴 그렇지만, 새로 추가할때 쿼리가 불필요하게 발생한다면 메서드를 분리해도 되고, 메서드안에서 분기를 쳐도 되고 하는 방법을 이용할 것 같아요

2024-07-22 06:00 UTC, Hongdonggeon approved these changes
제법님 안녕하세요
질문 남겨주신거에 답변 올려놓았습니다!
옵션 생성시 조회 쿼리 발생하는것도 고민 한번 해봐주세요!

2024-07-22 06:00 UTC, merged