경북대 BE_권다운 4주차 과제 (3단계, 4단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #331
Opened 2024-07-19 08:50 UTC by momnpa333

1. option 수량 decrease을 구현하였습니다. 처음에는 @Transactional과 syncronized를 같이 붙여 테스트를 하였는데, 통과가 되지 않아서 고민하다가 @transactional에서 프록시 객체를 만들면서 syncronized가 붙지 않는 다는 것을 알게 되었습니다. 
2. sycronized가 리소스를 너무 잡아먹는데 다른 방법으로 구현하려면 어떻게 해야하는지 궁금합니다.
3. productService에서 option을 만들어서 product가 가지고 있는 List에 option넣는 방법과 제가 구현한 방법중 어떤 방식이 더 적절한지 잘 모르겠습니다. 어떤 로직이 더 나을까요? 사실 저는 저번에 만들었던 productservice의 코드를 수정하는게 불편해서 이런식으로 구현하였는데, 곰곰이 생각하니 양방향 매핑을 하게된 이점을 제대로 활용하지 못하고 있다는 생각이 들어 질문 드립니다!
4. 동시성 테스트를 하려면 mock객체를 이용해서 test하기 힘들어 보이는데 mock을 사용해서 동시성 테스트를 구현할 수도 있나요?

2024-07-20 15:23 UTC, MangKyu requested changes
이번 과제도 잘 진행해주셨습니다! 몇 가지 개선하면 좋을 것 같은 부분들이 있어서, 해당 부분 개선해보면 좋을 것 같아요ㅎㅎ 리뷰 코멘트 확인 후에 개선 작업 진행해주시면 감사드리겠습니다! 🙇 
추가적으로 질문 주셨던 부분들에 대해서도 답변 남겨드리도록 하겠습니다ㅎㅎ

### 동시성 처리 방법
앞서 설명드렸듯이synchronized는 단일 서버 내에서만 동시성을 보장해주는 문제가 있습니다! 따라서 분산 저장소를 활용해야 하는데, 데이터베이스를 활용할 수도 있고 또는 Redis와 같은 캐시 그리고 최종적으로는 분산락 등을 활용할 수 있습니다!
데이터베이스의 잠금 중에서도 현재로는 낙관적 잠금 등을 활용할 수 있으니, 해당 기능에 대해 알아보시면 좋을 것 같습니다! 추가적으로 레디스와 분산락 관련하여는 [다음의 포스팅](https://mangkyu.tistory.com/311) 참고해주세요!


### Option과 Product의 처리
바라보는 시각에 따라 구현이 달라진다고 보시면 될 것 같아요ㅎㅎ Option을 Product의 하위 도메인으로 본다면 Product에 접근하여 Option에 대한 처리를 하는 것이 맞을 것 같습니다! 반면에 Option을 독립적인 도메인으로 바라본다면 지금의 구조가 맞을 것 같습니다ㅎㅎ 선택의 기준은 변경의 용이성으로 판단하시면 될 것 같고, Option을 분리하는 것이 좋다고 판단하였으니 현재 구조도 괜찮다는 생각입니다!


### 동시성 테스트
mock 객체가 필요한 순가는 협력하는 객체가 필요한 순간이라고 볼 수 있는데요~ 현재 구조에서는 충분히 mock을 써서도 처리가 가능한 구조인 것 같다는 생각입니다ㅎㅎ

2024-07-20 15:23 UTC, MangKyu commented on src/main/java/gift/controller/product/OptionController.java
> +        @RequestBody OptionRequest.Register request
유효성 검사가 작동되도록 `@Valid`를 붙여주어야 할 것 같습니다ㅎㅎ
```suggestion
        @RequestBody @Valid OptionRequest.Register request
```

2024-07-20 15:23 UTC, MangKyu commented on src/main/java/gift/controller/product/CategoryController.java
> +        return ResponseEntity.ok(CategoryResponse.Info.from(model));
전반적으로 작성하신 코드들이 일관성 있어서 좋은 것 같아요! 💯

2024-07-20 15:23 UTC, MangKyu commented on src/main/java/gift/controller/product/OptionController.java
> +        @RequestBody OptionRequest.Update request
개행도 깔끔하고 전반적으로 읽기가 좋은 것 같아요~

2024-07-20 15:23 UTC, MangKyu commented on src/main/java/gift/model/product/Option.java
> +    protected Option() {
protected 활용 💯

2024-07-20 15:23 UTC, MangKyu commented on src/main/java/gift/model/product/Option.java
> +    public void update(String name, Integer quantity) {
객체가 메서드를 가지면서 기능도 풍부해지고, 객체지향적인 모습을 갖춰가는 것 같습니다!

2024-07-20 15:23 UTC, MangKyu commented on src/main/java/gift/model/product/Option.java
> +            if (value < 0) {
요렇게 바뀌어야 하지 않을까요ㅎㅎ 테스트의 중요성, 테스트 중에서도 경계값 테스트의 중요성이 보이는 부분이네요!
```suggestion
            if (value <= 0) {
```

2024-07-20 15:23 UTC, MangKyu commented on src/main/java/gift/model/product/Options.java
> +        for (Option o : options) {
동일한 메서드가 2번 구현된 것 같네요ㅎㅎ

2024-07-20 15:23 UTC, MangKyu commented on src/main/java/gift/service/product/OptionService.java
> +        List<Option> optionList = command.toEntities(product);
command에서 Options를 반환하게 하고, options.validateOptions 하면 되지 않을까요~?
훌륭한 Options 클래스를 생성해두었는데, 여기서 활용되지 않는 부분이 아쉬워서 Options를 통해 직접 검사하도록 하면 좋을 것 같아요ㅎㅎ

2024-07-20 15:23 UTC, MangKyu commented on src/main/java/gift/service/product/OptionService.java
> +    public synchronized void puchaseOption(Long optionId, Integer quantity) {
동시성을 위해  synchronzied를 잘 활용해주셨군요! 하지만 일반적으로 서비스는 무중단을 위해 2개 이상의 서버가 떠잇는데, synchronized는 단일 서버 내에서만 동시성을 보장해주는 문제가 있습니다!

2024-07-20 15:23 UTC, MangKyu commented on src/main/java/gift/model/product/Options.java
> +    public static void validateOptions(List<Option> options) {
저는 참고로 이러한 exception까지 throw해버리는 validateXXX 메서드를 만들기 보다는 hasValidXXX를 통한 boolean 반환 메서드를 선호합니다! 이를 통해 메서드를 호출하는 클라이언트가 예외를 던질지 무시할지를 판단하도록 하여 범용성 있는 메서드를 작성합니다ㅎㅎ

2024-07-20 15:23 UTC, MangKyu commented on src/test/java/gift/model/product/OptionTest.java
> +public class OptionTest {
단위 테스트 보완 💯

2024-07-20 15:23 UTC, MangKyu commented on src/test/java/gift/service/OptionServiceMockTest.java
> +public class OptionServiceMockTest {
요기도 테스트 한번 작성 마무리해보시면 어떨까요~?
테스트는 상당히 중요하고, 유의미한 테스트를 작성하기 위해서는 많은 경험이 필요한 것 같아요ㅎㅎ

2024-07-20 15:23 UTC, MangKyu commented on src/test/java/gift/service/OptionServiceTest.java
> +public class OptionServiceTest {
오 추가 미션인 동시성 테스트까지 잘 작성해주셨군요ㅎㅎ 고생많으셨습니다!

2024-07-20 18:21 UTC, momnpa333 commented on src/main/java/gift/controller/product/OptionController.java
> +        @RequestBody OptionRequest.Register request
중요한 부분을 놓쳤네요 감사합니다!

2024-07-20 18:24 UTC, momnpa333 commented on src/main/java/gift/model/product/Option.java
> +            if (value < 0) {
감사합니다 확실히 테스트의 중요성을 다시한번 깨닫네요..

2024-07-21 04:51 UTC, MangKyu commented
@momnpa333 요거 컨플릭도 생긴 것 같은데 한번 수정해주시겠어용??

2024-07-21 08:53 UTC, momnpa333 commented
넵 닫고 다시 pr 날리겠습니다!

2024-07-21 08:55 UTC, closed without merging

2024-07-21 12:59 UTC, momnpa333 commented on src/main/java/gift/service/product/OptionService.java
> +    public synchronized void puchaseOption(Long optionId, Integer quantity) {
넵 조언해주신 덕분에 이미 리뷰해 주셨지만 낙관적 락을 사용하였습니다!

2024-07-21 13:10 UTC, momnpa333 commented on src/main/java/gift/model/product/Options.java
> +    public static void validateOptions(List<Option> options) {
아하 그렇군요. 확실히 그렇게 구현하면 좀 더 범용성 있는 메서드가 될것 같습니다!
수정했습니다!!

2024-07-21 14:16 UTC, momnpa333 commented on src/test/java/gift/service/OptionServiceMockTest.java
> +public class OptionServiceMockTest {
넵 optionServiceMockTest 제작했습니다!! 테스트하나 만들어놓으니 든든하네용! 리팩토링할때 마다 postman 하나씩 쏴보는 뻘짓을 안해도 되니 행복합니당!