강원대 BE_박지희 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #332
Opened 2024-07-19 08:50 UTC by peacefullyquietly

안녕하세요 멘토님! step1 코드리뷰를 바탕으로 step1 브랜치에 수정을 완료했습니다. 이후 step1 머지를 기다리고 있었으나, 과제 제출이 임박하여 부득이하게 머지 전 step2 PR을 넣게 되었습니다. step2에도 step1 코드 리뷰 기반의 변경 사항이 포함되어 있습니다.
항상 꼼꼼한 코드 리뷰 감사드립니다!

## 궁금한 점
- 옵선을 수정 하는 경우 현재 제 코드는 다음과 같습니다
- OptionService 클래스 내 옵션을 수정하는 메서드 부분입니다.
```
 @Transactional
    public void editOption(Long productId, Long optionId, OptionDTO optionDTO) {
        ProductEntity product = productRepository.findById(productId)
            .orElseThrow(() -> new EntityNotFoundException("해당 상품이 존재하지 않습니다. ID: " + productId));

        OptionEntity optionEntity = optionRepository.findById(optionId)
            .orElseThrow(() -> new EntityNotFoundException("해당 옵션이 존재하지 않습니다. ID: " + optionId));

        optionEntity.update(optionDTO.getName(), optionDTO.getQuantity());

        optionRepository.save(optionEntity);
    }
```
위와 같이 update에 이름과 수량을 넣은 후 OptionEntity 클래스 내에서 다음과 같이 사용하고 있습니다
```
    public void update(String name, int quantity) {
        this.name = name;
        this.quantity = quantity;
    }
```
그런데 setter 대신 사용하는 update 메서드를 이런식으로 사용하는 것이 맞는지에 대한 의구심이 계속 들었지만 별다른 방법이 떠오지않습니다. 혹시 어떤 식으로 사용하면 좋을 지 조언해주시면 감사하겠습니다!

2024-07-20 04:19 UTC, jaymarystella requested changes
안녕하세요.
코멘트 남겼는데 확인해주시고 의견및 반영부탁드립니다.

2024-07-20 04:19 UTC, jaymarystella commented on src/main/java/gift/entity/OptionEntity.java
> +    }
이렇게 하면 setter와 똑같습니다. 예를들어 수량은 음수가 될수없으니 해당 값들을 검증하는것으로 시작해보면어떨까요?

2024-07-20 04:19 UTC, jaymarystella commented on src/main/java/gift/controller/ProductController.java
> +    public ResponseEntity<?> addProduct(@RequestBody ProductDTO productDTO) {
void형태를 의도하신거죠?

2024-07-20 04:19 UTC, jaymarystella commented on src/main/java/gift/domain/OptionDTO.java
> +    private Long id;
id값은 필요없을것같은데 어떻게 생각하시나요?

2024-07-20 04:19 UTC, jaymarystella commented on src/main/java/gift/domain/OptionDTO.java
> +    @Max(value = 100_000_000, message = "수량은 최소 1개 이상, 최대 1억개 미만입니다.")
이거 inclusive여서 1억도 해당되지않나요?

2024-07-20 04:19 UTC, jaymarystella commented on src/main/java/gift/service/CategoryService.java
> +        category.update(categoryDTO);
도메인에 dto를 넘기는것보다 필요한 필드만을 넣어주면 어떨까요?

2024-07-20 04:19 UTC, jaymarystella commented on src/main/java/gift/entity/CategoryEntity.java
> +    }
이 부분도 검증을 포함해서 개선해주시면 좋을것같습니다.

2024-07-20 04:19 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +        return optionEntity;
옵션조회후 옵션을 반환하는데 상품정보는 사용되지 않는것처럼 보입니다.

2024-07-20 04:19 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +        return optionEntity;
서비스들에 대해서도 테스트를 전부 만들어주세요!

2024-07-20 04:19 UTC, jaymarystella commented on src/main/java/gift/entity/WishListEntity.java
> +    public static WishListDTO toDTO(WishListEntity wishListEntity) {
도메인들에 대해서도 테스트코드들을 만들어주시면 감사하겠습니다.

2024-07-20 10:03 UTC, peacefullyquietly commented on src/main/java/gift/domain/OptionDTO.java
> +    private Long id;
확인해보니 쓰이지 않고 있었습니다 수정하겠습니다!

2024-07-20 10:03 UTC, peacefullyquietly commented on src/main/java/gift/service/CategoryService.java
> +        category.update(categoryDTO);
넵 수정해보겠습니다

2024-07-20 10:03 UTC, peacefullyquietly commented on src/main/java/gift/entity/CategoryEntity.java
> +    }
넵 알겠습니다

2024-07-20 10:03 UTC, peacefullyquietly commented on src/main/java/gift/service/OptionService.java
> +        return optionEntity;
넵 작성해보겠습니다

2024-07-20 10:04 UTC, peacefullyquietly commented on src/main/java/gift/domain/OptionDTO.java
> +    @Max(value = 100_000_000, message = "수량은 최소 1개 이상, 최대 1억개 미만입니다.")
넵,, 확인해보니 멘토님 말씀이 맞는 것 같습니다 수정하겠습니다

2024-07-20 10:22 UTC, peacefullyquietly commented on src/main/java/gift/domain/OptionDTO.java
> +    private Long id;
넵.. 확인해보니 사용 되지 않고 있는 것 같습니다 수정하겠습니다

2024-07-21 23:35 UTC, jaymarystella approved these changes
리뷰반영하느라 고생하셨습니다.
다음단계 진행해주세요

2024-07-21 23:35 UTC, merged