강원대 BE_김병수 4주차 과제 (step2)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #333
Opened 2024-07-19 08:52 UTC by GamJaDo

# [전PR](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/139) 에서 리뷰 해주신 내용을 반영하였습니다.
---
## 멘토님 리뷰
```jsonc
카테고리이름이 같으면 어떻게 될까요?
```
## 답변
- [4주차 step1](https://edu.nextstep.camp/s/dGx30MLc/ls/6oM7Smel) 의 힌트 부분에 
```jsonc
alter table category
    add constraint uk_category unique (name)
```
로 DDL이 적혀 있었기에
Category.java에 name을
```jsonc
@Column(unique = true, nullable = false)
	private String name;
```
로 했습니다.
그렇기에 name의 중복은 없다고 생각했습니다.
---

2024-07-20 04:05 UTC, jaymarystella requested changes
안녕하세요
미션 구현 잘해주셨습니다.
컴파일안되는 부분만 수정해주시면 될 것 같습니다.

2024-07-20 04:05 UTC, jaymarystella commented on src/main/java/gift/entity/Option.java
> +	private String name;
jpa entity에 필요한 애노테이션일까요?

2024-07-20 04:05 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +		return OptionResponses;
stream처리로 개선해볼수도있을것같습니다.

2024-07-20 04:05 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +	public List<OptionResponse> getOptions(long id) {
인자를 상품id인것이 드러나도록 만드시는게 가독성에 좋을것같습니다.

2024-07-20 04:05 UTC, jaymarystella commented on src/test/java/gift/test/OptionRepositoryTest.java
> +package gift.test;
테스트코드 패키지도 나눠보면 어떨까요?

2024-07-20 04:05 UTC, jaymarystella commented on src/test/java/gift/test/ProductTest.java
>      private ProductUpdateRequest productUpdateRequest;
ProductUpdateRequest 이 클래스 이름이 잘못바뀐거같아요.

2024-07-20 08:24 UTC, GamJaDo commented on src/main/java/gift/service/OptionService.java
> +		return OptionResponses;
stream으로 개선했습니다.

2024-07-20 08:25 UTC, GamJaDo commented on src/main/java/gift/service/OptionService.java
> +	public List<OptionResponse> getOptions(long id) {
가독성있게 무슨 id인지 수정하였습니다.

2024-07-20 08:25 UTC, GamJaDo commented on src/test/java/gift/test/OptionRepositoryTest.java
> +package gift.test;
테스트코드들을 controller와 repository의 테스트로 나눴습니다.

2024-07-20 09:06 UTC, GamJaDo commented on src/main/java/gift/entity/Option.java
> +	private String name;
필요한 어노테이션만 사용하도록 변경하였습니다.

2024-07-20 16:16 UTC, GamJaDo commented on src/test/java/gift/test/ProductTest.java
>      private ProductUpdateRequest productUpdateRequest;
제 로컬에는 제대로 대문자로 되어 있어서 컴파일 할 때 잘 됐었는데 PR에 파일을 확인해 보니 소문자로 되어 있었습니다. 로컬에서 파일을 삭제하고 다시 생성 후 커밋을 해봐도 똑같이 뜨네요... 이렇게 하면 안 될 것 같긴 한데 깃에서 직접 파일이름을 수정했습니다.

2024-07-21 07:05 UTC, jaymarystella approved these changes
안녕하세요 리뷰반영하느라 고생많으셨습니다.
다음단계 진행해주세요~

2024-07-21 07:05 UTC, merged