경북대 BE_박준석_4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #334
Opened 2024-07-19 08:53 UTC by Lucerna00

옵션의 CRUD 기능을 구현하였습니다.
리팩토링 및 관리자 페이지에서도 옵션을 추가할 수 있도록 수정하겠습니다.

2024-07-19 16:38 UTC, gongdongho12 requested changes
2단계 작업도 깔끔하네요

고생많으셨습니다
대부분은 잘 작성되어 있네여 💯 

minor 한 부분들 코멘트 남겼습니다
그리고 conflict 해결 부탁드려요

2024-07-19 16:38 UTC, gongdongho12 commented on src/main/java/gift/controller/AdminController.java
> +        model.addAttribute("categories", categoryService.getCategories());
요구사항과 거리가 멀긴 한데요, 위 모델 아래모델 전부 카테고리 조회면 사실 DB에 매번 트리거가 될 것 같은데요

나중에 캐싱이 적용될 수 있는 부분일 것 같아요!

2024-07-19 16:38 UTC, gongdongho12 commented on src/main/java/gift/controller/CategoryController.java
> +    }
add만 자동이동인데요
update나 delete는 refresh 로직겸 이동을 하지 않은 이유가 있을까요?
이부분도 컨벤션이라고 하면 컨벤션에 어긋나 보일 수 있어서요
예를들어 새로고침을 js레벨에서 하는 거라면 이동도 js레벨에서 하는게 맞지 않을까 싶네요...

2024-07-19 16:38 UTC, gongdongho12 commented on src/main/java/gift/domain/Category.java
> +    }
아이디 유무에 따른 생성자를 다르게 한 부분 👍🏼
minor) 이부분 중복되는 부분은 this 호출해서 사용해볼 수 있지 않을까요?
```suggestion
    public Category(String name, String color, String imageUrl, String description) {
        this.name = name;
        this.color = color;
        this.imageUrl = imageUrl;
        this.description = description;
    }

    public Category(Long id, String name, String color, String imageUrl, String description) {
        this.id = id;
        this(name, color, imageUrl, description);
    }
```

2024-07-19 16:38 UTC, gongdongho12 commented on src/main/java/gift/service/OptionService.java
> +        }
이걸 여기에 넣기 보다는 옵션의 이름에 uniqueKey 적용해볼 수 있지 않을까요?

2024-07-19 16:38 UTC, gongdongho12 commented on src/test/java/gift/util/CategoryFixture.java
> +}
Fixture 별도 관리해보는 것과 기존 방식중에 어떤게 좋을까요?
-> 꼭 이렇게 해야 한다 보다는 작업해보시면서 편한 방향으로 적용되는게 제일 베스트라구 생각해요!

2024-07-19 18:34 UTC, Lucerna00 commented on src/main/java/gift/controller/AdminController.java
> +        model.addAttribute("categories", categoryService.getCategories());
넵 알겠습니다
@Cacheable도 활용해 보겠습니다

2024-07-19 18:34 UTC, Lucerna00 commented on src/main/java/gift/controller/CategoryController.java
> +    }
무작정 리소스 추가 시엔 201 Created를 반환해야 한다고 생각하였습니다
말씀하신 대로 새로고침은 js에서 하니 컨벤션에 맞춰 200 OK로 수정하였습니다!

2024-07-19 18:34 UTC, Lucerna00 commented on src/main/java/gift/domain/Category.java
> +    }
몇몇 엔티티엔 this() 생성자를 사용하지 않았네요..! 수정하였습니다

2024-07-19 18:35 UTC, Lucerna00 commented on src/main/java/gift/service/OptionService.java
> +        }
상품 id와 옵션 name으로 unique key를 이룬다고 생각하여 @UniqueConstraint를 사용하였습니다

2024-07-19 18:35 UTC, Lucerna00 commented on src/test/java/gift/util/CategoryFixture.java
> +}
repository나 service 등 여러 테스트에서 공동으로 사용되기에 별도의 클래스를 두는 것이 좋은 거 같습니다!

2024-07-20 14:05 UTC, gongdongho12 approved these changes
2단계 고생하셨습니다!

2024-07-20 14:05 UTC, merged