경북대 BE_권도윤 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #338
Opened 2024-07-19 08:54 UTC by doyooon

2024-07-20 13:58 UTC, MangKyu requested changes
안녕하세요ㅎㅎ 2단계도 고생많으셨습니다!
바로 머지를 해드리고 싶은데, 연관관계를 사용하지 않은 부분이 요구사항을 충족하지 못하여 요것만 고쳐주시면 바로 머지하도록 하겠습니다!🙇 
추가적으로 질문 주신 부분에 대해서도 답변을 드리겠습니다!


### 연관관계
해당 상황에서는 Product를 통해 항상 접근하고, 옵션을 관리해야 한다고 볼 수 있습니다ㅎㅎ 양방향으로 연관 관계를 맺게 되면 복잡도가 올라가므로, Product를 통해서만 Option을 관리하는 것도 좋은 전략이라고 생각합니다!
다만 현재는 연습을 거치는 단계이므로 해당 부분은 연관관계 매핑을 사용하도록 변경해주시면 감사드리겠습니다ㅎㅎ

2024-07-20 13:58 UTC, MangKyu commented on README.md
> +# step2
꼼꼼한 정리 너무 좋습니다 💯

2024-07-20 13:58 UTC, MangKyu commented on src/main/java/gift/category/CategoryController.java
> +    public ResponseEntity<HttpStatus> updateCategory(@RequestBody CategoryRequest categoryRequest){
현재 코드로는 HttpStatus가 200으로 내려가고 있을 것 같아요ㅎㅎ
다음과 같이 작성해야 201 생성 응답이 내려갈 것 같습니다!
```java
        return ResponseEntity
                .created(URI.create("/categories/" + category.getId()))
                .body(category);;
```

2024-07-20 13:58 UTC, MangKyu commented on build.gradle
> +    implementation 'com.google.code.gson:gson'
리뷰 반영 👍

2024-07-20 13:58 UTC, MangKyu commented on src/main/java/gift/category/CategoryRequest.java
> -    public void setColor(String color) {
불필요한 setter 제거 💯

2024-07-20 13:58 UTC, MangKyu commented on src/main/java/gift/option/Option.java
> +    private Long productId;
저희가 학습하고자 하는 것은 JPA와 그에 대한 연관관계입니다!
객체들 간의 관계를 연결하고 탐색할 수 있는 것이 이번 목표이므로, 해당 부분을 반영해주시면 좋을 것 같아요!

2024-07-20 13:58 UTC, MangKyu commented on src/main/java/gift/option/Option.java
> +    protected Option(){
protected로 제한한 부분 👍

2024-07-20 13:58 UTC, MangKyu commented on src/main/java/gift/option/Option.java
> +    public void update(String name, int quantity){
의미있는 메서드로 변경을 관리하는 부분 너무 좋네요!

2024-07-20 13:58 UTC, MangKyu commented on src/main/java/gift/option/OptionService.java
> +    public Option deleteOption(Long id){
삭제 처리에는 객체가 더 이상 존재하지 않으므로, void를 반환해야 혼란이 오지 않을 것 같아요ㅎㅎ
삭제된 객체의 참조가 돌아다닐 수 있게 되므로, 깔끔하게 delete 메서드에서 void로 반환하고 끊어버리는 것이 좋을 것 같습니다:)

2024-07-20 13:58 UTC, MangKyu commented on src/main/java/gift/product/ProductService.java
> +    public HttpStatus updateProduct(Product changeProduct) {
서비스는 비즈니스 로직을 담당하는 계층인데, HTTP 상태는 비즈니스 로직은 아닌 것 같아요!
따라서 차라리 변경된 Product를 변경하는 것이 더욱 바람직할 것 같습니다ㅎㅎ

2024-07-20 13:58 UTC, MangKyu commented on src/test/java/gift/category/CategoryServiceTest.java
> +    private CategoryRequest categoryRequest() {
중복되는 객체 생성을 분리하는 부분 💯

2024-07-20 13:58 UTC, MangKyu commented on src/test/java/gift/option/OptionRepositoryTest.java
> +class OptionRepositoryTest {
테스트 정말 꼼꼼하게 잘 작성해주셨네요 💯

2024-07-20 13:58 UTC, MangKyu commented on src/test/java/gift/option/OptionServiceTest.java
> +        assertThat(exception.getMessage()).isEqualTo(" 동일한 상품 내의 옵션 이름은 중복될 수 없습니다. ");
예외 메시지 까지! 꼼꼼하십니다ㅎㅎ

2024-07-21 03:03 UTC, doyooon commented on src/main/java/gift/option/OptionService.java
> +    public Option deleteOption(Long id){
반영했습니다!

2024-07-21 03:03 UTC, doyooon commented on src/main/java/gift/product/ProductService.java
> +    public HttpStatus updateProduct(Product changeProduct) {
넵! 반영했습니다!

2024-07-21 03:04 UTC, doyooon commented on src/main/java/gift/category/CategoryController.java
> +    public ResponseEntity<HttpStatus> updateCategory(@RequestBody CategoryRequest categoryRequest){
감사합니다! 반영했습니다!

2024-07-21 03:05 UTC, doyooon commented on src/main/java/gift/option/Option.java
> +    private Long productId;
넵! 반영했습니다!

2024-07-21 04:32 UTC, MangKyu approved these changes
고생하셨습니다! 시간이 많지 않아서 빠르게 다음 단계로 넘어가도록 하시죠! 🙇

2024-07-21 04:32 UTC, MangKyu commented on src/main/java/gift/category/CategoryController.java
> +    public ResponseEntity<HttpStatus> deleteCategory(@RequestParam Long id){
여기는 반영이 덜 된 것 같네용ㅎㅎ

2024-07-21 04:32 UTC, merged