경북대 BE_이상희 4주차 과제(2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #341
Opened 2024-07-19 08:55 UTC by sanghee0820

**구현내용**
ProductOption 관련 로직을 추가하였습니다.

**질문사항**
1. 어제 멘토링 때 Option 저장에 대해 말씀드렸는데요, 여기서 파사드 패턴을 사용하는 것은 어떻게 생각하시나요?
Product Create시, 파사드 패턴을 사용해 Product를 먼저 저장하고, 그 Id를 이용해 OptionService에서 Option을 추가하는 방법이 개인적으로 직관적이라고 생각하는데 준님의 의견이 궁금합니다.
2. Request부분에서, 최초 ProductRequest에 Option에 대한 정보를 List로 추가해주었었는데, 마음에 들지않아(?) Create하는 Request를 추가하고, ProductRequest와 List<Option>을 필드로 가지게 하였습니다. 또 ProductCommand와 OptionCommand를 나누어 Service에 인자로 받았는데, 이부분 피드백 부탁드립니다.
3. OptionService에서, 다음과 같이 매서드를 분리해놓았습니다.
```
private ProductOption getExistsProductOption(Long productId, Long optionId) {
        var option = productOptionRepository.findByProductIdAndId(productId, optionId)
                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 상품 옵션입니다."));
        return option;
    }

    private void validateDuplicatedProductName(Long productId, String name) {
        var productOption = productOptionRepository.findByProductId(productId);

        if (productOption.stream().anyMatch(option -> option.isSameName(name))) {
            throw new IllegalArgumentException("이미 존재하는 상품 옵션입니다.");
        }
    }
```
이렇게 매서드를 분리하는게, 너무 분리하는건 아닌가? 싶은 생각도드는데 어떻게 생각하시는지 궁금합니다.
4. Validation
저는 개인적으로 Nullable 같은 부분 이외에는 거의 모든 부분이 도메인에서 검증되어야 된다고 생각해 수정하려고합니다.
Request, Command에서 빠르게 검증하는것이 좋다고는 하지만, 어떠한 다른 부분에서 도메인이 생성된다면 유효하지 않은 도메인이 생성될 수 있다고 생각하기 때문입니다.
이부분에서 준님의 견해를 듣고싶습니다!

**부족한 부분**
유효성 검증 로직에 많이 신경쓰지 못했습니다. 추가하도록 하겠습니다.

2024-07-19 14:58 UTC, khj68 requested changes
상희님 고생 많으셨습니다 :)

2024-07-19 14:58 UTC, khj68 commented on src/main/java/gift/product/service/ProductOptionService.java
> +        }
에러문을 보았을 때 조건문이 사이즈가 1개보다 작을 때가 되어야 하지 않을까요?

2024-07-19 14:58 UTC, khj68 commented on src/main/java/gift/product/service/ProductOptionService.java
> +        if (productOption.stream().anyMatch(option -> option.isSameName(name))) {
스트림함수 anyMatch 잘 사용해주셨네요 :)

2024-07-19 15:07 UTC, khj68 commented
질문사항

1. 어제 멘토링 때 Option 저장에 대해 말씀드렸는데요, 여기서 파사드 패턴을 사용하는 것은 어떻게 생각하시나요?
Product Create시, 파사드 패턴을 사용해 Product를 먼저 저장하고, 그 Id를 이용해 OptionService에서 Option을 추가하는 방법이 개인적으로 직관적이라고 생각하는데 준님의 의견이 궁금합니다.
- 파사드 패턴은 실무에서도 최근들어 많이 적용하고 있는 패턴입니다.
- 컨트롤러와 서비스 사이에 파사드 패턴을 두어 상희님이 고민하시는 부분을 해결하곤 합니다. 좋습니다 :)

2. Request부분에서, 최초 ProductRequest에 Option에 대한 정보를 List로 추가해주었었는데, 마음에 들지않아(?) Create하는 Request를 추가하고, ProductRequest와 List을 필드로 가지게 하였습니다. 또 ProductCommand와 OptionCommand를 나누어 Service에 인자로 받았는데, 이부분 피드백 부탁드립니다.
- 실제 사용자가 어떻게 행동하는지에 대해 생각해보셔도 좋습니다.
- 실제 운영자들의 행동을 예측해보았을 때 상품과 옵션을 함께 추가할 것으로 얼핏 예상이 되는데요. 
- api를 나눠두면 옵션을 따로 생성하고 상품을 생성해야해서 어색한 ux가 예상됩니다.

3. OptionService에서, 다음과 같이 매서드를 분리해놓았습니다.

private ProductOption getExistsProductOption(Long productId, Long optionId) {
        var option = productOptionRepository.findByProductIdAndId(productId, optionId)
                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 상품 옵션입니다."));
        return option;
    }

    private void validateDuplicatedProductName(Long productId, String name) {
        var productOption = productOptionRepository.findByProductId(productId);

        if (productOption.stream().anyMatch(option -> option.isSameName(name))) {
            throw new IllegalArgumentException("이미 존재하는 상품 옵션입니다.");
        }
    }
이렇게 매서드를 분리하는게, 너무 분리하는건 아닌가? 싶은 생각도드는데 어떻게 생각하시는지 궁금합니다.

- 각 메서드는 하나의 역할에 충실한 것이 좋습니다.
- 검증 목적의 메소드라면 분리해두는 것이 좋다는 의견입니다.
- 묶어둘 수 있는 로직이라면 어느 정도 하나의 메소드에서 처리해도 좋겠습니다 :)

4. Validation
저는 개인적으로 Nullable 같은 부분 이외에는 거의 모든 부분이 도메인에서 검증되어야 된다고 생각해 수정하려고합니다.
Request, Command에서 빠르게 검증하는것이 좋다고는 하지만, 어떠한 다른 부분에서 도메인이 생성된다면 유효하지 않은 도메인이 생성될 수 있다고 생각하기 때문입니다.
이부분에서 준님의 견해를 듣고싶습니다!
- 충분히 좋은 의견이십니다.
- 다만 validate하는 의도에 대해서 세분화를 할 수도 있지 않을까 합니다.
- 컨트롤러에서의 validate는 입력값이 잘못되는 경우가 많습니다. 이러한 검증 로직까지 도메인으로 내리는 것은 과하다는 의견도 있습니다
- 도메인에서는 정말 도메인이 가져야 하는 성격을 검증하고, 어느 정도 광범위한 입력 같은 것은 컨트롤러 단에 두어도 되지 않을까 싶습니다. 비즈니스로직에 관한 것은 서비스에서 처리를 하고요 :)
- 도메인이 너무 무거워지는 것도 피해야 되는 방향이기도 합니다 :)

5. Stream의 사용
다음 코드에서 람다캡쳐링으로 인해 오류가 발생합니다.

    @Transactional
    public Long saveProduct(ProductCommand productRequest, List<ProductOptionCommand> productOptionRequests) {
        Category category = categoryRepository.findByName(productRequest.categoryName())
                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 카테고리입니다."));
        Product product = productRequest.toEntity(category);
        product = productRepository.save(product);

        List<ProductOption> productOptions = productOptionRequests.stream()
                .map(productOptionRequest -> productOptionRequest.toEntity(product))
                .toList();
        productOptionRepository.saveAll(productOptions);
        return product.getId();
    }
기존에 있던 product에 save의 값을 재할당 시켜주어서 effectively final이 되지 않아 발생한 오류 같습니다.
repository.save호출 시 리턴값을 버리는 방법과, 새로운 객체에 할당 시켜주는 방법이 있을 것 같은데, 어느 방법이 괜찮을까요?
또, 이와 별개로 같은 변수에 재할당 시키는 방법은 안좋은 방법일까요?

- 재할당 시키는 것은 좋은 방법은 아닌 것으로 보입니다.
- 스프링에서도 엔티티 클래스에 대해 재할당하는 것은 권장하지 않습니다.
- 이미 toEntity로 엔티티를 만들어주었으니, 이것을 그대로 사용하는 것이 깔끔한 로직으로 보입니다.
- save의 리턴값을 사용하지 않고요 :)


상희님 항상 좋은 질문 감사합니다.
고생 많으셨습니다 :)

2024-07-20 05:26 UTC, sanghee0820 commented on src/main/java/gift/product/service/ProductOptionService.java
> +        }
이 로직은, 상품에대한 옵션이 최소 한개 이상 있어야한다 -> 삭제 시 존재하는 product가 한개 인 경우 삭제가 불가능하다 라는 로직인데, 이 경우에도 <= 1 로 하는게 좋을까요?
감사합니다!

2024-07-20 08:38 UTC, sanghee0820 commented
추가적으로 질문 하나 드립니다.

Option을 적용하기 위해 일급 컬랙션을 사용하는 것에 대해 어떻게 생각하시나요? 코드는 다음과 같습니다.
```
@Entity
public class TestOptions {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne
    @JoinColumn(name = "product_id")
    private Product product;

    @ElementCollection
    private List<TestOption> testOptions = new ArrayList<>();
}
```
```
@Embeddable
public class TestOption {

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private Integer quantity;
}
```

이렇게 되면 다음과 같이 엔티티가 생성됩니다.
<img width="458" alt="스크린샷 2024-07-20 오후 5 37 06" src="https://github.com/user-attachments/assets/ae04e3ee-915f-4ab1-aa3f-5debb6aa2a01">

이렇게 되면 Options를 ProducId를 통해 접근할 수 있게 되고, 비지니스 로직을 Options에서 처리할 수 있게 될 것 같습니다.
감사합니다!

2024-07-20 13:48 UTC, khj68 commented on src/main/java/gift/product/service/ProductOptionService.java
> +        }
아하 제가 반대로 이해했군요 ㅎㅎ
확인했습니다.

2024-07-20 13:51 UTC, khj68 commented
상희님 고생하셨습니다.
질문 주신 것에서는 테이블이 과도하게 나눠지는 경향이 있는 것 같습니다.
product_option에서도 product_id를 통해 접근할 수 있는 것 아닐까요?

1:N 관계이기 때문에 굳이 중간 맵핑 테이블을 적용할 이유가 잘 보이지 않습니다.

2024-07-20 13:51 UTC, khj68 approved these changes
상희님, 고생하셨습니다 :)

2024-07-20 13:51 UTC, merged

2024-07-20 13:56 UTC, sanghee0820 commented
준님 피드백 감사합니다!!

@Entity
public class TestOptions {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne
    @JoinColumn(name = "product_id")
    private Product product;

    @ElementCollection
    private List<TestOption> testOptions = new ArrayList<>();
}
에서, ProductId로 모든 Option을 가져오기위해 ElementCollection을 사용하면 자동으로 중간 테이블을 만들어 주는 것 같더라구요.

저렇게 만들게 되면 코드상에서 Options를 통해 size를 삭제할 때 1이하라면 삭제하지 못한다 같은 비지니스 로직을 처리할 수 있을 것 같습니다. 개인적으로 조금 더 도메인적으로 생각할 수 있지 않을까 싶기도합니다.

테이블이 하나 더 늘어나는것이 왜 안좋은지 여쭤봐도 될까요?

2024-07-20 13:57 UTC, sanghee0820 commented
추가로 파사드패턴과, 일반적인 서비스호출 두개를 혼용하여 사용하는지도 궁금합니다!

2024-07-20 14:02 UTC, khj68 commented
우선 자동으로 테이블을 생성하는 것에 대해 부정적인 의견이 있습니다.
실무에서는 테이블과 데이터 하나하나가 조심스럽게 다뤄져야하기 때문에 jpa에서 auto로 생성하는 옵션을 절대 사용하지 않습니다.
그렇게 되면 jpa에 오히려 db가 종속되게 됩니다.
특정 프레임워크의 기능에 의존성이 생기게 되면 추후 언어나 프레임워크가 바뀔 때에 확장성이 떨어지게 됩니다.

따라서 프레임워크의 기능을 적절히 사용하되, 인프라 레벨의 것들이 의존적이게 되는 것에 대해서는 반대의 의견이 있습니다.



----
파사드 패턴광 일반적인 서비스 호출 두개를 혼용하여 사용하고 있습니다.
주로 서비스를 사용하다가 복잡도가 증가하거나 필요가 생길 때에 리팩토링하는 식으로 기존 코드를 보수하고 있습니다 :)