충남대 BE_신성희 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #342
Opened 2024-07-19 08:56 UTC by Shsin9797

하는데까지 해봤습니다! 좀더 수정하겠습니다!!

2024-07-19 18:48 UTC, asebn1 requested changes
성희님 안녕하세요~
1단계 코멘트 드린 부분과 2단계 PR 충돌 나는 부분 확인해주세요!
추가로 마감 기한에 맞춰서 올려주시면 리뷰하기 편합니다! (2단계 PR에서 1, 2단계를 함께 변경된 코드를 보아야해요 ㅠㅠ)

2024-07-19 18:48 UTC, asebn1 commented on README.md
> +    * 옵션 수량은 최소 1개 이상 1억 개 미만이다.
기능 요구사항 작성 좋습니다 👍 👍

2024-07-19 18:48 UTC, asebn1 commented on src/main/java/gift/dto/ProductResponseDto.java
>      }
dto에서 도메인계층인 option과 category를 의존하여 그대로 반환하고있어요
수정해봅시다!

2024-07-19 18:48 UTC, asebn1 commented on src/main/java/gift/service/OptionService.java
> +    }
서비스에서 `List<OptionResponse>`를 반환하도록 수정해봅시다

2024-07-19 18:48 UTC, asebn1 commented on src/main/java/gift/service/OptionService.java
> +    }
이 부분도 전체적으로 도메인을 반환하고있네요!

2024-07-19 19:51 UTC, Shsin9797 commented
넹 !! 🍡🐇 🦖 🐙  이제 부지런히 올릴게여 .. ㅠㅠㅋㅋㅋ 전왤케 미루기 대마왕인지 😅 🐌

2024-07-20 16:16 UTC, Shsin9797 commented on src/main/java/gift/dto/ProductResponseDto.java
>      }
3단계에서 바꿔놓겠습니다!

2024-07-20 16:16 UTC, Shsin9797 commented on src/main/java/gift/service/OptionService.java
> +    }
3단계에서 바꿔놓겠습니다!

2024-07-20 16:16 UTC, Shsin9797 commented on src/main/java/gift/service/OptionService.java
> +    }
3단계 할때 바꿔놓겠습니다!

2024-07-21 07:53 UTC, asebn1 approved these changes
2단계는 이만 머지하겠습니다 :)

2024-07-21 07:53 UTC, merged