충남대 BE_박서현 4주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #357
Opened 2024-07-19 14:54 UTC by sseooh

2024-07-21 06:29 UTC, jjongwa requested changes
3단계도 잘 구현해 주셨어요~!
정말 간단한 리뷰만 조금 남겼으니 해당 부분만 확인하고 다시 요청 주시면 바로 머지하겠습니다!

2024-07-21 06:29 UTC, jjongwa commented on src/main/java/gift/service/ProductService.java
> +    }
quantity를 감소하는 역할을 서비스에서 Option으로 넘겨보는건 어떨까요?

최대한 setter를 쓰지 않는 방식으로 코드를 작성하면 객체지향을 이해하기 쉬워질 거예요!

2024-07-21 06:29 UTC, jjongwa commented on src/main/java/gift/service/ProductService.java
> +    }
+만약 setQuantity 로직까진 올바르게 실행되고, optionRepostory.save()에서 예외가 발생하면 어떠한 상황이 일어날까요?

2024-07-21 06:29 UTC, jjongwa commented on src/test/java/gift/ProductServiceTest.java
> +    private ProductRepository productRepository;
publlic 빼도 됩니다~!

+ productRepository는 현재 사용하지 않는 것 같네요!

2024-07-21 06:29 UTC, jjongwa commented on src/test/java/gift/ProductServiceTest.java
> +        assertEquals("차감할 수량이 현재 수량보다 많습니다.", exception.getMessage());
모든 검증 로직에 assertEquals를 쓰는 것보단 assertThat과 assertThayThrownBy 등을 통해 조금 더 가독성과 해당 로직의 이유를 나타내주는 것도 좋습니다.!

2024-07-21 08:02 UTC, sseooh commented on src/main/java/gift/service/ProductService.java
> +    }
setQuantity 로직까진 올바르게 실행되고 optionRepository.save()에서 예외가 발생하게 되면 데이터베이스에는 해당 옵션 내용이 저장되지 않습니다!

2024-07-22 11:24 UTC, jjongwa commented on src/main/java/gift/service/ProductService.java
> +    }
넵넵 맞아요 그래서 이러한 메서드 같은 경우 트랜잭션이 매우매우 중요합니다~

2024-07-22 11:25 UTC, jjongwa approved these changes
👍 👍 👍

2024-07-22 11:25 UTC, merged