전남대 BE_서영우 4주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #370
Opened 2024-07-20 09:09 UTC by westzeroright

2024-07-21 12:26 UTC, pkeugine requested changes
안녕하세요 영우님,
미션 잘 진행해주셨네요!
몇 가지 코멘트 남겨보았으니 한 번 확인 부탁드려요.

2024-07-21 12:26 UTC, pkeugine commented on README.md
> +- [x] 이에 대한 적절한 테스트 코드
> 이번 과제는 전보다 리드미에 신경을 써 보았고

👍 👍 👍 
리드미 잘 정리된게 정말 보기 좋네요!!!

2024-07-21 12:26 UTC, pkeugine commented on src/main/java/gift/category/Category.java
> +    }
update 는 나름 해당 도메인의 중요한 로직 중 하나라서
getter 보다 위에 위치하면 관리할 때 더 편하지 않을까 싶어요.

2024-07-21 12:26 UTC, pkeugine commented on src/main/java/gift/category/CategoryController.java
> +    }
category 별 product 를 구하는 api 니까
오히려 uri 경로도 그렇고, 로직이 위치하는 곳도 product 쪽이 더 적절할 것 같은데,
영우님은 어떻게 생각하시나요?

2024-07-21 12:26 UTC, pkeugine commented on src/main/java/gift/option/OptionController.java
> +    }
option 으로 product 를 구할 때도 위의 코멘트와 같은 생각이에요.

2024-07-21 12:26 UTC, pkeugine commented on src/test/java/gift/category/CategoryRepositoryTest.java
> +class CategoryRepositoryTest {
> 다양한 테스트 코드 작성 기법을 배우고 테스트 코드 종류마다 필요한 정량이 있다는 것을 알게 되었습니다. 그래서 테스트 코드는 최대한 꼼꼼하게 여러 테스트 코드를 작성하는 것이 좋은 건지 궁금합니다.

이왕이면 만드는 기능에 대한 테스트, 그리고 유닛테스트가 잘 마련되어 있다면 개발하고 유지보수할 때 큰 도움이 된다고 생각해요.
하지만 모든 기능에 대해서, 모든 종류의 테스트를 다 만든다기보단 개발자 개인과 팀의 판단하에 어떤 종류의 테스트를 만들건지 결정하는게 포인트인 것 같네요. 그런데 그게 프로젝트마다 특성이 다르니 '정답'이 있다기보단 판단을 잘 해야하는거겠네요. 최대한 많은 종류의 테스트를 다 만드는게 늘 좋은건 아니라고 생각합니다. 앞서 말했듯이 그 테스트를 다 만들고 유지보수하는데 시간이 굉장히 많이 들테니까요.

> 테스트 코드는 배울수록 점점 더 어렵게 느껴지는데 테스트 코드를 어떻게 작성하는 것이 좋은지 가이드를 주시면 감사드겠습니다.

질문이 조금은 추상적인 것 같아요. 이 질문에 대한 답변은 오히려 위의 답변과는 반대되는 생각인데요, 최대한 많은 종류의 테스트를 작성해보고, 유지보수도 해보며 '아 이 상황에는 이런 종류의 테스트를 만드는 것보단 다른 종류의 테스트를 유지하는게 더 좋겠구나' 라는 생각을 해보는겁니다. 아니면 반대로 '막상 다 만들어보니 다 필요한 것들이네? 도움이 많이 되고 있어' 라고 생각을 할 수도 있어요. 직접 만들고 관리해보며 상황을 겪어봐야 가장 잘 흡수할 수 있을 것 같네요 :)

2024-07-21 12:26 UTC, pkeugine commented on src/main/java/gift/option/OptionService.java
> +        );
> 도메인으로 DTO로 변환하는 과정에서 코드에 낭비가 있다고 느꼈고 변환 클래스의 필요성에 대해서 인지하였습니다. 변환 클래스를 만드는 기준으로 얼마나 자주 사용되는가를 생각해볼 수 있을 것 같은데 지금은 2개의 DTO가 4~5개의 API에 관여하고 있지만 조금 더 프로젝트가 상세해질수록 다양한 DTO가 생길 것 같고 변환 클래스를 관리하기 어려울 것 같습니다. 따라서, 멘토님께서는 도메인에서 DTO 변환 클래스를 두는 것에 대해 어떻게 생각하시는지 궁금합니다.

저도 비슷하게 생각해요.
그리고 꽤 많은 상황에서 하나의 dto 가 한 곳에서만 쓰이는 경우가 많더라구요.
저는 그래서 영우님처럼 서비스에서 변환하거나, dto 에 정적 팩토리 메서드를 두는 편입니다.
그 방식이 그리 귀찮지는 않더라구요!

2024-07-21 12:26 UTC, pkeugine commented on src/main/java/gift/option/OptionService.java
> +        return ResponseEntity.ok("성공적으로 삭제되었습니다");
ResponseEntity, http 관련 클래스 및 로직은 controller 에서 다루면 좋을 것 같아요.
http 가 아닌 다른 프로토콜을 사용할 때도 service 를 재활용하면 좋으니까요

2024-07-21 12:28 UTC, westzeroright commented on README.md
> +- [x] 이에 대한 적절한 테스트 코드
ㅎㅎ감사합니다

2024-07-21 12:29 UTC, westzeroright commented on src/main/java/gift/category/Category.java
> +    }
넵 알겠습니다!

2024-07-21 12:31 UTC, westzeroright commented on src/main/java/gift/option/OptionService.java
> +        );
dto 정적 팩토리 메서드에 대해 알아봐야겠습니다. 감사합니다.

2024-07-21 12:45 UTC, westzeroright commented on src/main/java/gift/category/Category.java
> +    }
다만 [전에 멘토님이 조언해 주셨던 부분](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-wishlist/pull/7#discussion_r1660752585)에 대해서 생각해 본 것에 대해 답변을 드리자면,

- 상수는 가장 위에
- 멤버 변수
- 메서드 

순으로 두고 변수와 메서드 내의 순서에 관해서는 기본 설정을 위로 추가 설정을 아래에 두는 것이 제가 보기에 편할 것 같습니다. update 메서드를 찾을 때 중간보다는 아래에 있는 게 찾기 더 편할 것 같아요! 

하지만 제 코드는 저 혼자만 보는 것이 아니기 때문에 클래스 파일을 만들 때 이런 순서로 만들면 좋다!같은 게 있으면 말씀해 주시면 감사드리겠습니다 :)

2024-07-21 12:56 UTC, westzeroright commented on src/main/java/gift/category/CategoryController.java
> +    }
말씀해주신 부분대로 저도 ProductController에 해당 API들이 있는 것이 더 적절하다고 생각합니다.

구현을 할 때에도 이에 대해 생각을 해보았는데 도메인을 추가함으로써 생긴 기능이라 그 때의 도메인에 넣었습니다. 

다음부턴 해당 API가 어떤 도메인에 대한 비즈니스 로직을 수행하고 있는지 생각해 보고 구성해 보겠습니다.

2024-07-21 12:57 UTC, westzeroright commented on src/main/java/gift/option/OptionController.java
> +    }
반영해보겠습니다! 리뷰 남겨주셔서 감사합니다 😊

2024-07-21 13:01 UTC, westzeroright commented on src/test/java/gift/category/CategoryRepositoryTest.java
> +class CategoryRepositoryTest {
두 번째 문단이 많이 와닿네요! 역시 많이 경험해 보는 게 중요한 것 같아요 :) 코멘트 남겨주셔서 감사합니다 ☺️

2024-07-21 13:02 UTC, westzeroright commented on src/main/java/gift/option/OptionService.java
> +        return ResponseEntity.ok("성공적으로 삭제되었습니다");
좋은 의견 감사드립니다!

2024-07-21 13:50 UTC, pkeugine commented on src/main/java/gift/category/Category.java
> +    }
영우님께서 그렇게 생각하셨다면, 그게 맞습니다. 이 프로젝트는 영우님이 유지보수를 하는 사람이니까요.
저는 개인적으로 getter 처럼 비즈니스 로직에 영향을 크게 끼치지 않는 메서드는 아래로 내리는 편이에요.
프로젝트가 커질수록 로직도 많아질거고, 이왕이면 그 많은 로직들이 빠르게 찾을 수 있는 곳에 위치하는게 좋더라구요!

2024-07-21 13:52 UTC, pkeugine commented on src/test/java/gift/category/CategoryRepositoryTest.java
> +class CategoryRepositoryTest {
통합테스트와 유닛테스트를 중점으로 한 번 학습해보아요!!!!

2024-07-21 13:54 UTC, pkeugine approved these changes
안녕하세요 영우님,
이번 미션도 고생 많으셨습니다.
주말 잘 마무리하시고, 다음 미션에서 다시 뵙도록 할게요.
조금만 더 파이팅입니다!! 🔥 🔥 🔥

2024-07-21 13:54 UTC, merged

2024-07-30 13:22 UTC, westzeroright commented on src/main/java/gift/category/Category.java
> +    }
좋습니다!

2024-07-30 13:23 UTC, westzeroright commented on src/test/java/gift/category/CategoryRepositoryTest.java
> +class CategoryRepositoryTest {
넵 알겠습니다!