전남대 BE_박준형 4주차 과제(step3)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #373
Opened 2024-07-20 10:13 UTC by cliant

### 코드를 작성하면서 어려웠던 점

- 테스트 코드를 작성하면서 어려움을 겪었던 것 같습니다. 우선 기본적인 성공 테스트만 진행하도록 하였고 실패 테스트도 추가해볼 생각입니다. 테스트 코드의 흐름.? 이 맞는지와 수정할 점을 짚어주셨으면 합니다.

2024-07-21 07:25 UTC, jjongwa requested changes
3주차까지 잘 구현해 주셨어요!
실패하는 테스트가 있는데 해당 부분 변경 후 다시 요청해 주세요~!

2024-07-21 07:25 UTC, jjongwa commented on src/main/java/gift/controller/OptionController.java
> +    public ResponseEntity<?> addOption(@Valid @RequestBody OptionDto optionDto, BindingResult bindingResult, @PathVariable Long id){
앗ㅎㅎ 개인적인 생각이지만 productId로 맞춰주는게 가독성 측면에서 더 나을 수도 있을 것 같다고 생각이 드네요!

(물론 지금은 상관 없습니다!ㅎㅎ)

2024-07-21 07:25 UTC, jjongwa commented on src/main/java/gift/entity/Option.java
> +    }
수량 차감 로직 Option이 가지고 있는거 굿입니다~~ 👍 

조금 더 객체지향적으로 사용하려면 

```
public Option subtract(int substractQuantity){
        if(this.quantity <= substractQuantity){
            throw new CustomException("substract quantity is too big", HttpStatus.BAD_REQUEST);
        }
        return new Option(this.product, this.name, this.quantity - substractQuantity);
    }
```

이런 식으로 새로운 인스턴스를 만들어 반환하고, 이를 save해주는게 좋습니다!

지금도 물론 quntity를 줄이면 JPA가 알아서 db에까지 반영을 하겠지만, 로직이 복잡해지면 이렇게 엔티티의 필드값이 바뀌는 부분에 대해 모두 관리를 해야한다(알고 있어야 한다)는 단점이 있어요!

2024-07-21 07:25 UTC, jjongwa commented on src/main/resources/application.properties
> +# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
쓰지 않는건 지워주세요~! (다음 주차에서~)

2024-07-21 07:25 UTC, jjongwa commented on src/test/java/gift/service/OptionServiceTest.java
> +
OptionService를 `@InjectMocks` 로 놓고 SpringBoot 테스트가 아닌 완전한 모킹 테스트로 만들 수도 있었을 텐데, 이러한 방식을 선택한 이유가 있을까요?

2024-07-21 07:25 UTC, jjongwa commented on src/test/java/gift/service/OptionServiceTest.java
> +    }
요거 실패하는 거 같아요..!

<img width="631" alt="image" src="https://github.com/user-attachments/assets/13286766-bd74-47b5-a93b-d116a101819c">

2024-07-21 07:25 UTC, jjongwa commented on src/test/java/gift/service/OptionServiceTest.java
> +    }
테스트 흐름은 뭐 완벽합니다! 이렇게 짜면 충분하죠ㅎㅎ

조오금 디테일을 추가한다면 전 요렇게 바꿀 수 있을 것 같네요.!

```
@DisplayName("상품 ID를 통해 옵션을 올바르게 가져올 수 있다.")
@Test
    void findByProductId(){
        //given
        final Long productId = 1L;
        final Category category = new Category("category", "color", "url", ""); 
        final Product product = new Product("product", 0, "imageUrl", category);
        final Option option = new Option(product, "option", 1);

        //when
        when(productRepository.findById(productId))
            .thenReturn(Optional.of(product));
        when(optionRepository.findByProductId(productId))
            .thenReturn(List.of(option));

        final OptionResponse optionResponse = optionService.findByProductId(1L);

        // then
        assertAll(
            () -> assertNotNull(optionResponse),
            () -> assertEquals(option.getQuantity(), optionResponse.getOptions().size()),
            () -> assertEquals(option.getName(), optionResponse.getOptions().get(0).getName())
        );
    }
```

2024-07-21 07:25 UTC, jjongwa commented on src/test/java/gift/service/OptionServiceTest.java
> +    }
요런 테스트의 경우 결국 검증하는게 verify밖에 없다면 완전한 mock 테스트로도 충분해 보입니다!

2024-07-21 08:01 UTC, cliant commented on src/main/java/gift/controller/OptionController.java
> +    public ResponseEntity<?> addOption(@Valid @RequestBody OptionDto optionDto, BindingResult bindingResult, @PathVariable Long id){
반영하였습니다!

2024-07-21 08:02 UTC, cliant commented on src/main/java/gift/entity/Option.java
> +    }
넵! 기존 Option을 삭제하고 updatedOption을 save해주는 식으로 변경하였습니다.

2024-07-21 08:03 UTC, cliant commented on src/test/java/gift/service/OptionServiceTest.java
> +
InjectMocks에 대한 학습이 부족해 클론 코딩 강의에서 들은 MockBean을 사용했습니다. Mock에 대해 학습 하고 리팩토링해보겠습니다!

2024-07-21 08:04 UTC, cliant commented on src/test/java/gift/service/OptionServiceTest.java
> +    }
넵 수정하였습니다!

2024-07-21 08:05 UTC, cliant commented on src/test/java/gift/service/OptionServiceTest.java
> +    }
전체적인 코드에  final키워드를 적극 사용하는 방향으로 리팩토링 해보겠습니다! 감사합니다

2024-07-22 11:27 UTC, jjongwa commented on src/test/java/gift/service/OptionServiceTest.java
> +
넵넵 강의에서 들은 방식을 충분히 잘 활용하는게 기본이니 너무 부담갖지 않고 천천히 학습해보셔도 됩니다!

2024-07-22 11:32 UTC, jjongwa commented on src/test/java/gift/service/OptionServiceTest.java
> +    }
앗.! final이 중요하다기 보단 assert 검증문에서 비교하는 부분이 의도였습니다.!

given에서 주어진 우리가 예상하는 값(option.get~~ 에 해당하는 값)과 실제 로직을 거쳐 생성된 actual값(optionResponse에서 나온 값)을 비교하는게 가장 기본적인 흐름이에요!

기존에 있던 1과, "option" 같은 값은 물론 준형님이 given에서 만들어놓은 객체의 내부 필드와 같은 값을 가지지만 엄연히 다른 객체이니까요.!

항상 **expected** vs **actual**이 기본이다! 를 기억하면 좋을 것 같습니다~!

2024-07-22 11:33 UTC, jjongwa approved these changes
4주차 수고 많으셨습니다ㅎㅎ

앞으로 남은 5, 6주차도 파이팅하세요~~!! 🦾

2024-07-22 11:33 UTC, merged