경북대 BE_김은선 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #378
Opened 2024-07-20 11:29 UTC by eunsoni

상품 추가, 수정, 조회 기능에 옵션을 적용해두었습니다
1. 관리자가 상품 저장할 때 옵션 생성 및 저장
2. 상품리스트에서 각 상품에 해당되는 옵션들 조회, 선택 그리고 저장 
3. 디비 위시리스트 테이블의 OPTIONNAME 컬럼에 선택된 옵션의 이름 저장

+위시리스트 페이지에서 선택된 옵션을 표시하는 기능을 추가하고 싶어서 WishlistController의 getWishlistItems 메소드를 수정하는 중에 있습니다.

2024-07-21 09:12 UTC, gongdongho12 requested changes
2단계 작업 고생 많으셨습니다
작업 내용중에 옵션의 중복 부분이 빠져있는 점을 DB 관점에서 풀어보시면 좋을 것 같습니다!
3단계는 테스트 작성인데 이번 수정사항 작업하시면서 어떤 방향으로 테스트를 설계해볼지 같이 고민해주세요 👍🏼

2024-07-21 09:12 UTC, gongdongho12 commented on src/main/java/gift/controller/OptionController.java
> +    }
옵션 아이디별 조회와 상품 아이디별 조회를 구분하기 위해 product를 사용하신 것 같아요!
이부분은 어짜피 상품 조회할 때 한번에 조회해야 하는 대상으로 보이는데요
의견) 상품 조회 내부에 포함시키고 API로는 별도로 만들어주지 않아도 괜찮지 않을까요?

2024-07-21 09:12 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +            dto.setOptions(v.getOptions().stream().map(OptionDto::new).collect(Collectors.toList()));
옵션을 DTO로 바꾸는 기능인데요, getOptionsToDto() 같은 메서드로 적용해도 깔끔하지 않을까요?
DTO나 DAO 전환에 이런 스트림 문법이 자주 보이는데 공통화 되면 좋을 것 같습니다

2024-07-21 09:12 UTC, gongdongho12 commented on src/main/java/gift/controller/ProductController.java
> +
path가 API인데 페이지 전환 기능과 함께 표현되고 있는 것 같아요
html을 렌더링해주는 템플릿 페이지와 실제 API를 구분지어서 정리해보면 좋지 않을까요?

2024-07-21 09:12 UTC, gongdongho12 commented on src/main/java/gift/entity/Wishlist.java
> +        this.optionName = optionName;
위시리스트에 단순 상품이 아닌 옵션까지 구체화 하셨군요 💯

2024-07-21 09:12 UTC, gongdongho12 commented on src/main/java/gift/entity/Product.java
> +    }
옵션은 상품 하위로 업데이트 가능하게 제한했군요 👍🏼

2024-07-21 09:12 UTC, gongdongho12 commented on src/main/java/gift/entity/Product.java
> +    }
여기에 만약 setProduct를 안 해주었을 때도 확인해보셨을까요?

2024-07-21 09:12 UTC, gongdongho12 commented on src/main/java/gift/service/OptionService.java
> +        }
만약 optionDetails에 product_id가 다르다거나 id가 다르면 validation이 이루어지는게 맞지 않을까요?
이름과 갯수만 쓴다고 하더라두요

2024-07-21 09:12 UTC, gongdongho12 commented on src/main/java/gift/repository/OptionRepository.java
> +    Set<Option> findByProductId(Long productId);
옵션의 조회는 Set을 통해 중복을 방지할텐데요
저장은 따로 중복 방지를 하지 않아도 괜찮을까요?

2024-07-21 09:12 UTC, gongdongho12 commented on src/main/java/gift/entity/Product.java
> +    }
옵션의 중복을 막을 방안에 대해 고민이 필요할 것 같아요!

2024-07-21 09:12 UTC, gongdongho12 commented on src/main/java/gift/service/WishlistService.java
> +        Optional<Option> optionOptional = optionService.getOptionById(optionId);
서비스에서 가져온 값은 optional로 하기 보다는 서비스 자체 메서드에서 리턴될 떄 null이면 예외를 포함시켜두는게 깔끔하지 않을까요?

2024-07-21 17:11 UTC, eunsoni commented on src/main/java/gift/entity/Product.java
> +    }
옵션삭제기능은 요구사항이 아니어서 메소드만 만들어 놓은 상태입니다! 
테스트해보지않았고 쓰지않는 기능이 될 것 같아서 삭제하게 될 것 같습니다!

2024-07-21 17:14 UTC, eunsoni commented on src/main/java/gift/controller/ProductController.java
> +            dto.setOptions(v.getOptions().stream().map(OptionDto::new).collect(Collectors.toList()));
옵션을 DTO로 바꾸는 기능 추가하고 다른 부분들도 찾아서 수정하겠습니다!

2024-07-22 07:25 UTC, eunsoni commented on src/main/java/gift/controller/OptionController.java
> +    }
확인해보니 ProductController(getProducts)에서 상품 조회할 때 옵션도 같이 조회하고 있어서 삭제하겠습니다!

2024-07-22 11:36 UTC, eunsoni commented on src/main/java/gift/controller/ProductController.java
> +
넵 html 렌더링은 /api가 아니라 /view로 시작하도록 구분해놓았습니다

2024-07-22 12:08 UTC, eunsoni commented on src/main/java/gift/service/OptionService.java
> +        }
validation 추가했습니다!

2024-07-23 06:23 UTC, eunsoni commented on src/main/java/gift/service/WishlistService.java
> +        Optional<Option> optionOptional = optionService.getOptionById(optionId);
서비스에 예외처리하는 방식으로 변경하였습니다 !!

2024-07-23 06:31 UTC, eunsoni commented on src/main/java/gift/entity/Product.java
> +    }
`private void checkDuplicateOptionName(String optionName) {
        for (Option option : options) {
            if (option.getName().equals(optionName)) {
                throw new IllegalArgumentException("같은 상품 내에 있는 옵션들의 이름은 중복될 수 없습니다.");
            }
        }
    }`
    
    일단 옵션 중복 저장을 방지하기 위해서 Product 엔터티에 예외처리해두었습니다.
    그런데 옵션 기능을 '상품 추가' 기능에 추가한 이후에 '상품 추가' 기능이 정상적으로 작동하지 않아서 수정해보았는데 해결하지 못했습니다.
    관리자가 옵션을 추가하는 기능은 이번 과제에서 선택사항이라서 프로젝트 종료 후에 이어서 구현해야할지 고민입니다..

2024-07-23 06:37 UTC, eunsoni commented on src/main/java/gift/repository/OptionRepository.java
> +    Set<Option> findByProductId(Long productId);
위에서 Product 엔터티에 중복 예외처리로 이 문제도 해결되는 것이 맞을까요?

2024-07-23 14:56 UTC, gongdongho12 commented on src/main/java/gift/repository/OptionRepository.java
> +    Set<Option> findByProductId(Long productId);
넵 맞습니다!

2024-07-23 15:46 UTC, gongdongho12 commented on src/main/java/gift/entity/Product.java
> +    }
@eunsoni 예외를 로직에 넣기 보다는 DB의 유니크 키 기능을 활용해보면 어떨까 싶습니다!
이부분은 유니크키 멀티 칼럼 관련해서 검색해보시구 만약 이해안가는 부분이 있으면 질문주시면 제가 실제 예시상황을 제공해볼게요

4주차 과제 기간이 길어지구 있어서 머지해두겠습니다

2024-07-23 15:47 UTC, gongdongho12 approved these changes
4주차 작업이 너무 길어지고 있어서 추후 작업하실 때, 코멘트 드린부분에 대해 염두하고 작성해보시면 좋을 것 같습니다
작업해야 할 내용도 많은데 학습도 같이 진행하시느라 정말 고생많으셨습니다 🥇

2024-07-23 15:47 UTC, merged