충남대 BE_이은경 4주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #379
Opened 2024-07-20 12:39 UTC by pkyung

## 과제 진행 사항
### 옵션 수량 차감
- [x] 수량 차감 메서드 생성
- [x] 얼만큼 양을 뺄 건지의 dto
- [x] 부족한 수량에 대한 exception 생성

2024-07-21 04:35 UTC, ksy90101 requested changes
고생많으셨어요~
간단한 피드백을 남겼으니 확인해주세요!

2024-07-21 04:35 UTC, ksy90101 commented on src/main/java/gift/dto/OptionSubtractRequest.java
> +public record OptionSubtractRequest(
Null 체크는 괜찮을까요?

2024-07-21 04:35 UTC, ksy90101 commented on src/main/java/gift/exception/OutOfStockException.java
> +}
```suggestion
}

```

2024-07-21 04:35 UTC, ksy90101 commented on src/main/java/gift/model/Option.java
> +        if (this.quantity - quantity >= 0) {
this.quantity - quantity
이 부분을 변수로 지정해두면 어떨까요?
그럼 훨씬 더 깔끔한 코드가 될거 같습니다.

2024-07-21 04:35 UTC, ksy90101 commented on src/main/java/gift/model/Option.java
> +        if (this.quantity - quantity >= 0) {
if(new quantity < 0) {
            throw new OutOfStockException("해당 옵션의 수량이 부족합니다.");
}
이런식의 코드가 더 좋지 않을까요?

2024-07-21 04:35 UTC, ksy90101 commented on src/main/java/gift/model/Option.java
> +    public void subtract(Long quantity) {
이부분에 대한 테스트 코드를 작성해보면 어떨까요?
모델의 테스트 코드도 한번 연습해보시면 좋을거 같아요.

2024-07-21 04:35 UTC, ksy90101 commented on src/test/java/gift/service/OptionServiceTest.java
> +    }
이건 옵션 테스트 아닌가요?

2024-07-21 04:35 UTC, ksy90101 commented on src/main/java/gift/service/OptionService.java
> +    public void subtractQuantity(OptionSubtractRequest request) {
이부분에 대한 테스트코드 잘 되었는지 체크해보면 좋겠습니다.

2024-07-21 07:04 UTC, pkyung commented on src/main/java/gift/dto/OptionSubtractRequest.java
> +public record OptionSubtractRequest(
저번에 json 형식으로 입력 받을 때 정수형은 null이 불가능하다고 하셔서 하지 않았습니다!

2024-07-21 07:06 UTC, pkyung commented on src/main/java/gift/model/Option.java
> +        if (this.quantity - quantity >= 0) {
네 변수로 지정하도록 하겠습니다.

2024-07-21 07:06 UTC, pkyung commented on src/main/java/gift/model/Option.java
> +        if (this.quantity - quantity >= 0) {
그렇게 하면 return도 안 쓸 수 있어서 좋은 것 같습니다. 수정하겠습니다.

2024-07-21 07:28 UTC, pkyung commented on src/main/java/gift/model/Option.java
> +    public void subtract(Long quantity) {
네 적용해보겠습니다.

2024-07-21 07:28 UTC, pkyung commented on src/test/java/gift/service/OptionServiceTest.java
> +    }
수정했습니다.

2024-07-22 01:31 UTC, ksy90101 approved these changes
고생많으셨습니다~
5주차 미션에서 뵐게요!
홧팅입니다!

2024-07-22 01:31 UTC, ksy90101 commented on src/main/java/gift/dto/OptionSubtractRequest.java
> +public record OptionSubtractRequest(
primery Type vs Boxed Type의 차이를 한번 알아보시면 좋을거 같습니다.

참고링크 : https://stackoverflow.com/questions/2382058/unboxing-null-object-to-primitive-type-results-in-nullpointerexception-fine

2024-07-22 01:31 UTC, ksy90101 commented on src/main/java/gift/model/Option.java
> +        this.quantity -= quantity;
```suggestion
        this.quantity = remainingQuantity;
```

굳이 두번 계산할 필요가 없을거 같아서 변수 추출을 이야기 드린거였습니다.

2024-07-22 01:32 UTC, merged