경북대 BE 탁정민 4단계 Step3
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #380
Opened 2024-07-20 12:51 UTC by xkrwjdals

약먹고 많이 괜찮아졌습니다! 감사합니당

# 질문
`fetch` 는 언제 사용하면 좋은 것인지 궁금합니다! `step2` 피드백에서 `fetch` 사용에 대한 피드백을 주셨는데, 해당 개념을 처음들어봐 검색을 해봤습니다. 옵션 객체는 상품에 최대 1억개까지 추가될 수 있어서 `fetch` 사용을 권하신걸까요?

2024-07-21 10:43 UTC, jadie0319 commented
안녕하세요 정민님!
4주차 미션하시느라 고생 정말 많으셨습니다.
질문 주신것 답변 드릴게요

# 질문
`fetch` 는 언제 사용하면 좋은 것인지 궁금합니다! `step2` 피드백에서 `fetch` 사용에 대한 피드백을 주셨는데, 해당 개념을 처음들어봐 검색을 해봤습니다. 옵션 객체는 상품에 최대 1억개까지 추가될 수 있어서 `fetch` 사용을 권하신걸까요?

# 답변
아닙니다. 단순히 궁금해서 여쭤본거에요ㅎ 만약 잘 모르신다면 이번 기회에 공부하셨으면 하는 마음에서 질문 드렸습니다. `@ManyToOne` 사용할 때 fetch 를 직접 지정하지 않으면 featch 가 EAGER 방식으로 동작을 해요. `@OneToMany` 는 LAZY 방식으로 동작합니다. 이 설정을 필요에 맞게 적절히 사용해야 데이터를 조회할 때 문제가 발생하지 않는데, 설정을 안해주셔서 질문드린거에요. 보통 연관관계 매핑을 할 때 fetch 설정을 하기 때문에 지식이 있으셔서 일부러 안쓰신건지 궁금해서 여쭤본거에요! 

만약 잘 모르신다면 EAGER 로딩 방식, LAZY 로딩 방식, N+1 문제등의 키워드로 검색을 해보시면 많은 공부가 되실거에요 🙂

2024-07-21 12:00 UTC, jadie0319 requested changes
안녕하세요 정민님. 
4주차 미션하시느라 고생 많으셨습니다.
피드백과 질문에 대한 답변 남겼으니 확인 부탁바랍니다!

2024-07-21 12:00 UTC, jadie0319 commented on src/main/java/gift/controller/CategoryController.java
피드백 반영 좋습니다 👍

2024-07-21 12:00 UTC, jadie0319 commented on src/main/java/gift/model/Option.java
> +    }
만약 차감하려는 quantity 의 값이 더 크면 quantity 가 음수가 나올거에요.
음수가 되지 않게 유효성 검사 로직을 추가해볼까요?

2024-07-21 12:00 UTC, jadie0319 commented on src/main/java/gift/model/Option.java
> +        if (product != null && !product.getOptions().contains(this)) {
```suggestion
        if (product != null && !product.contains(this)) {
```
점(.) 을 하나만 찍을 수 있게 위와 같이 변경해보면 어떨까요?
그러면 좀 더 객체지향적인 코드가 될 것 같아요~

2024-07-21 12:00 UTC, jadie0319 commented on src/main/java/gift/model/Product.java
> +    private List<Option> options = new ArrayList<>();
casecade 설정 좋습니다!

2024-07-21 12:00 UTC, jadie0319 commented on src/main/java/gift/model/Option.java
> +    }
테스트 코드도 추가해보면 좋을 것 같아요~

2024-07-21 12:00 UTC, jadie0319 commented on src/main/java/gift/service/OptionService.java
>              product);
OptionService#updateOption() 기능은 옵션의 정보를 변경하는 기능 같아요.
옵션만 조회하고 옵션의 name 이나 quantity 만 변경하면 될 것 같은데 product 도 조회해야 할까요?
product 로직을 삭제하면 아래와같은 코드가 될것 같아요!
```java
public OptionDTO updateOption(long optionId, OptionDTO optionDTO) {
    Option option = optionRepository.findById(optionId)
            .orElseThrow(() -> new RepositoryException(ErrorCode.OPTION_NOT_FOUND, optionId));
    option.update(optionDTO.name(), optionDTO.quantity());
    return convertToDTO(optionRepository.save(option));
}
```

2024-07-21 15:52 UTC, xkrwjdals commented
@jadie0319  
피드백 반영 완료했습니다!

2024-07-22 00:55 UTC, jadie0319 approved these changes
피드백 반영하시느라 고생하셨습니다!
5주차 미션을 위해 머지할게요!
5주차도 화이팅 하세요!

2024-07-22 00:55 UTC, merged