충남대 BE_이택 4주차 과제 step3
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #385
Opened 2024-07-20 16:10 UTC by LeeTaek2T

2024-07-22 01:33 UTC, ksy90101 requested changes
고생많으셨습니다~
간단한 피드백을 남겼으니 확인해주세요!

2024-07-22 01:33 UTC, ksy90101 commented on src/main/java/gift/DTO/Option.java
> +  public boolean subtract(int amount) {
boolean을 리턴해야 하는 이유가 무엇인가요?

2024-07-22 01:33 UTC, ksy90101 commented on src/main/java/gift/Service/OptionService.java
> +  public boolean optionQuantitySubtract(Long id, int amount) {
여기도 boolean이여야 하는 이유가 무엇인가요?

2024-07-22 01:33 UTC, ksy90101 commented on src/main/java/gift/Service/OptionService.java
> +  public boolean optionQuantitySubtract(Long id, int amount) {
DTO를 만들어서 처리하면 어떨까요?

2024-07-22 01:33 UTC, ksy90101 commented on src/main/java/gift/DTO/Option.java
> +  public boolean subtract(int amount) {
이부분도 테스트 코드를 작성해주시면 좋을거 같습니다.

2024-07-22 05:19 UTC, LeeTaek2T commented on src/main/java/gift/Service/OptionService.java
> +  public boolean optionQuantitySubtract(Long id, int amount) {
그게 더 좋은 방법인 것 같습니다!
수정하겠습니다!

2024-07-22 05:46 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Option.java
> +  public boolean subtract(int amount) {
네 작성하겠습니다!

2024-07-22 05:48 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Option.java
> +  public boolean subtract(int amount) {
실제로 무엇을 넘겨줘야 될지 감이 안잡혀서 boolean으로 리턴을 하였습니다.
하지만 실제 동작을 생각해보니 리턴값이 필요하지 않다는 생각이 들어 void로 변경하겠습니다.

2024-07-22 05:49 UTC, ksy90101 commented on src/main/java/gift/DTO/Option.java
> +  public boolean subtract(int amount) {
예외를 던지면 되죠~

2024-07-22 06:00 UTC, LeeTaek2T commented on src/main/java/gift/Service/OptionService.java
> +  public boolean optionQuantitySubtract(Long id, int amount) {
제대로 잘 차감되었는지 확인할 수 있도록 boolean으로 해두었습니다

2024-07-22 10:56 UTC, LeeTaek2T commented on src/main/java/gift/DTO/Option.java
> +  public boolean subtract(int amount) {
나중에 쓸 것이라 생각해서 너무 막연하게 생각했던 것 같습니다..
집중하겠습니다!

2024-07-22 13:49 UTC, ksy90101 approved these changes
고생하셨습니다~
간단한 질문 드렸는데 5주차에서 같이 해보시죠!

2024-07-22 13:49 UTC, ksy90101 commented on src/test/java/gift/OptionTest.java
> +  void subtractTest() throws IllegalAccessException {
모델 테스트에서 Mock을 쓸 필요가 없어보이는데요.
혹시 Mock을 쓰신 이유가 있나요?

2024-07-22 13:49 UTC, merged

2024-07-22 16:31 UTC, LeeTaek2T commented on src/test/java/gift/OptionTest.java
> +  void subtractTest() throws IllegalAccessException {
특별한 이유는 없었습니다.
저도 생각해보니 Mock을 쓸 이유가 없다는 생각이 들어 SpringbootTest로 바꿨습니다!

2024-07-22 16:38 UTC, ksy90101 commented on src/test/java/gift/OptionTest.java
> +  void subtractTest() throws IllegalAccessException {
Springboot도 필요없습니다
모델은 모델 그자체로 테스트 하면 되기때문에 실제 클래스를 그냥 테스트한다고 보면 됩니다

2024-07-23 05:27 UTC, LeeTaek2T commented on src/test/java/gift/OptionTest.java
> +  void subtractTest() throws IllegalAccessException {
네! 알겠습니다!!
감사합니다