충남대 BE_이동현 4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #389
Opened 2024-07-20 19:01 UTC by Thornappl2

- DTO 관련 공부를 진행하던 중, DTO를 Request와 Response로 나눠 설계하는 것이 더 옳은지가 궁금합니다.
- 옵션 또한 리스트로 구현을 진행하다 보니, 상품 생성 시 로직을 많이 고민하였습니다.
- createProduct에서, 람다 캡처링 문제가 발생하여 이를 해결하는 것이 힘들었습니다.

2024-07-21 04:44 UTC, ksy90101 requested changes
간단한 피드백을 남겼으니 확인해주세요~
언제든 홧팅입니다!

2024-07-21 04:44 UTC, ksy90101 commented on src/main/java/gift/controller/OptionController.java
> +        return ResponseEntity.ok(savedOption);
create인 경우엔 201 status를 사용하는 편입니다.
한번 201 status를 한번 공부해보시면 어덜까요?

2024-07-21 04:44 UTC, ksy90101 commented on src/main/java/gift/dto/OptionDTO.java
> +public class OptionDTO {
DTO에 계속 setter가 들어가네요 ㅠㅠ

setter가 필요 없는데, 혹시 왜 필요 없을지 공부해보시면 어덜까 해요. ㅠ

2024-07-21 04:44 UTC, ksy90101 commented on src/main/java/gift/model/Option.java
> +public class Option {
중복된 옵션은 구매 시 고객에게 불편을 줄 수 있다. 동일한 상품 내의 옵션 이름은 중복될 수 없다.

이부분에 대해서 유니크 인덱스를 한번 공부해보고 적용해보면 어떨까요?

2024-07-21 04:44 UTC, ksy90101 commented on src/main/java/gift/model/Product.java
> +    private List<Option> options;
중복된 옵션은 구매 시 고객에게 불편을 줄 수 있다. 동일한 상품 내의 옵션 이름은 중복될 수 없다.

이부분에 대한 validate를 도메인 로직 내에서 체크해보면 어떨까요?

2024-07-21 04:44 UTC, ksy90101 commented on src/main/java/gift/service/OptionService.java
> +            throw new IllegalArgumentException("Option name already exists for this product");
👍

2024-07-21 15:29 UTC, Thornappl2 commented on src/main/java/gift/controller/OptionController.java
> +        return ResponseEntity.ok(savedOption);
공부한 후 수정하였습니다

2024-07-21 15:31 UTC, Thornappl2 commented on src/main/java/gift/dto/OptionDTO.java
> +public class OptionDTO {
네 알겠습니다

2024-07-21 15:45 UTC, Thornappl2 commented on src/main/java/gift/model/Option.java
> +public class Option {
공부 후 적용하였습니다.

2024-07-21 16:30 UTC, Thornappl2 commented on src/main/java/gift/model/Product.java
> +    private List<Option> options;
도메인 로직 내에 검증 메서드를 생성하고, 서비스에서 검증을 수행하는 식으로 수정하였습니다.

2024-07-22 01:37 UTC, ksy90101 approved these changes
고생많으셨습니다~
3단계에서 뵐게요!
홧팅입니다!

2024-07-22 01:37 UTC, merged