전남대 BE_김보민_4주차 과제 (2단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #390
Opened 2024-07-20 19:05 UTC by KBM05haruin30

# 2단계
### 코드 작성하면서 어려웠던 점
처음에 quantity 개념을 제대로 이해하지 못했습니다. 저는 사용자가 구매할 수량이라고 생각하여 코드를 작성 중이었는데 너무 어려워 팀원들에게 quantity가 무엇인지 물어보았습니다. 이 때 quantity는 상품의 남은 수량이라는 것을 알게 되어 다시 코드를 작성하다 보니 많이 늦어졌습니다. 
과제의 요구 사항 중 '상품에는 항상 하나 이상의 옵션이 있어야 한다.' 부분을 해결하기 위해 어떻게 할 지 고민을 좀 했었습니다. 생각한 것은 상품이 만들어질 때마다 임시 옵션을 부여하는 것이었습니다. 추가로 옵션이 1 개가 될 때 지울 수 없도록 하면 항상 하나 이상의 옵션을 갖게 된다고 생각했습니다. 이걸 바탕으로 코드를 작성했습니다.
요구 사항 중 동일한 상품 내의 옵션 이름은 중복될 수 없다는 것이 어려웠습니다. 동일한 상품이므로 product_id를 사용하고, 옵션 이름이므로 name을 사용해야 한다는 것은 알겠는데 이걸 어떻게 사용해야 하는지 몰랐었습니다. 검색을 하다 보니 나온 것은 exists였습니다. product_id와 name으로 이미 존재하는지 확인하는 메서드를 Repository에 작성했습니다. 이걸 사용하여 요구 사항을 해결할 수 있었습니다.

### 중점적으로 봐주셨으면 하는 점
요구 사항을 잘 만족했는지 봐주셨으면 합니다. 추가로 테스트 코드도 봐주셨으면 합니다. 

### 궁금한 점
현재 step1 브랜치에서 step2 브랜치를 만들었습니다. 저번의 rebase를 통해서 step1의 커밋들을 안보이게 하고 싶었지만 잘 안됩니다.. 만약 step1이 머지가 된 이후 rebase를 하게 된다면 step2 pr에서 step1의 커밋들이 안보이게 되는지 궁금합니다.
data.sql에 INSERT INTO options를 사용하여 임시 데이터를 넣기 위해 코드를 작성했습니다. 다른 테이블의 값은 생성되었지만 options 테이블만 값이 입력되지 않았습니다. 이를 해결하기 위해 `application.properties` 에 `spring.jpa.hibernate.ddl-auto=update` 를 입력하였습니다. 왜 options 테이블에만 값이 입력되지 않은 것인지 궁금합니다.
기능 요구 사항을 만족하기 위해 상품이 생성될 때 임시 옵션을 추가하는 방식으로 했습니다. 이 방식이 아닌 다른 방식으로 기능 요구 사항을 만족 시킬 수 있는지 궁금합니다.

2024-07-21 08:52 UTC, Hongdonggeon requested changes
보민님 안녕하세요
2단계도 비교적 요구사항이 간단하네요
현재 update 메서드를 만들어줬는데 메서드명만 다르지 setter와 크게 다른게 없는 것 같아요 
어떻게 하면 좋을지 고민해보면 좋을 것 같습니다
수고하셨어요!

2024-07-21 08:52 UTC, Hongdonggeon commented on src/main/java/gift/model/Product.java
> +    public void updateName(String name) {
setter와 다른게 뭘까요?

2024-07-21 08:52 UTC, Hongdonggeon commented on src/main/java/gift/service/ProductService.java
> +            existingProduct.updateImageUrl(productDTO.imageUrl());
각 필드에 대해 update 메서드를 만드는 것보다 모든 필드에 대해 합쳐주는게 좋을 것 같아요

2024-07-21 08:52 UTC, Hongdonggeon commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
이 옵션을 추가한 이유가 뭘까요?

2024-07-21 08:52 UTC, Hongdonggeon commented on src/main/java/gift/model/Option.java
> +    @JoinColumn(name = "product_id", nullable = false)
다대일 연관관계로 맺은 이유가 궁금해요 (그냥 보민님 생각이 궁금해서)

2024-07-21 09:05 UTC, KBM05haruin30 commented on src/main/java/gift/model/Option.java
> +    @JoinColumn(name = "product_id", nullable = false)
카테고리와 상품의 관계와 비슷하다고 생각했습니다. 하나의 카테고리 안에 여러 개의 상품이 존재할 수 있듯이 이것도 하나의 상품 안에 여러 개의 옵션이 존재할 수 있다 생각하여 다대일 연관 관계로 맺엇습니다!

2024-07-21 09:20 UTC, KBM05haruin30 commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
data.sql에 INSERT INTO options를 사용하여 임시 데이터를 넣기 위해 코드를 작성했습니다. 다른 테이블의 값은 생성되었지만 options 테이블만 값이 입력되지 않았습니다. 이를 해결하기 위해 application.properties 에 spring.jpa.hibernate.ddl-auto=update 를 입력하였습니다. 
ddl-auto 중 update는 엔티티와 데이터베이스 테이블의 구조가 비교하여 필요할 때 테이블을 수정해 주는 것입니다. 
엔티티와 데이터베이스 테이블 구조를 적절하게 작성했다고 생각하였는데 잘 되지 않아서 이를 해결하고자 사용했었습니다..

2024-07-21 11:03 UTC, KBM05haruin30 commented on src/main/java/gift/service/ProductService.java
> +            existingProduct.updateImageUrl(productDTO.imageUrl());
넵 알겠습니다!

2024-07-21 11:05 UTC, KBM05haruin30 commented on src/main/java/gift/model/Product.java
> +    public void updateName(String name) {
처음에는 한꺼번에 업데이트가 가능하도록 만들려고 했었습니다. 그러다가 생각난 것이 하나씩 업데이트를 하면 테스트하기 편할 것 같다고 생각했습니다. 그렇게 생각하다 보니 이름만 바꾸게 되어 setter의 동작과는 달라진 것이 없던 것 같습니다. 굳이 비교하자면 메서드 이름이 더 사용한 의도나 의미를 알 수 있다는 점이 있습니다. 수정한 코드가 setter와의 동작이 같으므로 필드를 한 번에 업데이트하는 메서드로 수정하겠습니다!

2024-07-21 11:12 UTC, KBM05haruin30 commented on src/main/java/gift/model/Product.java
> +    public void updateName(String name) {
수정 중에 궁금한 점이 있습니다. Product와 Option 같은 경우 1개가 아닌 2개 이상을 한 번에 업데이트하도록 수정했습니다. 하지만 Category는 name 1개만 수정하므로 setter와 같은 동작을 하게 되는데 이 때 어떻게 해야 하는지 궁금합니다.

2024-07-22 06:06 UTC, Hongdonggeon commented on src/main/java/gift/model/Product.java
> +    public void updateName(String name) {
update 메서드도 사실 setter 와 동작이 동일해서 사실 메서드명만 다르다고 생각이 들수도 있긴 한데요
그래도 update 한곳에서 같이 변경해주는게 낫겟다 생각한건, 객체의 상태를 변경하는 메서드의 수를 여러개에서 1개로 줄일 수 있다는 점과 메서드명으로 분명하게 의도를 전달할 수 있는 점이 setter 보다 낫다고 생각했어요
category 는 필드가 1개 밖에 없어서 어쩔수 없겠네요

2024-07-22 06:08 UTC, Hongdonggeon commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=update
이 옵션은 조심해서 사용해야해요. 어플리케이션이 재실행될때마다 ddl 쿼리를 다시 실행시켜서 기존 데이터가 날라가기도 하고 그럴 수 있죠.. 보통 실무에서는 이런 옵션을 사용하지 않고 있어요! 
참고차 말씀드립니다!

2024-07-22 06:09 UTC, Hongdonggeon approved these changes
안녕하세요 보민님
질문에 대한 답변과 고민해보면 좋을 것에 대해 코멘트 남겨 놓았습니다!
확인 한번해주세요
머지할게요!! 수고하셨습니다

2024-07-22 06:09 UTC, merged