경북대 BE_박한솔 4주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #393
Opened 2024-07-21 02:45 UTC by pjhcsols

feat: ProductOption 상품 옵션 수량 차감 기능 추가
fix: subtract 메소드에서 수량 부족 처리
test: 수량 차감 기능에 대한 단위 테스트 추가
& step2 요구사항 수정

2024-07-21 11:45 UTC, lsm7179 requested changes
한솔님 과제 수고하셨습니다.
몇가지 피드백 드렸는데 반영 후 재요청주세요.🤗

2024-07-21 11:45 UTC, lsm7179 commented on src/main/java/gift/domain/product/Product.java
> +         */
왜 주석을 달았나요?
불필요한 내용이면 제거해주세요.

2024-07-21 11:45 UTC, lsm7179 commented on src/main/java/gift/service/product/ProductService.java
> +    private EntityManager em;
`ProductRepository`를 사용해서 구현해주세요.

2024-07-21 11:45 UTC, lsm7179 commented on src/main/java/gift/service/product/ProductService.java
> +        }
set을 사용하지 않고 update해주세요. `product.update`를 이용하면 좋을거 같네요~

2024-07-21 11:45 UTC, lsm7179 commented on src/main/java/gift/controller/product/option/ProductOptionController.java
> +        private String optionName;
`optionId`도 클라이언트에서 받을수있을거같은데 이름으로 받는 이유가 있나요?

2024-07-21 11:45 UTC, lsm7179 commented on src/main/java/gift/domain/product/option/ProductOption.java
> +    }
service계층에서 테스트가 아닌 `ProductOptionTest` 로 단위테스트코드를 만들어보아요~😁

2024-07-21 13:17 UTC, pjhcsols commented on src/main/java/gift/domain/product/Product.java
> +         */
제거하였습니다!!

2024-07-21 13:17 UTC, pjhcsols commented on src/main/java/gift/service/product/ProductService.java
> +    private EntityManager em;
update시에 ProductRepository를 사용하여 변경하였습니다!!

2024-07-21 13:18 UTC, pjhcsols commented on src/main/java/gift/service/product/ProductService.java
> +        }
product.update를 활용하여 Update로직을 변경하였습니다.

2024-07-21 13:22 UTC, pjhcsols commented on src/main/java/gift/controller/product/option/ProductOptionController.java
> +        private String optionName;
따로 이유는 없지만 개인적으로 옵션의 수가 많은 경우 이름으로 클라이언트 측에서 바로 받아 확인하는 것이 더욱 명확해 보여서 name으로 해보았습니다.

2024-07-21 13:24 UTC, pjhcsols commented on src/main/java/gift/controller/product/option/ProductOptionController.java
> +        private String optionName;
또한 브랜드 및 어드민 사용자가 ID를 기억하거나 확인하는 것보다 이름을 사용하는 것이 더 쉬울 수 있겠다 싶어서 이 부분에서는 name을 사용하였습니다.

추가적인 요구사항이 있다면 맞춰서 변경하겠습니다.

2024-07-21 13:29 UTC, pjhcsols commented on src/main/java/gift/domain/product/option/ProductOption.java
> +    }
추가하였습니다!!

2024-07-22 12:05 UTC, lsm7179 approved these changes
한솔님 수고하셨습니다.
머지하겠습니다~

2024-07-22 12:05 UTC, lsm7179 commented on src/test/java/gift/domain/product/option/ProductOptionTest.java
> +public class ProductOptionTest {
👍

2024-07-22 12:05 UTC, merged