경북대 4주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #395
Opened 2024-07-21 04:33 UTC by donghyuun

2024-07-21 10:08 UTC, MangKyu requested changes
이번 미션도 고생 많으셨습니다! 몇 가지 개선되면 좋을 포인트들이 보여서, 개선하고 넘어가면 좋을 것 같아요ㅎㅎ 추가적으로 동시성 관련하여도 코멘트 드리도록 하겠습니다!

## 동시성 처리 방법
기본적으로 자바는 동시성 제어를 위해 synchronized와 같은 키워드를 제공하고 있습니다. 하지만 이는 단일 서버 내에서만 동시성을 보장해주는 문제가 있습니다! 따라서 분산 저장소를 활용해야 하는데, 데이터베이스를 활용할 수도 있고 또는 Redis와 같은 캐시 그리고 최종적으로는 분산락 등을 활용할 수 있습니다!
데이터베이스의 잠금 중에서도 현재로는 낙관적 잠금 등을 활용할 수 있으니, 해당 기능에 대해 알아보시면 좋을 것 같습니다! 추가적으로 레디스와 분산락 관련하여는 [다음의 포스팅](https://mangkyu.tistory.com/311) 참고해주세요!

2024-07-21 10:08 UTC, MangKyu commented on src/main/java/gift/domain/option/Option.java
> +    public void decrease(Long quantity) {
핵심 비즈니스에 대한 부분을 담아주신 부분 💯

2024-07-21 10:08 UTC, MangKyu commented on src/main/java/gift/domain/Category/CategoryService.java
> +
꾸준한 정리 👍

2024-07-21 10:08 UTC, MangKyu commented on src/main/java/gift/domain/option/OptionService.java
> +        if (option.getQuantity() < quantity || quantity < 0) {
이 부분도 다음과 같이 비즈니스 로직을 객체 안으로 넣어버리면 더욱 좋을 것 같아요ㅎㅎ
```suggestion
        if (option.canDecrease(quantity)) {
```

2024-07-21 10:08 UTC, MangKyu commented on src/main/java/gift/domain/option/OptionService.java
> +        if (option.getQuantity() < quantity || quantity < 0) {
추가적으로 삭제 부분이 다음과 같이 변경되어야 하지 않을까 싶어요!
테스트의 중요성, 테스트 중에서도 경계값 테스트의 중요성이 보이는 부분이네요!
```java
quantity <= 0
```

2024-07-21 10:08 UTC, MangKyu commented on src/main/java/gift/domain/option/OptionService.java
> +        if (option.getQuantity() == quantity) {
이 부분은 객체 비교라 equals로 해주어야 할 것 같습니다!
```suggestion
        if (Objects.equals(option.getQuantity(), quantity)) {
```

2024-07-21 10:08 UTC, MangKyu commented on src/main/java/gift/domain/option/OptionService.java
> +            if (product.getOptions().size() == 1) {
```suggestion
            if (product.hasOneOption()) {
```

2024-07-22 02:40 UTC, MangKyu approved these changes
동시성을 보완하는 부분은 optional한 미션이라서, 다음의 4주차 0단계 과제의 원활한 진행을 위해 머지하도록 하겠습니다! 추가적으로 리뷰 반영하는 부분에 대하여도, 다음에 반영해주시면 함께 고려하여 리뷰하도록 하겠습니다! 혹시 학습하시다가 추가적인 궁금한 부분 있으면 말씀해주세요ㅎㅎ

2024-07-22 02:40 UTC, merged

2024-07-22 10:47 UTC, donghyuun commented on src/main/java/gift/domain/option/OptionService.java
> +        if (option.getQuantity() < quantity || quantity < 0) {
앗 그러네요 수정하겠습니다! 
말씀대로 경계값 테스트를 수행하면 이러한 부분을 파악할 수 있어서 좋은 것 같습니다!

2024-07-22 10:51 UTC, donghyuun commented on src/main/java/gift/domain/option/OptionService.java
> +            if (product.getOptions().size() == 1) {
메서드로 처리하는 방식으로 개발토록 하겠습니다ㅎㅎ

2024-07-22 10:52 UTC, donghyuun commented on src/main/java/gift/domain/option/OptionService.java
> +        if (option.getQuantity() == quantity) {
수정하겠습니다!