부산대 BE_김동현 4주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #397
Opened 2024-07-21 06:59 UTC by donghyun5434

매번 최선을 다해서 리뷰해주신 점 너무 감사드립니다!!
이번 주차 과제에서 여러모로 부족한 점이 많았는데 리뷰가 정말 도움되었습니다!!

## 요청 사항
1. 리뷰해 주실 때 확정적으로 말씀해 주실 수 있을까요

예를 들면 "A방법을 사용한 이유가 무엇일까요?" 보다는 "A방법보다는 B방법을 사용해 주세요"
프로그래밍에 정답이 없기에 포괄적으로 말씀해 주신다고 생각합니다.
하지만 저의 지식과 경험은 0에 수렴하기 때문에 일단은 가장 보편적인 방법을 외우는 것이 시기적으로 더 적절하다고 생각합니다.

## 리뷰 요청 사항

1. 2단계 요구 사항 중 "상품에는 항상 하나 이상의 옵션이 있어야 한다"를 구현하는 방법
: 상품 생성 시에 옵션을 동시에 생성해서 옵션을 추가하는 방법을 사용해야 할까요?

2. 과제가 진행됨에 따라 코드 작성이 배보다 배꼽이 더 커지고 있습니다.
예를 들면 1주차에는 dto을 사용하지 않고 도메인을 직접 사용 했습니다. 
n주차에 1주차 코드를 재사용해야 할 때가 되면 1주차 코드를 전부 수정하느라(연관된 모든 코드도) 과제에 과도하게 시간을 소비하게 됩니다.
**이런 부작용을 막기 위해서 코드를 재사용하지 않고 별도의 코드를 작성해도 될까요?**
예를 들면 1주차에 사용한 save(Member member) 메서드를 수정하지 않고 새롭게 save메서드를 생성해도 되나요?
하나의 완성된 프로젝트로써는 부적절하겠지만 주차별 과제 수행에는 좀 더 적절하다고 생각합니다.

피드백을 반영하여 매 주 더 성장할 수 있도록 노력하겠습니다.

2024-07-21 10:05 UTC, jadie0319 requested changes
안녕하세요 동현님.
4주차 미션 하시느라 고생하셨습니다.
질문 주신것 답변 남겨드렸으니 확인 부탁드립니다.
화이팅 하세요!

2024-07-21 10:05 UTC, jadie0319 commented on src/main/java/gift/service/OptionService.java
> +        optionValidator.validateOptionQuantity(optionRequestDto.getQuantity());
https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/319#discussion_r1684552393
도메인 객체에 반영했으니 테스트를 할 수 있을거라고 피드백을 드렸던 거였는데 의도가 잘못 전달됐네요. 

지금 작성해주신 방식처럼 서비스에 코딩하게 되면 옵션을 생성, 변경 하는 모든 곳에 같은 기능을 구현해야 해요. 이러한 검증 로직은 도메인 객체가 가지고 있는게 코드 중복을 발생시키지 않기 때문에 좋습니다.
지금 구현하신 OptionValidator 로직을 재사용할 수 있을 것 같아요. OptionValidator 의 로직만 옮겨서 아래와 같이 해볼까요? quantity 도 이와 같이 옮기시면 될것 같아요


```java
public Option(String name, int quantity) {
        validateOptionName(name);
        this.name = name;
        this.quantity = quantity;
    }
    private void validateOptionName(String optionName){
        if (optionName == null || optionName.trim().isEmpty()) {
            throw new IllegalArgumentException("상품 이름을 비우거나 공백으로 설정할 수 없습니다");
        }
        if (optionName.length() > 50) {
            throw new IllegalArgumentException("옵션명은 공백 포함하여 최대 50자까지 입력할 수 있습니다");
        }
        if (!optionName.matches("^[\\w\\s\\(\\)\\[\\]\\+\\-\\&\\/\\_가-힣]*$")) {
            throw new IllegalArgumentException("특수 문자는 ( ), [ ], +, -, &, /, _ 만 사용할 수 있습니다.");
        }
    }
```

2024-07-21 10:05 UTC, jadie0319 commented on src/main/java/gift/service/OptionService.java
> +        option.setQuantity(newQuantity);
이 로직을 Option 에서 구현해봅시다.
```java
option.subtract(optionQuantityRequestDto.getQuantity());
```
도메인 객체로부터 값을 가져와 서비스에서 연산을 하는게 아니라
도메인 객체에게 연산을 시킨다고 생각하시면 도움이 될것 같아요.

2024-07-21 10:05 UTC, jadie0319 commented on src/test/java/gift/validator/OptionValidatorTest.java
> +class OptionValidatorTest {
Mock, InjectMocks 잘 사용하셨습니다 👍 
테스트 케이스도 다양하게 잘 만드셨네요!

2024-07-21 10:10 UTC, jadie0319 commented
안녕하세요 동현님!
4주차 미션하시느라 고생하셨어요!
질문 주신것 답변 드릴게요!
피드백 드린 것과 아래 드린 답변을 참고해서 기능을 완성 시켜봐요! 일단 요구사항을 충족하는 기능을 만들어보고 
코드 품질을 높이는것은 이후에 생각해봅시다.


# 요청사항 답변

요청사항 남겨주셔서 감사합니다 ㅎ 저도 멘트를 남길때마다 고민이 많았었어요. 답을 주는 것 보다는 좀 더 고민해 봤으면 하는 부분에서 두루뭉실하게 대답을 했었어요. 물론 단순한 호기심으로 의도가 궁금해서 질문한적도 있습니다 🙂 요청 사항 반영해서 좀 더 확실하게 답변 드리도록 노력해볼게요! 고민해 봤으면 하는 부분도 고민해야 하는 부분을 설명해 드리도록 노력해볼게요! 의견 감사합니다!

# 질문 1 

2단계 요구 사항 중 "상품에는 항상 하나 이상의 옵션이 있어야 한다"를 구현하는 방법
: 상품 생성 시에 옵션을 동시에 생성해서 옵션을 추가하는 방법을 사용해야 할까요?

### 답변

요구사항 : 상품은 항상 하나 이상의 옵션이 있어야 한다.
→ 다시 말하면 옵션이 없는 상품은 존재할 수 없다. 라고도 얘기할 수 있어요.

상품을 저장할 때 옵션도 함께 저장해야 합니다. 상품과 옵션을 동시에 생성하는 코드가 어려우시면 따로따로 구현을 해봅시다. ProductService 에 OptionRepository 를 추가해서 구현을 해보시면 될 것 같아요. ProductService 에서 productRepository.save() 도 호출하고 optionRepository.save() 도 호출하는 코드를 작성해보시면 됩니다. 일단 요구사항을 만족시키는 코드를 작성하고 이후에 코드를 개선시켜봐요.

# 질문2

과제가 진행됨에 따라 코드 작성이 배보다 배꼽이 더 커지고 있습니다. 예를 들면 1주차에는 dto을 사용하지 않고 도메인을 직접 사용 했습니다. n주차에 1주차 코드를 재사용해야 할 때가 되면 1주차 코드를 전부 수정하느라(연관된 모든 코드도) 과제에 과도하게 시간을 소비하게 됩니다.

**이런 부작용을 막기 위해서 코드를 재사용하지 않고 별도의 코드를 작성해도 될까요?**

예를 들면 1주차에 사용한 save(Member member) 메서드를 수정하지 않고 새롭게 save메서드를 생성해도 되나요?하나의 완성된 프로젝트로써는 부적절하겠지만 주차별 과제 수행에는 좀 더 적절하다고 생각합니다.


### 답변

나중에 일을 하실 때 경험하시겠지만, 요구사항이 바뀌거나 수정사항이 생길때 관련된 것들을 모두 변경해야 하는건 자연스러운 거에요. 그래서 변경이 발생했을 때 변경이 많은 곳으로 전파되지 않게 코딩하는게 중요하죠 🙂

미션을 수행하실 때 기존 기능을 사용하지 않고 새로 만드는게 시간이 짧게 걸리실 것 같으시면 새로 생성해서 사용하는 걸로 하시죠. 일단 요구사항을 만족시키는 코드를 짜고 개선해야 할 점은 하나씩 바꿔 봅시다.

2024-07-22 05:14 UTC, donghyun5434 commented on src/main/java/gift/service/OptionService.java
> +        optionValidator.validateOptionQuantity(optionRequestDto.getQuantity());
검증 로직은 도메인 객체가 가지도록 수정하겠습니다!

2024-07-22 05:15 UTC, donghyun5434 commented on src/main/java/gift/service/OptionService.java
> +        option.setQuantity(newQuantity);
도메인 객체에서 연산을 수행하고 private로 선언된 검증 로직까지 수행하도록 수정하겠습니다.

2024-07-22 07:26 UTC, jadie0319 approved these changes
안녕하세요 동현님!
피드백 잘 반영해주셨어요.
5주차 미션을 위해 빠르게 머지하겠습니다!
5주차도 화이팅 하세요!

2024-07-22 07:26 UTC, merged