강원대 BE_김송목 4주차 과제(Step 3)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #405
Opened 2024-07-21 08:41 UTC by kimsongmok

멘토님 말씀대로 updateFromDto 에 검증 로직을 추가했습니다!
Step3, Option 에서 수량 빼기를 넣었습니다

2024-07-21 23:40 UTC, jaymarystella requested changes
3단계 변경사항은 많이 없네요
피드백 몇가지만 확인부탁드립니다.

2024-07-21 23:40 UTC, jaymarystella commented on src/main/java/gift/model/Product.java
> +    }
테스트코드도 작성부탁드립니다.

2024-07-21 23:40 UTC, jaymarystella commented on src/main/java/gift/model/Option.java
> +    return Pattern.matches("^[\\p{L}\\p{N}\\s\\(\\)\\[\\]\\+\\-\\&\\/_]+$", name);
핵심클래스들에 대해서 테스트코드가 누락된부분을 전체적으로 확인부탁드리겠습니다.

2024-07-22 06:22 UTC, kimsongmok commented on src/main/java/gift/model/Option.java
> +    return Pattern.matches("^[\\p{L}\\p{N}\\s\\(\\)\\[\\]\\+\\-\\&\\/_]+$", name);
Product에 대한 테스트코드와 Category에 대한 테스트코드, Option 내 isValidName에 대한 테스트 코드를 추가했습니다!

2024-07-23 11:21 UTC, jaymarystella approved these changes
안녕하세요 마지막 단계까지 고생많으셨습니다.
다음 미션도 화이팅입니다!

2024-07-23 11:21 UTC, merged