경북대 BE_권도윤 4주차 과제 (3,4단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #408
Opened 2024-07-21 09:27 UTC by doyooon

동시성 테스트가 제대로 이뤄지지 않는 것 같습니다. 제가 어떤 부분 때문에 동시성 테스트가 이뤄지지 않는지 도무지 모르겠습니다..ㅠㅠ

2024-07-21 12:13 UTC, MangKyu requested changes
다음과 같이 동시성 테스트 적용하시면 될 것 같습니다!
해당 기능에 대한 테스트 타깃은 option이므로, 굳이 스프링 컨테이너를 띄울 필요 없이 단위 테스트로 작성하면 될 것 같습니다ㅎㅎ

```java
package gift.option;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class OptionTest {


    @DisplayName("동시성 테스트")
    @Test
    void asyncSubtract() throws InterruptedException {
        Option option = new Option(1L, "Test Option", 201);
        int numberOfThreads = 100; // Increased number of threads

        ExecutorService executorService = Executors.newFixedThreadPool(numberOfThreads);
        List<Callable<Boolean>> tasks = new ArrayList<>();

        for (int i = 0; i < numberOfThreads; i++) {
            int finalI = i;
            Callable<Boolean> callable = () -> option.subtract(50, finalI);
            tasks.add(callable);
        }

        executorService.invokeAll(tasks);
        executorService.shutdown();
    }
}
```

2024-07-21 12:13 UTC, MangKyu commented on src/main/java/gift/option/Option.java
> +        if(quantity >= this.quantity){
`Command + Option + L`을 눌러 자동 포매팅을 적용할 수 있습니다ㅎㅎ

2024-07-22 00:50 UTC, doyooon commented on src/main/java/gift/option/Option.java
> +        if(quantity >= this.quantity){
넵!! 커밋전에 까먹지 않고 포매팅 하겠습니다!

2024-07-22 02:37 UTC, MangKyu approved these changes
동시성을 보완하는 부분은 optional한 미션이라서, 다음의 4주차 0단계 과제의 원활한 진행을 위해 머지하도록 하겠습니다! 혹시 학습하시다가 추가적인 궁금한 부분 있으면 말씀해주세요ㅎㅎ

2024-07-22 02:37 UTC, merged