경북대 BE_박준석_4주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #411
Opened 2024-07-21 10:37 UTC by Lucerna00

옵션 수량 차감을 위해 엔티티에 subtract 메서드를 두었고,
관리자 페이지에서 옵션을 추가, 수정, 삭제할 수 있도록 변경하였습니다.

Q. `상품에는 항상 하나 이상의 옵션이 있어야 한다.` 해당 요구 사항을 충족시키기 위해 많이 고민하였지만 잘 모르겠습니다.
product 엔티티에 `@OneToMany`로 `List<Option>`을 둬서 생성자에서 이를 받아야 하는지 궁금합니다.

2024-07-21 13:03 UTC, gongdongho12 requested changes
3단계 작업까지 고생하셨습니다

테스트가 두개가 있는데 객체의 테스트 보다는, 서비스 테스트 / 레포지토리 테스트가 실제 코드 검증에 더 도움이 된다고 생각합니다
아 물론 객체 테스트 하는 경우도 있는데 지금처럼 간단한 경우에는 서비스와 레포지토리에 사실 포함되어있다 봐도 무방하니까요!

> Q. 상품에는 항상 하나 이상의 옵션이 있어야 한다. 해당 요구 사항을 충족시키기 위해 많이 고민하였지만 잘 모르겠습니다.
product 엔티티에 @OneToMany로 List<Option>을 둬서 생성자에서 이를 받아야 하는지 궁금합니다.

상품을 추가할 때, 옵션을 필수로 받게 하고, 옵션이 1개인 경우 삭제를 못하게 하면 말씀주신 내용을 반영해줄 수 있는거 아닐까요?

2024-07-21 13:03 UTC, gongdongho12 commented on src/main/java/gift/exception/InsufficientQuantityException.java
> +    }
이런 메시지 좋네요 👍🏼 
재고 남은 갯수를 보여주는 것도 사용자 편의성 관점에서 좋지 않을까요? 
ex) 5개 남았는데 6개 주문했는데 몇개 빼야하지 등을 개선해줄 수 있을 것 같습니다

2024-07-21 13:03 UTC, gongdongho12 commented on src/test/java/gift/domain/OptionTest.java
> +    }
이부분은 실제 DB의 레포지토리를 DataJpaTest 어노테이션 받아서 주입받아서 적용하는게 낫지 않을까요?
실제 DB 반영방식을 테스트 하는건데 지금 로직은 단순 숫자 덧셈 뺄셈 로직만 의미하고 있어서요

명명도 바꾼다고 한다면, OptionRepositoryTest 정도로요!

2024-07-21 15:04 UTC, Lucerna00 commented on src/main/java/gift/exception/InsufficientQuantityException.java
> +    }
남은 수량도 같이 표기하였습니다!

2024-07-21 15:06 UTC, Lucerna00 commented on src/test/java/gift/domain/OptionTest.java
> +    }
저장된 option의 수량을 차감하고 다시 저장하는 식으로 repository 테스트를 해보았습니다

2024-07-21 15:08 UTC, Lucerna00 commented
멘토님, 그러면 `상품을 추가할 때 옵션을 필수로 받게 하고, 옵션이 1개인 경우는 삭제 못 하게` 하는 것은 프론트에서 처리해도 되는 건가요?

2024-07-22 23:30 UTC, gongdongho12 commented
프론트에서는 막아도 네트워크가 느려서 두번 호출될 수 있다고 생각해요
그래서 백엔드에 밸리데이션 로직이 있는게 맞지 않을까요?

2024-07-23 07:01 UTC, Lucerna00 commented
`List<Option>`과 여러 validation을 추가하여 나름대로 구현해 보았습니다.
지저분해진 감이 없지 않아 있는데, DTO를 세분화하면 좋을까요?

2024-07-25 14:58 UTC, gongdongho12 approved these changes
4주차 프로젝트 마무리까지 고생하셨습니다
5주차도 화이팅입니다!

2024-07-25 14:58 UTC, gongdongho12 commented on src/test/java/gift/service/OptionLockTest.java
> +        countDownLatch.await();
락 테스트에 스레드 👍🏼

2024-07-25 14:58 UTC, merged