강원대 BE_김병수 4주차 과제 (step3)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #412
Opened 2024-07-21 10:39 UTC by GamJaDo

2024-07-21 23:48 UTC, jaymarystella requested changes
3단계 코멘트 남겨두었습니다.
확인주시고 반영부탁드려요

2024-07-21 23:48 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +		optionRepository.save(option);
save호출을 하지 않으면 어떻게 될까요

2024-07-21 23:48 UTC, jaymarystella commented on src/main/java/gift/service/OptionService.java
> +	}
로직을 도메인객체에서 담당하도록 수정해볼까요

2024-07-21 23:48 UTC, jaymarystella commented on src/main/java/gift/entity/Option.java
> +	}
음수로 들어가면 어떻게 되나요? 단순 setter는 전체적으로 확인부탁드려요

2024-07-22 01:47 UTC, GamJaDo commented on src/main/java/gift/service/OptionService.java
> +	}
entity로 메서드를 옮겼습니다.

2024-07-22 01:47 UTC, GamJaDo commented on src/main/java/gift/entity/Option.java
> +	}
음수가 들어가면 안되는 부분에 음수가 들어오면 예외 처리 되도록 변경하였습니다.

2024-07-22 02:32 UTC, GamJaDo commented on src/main/java/gift/service/OptionService.java
> +		optionRepository.save(option);
save를 하지 않고 테스트를 해본 결과
테스트가 통과되었습니다.

왜 save를 하지 않았는데 통과가 되었는지 찾아보니까 테스트에서는 실제로 데이터베이스를 사용하지 않고, 메모리 내에서 객체를 직접 다뤄서 그렇다고 합니다.

2024-07-22 15:18 UTC, jaymarystella commented
(질문주신 내용입니다)
앞단의 검증이 빠지고 핵심 도메인 클래스에 검증이 없다면 잘못된 값이 세팅이 되게 될거에요. 수업시간에 배우셨을거같은데 핵심도메인에 대한 역할부여와 테스트는 해주셔야합니다.

2024-07-22 15:19 UTC, jaymarystella approved these changes
4주차도 고생많으셨어요
다음 미션에서 뵐게요

2024-07-22 15:19 UTC, merged