전남대 BE_나제법 4주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #419
Opened 2024-07-21 13:22 UTC by nove1080

매번 코드리뷰를 남겨주셔서 감사합니다!
이번주 피드백 중 반영이 안된 부분은 확인 후에 현재 PR에 반영하도록 하겠습니다

2024-07-22 06:31 UTC, Hongdonggeon requested changes
안녕하세요 제법님
요구사항이 간단하네요 코멘트 남겨 놓았습니다! 확인 한번 해주세요

2024-07-22 06:31 UTC, Hongdonggeon commented on src/main/java/gift/domain/validator/ProductValidator.java
> +    public static void validateProductOptionsPresence(List<ProductOption> productOptions) {
사용되고 있지 않은 것 같네요

2024-07-22 06:31 UTC, Hongdonggeon commented on src/main/java/gift/domain/validator/ProductOptionValidator.java
> +    public static void validatedRequestQuantity(int stock, int quantity) {
validator 클래스를 따로 구분할 필요 없이, ProductOption 엔티티에서 이 메서드를 만들어도 될 것 같아요

2024-07-22 06:40 UTC, nove1080 commented on src/main/java/gift/domain/validator/ProductValidator.java
> +    public static void validateProductOptionsPresence(List<ProductOption> productOptions) {
`Product`의 `Builder`에서 사용하고 있었는데 이 부분은 동건님의 말씀대로 별도의 Validator 클래스를 만들지 않고 도메인에 검증코드를 작성하는 방법으로 수정하겠습니다

2024-07-22 06:46 UTC, nove1080 commented on src/main/java/gift/domain/validator/ProductOptionValidator.java
> +    public static void validatedRequestQuantity(int stock, int quantity) {
이후에 검증할 부분이 많아지면 코드가 길어지는게 아닐까 라는 생각에서 validator를 따로 생성하였는데 
어짜피 도메인 검증 코드는 해당 도메인 안에서만 사용되는데 따로 분리하는 바람에 이것이 도메인 클래스의 응집도를 떨어뜨리게 되어서 이러한 이유에서 엔티티 안에 검증 로직을 넣어두려는데 다른 이유가 더 있을까요? 

혹시 추가로 궁금한 건데 검증 코드가 많아지더라도 도메인 안에 위치하는게 더 나은가요? 혹은 다른 방법이 있을까요?

2024-07-22 14:58 UTC, nove1080 commented
안녕하세요 동건님 
1. 도메인 검증 로직을 해당 도메인 안에서 구현
2. 2단계에서 남기신 https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/pull/329#pullrequestreview-2190689209 옵션 생성 시 불필요한 조회 쿼리 발생 없애기

위 두 가지 사항을 반영하였습니다!

옵션 생성에 관한 구현은 좀 더 나은 구현 방법이 있을 것 같아 조금 더 고민해보겠습니다

2024-07-28 06:46 UTC, Hongdonggeon commented on src/main/java/gift/domain/validator/ProductOptionValidator.java
> +    public static void validatedRequestQuantity(int stock, int quantity) {
검증 로직이 많아지면 많아질수록 각자 도메인이 나눠가지는게 응집도가 더좋지 않을까여?
validator에서 모이게 된다면 오히려 validator가 가지는 역할이 너무 많아질 것 같아요

2024-07-28 06:46 UTC, Hongdonggeon approved these changes
안녕하세요 제법님
3단계 미션 머지할게요
질문에 대한 답변도 확인해주세요

2024-07-28 06:46 UTC, merged