전남대 BE_김보민_4주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #429
Opened 2024-07-21 16:24 UTC by KBM05haruin30

# 3단계
### 코드 작성하면서 어려웠던 점
다행히 3단계 미션은 그렇게 어렵지 않았습니다.

### 중점적으로 봐주셨으면 하는 점
Option 엔티티에 옵션 수량 차감 검증 메서드를 작성했는데 맞게 작성했는지 궁금합니다.

2024-07-22 06:41 UTC, Hongdonggeon requested changes
보민님
3단계 미션은 비교적 간단하네요
현재 validateSubtractQuantity 메서드가 사용되고 있지 않고 있어요
이 부분만 다시 확인해주세요

2024-07-22 06:41 UTC, Hongdonggeon commented on src/main/java/gift/model/Option.java
> +    private void validateSubtractQuantity(Long subtractQuantity) {
사용되고 있지 않네요

2024-07-22 06:45 UTC, KBM05haruin30 commented on src/main/java/gift/model/Option.java
> +    private void validateSubtractQuantity(Long subtractQuantity) {
subtractQuantity 메서드에서 검증을 하도록 사용했습니다. 간단하게 Tab 누르다가 validateSubtractQuantity가 아닌 validateQuantity로 바뀐 것을 눈치 못채고 넘어갔던 것 같습니다....

2024-07-22 06:54 UTC, Hongdonggeon commented on src/main/java/gift/model/Option.java
> +    private void validateSubtractQuantity(Long subtractQuantity) {
근데 subtractQuantity에 대한 값을 엔티티에서 검증할 필요가 있을까하는 생각이 들어요
이 값으로 객체의 상태를 변경시키긴 하지만, 객체 생성시 초기화하는데 사용되거나 하는 값이 아닌데요.
이 값이 null이거나 음수거나 이 정도의 검증은 엔티티보다 dto해서 해주는게 더 나을 것 같다는 생각이 듭니다

2024-07-22 07:40 UTC, KBM05haruin30 commented on src/main/java/gift/model/Option.java
> +    private void validateSubtractQuantity(Long subtractQuantity) {
넵 알겠습니다! null이거나 음수인 경우의 검증은 새 DTO를 만들어서 검증을 했습니다. 하지만 현재 수량과 차감할 수량을 비교하는 것은 엔티티에서 해야한다고 생각해서 subtractQuantity 메서드 안으로 이동시켰습니다.

2024-07-28 06:44 UTC, Hongdonggeon approved these changes
보민님 안녕하세요
3단계 미션 머지할게요!

2024-07-28 06:44 UTC, merged