충남대 BE_김민지 4주차 과제(3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #430
Opened 2024-07-21 16:25 UTC by alsswl

2024-07-21 23:53 UTC, Hyeon9mak requested changes
안녕하세요 민지님, 이번 단계 미션의 요구사항과 상이한 구현 내용이 PR 로 올라온 것 같아요.
요구사항을 다시 확인하신 후 리뷰요청 주세요!

2024-07-21 23:53 UTC, Hyeon9mak commented on src/main/java/gift/service/CategoryService.java
> +    }
<img width="580" alt="image" src="https://github.com/user-attachments/assets/3693c4f7-847a-49ee-b796-ddaac42423d9">

이번 단계 미션의 요구사항은 옵션의 수량을 지정된 수만큼 차감하는 것이었는데요,
요구사항이 잘못 전달된 것 같아요.

2024-07-22 03:07 UTC, Hyeon9mak approved these changes
3단계 잘 진행해주셨어요~ 다음 주차 미션에서 만나요~!

2024-07-22 03:07 UTC, Hyeon9mak commented on src/main/java/gift/domain/Option.java
> +    }
`1_000_000_000` 와 같이 `_` 기호로 자리수를 표기해주면 가독성이 더욱 높아지겠네요~

2024-07-22 03:07 UTC, Hyeon9mak commented on src/main/java/gift/domain/Option.java
> +    }
`quantity <= 0` 이 1 이상이 맞나요? 🤔

2024-07-22 03:07 UTC, Hyeon9mak commented on src/main/java/gift/domain/OptionRequest.java
> +        Long quantity
특수문자랑 1 이상 1억 미만은 비즈니스적 요구사항 아닐까요? 🤔

2024-07-22 03:07 UTC, Hyeon9mak commented on src/main/java/gift/service/CategoryService.java
> +
기본 카테고리는 기본 카테고리인 형상으로... 별도 생성자를 만들어주는 건 어떨까요?

2024-07-22 03:07 UTC, Hyeon9mak commented on src/main/java/gift/domain/Option.java
> +    }
관련된 테스트코드도 다음 주차에 추가되면 좋겠네요~

2024-07-22 03:07 UTC, merged

2024-07-23 17:46 UTC, alsswl commented on src/main/java/gift/domain/Option.java
> +    }
quantity<=0이거나 1억 초과면 에러가 나게 하도록 하였습니다!
테스트코드 추가하겠습니다!

2024-07-23 17:58 UTC, alsswl commented on src/main/java/gift/domain/OptionRequest.java
> +        Long quantity
혹시 비즈니스적 요구사항은 dto에서 검증하는게 아니라 엔티티쪽에서 검증해야하는걸까요?
이 부분은 찾아봐도 잘 안나와서 여쭤봅니다 : )

2024-07-23 18:00 UTC, alsswl commented on src/main/java/gift/service/CategoryService.java
> +
넵!