전남대 BE_김수랑 4주차 과제 (3단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #439
Opened 2024-07-22 06:53 UTC by rdme0

Step3 기능 요구사항 반영하고, Step2 피드백 반영하였습니다!

- [✨ feat: 옵션 수량을 빼는 메서드 구현](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/commit/9e04ffa04e4a1178fdbec1f75bb45b4ed23715ac)

- [♻️ refactor: 클래스 통합 및 테스트 코드 리팩터링](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/commit/aaca0fbf712cce71f67d22e3002b891c0b69d15f)

- [♻️ refactor: 클래스 통합 및 테스트 코드 리팩터링](https://github.com/kakao-tech-campus-2nd-step2/spring-gift-enhancement/commit/4f966953b0279ae0132ae37d56994a7e533bf345)

2024-07-22 07:11 UTC, Hongdonggeon requested changes
수량 차감하는 메서드가 호출되고 있지 않습니다
확인 및 차감에 대한 테스트코드도 작성해서 검증해주세요

2024-07-22 07:11 UTC, Hongdonggeon commented on src/main/java/gift/entity/Option.java
> +    public void subtractQuantity(Integer subtractQuantity){ //나중에 사용할 메서드
이 메서드가 사용되고 있지 않습니다!

2024-07-22 07:41 UTC, rdme0 commented on src/main/java/gift/entity/Option.java
> +    public void subtractQuantity(Integer subtractQuantity){ //나중에 사용할 메서드
테스트 코드 작성 하였습니다!

2024-07-22 07:41 UTC, rdme0 commented
피드백 반영하였습니다!

2024-07-28 06:44 UTC, Hongdonggeon approved these changes
수랑님 안녕하세요
3단계 미션 머지할게요!

2024-07-28 06:44 UTC, merged