부산대 BE_신예준_4주차 과제
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #447
Opened 2024-07-23 14:49 UTC by pnuece

2024-07-24 12:15 UTC, yoo-jaein commented
5주차 부터는 pr 작성 후 nextstep에서 코드리뷰 요청을 눌러주세요~

2024-07-24 12:33 UTC, yoo-jaein requested changes
4주차 과제 고생하셨습니다!
코멘트 확인 부탁드려요

2024-07-24 12:33 UTC, yoo-jaein commented on src/main/resources/db/schema.sql
> +create table Wish
Option에 대한 스키마도 있으면 좋겠습니다

2024-07-24 12:33 UTC, yoo-jaein commented on src/main/java/gift/domain/wishlist/WishList.java
> +@Entity
schema.sql 내의 실제 테이블 이름과 클래스 이름이 일치하지 않네요

2024-07-24 12:33 UTC, yoo-jaein commented on src/main/java/gift/service/ProductService.java
> +        System.out.println("tetetetetet");
System.out.println 대신 로깅 프레임워크(SLF4J, Logback..)를 사용하는 것이 좋습니다!

2024-07-24 12:33 UTC, yoo-jaein commented on src/main/java/gift/controller/OptionController.java
> +    public void createOption(@PathVariable Long productId,
옵션 생성 / 수정시 요구 사항을 반영해주세요
- 중복된 옵션은 구매 시 고객에게 불편을 줄 수 있다. 동일한 상품 내의 옵션 이름은 중복될 수 없다.

2024-07-24 12:33 UTC, yoo-jaein commented on src/main/java/gift/controller/OptionController.java
> +public class OptionController {
api path가 좋네요

2024-07-24 12:33 UTC, yoo-jaein commented on README.md
> +# spring-gift-enhancement
필수 비즈니스 로직 (주요 요구 사항) 에 대해 테스트 코드가 있으면 좋겠습니다

2024-07-24 12:33 UTC, yoo-jaein commented on src/main/java/gift/repository/WishListRepository.java
> +    Optional<WishList> findByMemberAndProduct(Member Member, Product Product);
메서드 파라미터 이름은 소문자로 시작해야 합니다
```java
Optional<WishList> findByMemberAndProduct(Member member, Product product);
```

2024-07-27 12:14 UTC, pnuece commented on src/main/resources/db/schema.sql
> +create table Wish
Option 스키마도 추가했습니다!

2024-07-27 12:14 UTC, pnuece commented on src/main/java/gift/domain/wishlist/WishList.java
> +@Entity
스키마를 클래스와 동일하게 WishList로 수정했습니다

2024-07-27 12:16 UTC, pnuece commented on src/main/java/gift/service/ProductService.java
> +        System.out.println("tetetetetet");
API 테스트 중 값을 확인하려고 출력문을 넣었는데 실수로 지우지 않고 커밋되어 제거했습니다.
아직 Java 디버깅에 익숙하지 않아 출력문을 넣어 확인하고 있는데 앞으로는 디버깅으로 확인할 수 있도록 해보겠습니다!

2024-07-27 12:17 UTC, pnuece commented on src/main/java/gift/controller/OptionController.java
> +    public void createOption(@PathVariable Long productId,
누락된 요구사항들을 모두 반영하여 수정 커밋하였습니다 :)

2024-07-27 12:26 UTC, pnuece commented on README.md
> +# spring-gift-enhancement
DTO 제약조건과 OptionService에 대한 테스트 코드 작성하였습니다!
처음 테스트 코드를 작성할 때는 모킹하여 계층별 단위 테스트를 수행해보려고 했지만.. 아직 잘 안되는 부분들이 많아 통합테스트로 변경했습니다

2024-07-27 12:26 UTC, pnuece commented on src/main/java/gift/repository/WishListRepository.java
> +    Optional<WishList> findByMemberAndProduct(Member Member, Product Product);
수정하였습니다!

2024-07-27 15:03 UTC, yoo-jaein approved these changes
4주차 과제하시느라 고생 많으셨어요!
리뷰 반영된 것 확인했습니다 :)
머지하겠습니다

2024-07-27 15:03 UTC, merged