경북대 BE_배준호 4주차 과제 (1단계)
kakao-tech-campus-2nd-step2/spring-gift-enhancement pull request #55
Opened 2024-07-15 07:51 UTC by BaeJunH0

테스트에 대한 부분 외에 요구사항 충족한 것 같아서 PR 보냅니다, 피드백 부탁드립니다.
테스트에 대한 부분은 빠르게 채우겠습니다

2024-07-16 10:20 UTC, BaeJunH0 commented
테스트 부분과 함께 정렬 방식을 View에서 선택하는 방식까지 구현해보겠습니다, 해당 부분 제외하고 피드백 해주세요!

2024-07-16 14:13 UTC, lsm7179 commented
> 테스트 부분과 함께 정렬 방식을 View에서 선택하는 방식까지 구현해보겠습니다, 해당 부분 제외하고 피드백 해주세요!

네! 따로 코멘트는 안하겠습니다.
혹시라도 테스트 코드 작성이 어렵거나 도움이 필요하면 언제든DM주세요!
일정조율도 가능하니 멘토링도 활용 해보세요.

2024-07-16 14:13 UTC, lsm7179 requested changes
준호님 과제하느라 수고하셨습니다.
몇가지 코멘트 남겼습니다.
같이 반영해주세요~

2024-07-16 14:13 UTC, lsm7179 commented on src/main/java/gift/Application.java
> +    }
jpa 초기 세팅하는 방법을 사용해보세요~
https://wildeveloperetrain.tistory.com/228

2024-07-16 14:13 UTC, lsm7179 commented on src/main/java/gift/DTO/Product/ProductResponse.java
> +    Category category;
`CategoryResponse`가 있으니 활용해보는건 어떨까요?

2024-07-16 14:13 UTC, lsm7179 commented on src/main/java/gift/controller/CategoryController.java
> +@Controller
`@RestController`가 더 적절해보이는데 어떤가요?

2024-07-16 14:13 UTC, lsm7179 commented on src/main/java/gift/controller/CategoryController.java
> +    }
nit: 지난주에 사용했던 paging 처리도 하면 좋을거 같습니다.😁

2024-07-16 14:13 UTC, lsm7179 commented on src/main/java/gift/controller/CategoryController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
[`HttpStatus.NO_CONTENT`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html#NO_CONTENT) 
삭제는 상태코드로 no_content가 더 적절해보이네요.

2024-07-16 14:13 UTC, lsm7179 commented on src/main/java/gift/domain/Category.java
> +    Long id;
계속해서 엔티티 클래스에 반복되는 id
baseEntity를 도출해보세요.
https://devfunny.tistory.com/684

2024-07-16 14:13 UTC, lsm7179 commented on src/main/java/gift/service/CategoryService.java
> +        );
`categoryRequest`에서 카테고리를 직접 생성해보세요~

2024-07-16 14:13 UTC, lsm7179 commented on src/main/java/gift/service/CategoryService.java
> +        Category savedCategory = categoryRepository.findById(id).orElseThrow();
예외처리는 안해도 될까요?

2024-07-16 14:13 UTC, lsm7179 commented on src/main/java/gift/service/ProductService.java
>      public void createProduct(ProductRequest product){
productRequest로 받아야 도메인객체가 아니다 라고 명확해질거같은데 어떻게 생각하시나요?

2024-07-16 14:13 UTC, lsm7179 commented on src/main/java/gift/service/WishListService.java
> +        WishProduct wish = wishListRepository.findById(wishId).orElseThrow();
예외처리는 안해도 될까요?

2024-07-17 05:13 UTC, BaeJunH0 commented on src/main/java/gift/DTO/Product/ProductResponse.java
> +    Category category;
수정 했습니다! 제가 왜 이렇게 했는지... ㅎㅎ...

2024-07-17 05:13 UTC, BaeJunH0 commented on src/main/java/gift/controller/CategoryController.java
> +@Controller
하하... 요즘 더워서 그런지 이상한 실수가 많네요... 정신 차리겠습니다!

2024-07-17 05:14 UTC, BaeJunH0 commented on src/main/java/gift/controller/CategoryController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
수정했습니다~

2024-07-17 05:16 UTC, BaeJunH0 commented on src/main/java/gift/service/CategoryService.java
> +        Category savedCategory = categoryRepository.findById(id).orElseThrow();
하겠습니다!

2024-07-17 05:16 UTC, BaeJunH0 commented on src/main/java/gift/service/WishListService.java
> +        WishProduct wish = wishListRepository.findById(wishId).orElseThrow();
하겠습니다!

2024-07-17 05:21 UTC, BaeJunH0 commented on src/main/java/gift/service/ProductService.java
>      public void createProduct(ProductRequest product){
음... 저번에도 지적해주셨듯이 UserEntity와 User 보다는 User와 UserDTO 같은 형식이 알아보기 쉬울텐데, 또 까먹었나봅니다, 수정하겠습니다~

2024-07-17 05:21 UTC, BaeJunH0 commented on src/main/java/gift/service/CategoryService.java
> +        );
잘 이해가 안갑니다!

2024-07-17 05:22 UTC, BaeJunH0 commented on src/main/java/gift/controller/CategoryController.java
> +    }
해보겠습니다~

2024-07-17 06:00 UTC, BaeJunH0 commented on src/main/java/gift/Application.java
> +    }
적용했습니다!

2024-07-17 06:10 UTC, BaeJunH0 commented on src/main/java/gift/domain/Category.java
> +    Long id;
적용했습니다!

2024-07-18 12:31 UTC, BaeJunH0 commented
"categoryRequest에서 카테고리를 직접 생성해보세요~" 이 부분 외에는 피드백 및 테스팅 반영했습니다.
아직 상위 계층에서의 테스팅은 없고 Repository 계층까지만 구현했습니다...
step 2 진행하고 있겠습니다 ㅠㅠ

2024-07-18 13:18 UTC, lsm7179 commented on src/main/java/gift/service/CategoryService.java
> +        );
` Category category = categoryRequest .toCartegory()`메소드를 만들어서 categoryRequest클래스에서 객체생성하여 전달해보세요~

2024-07-18 13:21 UTC, lsm7179 approved these changes
준호님 수고하셨습니다~!
다음단계도 화이팅입니다.🔥

2024-07-18 13:21 UTC, lsm7179 commented on src/main/java/gift/domain/BaseEntity.java
> +public class BaseEntity {
👍

2024-07-18 13:21 UTC, merged